Repository mapbox/mapbox-navigation-android, pull requests merged in 2018-12, with the labels that each got.

#1586 Bump mapbox-navigation-native version to 3.4.6
  gradle/dependencies.gradle
Labels: navigation-core, quick fix, ✓ ready for review

#1592 Update Navigator to 3.4.7
  gradle/dependencies.gradle
Labels: navigation-core, ✓ ready for review

#1579 0.24.0 release readme bump
  README.md
Labels: ✓ ready for review

#1594 Release v0.24.0
  CHANGELOG.md
  gradle.properties
Labels: navigation-core, navigation-ui, release

#1597 Setup CI to publish the sample app to Google Play
  app/build.gradle
  app/src/main/res/xml/fragment_navigation_preferences.xml
  build.gradle
  circle.yml
  gradle/dependencies.gradle
  gradle/script-git-version.gradle
  navigation_testapp.keystore
Labels: test app

#1599 Bump mapboxSdkServices version to 4.2.0
  gradle/dependencies.gradle
Labels: navigation-core, navigation-ui, quick fix, ✓ ready for review

#1603 Update Navigator 3.4.9
  gradle/dependencies.gradle
Labels: navigation-core, ✓ ready for review

#1604 Increment leg index upon way point arrival
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigator.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteProcessorRunnable.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/RouteProcessorRunnableTest.java
Labels: bug, navigation-core, ✓ ready for review

#1609 Update README.md for 0.24.1
  README.md
Labels: navigation-core, navigation-ui, release, ✓ ready for review

#1610 Add check to only cache instructions if the language setup is supported by Voice API
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/VoiceInstructionLoader.java
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/voice/VoiceInstructionLoaderTest.java
Labels: bug, topic: instructions, topic: localization, topic: voice, ✓ ready for review

#1612 Target API 28 and add FOREGROUND_SERVICE permission
  gradle/dependencies.gradle
  libandroid-navigation/src/main/AndroidManifest.xml
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/milestone/TriggerPropertyTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/milestone/TriggerTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/NavigationEventDispatcherTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/NavigationHelperTest.java
Labels: navigation-core, navigation-ui, ✓ ready for review

#1617 Update script-git-version.gradle with try/catch
  app/build.gradle
  gradle/script-git-version.gradle
Labels: low priority, test app, ✓ ready for review

#1616 Move SummaryBottomSheet above RecenterBtn in navigation_view_layout.xml
  libandroid-navigation-ui/src/main/res/layout-land/navigation_view_layout.xml
  libandroid-navigation-ui/src/main/res/layout/navigation_view_layout.xml
Labels: bug, navigation-ui, ✓ ready for review

#1619 Generate unique filenames for archives in check binary size script
  circle.yml
  scripts/check_binary_size.sh
Labels: navigation-core, navigation-ui, performance

#1620 Check for successful tar response in TarFetchedCallback
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/DownloadUpdateListener.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxOfflineRouter.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OfflineNavigator.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteTileDownloader.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/TarFetchedCallback.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/TarResponseErrorMap.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/TileUnpacker.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/UnpackProgressUpdateListener.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/UnpackerTask.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/DownloadUpdateListenerTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/RouteTileDownloaderTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/TarFetchedCallbackTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/TarResponseErrorMapTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/UnpackProgressUpdateListenerTest.java
Labels: navigation-core, tests, ✓ ready for review

#1622 Fix turn-by-turn UI voice instructions repeated after a config change
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewRouteEngineListener.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewSubscriber.java
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewRouteEngineListenerTest.java
Labels: bug, navigation-ui, topic: instructions, topic: voice, ✓ ready for review

#1627 Fix voice instruction cache not getting initialized with injected speech player
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java
Labels: bug, navigation-ui, topic: instructions, topic: voice, ✓ ready for review

#1628 Include 'exit roundabout' in Navigation Constants
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/maneuver/ManeuverView.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/maneuver/ManeuverViewMap.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationConstants.java
Labels: topic: directions

#1089 Changed the elevation of the InstructionView so that it doesn't encounter overlapping issues.
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationInstructionListListener.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationPresenter.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationView.java
Labels: ✓ ready for review

#1631 Bump mapbox-navigation-native version to 3.4.10
  gradle/dependencies.gradle
Labels: quick fix, ✓ ready for review

#1635 Update Navigator to 3.4.11
  gradle/dependencies.gradle
Labels: navigation-core, navigation-ui, ✓ ready for review

#1638 Update README.md for 0.25.0
  README.md
Labels: navigation-core, navigation-ui, ✓ ready for review

#1642 Update Maps SDK 6.8.0
  gradle/dependencies.gradle
Labels: navigation-ui, ✓ ready for review

#1645 Release v0.26.0
  CHANGELOG.md
  README.md
  gradle.properties
Labels: navigation-core, navigation-ui, release

#1646 Add SemVer flag to versions and PRs including breaking changes in the CHANGELOG
  CHANGELOG.md
Labels: topic: documentation
