Repository mapbox/mapbox-navigation-android, pull requests merged in 2019-04, with the labels that each got.

#1852 Update LocationComponent to use LocationComponentActivationOptions
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/NavigationMapboxMap.java
Labels: deprecated method, navigation-ui, ✓ ready for review

#1855 Add periodic refresh
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationOptions.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationConstants.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRoute.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteProcessorRunnable.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteRefresh.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteRefreshCallback.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteRefresher.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteRefresherCallback.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/RouteRefresherCallbackTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/RouteRefresherTest.java
Labels: feature, new API(s), topic: directions, topic: traffic, ✓ ready for review

#1861 Release 0.34.0
  CHANGELOG.md
  README.md
  gradle.properties
Labels: navigation-core, navigation-ui, release

#1862 Add offline options to Navigation Launcher
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationLauncherActivity.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/MapboxNavigationActivity.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationLauncher.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationLauncherOptions.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationUiOptions.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewOptions.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationConstants.java
Labels: navigation-ui, needs field testing, ✓ ready for review

#1864 Add offline version check to Navigation View Router
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewRouter.java
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewRouterTest.java
Labels: bug, navigation-ui, ✓ ready for review

#1866 Add check to only start Route Processor Background Thread once
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteProcessorBackgroundThread.java
Labels: bug, navigation-core, ✓ ready for review

#1867 Bump mapbox-android-plugin-annotation-v7 version to 0.6.0
  gradle/dependencies.gradle
Labels: navigation-ui, quick fix, ✓ ready for review

#1876 Bump mapbox-android-telemetry version to 4.3.0
  gradle/dependencies.gradle
Labels: quick fix, topic: telemetry, ✓ ready for review

#1880 Bump mapbox-android-sdk version to 7.3.1
  gradle/dependencies.gradle
Labels: bug, ✓ ready for review

#1877 Updated mapbox java to 4.6.0
  gradle/dependencies.gradle
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/milestone/BannerInstructionMilestoneTest.java
Labels: chore

#1881 Add custom history events for MapboxNavigation
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/HistoryActivity.java
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/ComponentNavigationActivity.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigator.java
Labels: test app, ✓ ready for review

#1879 Github PR template refactor
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#1883 Release 0.35.0
  CHANGELOG.md
  README.md
  gradle.properties
Labels: navigation-core, navigation-ui, release

#1885 Bump mapbox-navigation-native version to 6.1.2
  gradle/dependencies.gradle
Labels: quick fix, ✓ ready for review

#1889 Fix notification and banner ETAs not in sync
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationNotification.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationNotificationTest.java
Labels: bug, ✓ ready for review

#1891 Add NavigationMapboxMap#addCustomMarker for usage of SymbolManager
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationView.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/NavigationMapboxMap.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/NavigationSymbolManager.java
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/map/NavigationMapboxMapTest.java
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/map/NavigationSymbolManagerTest.java
Labels: SEMVER, deprecated method, navigation-ui, new API(s), ✓ ready for review

#1892 Update navigator to 6.1.3
  gradle/dependencies.gradle
Labels: navigation-core, navigation-ui, ✓ ready for review

#1818 Add NavigationMapRoute attribute for styling route line cap expression
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/MapRouteDrawableProvider.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/MapRouteLayerProvider.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/MapRouteLine.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/MapRouteSourceProvider.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/NavigationMapRoute.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/utils/MapUtils.java
  libandroid-navigation-ui/src/main/res/values/attrs.xml
  libandroid-navigation-ui/src/main/res/values/styles.xml
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/route/MapRouteLineTest.java
Labels: navigation-ui, platform parity, ✓ ready for review

#1894 Bump mapbox-android-sdk version to 7.3.2
  gradle/dependencies.gradle
Labels: bug, ✓ ready for review

#1888 Create NavigationViewRouter timeout to unblock routing state
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewRouter.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/OfflineRouteFoundCallback.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/RouteCallStatus.java
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewRouterTest.java
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/OfflineRouteFoundCallbackTest.java
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/RouteCallStatusTest.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/route/RouteFetcher.java
Labels: bug, navigation-ui, needs field testing, ✓ ready for review

#1896 Prevent RouteLeg list access for current step creation
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/TestRouteProgressBuilder.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteProcessor.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/RouteLegProgress.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/RouteProgress.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/TestRouteProgressBuilder.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/routeprogress/RouteLegProgressTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/utils/RouteUtilsTest.java
Labels: bug, navigation-core, ✓ ready for review

#1898 Release 0.36.0
  CHANGELOG.md
  README.md
  gradle.properties
Labels: navigation-core, navigation-ui, release

#1899 Allow default notification color setting via MapboxNavigationOptions
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationNotification.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationOptions.java
  libandroid-navigation/src/main/res/layout/collapsed_navigation_notification_layout.xml
  libandroid-navigation/src/main/res/layout/expanded_navigation_notification_layout.xml
  libandroid-navigation/src/main/res/values/colors.xml
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationNotificationTest.java
Labels: feature, navigation-ui, new API(s), ✓ ready for review

#1884 ExampleActivity refactor for simplicity/stability
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/ExampleActivity.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/ExamplePresenter.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/ExampleView.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/ExampleViewModel.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/PresenterState.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/navigation/ExampleRouteFinder.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/navigation/RouteFinder.kt
  app/src/main/res/layout/activity_example.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/fragment_navigation_preferences.xml
Labels: feature, refactor

#1909 Check for valid DirectionsRoute in RouteRefresh
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteRefresh.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/RouteRefreshTest.java
Labels: bug, navigation-core, ✓ ready for review

#1908 Fix intermediate way point arrival not triggered
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationLauncherActivity.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteProcessor.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteProcessorRunnable.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteProcessorTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/RouteProcessorRunnableTest.java
Labels: bug, navigation-core, navigation-ui, ✓ ready for review

#1901 Add connectivity status check to SpeechPlayer provider
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/ConnectivityStatusProvider.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/VoiceInstructionCache.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/SpeechPlayerProvider.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/VoiceInstructionLoader.java
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/VoiceInstructionCacheTest.java
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/voice/SpeechPlayerProviderTest.java
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/voice/VoiceInstructionLoaderTest.java
Labels: navigation-ui, ✓ ready for review

#1906 Update Java Services to 4.7.0
  gradle/dependencies.gradle
Labels: navigation-core, navigation-ui, ⚠️ DO NOT MERGE

#1914 Fix Navigation Launcher test app Activity incorrect profile regression
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
Labels: bug, test app, ✓ ready for review

#1913 Fix NavigationLauncherActivity camera animations
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationLauncherActivity.java
Labels: bug, test app, ✓ ready for review

#1915 Improve PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore, ✓ ready for review
