Repository mapbox/mapbox-navigation-android, pull requests merged in 2019-10, with the labels that each got.

#2070 Kyv ktlint setup
  app/build.gradle
  app/src/main/java/com/mapbox/services/android/navigation/testapp/NavigationApplication.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/OfflineRegionDownloadActivity.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/ExampleActivity.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/ExampleLocationEngineCallback.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/ExamplePresenter.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/ExampleView.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/ExampleViewModel.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/PresenterState.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/autocomplete/AutoCompleteBottomSheetCallback.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/autocomplete/AutocompleteBottomSheetBehavior.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/autocomplete/ExampleAutocompleteAdapter.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/navigation/ExampleMilestoneEventListener.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/navigation/ExampleOffRouteListener.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/navigation/ExampleProgressChangeListener.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/navigation/ExampleRouteFinder.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/navigation/OfflineRouteFinder.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/navigation/OnRoutesFoundCallback.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/navigation/RouteFinder.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/permissions/PermissionRequestDialog.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/utils/ActivityExt.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/utils/DelegatesExt.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/utils/RouteProgressUtils.kt
  circle.yml
  docs/ktlint-setup-and-using.md
  gradle/dependencies.gradle
  gradle/ktlint.gradle
  libandroid-navigation-ui/build.gradle
  libandroid-navigation/build.gradle
Labels: feature, kotlin-conversion

#2069 LocationUpdater Null checks
  gradle/dependencies.gradle
  libandroid-navigation/build.gradle
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/LocationUpdater.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/LocationUpdater.kt
Labels: kotlin-conversion

#2072 ConfigureRouterTask: java -> kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/ConfigureRouterTask.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/ConfigureRouterTask.kt
Labels: kotlin-conversion

#2043 Bumped Java SDK dependency to 4.9.0
  gradle/dependencies.gradle
  libandroid-navigation-ui/proguard-consumer.pro
  libandroid-navigation/proguard-consumer.pro
Labels: ✓ ready for review

#2073 DownloadUpdateListener: to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/DownloadUpdateListener.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/DownloadUpdateListener.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/DownloadUpdateListenerTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/DownloadUpdateListenerTest.kt
Labels: kotlin-conversion

#2074 MapboxOfflineRouter: to kotlin
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/OfflineRegionDownloadActivity.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxOfflineRouter.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxOfflineRouter.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxOfflineRouterTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxOfflineRouterTest.kt
Labels: kotlin-conversion

#2075 OfflineCriteria: to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OfflineCriteria.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OfflineCriteria.kt
Labels: kotlin-conversion

#2083 BatteryMonitor convert to Kotlin.
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/BatteryMonitor.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/BatteryMonitor.kt
Labels: kotlin-conversion

#2084 Counter, DoubleCounter, FloatCounter convert to Kotlin.
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/Counter.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/Counter.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/DoubleCounter.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/DoubleCounter.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/FloatCounter.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/FloatCounter.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/IntCounter.java
Labels: kotlin-conversion

#2086 MetadataBuilder convert to Kotlin.
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MetadataBuilder.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MetadataBuilder.kt
Labels: kotlin-conversion

#2079 Java-to-Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationNotification.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationNotification.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/LocaleUtils.java
Labels: kotlin-conversion

#2081 Attribute, BatteryChargeReporter, BatteryEvent convert to Kotlin.
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/Attribute.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/Attribute.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/BatteryChargeReporter.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/BatteryChargeReporter.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/BatteryEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/BatteryEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteCallback.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/BatteryChargeReporterTest.java
Labels: kotlin-conversion

#2076 OfflineError and OfflineRouteError: to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OfflineError.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OfflineError.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OfflineRouteError.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OfflineRouteError.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/TarFetchedCallbackTest.java
Labels: kotlin-conversion

#2082 jacoco: html report
  gradle/jacoco.gradle
Labels: feature, kotlin-conversion

#2085 Mock dependency and small changes as a sample
  app/build.gradle
  gradle/dependencies.gradle
  libandroid-navigation-ui/build.gradle
  libandroid-navigation/build.gradle
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxOfflineRouterTest.kt
Labels: kotlin-conversion, tests

#2096 Fix intermittent memory issues in CI
  CHANGELOG.md
  libandroid-navigation-ui/build.gradle
  libandroid-navigation/build.gradle
Labels: bug, navigation-core, navigation-ui, tests

#2098 Null extensions
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/extensions/NullEx.kt
Labels: feature

#2087 OfflineRouteRetrievalTask: to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OfflineRouteRetrievalTask.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OfflineRouteRetrievalTask.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/OfflineRouteRetrievalTaskTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/OfflineRouteRetrievalTaskTest.kt
Labels: kotlin-conversion

#2080 OfflineTiles: to kotlin
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/OfflineRegionDownloadActivity.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OfflineTiles.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OfflineTiles.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/OfflineTilesTest.kt
Labels: kotlin-conversion

#2092 Kyv tile unpacker to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/TileUnpacker.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/TileUnpacker.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/DownloadUpdateListenerTest.kt
Labels: kotlin-conversion

#2103 Fix Javadoc Kotlin issues
  CHANGELOG.md
  gradle/mvn-push-android.gradle
  libandroid-navigation-ui/javadoc.gradle
  libandroid-navigation/javadoc.gradle
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OnOfflineTilesConfiguredCallback.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OnOfflineTilesRemovedCallback.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OnTileVersionsFoundCallback.java
Labels: kotlin-conversion, navigation-core, navigation-ui

#2088 NavigationPerformanceEvent and NavigationPerformanceMetadata convert to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/BatteryEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationPerformanceEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationPerformanceEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationPerformanceMetadata.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationPerformanceMetadata.kt
Labels: kotlin-conversion

#2089 NavigationRouteCallback convert to Kotlin.
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationRouteCallback.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationRouteCallback.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRoute.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationRouteCallbackTest.java
Labels: kotlin-conversion

#2093 NavigationRouteEventListener and ElapsedTime convert to Kotlin.
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/ElapsedTime.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/ElapsedTime.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationRouteEventListener.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationRouteEventListener.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/utils/Time.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/ElapsedTimeTest.java
Labels: kotlin-conversion

#2110 migrate mapbox navigator to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/MapboxNavigator.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/MapboxNavigator.kt
Labels: kotlin-conversion

#2114 convert NavigationEventListener to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationEventListener.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationEventListener.kt
Labels: kotlin-conversion

#2104 DepartEventFactory and DepartEventHandler convert to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/DepartEventFactory.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/DepartEventFactory.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/DepartEventHandler.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/DepartEventHandler.kt
Labels: kotlin-conversion

#2099 TarResponseErrorMap: to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/TarResponseErrorMap.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/TarResponseErrorMap.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/TarResponseErrorMapTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/TarResponseErrorMapTest.kt
Labels: kotlin-conversion

#2101 RouteTileDownloader: to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OfflineTiles.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteTileDownloader.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteTileDownloader.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/RouteTileDownloaderTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/RouteTileDownloaderTest.kt
Labels: kotlin-conversion

#2100 TarFetchedCallback and RouteTileDownloadListener: to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteTileDownloadListener.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteTileDownloadListener.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/TarFetchedCallback.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/TarFetchedCallback.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/TarFetchedCallbackTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/TarFetchedCallbackTest.kt
Labels: kotlin-conversion

#2105 RingBuffer and SdkVersionChecker convert to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationTelemetry.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/SdkVersionChecker.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/SdkVersionChecker.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/utils/RingBuffer.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/RingBuffer.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/utils/RingBufferTest.java
Labels: kotlin-conversion

#2119 convert navigationFasterRouteListener to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationFasterRouteListener.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationFasterRouteListener.kt
Labels: kotlin-conversion

#2120 convert navigationNotificationProvider to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationNotificationProvider.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationNotificationProvider.kt
Labels: kotlin-conversion

#2112 Convert NavigationEngineFactory to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationEngineFactory.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationEngineFactory.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/NavigationEngineFactoryTest.java
Labels: kotlin-conversion

#2130 convert navigationEventDispatcher to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationEventDispatcher.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationEventDispatcher.kt
Labels: kotlin-conversion

#2134 convert routeProcessorBackgroundThread to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteProcessorBackgroundThread.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteProcessorBackgroundThread.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteProcessorThreadListener.java
Labels: kotlin-conversion

#2126 OfflineTileVersions, OfflineNavigator: to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OfflineNavigator.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OfflineNavigator.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OfflineTileVersions.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OfflineTileVersions.kt
Labels: kotlin-conversion

#2124 OnTileVersionsFoundCallback, OnOfflineTilesRemovedCallback, OnOffline…
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/OfflineRegionDownloadActivity.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OnOfflineTilesConfiguredCallback.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OnOfflineTilesConfiguredCallback.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OnOfflineTilesRemovedCallback.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OnOfflineTilesRemovedCallback.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OnTileVersionsFoundCallback.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OnTileVersionsFoundCallback.kt
Labels: kotlin-conversion

#2138 Convert MetricsLocation to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/location/MetricsLocation.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/location/MetricsLocation.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationRouteCallback.java
Labels: kotlin-conversion

#2140 NavigationRerouteEvent Convert to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationRerouteEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationRerouteEvent.kt
Labels: kotlin-conversion

#2125 NavigationArriveEvent, NavigationCancelEvent, NavigationDepartEvent convert to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationArriveEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationArriveEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationCancelEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationCancelEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationDepartEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationDepartEvent.kt
Labels: kotlin-conversion

#2139 NavigationFeedbackEvent convert to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationFeedbackEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationFeedbackEvent.kt
Labels: kotlin-conversion

#2145 BatteryEvent: mark `sessionId` and `metadata` by `@Transient` to avoi…
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/BatteryEvent.kt
Labels: bug, topic: telemetry

#2144 NavigationUtils, RouteState convert to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationUtils.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationUtils.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/PhoneState.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/PhoneState.kt
Labels: kotlin-conversion

#2142 NavigationStepData convert to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationStepData.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationStepData.kt
Labels: kotlin-conversion

#2123 AudioType convert to Kotlin.
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/audio/AudioTypeChain.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/audio/AudioTypeChain.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/audio/AudioTypeResolver.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/audio/AudioTypeResolver.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/audio/BluetoothAudioType.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/audio/HeadphonesAudioType.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/audio/SpeakerAudioType.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/audio/UnknownAudioType.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/audio/AudioTypeChainTest.kt
Labels: kotlin-conversion

#2141 Convert ReplayLocationDispatcher, ReplayLocationListener to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/location/replay/ReplayLocationDispatcher.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/location/replay/ReplayLocationListener.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/replay/GpxParser.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/replay/ParseGpxTask.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/replay/ReplayJsonRouteDto.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/replay/ReplayJsonRouteLocationMapper.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/replay/ReplayLocationDispatcher.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/replay/ReplayLocationListener.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/replay/ReplayRouteLocationEngine.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/replay/ReplayRouteLocationListener.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/location/replay/GpxParserTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/location/replay/ReplayJsonRouteDto.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/location/replay/ReplayJsonRouteLocationMapperTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/location/replay/ReplayLocationDispatcherTest.java
Labels: kotlin-conversion

#2150 Migrate NavigationMetricsWrapper and its dependencies
  circle.yml
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/location/MetricsLocation.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/BatteryEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/InitialGpsEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/InitialGpsEventHandler.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationMetricsWrapper.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationMetricsWrapper.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationService.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationTelemetry.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteProcessorThreadListener.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteRetrievalEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationNotificationProvider.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationPerformanceEvent.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationNotificationProviderTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteProcessorThreadListenerTest.java
Labels: kotlin-conversion

#2148 utils, span and time: to kotlin
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/utils/RouteProgressUtils.kt
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationView.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/summary/SummaryBottomSheet.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/summary/SummaryModel.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationOptions.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationTimeFormat.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/extensions/SpanEx.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/span/SpanItem.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/span/SpanItem.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/span/SpanUtils.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/span/TextSpanItem.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/span/TextSpanItem.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/time/NoneSpecifiedTimeFormat.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/time/NoneSpecifiedTimeFormat.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/time/TimeFormatResolver.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/time/TimeFormatResolver.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/time/TimeFormatter.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/time/TimeFormatter.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/time/TimeFormattingChain.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/time/TimeFormattingChain.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/time/TwelveHoursTimeFormat.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/time/TwelveHoursTimeFormat.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/time/TwentyFourHoursTimeFormat.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/time/TwentyFourHoursTimeFormat.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/utils/time/TimeFormatterTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/utils/time/TimeFormatterTest.kt
Labels: kotlin-conversion

#2152 DistanceFormatter: to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/DistanceFormatter.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/DistanceFormatter.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/abbreviation/AbbreviationArray.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/abbreviation/StringAbbreviator.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/package-info.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/utils/DistanceFormatterTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/utils/DistanceFormatterTest.kt
Labels: kotlin-conversion

#2147 NavigationEvent convert to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationEvent.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationEventFactoryTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/SchemaTest.java
Labels: kotlin-conversion

#2097 RouteRetrievalEvent, InitialGpsEvent, InitialGpsEventHandler, InitialGpsEventFactory convert to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/BatteryEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/InitialGpsEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/InitialGpsEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/InitialGpsEventFactory.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/InitialGpsEventFactory.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/InitialGpsEventHandler.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/InitialGpsEventHandler.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/LocationUpdater.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/MetadataBuilder.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationMetricsWrapper.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationService.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationTelemetry.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteRetrievalEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteRetrievalEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationPerformanceEvent.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/InitialGpsEventFactoryTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/LocationUpdaterTest.java
Labels: kotlin-conversion

#2151 FeedbackEvent, RerouteEvent, TelemetryEvent convert to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationTelemetry.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/FeedbackEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/FeedbackEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/RerouteEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/RerouteEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/TelemetryEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/TelemetryEvent.kt
Labels: kotlin-conversion

#2149 NavigationEventFactory convert to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/MetadataBuilder.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationEventFactory.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationEventFactory.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationEventFactoryTest.java
Labels: kotlin-conversion

#2157 Remove non necessary MeasurementUtils class
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/MeasurementUtils.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/utils/MeasurementUtilsTest.java
Labels: kotlin-conversion

#2159 Convert Snap to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/snap/Snap.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/snap/Snap.kt
Labels: kotlin-conversion

#2156 Convert NavigationService to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationService.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationService.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationNotificationProvider.kt
Labels: kotlin-conversion

#2168 Convert RrefreshCallback to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RefreshCallback.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RefreshCallback.kt
Labels: kotlin-conversion

#2164 Convert NavigationRouteWaypoint to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteWaypoint.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteWaypoint.kt
Labels: kotlin-conversion

#2187 Convert RouteHandler to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteHandler.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteHandler.kt
Labels: kotlin-conversion

#2186 Convert SnapToRoute to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/snap/SnapToRoute.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/snap/SnapToRoute.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/snap/package-info.java
Labels: kotlin-conversion

#2188 Convert RouteRefresh to Kotlin
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/MockNavigationActivity.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteRefresh.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteRefresh.kt
Labels: kotlin-conversion

#2162 Convert OffROuteCallback to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteCallback.java
Labels: kotlin-conversion

#2185 NavigationLifecycleMonitor convert to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationLifecycleMonitor.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationLifecycleMonitor.kt
Labels: kotlin-conversion

#2170 Convert RouteAnnotationUpdater to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteAnnotationUpdater.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteAnnotationUpdater.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteRefreshCallback.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteRefreshCallback.kt
Labels: kotlin-conversion

#2177 Convert RouteRefresher and RouteRefresherCallback to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteRefresher.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteRefresher.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteRefresherCallback.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteRefresherCallback.kt
Labels: kotlin-conversion

#2180 Convert MapboxNavigationNotification to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/location/MetricsLocation.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/MapboxNavigationNotification.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationService.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/notification/NavigationNotification.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/notification/NavigationNotification.kt
Labels: kotlin-conversion

#2183 MetricsRouteProgress convert to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationStepData.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/routeprogress/MetricsRouteProgress.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/routeprogress/MetricsRouteProgress.kt
Labels: kotlin-conversion

#2182 Migrate NavigationTelemetry to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/location/MetricsLocation.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/LocationUpdater.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationRouteCallback.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationService.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationTelemetry.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationTelemetry.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/SessionState.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationRouteCallbackTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationRouteCallbackTest.kt
Labels: kotlin-conversion

#2184 Convert replay location package to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/location/replay/ReplayLocationDto.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/location/replay/ReplayRouteLocationConverter.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/location/replay/ReplayRouteLocationListener.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/location/replay/TimestampAdapter.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/RawLocationListener.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/RawLocationListener.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/replay/ReplayLocationDto.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/replay/ReplayRouteLocationConverter.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/replay/ReplayRouteLocationEngine.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/replay/ReplayRouteLocationEngine.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/replay/ReplayRouteLocationListener.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/replay/TimestampAdapter.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/location/replay/ReplayJsonRouteDto.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/location/replay/ReplayLocationDispatcherTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/location/replay/ReplayRouteLocationListenerTest.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/location/replay/ReplayRouteParserTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/location/replay/ReplayRouteLocationListenerTest.java
Labels: kotlin-conversion

#2181 DownloadTask: to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/DownloadTask.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/DownloadTask.kt
Labels: kotlin-conversion

#2190 Convert Unpacker classes to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/UnpackProgressUpdateListener.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/UnpackProgressUpdateListener.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/UnpackUpdateTask.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/UnpackUpdateTask.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/UnpackerTask.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/UnpackerTask.kt
Labels: kotlin-conversion

#2169 Convert RefreshError to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RefreshError.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RefreshError.kt
Labels: kotlin-conversion

#2193 Convert all utils to kotlin
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/NavigationCamera.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/InstructionView.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/summary/list/InstructionListAdapter.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/summary/list/InstructionListPresenter.java
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/summary/list/InstructionListPresenterTest.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/utils/ValidationUtils.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/LocaleUtils.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/LocaleUtils.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/MathUtils.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/RouteUtils.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/RouteUtils.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/ValidationUtils.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/utils/ValidationUtilsTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/utils/RouteUtilsTest.java
Labels: kotlin-conversion

#2189 Kyv navigation utils to kotlin
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationLauncherActivity.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationView.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/InstructionView.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/summary/SummaryBottomSheet.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/MapboxNavigationNotification.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRoute.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/DistanceFormatter.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/extensions/ContextEx.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/extensions/LocaleEx.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteTest.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/OfflineRouteTest.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/testsupport/MockStaticSupport.kt
Labels: kotlin-conversion

#2201 Fix NavigationLifecycleMonitor crash with nullable types in overrided methods
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationLifecycleMonitor.kt
Labels: bug, kotlin-conversion

#2199 Convert DirectionsRouteType, NavigationConstants and OnOfflineRouteFoundCallback to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/DirectionsRouteType.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/DirectionsRouteType.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationConstants.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationConstants.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OnOfflineRouteFoundCallback.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OnOfflineRouteFoundCallback.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/OfflineRouteRetrievalTaskTest.kt
Labels: kotlin-conversion

#2202 Convert NavigationHelper to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationHelper.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationHelper.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationRouteProcessor.java
Labels: kotlin-conversion

#2153 SessionState, NavigationMetricsListener convert to Kotlin.
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/DepartEventFactory.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationTelemetry.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/FeedbackEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationEventFactory.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationMetricListener.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationMetricListener.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/SessionState.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/SessionState.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/TelemetryEvent.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/DepartEventFactoryTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationEventFactoryTest.java
Labels: kotlin-conversion

#2205 Operations convert to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/Operation.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/Operation.kt
Labels: kotlin-conversion

#2206 TriggerProperty convert to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/TriggerProperty.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/TriggerProperty.kt
Labels: kotlin-conversion

#2207 Convert offroute package to Kotlin
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/navigation/ExampleOffRouteListener.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/package-info.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/OffRoute.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/OffRoute.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetector.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetector.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteListener.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteListener.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/package-info.java
Labels: kotlin-conversion

#2204 Convert RouteProcessorRunnable to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteProcessorRunnable.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteProcessorRunnable.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteProcessorRunnableTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteProcessorRunnableTest.kt
Labels: kotlin-conversion

#2198 convert navigation>camera to kotlin
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/DynamicCamera.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/NavigationCamera.java
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/camera/DynamicCameraTest.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/camera/Camera.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/camera/Camera.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/camera/RouteInformation.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/camera/RouteInformation.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/camera/SimpleCamera.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/camera/SimpleCamera.kt
Labels: kotlin-conversion

#2212 Trigger, MilestoneEventListener convert to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/audio/AudioTypeChain.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/MilestoneEventListener.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/MilestoneEventListener.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/Trigger.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/Trigger.kt
Labels: kotlin-conversion

#2211 Milestone, BannerInstructionMilestone, RouteMilestone, StepMilestone, VoiceInstructionMilestone convert to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationHelper.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/BannerInstructionMilestone.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/BannerInstructionMilestone.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/Milestone.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/Milestone.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/RouteMilestone.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/RouteMilestone.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/StepMilestone.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/StepMilestone.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/TriggerProperty.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/VoiceInstructionMilestone.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/VoiceInstructionMilestone.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/package-info.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/milestone/VoiceInstructionMilestoneTest.java
Labels: kotlin-conversion

#2209 convert route package to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationFasterRouteListener.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/route/FasterRoute.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/route/FasterRoute.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/route/FasterRouteDetector.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/route/FasterRouteDetector.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/route/FasterRouteListener.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/route/FasterRouteListener.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/route/RouteFetcher.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/route/RouteFetcher.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/route/RouteListener.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/route/RouteListener.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/FasterRouteDetectorTest.java
Labels: kotlin-conversion

#2214 Convert navigationWalkingOptions to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRoute.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationWalkingOptions.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationWalkingOptions.kt
Labels: kotlin-conversion

#2136 converted
  gradle/dependencies.gradle
  gradle/wrapper/gradle-wrapper.properties
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationRouteProcessor.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationRouteProcessor.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteProcessorRunnable.kt
Labels: kotlin-conversion

#2217 Convert routeProgress package to kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationHelper.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/CurrentLegAnnotation.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/CurrentLegAnnotation.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/ProgressChangeListener.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/ProgressChangeListener.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/RouteProgressState.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/RouteProgressState.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/RouteProgressStateMap.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/RouteProgressStateMap.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationHelperTest.java
Labels: kotlin-conversion

#2195 RouteProgress conversion to Kotlin
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/utils/RouteProgressUtils.kt
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/TestRouteProgressBuilder.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/MapboxNavigationNotification.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationRouteProcessor.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/routeprogress/MetricsRouteProgress.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/StepMilestone.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/TriggerProperty.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteRefresh.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/camera/SimpleCamera.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/route/FasterRouteDetector.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/route/RouteFetcher.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/RouteProgress.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/RouteProgress.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/RouteUtils.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/extensions/NullEx.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/TestRouteProgressBuilder.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/routeprogress/RouteProgressTest.java
Labels: kotlin-conversion

#2095 java to Kotlin MapboxNavigationOptions
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/MockNavigationActivity.java
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/RerouteActivity.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/MapboxNavigationActivity.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewOptions.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteProcessorRunnable.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationOptions.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationOptions.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteProcessorRunnableTest.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/FasterRouteDetectorTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java
Labels: kotlin-conversion

#2221 Initial interface and module definitions for directions session
  libandroid-navigation/build.gradle
  libandroid-navigation/src/main/java/com/mapbox/navigation/DefaultDirectionsSession.kt
  libandroid-navigation/src/test/java/com/mapbox/navigation/DefaultDirectionsSessionTest.kt
  libdirections-hybrid/.gitignore
  libdirections-hybrid/build.gradle
  libdirections-hybrid/consumer-rules.pro
  libdirections-hybrid/proguard-rules.pro
  libdirections-hybrid/src/main/AndroidManifest.xml
  libdirections-hybrid/src/main/java/com/mapbox/navigation/route/hybrid/MapboxHybridRouter.kt
  libdirections-offboard/.gitignore
  libdirections-offboard/build.gradle
  libdirections-offboard/consumer-rules.pro
  libdirections-offboard/proguard-rules.pro
  libdirections-offboard/src/main/AndroidManifest.xml
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/MapboxOffboardRouter.kt
  libdirections-onboard/.gitignore
  libdirections-onboard/build.gradle
  libdirections-onboard/consumer-rules.pro
  libdirections-onboard/proguard-rules.pro
  libdirections-onboard/src/main/AndroidManifest.xml
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouter.kt
  libnavigator/.gitignore
  libnavigator/build.gradle
  libnavigator/src/main/AndroidManifest.xml
  libnavigator/src/main/java/com/mapbox/navigation/navigator/MapboxNavigator.kt
  linavigation-base/.gitignore
  linavigation-base/build.gradle
  linavigation-base/src/main/java/com/mapbox/navigation/route/DirectionsSession.kt
  linavigation-base/src/main/java/com/mapbox/navigation/route/Route.kt
  linavigation-base/src/main/java/com/mapbox/navigation/route/Router.kt
  settings.gradle
Labels: navigation-core, new API(s)

#2225 Fix reroute regression
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationFasterRouteListener.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/route/RouteFetcher.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/route/RouteListener.kt
Labels: bug, kotlin-conversion

#2224 Convert RouteLegProgress and RouteStepProgress to Kotlin
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/MapboxNavigationNotification.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationRouteProcessor.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/routeprogress/MetricsRouteProgress.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/TriggerProperty.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/RouteLegProgress.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/RouteLegProgress.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/RouteProgress.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/RouteStepProgress.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/RouteStepProgress.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/package-info.java
Labels: kotlin-conversion

#2066 Fix methods for recalculating waypoints coordinates, names, indices, approaches.
  CHANGELOG.md
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/WaypointNavigationActivity.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/route/RouteFetcher.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/RouteUtils.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/route/RouteFetcherTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/route/RouteFetcherTest.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/utils/RouteUtilsTest.java
Labels: bug, high priority, navigation-core

#2228 one line fix for the round-about issue
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/maneuver/ManeuverView.java
Labels: bug, high priority, navigation-ui, topic: instructions

#2229 Logger interface definition and observer hook
  liblogger/.gitignore
  liblogger/build.gradle
  liblogger/consumer-rules.pro
  liblogger/proguard-rules.pro
  liblogger/src/main/AndroidManifest.xml
  liblogger/src/main/java/com/mapbox/navigation/logger/LogEntry.kt
  liblogger/src/main/java/com/mapbox/navigation/logger/LogLevel.kt
  liblogger/src/main/java/com/mapbox/navigation/logger/LoggerObserver.kt
  liblogger/src/main/java/com/mapbox/navigation/logger/MapboxLogger.kt
  linavigation-base/src/main/java/com/mapbox/navigation/logger/Logger.kt
  settings.gradle
Labels: feature, navigation-core

#2235 project-tools.md: short description of project's tools
  docs/project-tools.md
Labels: kotlin-conversion, topic: documentation

#2237 - WorkThreadHandler; - Telemetry Events hooks to separate thread
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/MapboxMetricsReporter.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/extensions/GsonEx.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/extensions/HandlerThreadEx.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/thread/ThreadHandler.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/thread/WorkThreadHandler.kt
Labels: feature

#2236 Metrics emitter hook
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/MockNavigationActivity.java
  build.gradle
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/BatteryChargeReporter.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/BatteryEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/BatteryMonitor.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/DepartEventHandler.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/DoubleCounter.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/FloatCounter.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/InitialGpsEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/InitialGpsEventFactory.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/InitialGpsEventHandler.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationMetricsWrapper.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationTelemetry.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/RouteRetrievalEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/DirectionsMetrics.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/MapboxMetricsReporter.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/MetricEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/MetricsObserver.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/MetricsReporter.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationArriveEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationCancelEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationDepartEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationFeedbackEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationMetrics.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationPerformanceEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationRerouteEvent.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/routeprogress/MetricsRouteProgress.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/extensions/GsonEx.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/extensions/MetricEx.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/BatteryChargeReporterTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/BatteryMonitorTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/InitialGpsEventFactoryTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationEventDispatcherTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/MapboxMetricsReporterTest.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/audio/AudioTypeChainTest.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/FasterRouteDetectorTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/FasterRouteDetectorTest.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.kt
  libnavigation-base/build.gradle
  libnavigation-base/src/main/java/com/mapbox/navigation/base/metrics/DirectionsMetrics.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/metrics/MetricEvent.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/metrics/MetricsObserver.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/metrics/MetricsReporter.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/metrics/NavigationMetrics.kt
  libnavigation-metrics/.gitignore
  libnavigation-metrics/build.gradle
  libnavigation-metrics/consumer-rules.pro
  libnavigation-metrics/proguard-rules.pro
  libnavigation-metrics/src/main/AndroidManifest.xml
  libnavigation-metrics/src/main/java/com/mapbox/navigation/metrics/MapboxMetricsReporter.kt
  libnavigation-metrics/src/main/java/com/mapbox/navigation/metrics/extensions/MetricEx.kt
  libnavigation-metrics/src/test/java/com/mapbox/navigation/metrics/MapboxMetricsReporterTest.kt
  libnavigation-util/build.gradle
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/extensions/HandlerThreadEx.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/thread/ThreadHandler.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/thread/WorkThreadHandler.kt
  settings.gradle
Labels: feature, navigation-core, new API(s)
