Repository mapbox/mapbox-navigation-android, pull requests merged in 2019-07, with the labels that each got.

#1890 Move events from telemetry to nav sdk
  CHANGELOG.md
  gradle/dependencies.gradle
  gradle/download-schema.gradle
  libandroid-navigation/.gitignore
  libandroid-navigation/build.gradle
  libandroid-navigation/src/main/AndroidManifest.xml
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationMetricsWrapper.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationArriveEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationCancelEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationDepartEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationEventFactory.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationFeedbackEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationRerouteEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationStepData.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationUtils.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/PhoneState.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/audio/AudioTypeChain.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/audio/AudioTypeResolver.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/audio/BluetoothAudioType.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/audio/HeadphonesAudioType.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/audio/SpeakerAudioType.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/audio/UnknownAudioType.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationEventFactoryTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/metrics/SchemaTest.java
Labels: navigation-core, refactor, topic: telemetry

#1995 interchange the navigation sequence
  CHANGELOG.md
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationView.java
Labels: bug

#1997 bump version to 41 for release
  README.md
  gradle.properties
Labels: navigation-core, navigation-ui, release

#1998 Fix CHANGELOG for v0.41.0
  CHANGELOG.md
Labels: quick fix, release, ✓ ready for review

#2003 Update translations to latest Transifex
  CHANGELOG.md
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-gl/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-my/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-yo/strings.xml
  libandroid-navigation-ui/src/main/res/values-ar/strings.xml
  libandroid-navigation-ui/src/main/res/values-bg/strings.xml
  libandroid-navigation-ui/src/main/res/values-bn/strings.xml
  libandroid-navigation-ui/src/main/res/values-cs/strings.xml
  libandroid-navigation-ui/src/main/res/values-da/strings.xml
  libandroid-navigation-ui/src/main/res/values-de/strings.xml
  libandroid-navigation-ui/src/main/res/values-es/strings.xml
  libandroid-navigation-ui/src/main/res/values-fr/strings.xml
  libandroid-navigation-ui/src/main/res/values-gl/strings.xml
  libandroid-navigation-ui/src/main/res/values-he/strings.xml
  libandroid-navigation-ui/src/main/res/values-hu/strings.xml
  libandroid-navigation-ui/src/main/res/values-it/strings.xml
  libandroid-navigation-ui/src/main/res/values-ko/strings.xml
  libandroid-navigation-ui/src/main/res/values-my/strings.xml
  libandroid-navigation-ui/src/main/res/values-pt-rBR/strings.xml
  libandroid-navigation-ui/src/main/res/values-pt-rPT/strings.xml
  libandroid-navigation-ui/src/main/res/values-ru/strings.xml
  libandroid-navigation-ui/src/main/res/values-sv/strings.xml
  libandroid-navigation-ui/src/main/res/values-uk/strings.xml
  libandroid-navigation-ui/src/main/res/values-vi/strings.xml
  libandroid-navigation-ui/src/main/res/values-yo/strings.xml
  libandroid-navigation/src/main/res/values-ar/strings.xml
  libandroid-navigation/src/main/res/values-bn/strings.xml
  libandroid-navigation/src/main/res/values-da/strings.xml
  libandroid-navigation/src/main/res/values-gl/strings.xml
  libandroid-navigation/src/main/res/values-he/strings.xml
  libandroid-navigation/src/main/res/values-hu/strings.xml
  libandroid-navigation/src/main/res/values-my/strings.xml
  libandroid-navigation/src/main/res/values-sv/strings.xml
  libandroid-navigation/src/main/res/values-uk/strings.xml
  libandroid-navigation/src/main/res/values-yo/strings.xml
Labels: navigation-core, navigation-ui, test app, topic: localization, ✓ ready for review

#2002 add auto license generation
  CHANGELOG.md
  LICENSE
  LICENSE.md
  Makefile
  build.gradle
  circle.yml
  gradle/dependencies.gradle
  gradle/nitpick.gradle
  libandroid-navigation-ui/build.gradle
  libandroid-navigation/build.gradle
  scripts/generate-license.py
  scripts/validate-license.py
Labels: feature, navigation-core, navigation-ui

#2014 Bump Mapbox Annotation Plugin version to v8 0.7.0
  CHANGELOG.md
  gradle/dependencies.gradle
Labels: navigation-ui, ✓ ready for review

#2013 Bump mapbox-android-sdk version to 8.2.1
  CHANGELOG.md
  gradle/dependencies.gradle
Labels: blocked: upstream, bug, navigation-ui, topic: camera, ⚠️ DO NOT MERGE

#2015 Fix NavigationStepData regression from #1890
  CHANGELOG.md
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationDepartEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationStepData.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/audio/BluetoothAudioType.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/audio/HeadphonesAudioType.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/audio/SpeakerAudioType.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/audio/UnknownAudioType.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationEventFactoryTest.java
Labels: SEMVER, bug, navigation-core, topic: telemetry, ✓ ready for review
