Repository mapbox/mapbox-navigation-android, pull requests merged in 2020-04, with the labels that each got.

#2690 Bump NN, mapboxSdkServices and mapboxSdkDirectionsModels versions
  LICENSE.md
  gradle/dependencies.gradle
  libnavigator/build.gradle
Labels: ✓ ready for review

#2694 Bump NN version to 10.0.3
  LICENSE.md
  gradle/dependencies.gradle
  libnavigator/build.gradle
Labels: quick fix, ✓ ready for review

#2691 Kyv dokka ci validation
  libdirections-hybrid/build.gradle
  libdirections-offboard/build.gradle
  libdirections-onboard/build.gradle
  libnavigation-base/build.gradle
  libnavigation-base/src/main/java/com/mapbox/navigation/base/extensions/NullUtils.kt
  libnavigation-core/build.gradle
  libnavigation-metrics/build.gradle
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/extensions/NullUtils.kt
  libnavigator/build.gradle
  libnavigator/src/main/java/com/mapbox/navigation/navigator/SensorMapper.kt
  libtrip-notification/build.gradle
  scripts/dokka-validate.sh
Labels: topic: documentation

#2695 Fix turnstile SKU id
  libnavigation-core/src/main/java/com/mapbox/navigation/core/accounts/MapboxNavigationAccounts.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
Labels: Core SDK v1+, topic: telemetry, ✓ ready for review

#2697 Remove min zoom level constraint when initializing the Nav SDK
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/NavigationMapboxMap.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationConstants.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/legacy/NavigationConstants.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java
Labels: UI SDK v1+

#2680 Rl 237 sdk nn sync in polling
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/CoreActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/DebugMapboxNavigationKt.kt
  examples/src/main/res/layout/activity_debug_mapbox_navigation.xml
  examples/src/main/res/values/strings.xml
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-ui/src/main/res/drawable/ic_circle_blue.xml
  libnavigation-ui/src/main/res/drawable/ic_circle_red.xml
Labels: bug, navigation-core

#2703 Fix map progress change crash
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListener.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListener.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/NavigationMapRoute.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListenerTest.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListenerTest.kt
Labels: UI SDK v1+, bug

#2705 fix typo which will cause a problem that the observer is not registered.
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/NavigationMapRoute.java
Labels: UI SDK v1+

#2624 Bug fix #1990 using direction route speech language rather than devic…
  examples/src/main/java/com/mapbox/navigation/examples/core/TripServiceActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/TripSessionActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewActivity.kt
  gradle/dependencies.gradle
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/RouteBuilderProvider.kt
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/extension/LocaleEx.kt
  libdirections-offboard/src/test/java/com/mapbox/navigation/route/offboard/router/NavigationRouteTest.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/extensions/ContextEx.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/extensions/LocaleEx.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/extensions/LocaleExTest.kt
  libnavigation-core/build.gradle
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxDistanceFormatter.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxDistanceFormatterTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-ui/build.gradle
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/summary/SummaryBottomSheet.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/summary/SummaryModel.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/utils/LocaleEx.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/summary/SummaryModelTest.kt
  libnavigation-util/src/test/java/com/mapbox/navigation/utils/testsupport/MockStaticSupport.kt
  libtrip-notification/build.gradle
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/utils/time/TimeFormatter.kt
  libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/utils/time/TimeFormatterTest.kt
Labels: SEMVER

#2700 Hybrid/Onboard/Offboard Router: remaining docs
  libdirections-hybrid/src/main/java/com/mapbox/navigation/route/hybrid/MapboxHybridRouter.kt
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/MapboxOffboardRouter.kt
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/router/MapboxDirectionsUtils.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouter.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/OfflineCriteria.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/model/OfflineError.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/Router.kt
Labels: topic: documentation

#2701 base module: `NullUtils` -> `internal`
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomPuckActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewActivity.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/extensions/NullUtils.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/FasterRouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/MapboxNativeNavigatorImpl.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/utils/NullUtils.kt
Labels: navigation-core, quick fix

#2725 Fix release-core-1_0-prod job filter
  circle.yml
Labels: quick fix, ✓ ready for review

#2723 Fix issue 2722
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/puck/NavigationPuckPresenter.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/map/NavigationMapboxMapTest.java
Labels: UI SDK v1+, bug, navigation-ui, quick fix

#2711 notification module: - docs; minor changes.
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/notification/TripNotification.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/MapboxTripNotification.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/RemoteViewsProvider.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/maneuver/ManeuverIconDrawer.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/maneuver/ManeuverIconHelper.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/utils/time/TimeFormatter.kt
Labels: topic: documentation

#2707 base module: - dokka settings; - docs
  libnavigation-base/build.gradle
  libnavigation-base/src/main/java/com/mapbox/navigation/base/extensions/RouteOptionsUtils.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/formatter/DistanceFormatter.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/metrics/MetricEvent.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/Endpoint.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/MapboxOnboardRouterConfig.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/RouteRefreshCallback.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/MapboxNotificationData.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/RouteLegProgress.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/RouteProgress.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/RouteProgressState.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/RouteStepProgress.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/notification/NotificationAction.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/typedef/RoundingIncrement.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/typedef/TimeFormatType.kt
Labels: topic: documentation

#2708 metrics module: - dokka settings; - docs
  libnavigation-metrics/build.gradle
  libnavigation-metrics/src/main/java/com/mapbox/navigation/metrics/MapboxMetricsReporter.kt
Labels: topic: documentation

#2730 Bump Maps SDK version to 9.1.0
  gradle/dependencies.gradle
Labels: quick fix, ✓ ready for review

#2729 Fix Navigator synchronization issue
  LICENSE.md
  gradle/dependencies.gradle
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigator/build.gradle
  libnavigator/src/main/java/com/mapbox/navigation/navigator/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/MapboxNativeNavigatorImpl.kt
Labels: Core SDK v1+, bug, needs field testing, ✓ ready for review

#2696 Add replay history example
  examples/src/main/AndroidManifest.xml
  examples/src/main/assets/replay-history-activity.json
  examples/src/main/java/com/mapbox/navigation/examples/CoreActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/res/layout/replay_history_example_activity_layout.xml
  examples/src/main/res/values/strings.xml
Labels: feature

#2744 Fix guidance view activity
  examples/src/main/java/com/mapbox/navigation/examples/core/GuidanceViewActivity.kt
Labels: bug

#2742 Fix issue 2732: stop tripSession when MapboxNavigation destroy
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
Labels: bug, quick fix

#2660 Fix 2603: UI SDK components style refactor
  examples/src/main/java/com/mapbox/navigation/examples/core/InstructionViewActivity.kt
  examples/src/main/res/layout/activity_instruction_view_layout.xml
  examples/src/main/res/values-night/colors.xml
  examples/src/main/res/values/colors.xml
  examples/src/main/res/values/styles.xml
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/FeedbackButton.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/RecenterButton.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/SoundButton.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/ThemeSwitcher.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/alert/AlertView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/feedback/FeedbackAdapter.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/feedback/FeedbackBottomSheet.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/feedback/FeedbackViewHolder.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/WayNameView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/summary/SummaryBottomSheet.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/summary/list/InstructionListAdapter.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/summary/list/InstructionListView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/summary/list/InstructionViewHolder.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/utils/ViewUtils.java
  libnavigation-ui/src/main/res/drawable-v21/alert_progress_drawable.xml
  libnavigation-ui/src/main/res/drawable-v21/feedback_bottomsheet_background.xml
  libnavigation-ui/src/main/res/drawable-v21/feedback_progress_drawable.xml
  libnavigation-ui/src/main/res/drawable-v21/instruction_background.xml
  libnavigation-ui/src/main/res/drawable-v21/sound_chip_background.xml
  libnavigation-ui/src/main/res/drawable-v21/sub_banner_background.xml
  libnavigation-ui/src/main/res/drawable-v21/wayname_text_background.xml
  libnavigation-ui/src/main/res/layout-land/feedback_bottom_sheet_layout.xml
  libnavigation-ui/src/main/res/layout-land/feedback_viewholder_layout.xml
  libnavigation-ui/src/main/res/layout-land/instruction_content_layout.xml
  libnavigation-ui/src/main/res/layout-land/instruction_layout.xml
  libnavigation-ui/src/main/res/layout-land/instruction_layout_alt.xml
  libnavigation-ui/src/main/res/layout-land/instruction_viewholder_layout.xml
  libnavigation-ui/src/main/res/layout-land/navigation_view_layout.xml
  libnavigation-ui/src/main/res/layout-land/sub_instruction_layout.xml
  libnavigation-ui/src/main/res/layout-land/summary_peek_content_layout.xml
  libnavigation-ui/src/main/res/layout-land/summary_peek_layout.xml
  libnavigation-ui/src/main/res/layout-v21/feedback_viewholder_layout.xml
  libnavigation-ui/src/main/res/layout/alert_view_layout.xml
  libnavigation-ui/src/main/res/layout/feedback_bottom_sheet_layout.xml
  libnavigation-ui/src/main/res/layout/feedback_button_layout.xml
  libnavigation-ui/src/main/res/layout/feedback_viewholder_layout.xml
  libnavigation-ui/src/main/res/layout/instruction_content_layout.xml
  libnavigation-ui/src/main/res/layout/instruction_layout.xml
  libnavigation-ui/src/main/res/layout/instruction_list_layout.xml
  libnavigation-ui/src/main/res/layout/instruction_view_layout.xml
  libnavigation-ui/src/main/res/layout/instruction_viewholder_layout.xml
  libnavigation-ui/src/main/res/layout/navigation_view_layout.xml
  libnavigation-ui/src/main/res/layout/recenter_btn_layout.xml
  libnavigation-ui/src/main/res/layout/sound_layout.xml
  libnavigation-ui/src/main/res/layout/sub_instruction_layout.xml
  libnavigation-ui/src/main/res/layout/summary_peek_content_layout.xml
  libnavigation-ui/src/main/res/layout/summary_peek_layout.xml
  libnavigation-ui/src/main/res/layout/turn_lane_layout.xml
  libnavigation-ui/src/main/res/layout/wayname_view_layout.xml
  libnavigation-ui/src/main/res/values-night/colors.xml
  libnavigation-ui/src/main/res/values/attrs.xml
  libnavigation-ui/src/main/res/values/colors.xml
  libnavigation-ui/src/main/res/values/styles.xml
Labels: bug, navigation-ui, ✓ ready for review

#2392 HybridRouterTest refactoring
  libdirections-hybrid/src/main/java/com/mapbox/navigation/route/hybrid/MapboxHybridRouter.kt
  libdirections-hybrid/src/test/java/com/mapbox/navigation/route/hybrid/MapboxHybridRouterTest.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/thread/ThreadController.kt
Labels: refactor

#2740 Add HybridRouterActivity
  examples/build.gradle
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/CoreActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/HybridRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/HybridRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/OffboardRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/OffboardRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/OnboardRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/OnboardRouterActivityKt.kt
  examples/src/main/res/values/strings.xml
Labels: feature

#2754 Fix the null pointer better
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListener.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListenerTest.kt
Labels: bug

#2768 Bump NN version to 10.0.4
  gradle/dependencies.gradle
Labels: quick fix, ✓ ready for review

#2719 Fix for calling updateLocation and getStatus from one coroutine.
  examples/src/main/java/com/mapbox/navigation/examples/core/DebugMapboxNavigationKt.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistoryLocationEngine.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistoryPlayer.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/MapboxNativeNavigatorImpl.kt
Labels: bug, navigation-core

#2772 Pull in the latest translations from Transifex
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-uk/strings.xml
  libandroid-navigation-ui/src/main/res/values-de/strings.xml
  libandroid-navigation-ui/src/main/res/values-fr/strings.xml
  libandroid-navigation-ui/src/main/res/values-hu/strings.xml
  libandroid-navigation/src/main/res/values-fr/strings.xml
  libnavigation-util/src/main/res/values-ar/strings.xml
  libnavigation-util/src/main/res/values-bg/strings.xml
  libnavigation-util/src/main/res/values-cs/strings.xml
  libnavigation-util/src/main/res/values-da/strings.xml
  libnavigation-util/src/main/res/values-de/strings.xml
  libnavigation-util/src/main/res/values-es/strings.xml
  libnavigation-util/src/main/res/values-fa/strings.xml
  libnavigation-util/src/main/res/values-fr/strings.xml
  libnavigation-util/src/main/res/values-gl/strings.xml
  libnavigation-util/src/main/res/values-he/strings.xml
  libnavigation-util/src/main/res/values-hu/strings.xml
  libnavigation-util/src/main/res/values-ja/strings.xml
  libnavigation-util/src/main/res/values-ko/strings.xml
  libnavigation-util/src/main/res/values-my/strings.xml
  libnavigation-util/src/main/res/values-pt-rBR/strings.xml
  libnavigation-util/src/main/res/values-pt-rPT/strings.xml
  libnavigation-util/src/main/res/values-ru/strings.xml
  libnavigation-util/src/main/res/values-sv/strings.xml
  libnavigation-util/src/main/res/values-uk/strings.xml
  libnavigation-util/src/main/res/values-uz/strings.xml
  libnavigation-util/src/main/res/values-vi/strings.xml
  libnavigation-util/src/main/res/values-yo/strings.xml
  libtrip-notification/src/main/res/values-fr/strings.xml
Labels: ✓ ready for review

#2773 Add more syntax highlighting to the readme file
  README.md
Labels: quick fix

#2758 cleanUp router onDestroy
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityKt.kt
  libdirections-hybrid/src/main/java/com/mapbox/navigation/route/hybrid/MapboxHybridRouter.kt
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/MapboxOffboardRouter.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouter.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/Router.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/DirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSessionTest.kt
Labels: bug

#2590 Enable Orchestrator
  circle.yml
  examples/build.gradle
  gradle/dependencies.gradle
Labels: quick fix, tests

#2759 libnavigator: remaining docs
  libnavigator/src/main/java/com/mapbox/navigation/navigator/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/MapboxNativeNavigatorImpl.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/TripStatus.kt
Labels: topic: documentation, ✓ ready for review

#2724 Refactored RouteListener final destination arrival callback and arrival building highlight example
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/UIActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/ArrivalUiBuildingExtrusionActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/ArrivalUiBuildingExtrusionLayerActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/ArrivalUiFootprintHighlightActivityKt.kt
  examples/src/main/res/layout/activity_arrival_building_extrusion.xml
  examples/src/main/res/layout/activity_final_destination_arrival_building_highlight.xml
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
Labels: UI SDK v1+, ✓ ready for review

#2779 Added and adjusted examples test app snackbars
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/DebugMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/FasterRouteActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/InstructionViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReRouteActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/SummaryBottomSheetActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomUIComponentStyleActivity.kt
  examples/src/main/res/values/strings.xml
Labels: Core SDK v1+, UI SDK v1+, test app, ✓ ready for review

#2750 core module: remaining docs
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxDistanceFormatter.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/accounts/MapboxNavigationAccounts.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/DirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayEvents.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistoryDTO.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistoryLocationEngine.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistoryMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route/ReplayLocationConverter.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route/ReplayLocationListener.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route/ReplayRouteLocationEngine.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/ItemAccumulationEventDescriptor.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryInterface.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/TelemetryUtils.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/FeedbackEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/MetricsLocation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/MetricsRouteProgress.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/PhoneState.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/RerouteEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/SessionState.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/service/MapboxTripService.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/service/NavigationNotificationService.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/service/TripService.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/BannerInstructionEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/BannerInstructionsObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/LocationObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/OffRouteObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/RouteProgressObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSessionStateObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/VoiceInstructionEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/VoiceInstructionsObserver.kt
Labels: topic: documentation, ✓ ready for review

#2780 Make faster route configurable
  examples/src/main/java/com/mapbox/navigation/examples/core/FasterRouteActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/ArrivalUiBuildingExtrusionActivityKt.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/FasterRouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/FasterRouteObserver.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/fasterroute/FasterRouteControllerTest.kt
Labels: Core SDK v1+, SEMVER

#2761 dokka + CI: - dokka validation on each build; - refactored dokka-vali…
  circle.yml
  libnavigation-base/src/main/java/com/mapbox/navigation/base/extensions/LocaleEx.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/sensors/SensorEventEmitter.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/sensors/SensorOptions.kt
  scripts/dokka-validate.sh
Labels: topic: documentation, ✓ ready for review

#2785 Fix navigator prediction naming
  examples/src/main/java/com/mapbox/navigation/examples/core/DebugMapboxNavigationKt.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/route/options/NavigationOptionsTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
Labels: Core SDK v1+, SEMVER, ✓ ready for review

#2762 force to use okhttp version 3.12.x to keep compatibility of Android OS 19
  LICENSE.md
  app/build.gradle
  examples/src/main/res/drawable/bottom_button_background.xml
  examples/src/main/res/layout/activity_instruction_view_layout.xml
  gradle/dependencies.gradle
  libandroid-navigation-ui/build.gradle
  libandroid-navigation/build.gradle
  libdirections-offboard/build.gradle
  libnavigation-ui/build.gradle
Labels: UI SDK v1+, bug, navigation-ui, quick fix

#2795 Bump Kotlin dependency version to 1.3.72
  gradle/dependencies.gradle
Labels: quick fix, ✓ ready for review

#2812 fix example app crash on Android OS 19
  examples/src/main/java/com/mapbox/navigation/examples/NavigationApplication.kt
Labels: bug, quick fix, ✓ ready for review

#2814 Bump mapboxEvents, mapboxCore and NN dependency versions to 5.0.1, 2.0.1 and 11.0.0
  gradle/dependencies.gradle
  gradle/unit-testing-dependencies.gradle
  libandroid-navigation/build.gradle
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationEventDispatcherTest.java
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
Labels: quick fix, ✓ ready for review

#2815 Base router activity leak fix
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityKt.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java
Labels: bug

#2816 Proguard rules: moved rules for configurable modules to Core's proguard
  libdirections-hybrid/proguard-rules.pro
  libdirections-offboard/proguard-rules.pro
  libdirections-onboard/proguard-rules.pro
  libnavigation-core/build.gradle
  libnavigation-core/proguard-rules.pro
  libtrip-notification/proguard-rules.pro
Labels: Core SDK v1+, navigation-core

#2813 Added an `examples` test app activity to show Maps SDK + Nav SDK only combo
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/CoreActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavSdkOnlyActivity.kt
  examples/src/main/res/layout/activity_basic_navigation_sdk_only_layout.xml
  examples/src/main/res/values/strings.xml
Labels: Core SDK v1+, test app, ✓ ready for review

#2818 Add the route origination as Camera Position when initialize NaivgationView
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewActivity.kt
Labels: navigation-ui, quick fix, ✓ ready for review

#2819 improve the UI style customization as a follow-up of #2660
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/utils/Utils.java
  examples/src/main/res/layout/activity_custom_ui_component_style.xml
  examples/src/main/res/values/styles.xml
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/FeedbackButton.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationButton.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/RecenterButton.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/SoundButton.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/alert/AlertView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java
  libnavigation-ui/src/main/res/values/attrs.xml
Labels: SEMVER, UI SDK v1+, navigation-ui, quick fix, ✓ ready for review

#2774 Inject logger into sdk modules
  LICENSE.md
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/TripServiceActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/TripSessionActivityKt.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouter.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouterTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/FasterRouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayEventSimulator.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayEvents.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistoryMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistoryPlayer.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/sensors/SensorMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/service/MapboxTripService.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/fasterroute/FasterRouteControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/history/ReplayHistoryMapperTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/history/ReplayHistoryPlayerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/sensors/SensorMapperTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/service/MapboxTripServiceTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigator/build.gradle
  libnavigator/src/main/java/com/mapbox/navigation/navigator/MapboxNativeNavigator.kt
Labels: Core SDK v1+, SEMVER

#2829 Logger tailwork
  LICENSE.md
  libnavigation-core/build.gradle
  libnavigator/build.gradle
Labels: Core SDK v1+, bug, quick fix, ✓ ready for review

#2828 Cancel active fetching on a new route request
  libdirections-hybrid/src/main/java/com/mapbox/navigation/route/hybrid/MapboxHybridRouter.kt
Labels: bug

#2831 Expose Maps SDK transitively from UI SDK
  libnavigation-ui/build.gradle
Labels: UI SDK v1+, quick fix, ✓ ready for review

#2834 fix to prevent duplicate listener registration
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/camera/NavigationCamera.java
Labels: UI SDK v1+, bug, quick fix

#2836 Add internal package to libnavigator and libtrip-notification
  examples/src/main/java/com/mapbox/navigation/examples/MainActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/settings/NavigationSettingsActivity.java
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouter.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/task/RemoveTilesTask.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouterTest.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/task/RemoveTilesTaskTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/maneuver/ManeuverView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/summary/SummaryModel.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/summary/SummaryModelTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/NullUtils.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/TripStatus.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/MapboxTripNotification.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/TimeFormatter.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/maneuver/ManeuverIconDrawer.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/maneuver/ManeuverIconHelper.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/maneuver/ManeuversStyleKit.java
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/time/NoneSpecifiedTimeFormat.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/time/TimeFormatResolver.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/time/TimeFormattingChain.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/time/TwelveHoursTimeFormat.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/time/TwentyFourHoursTimeFormat.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/time/span/SpanEx.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/time/span/SpanItem.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/time/span/TextSpanItem.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/utils/time/span/SpanItem.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/utils/time/span/TextSpanItem.kt
  libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/MapboxTripNotificationTest.kt
  libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/internal/TimeFormatterTest.kt
Labels: Core SDK v1+, SEMVER, refactor, ✓ ready for review

#2838 Add example to show how to integrate with the Feedback Button component.
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/CoreActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/FeedbackButtonActivity.kt
  examples/src/main/res/layout/activity_feedback_button.xml
  examples/src/main/res/layout/activity_main.xml
  examples/src/main/res/values/strings.xml
Labels: UI SDK v1+, navigation-ui, test app, ✓ ready for review

#2842 Bump NN dependency version to 11.0.1
  gradle/dependencies.gradle
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
Labels: quick fix, ✓ ready for review

#2832 fix example app issues #2733
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/InstructionViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/SummaryBottomSheetActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomUIComponentStyleActivity.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java
Labels: UI SDK v1+, bug, navigation-ui, quick fix, ✓ ready for review

#2843 Remove unnecessary NN Proguard rules
  libnavigation-core/proguard-rules.pro
  libnavigator/proguard-rules.pro
Labels: Core SDK v1+, quick fix, ✓ ready for review

#2846 Add feedback description for 2TAP feedback flow
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/FeedbackEvent.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/feedback/FeedbackBottomSheet.java
  libnavigation-ui/src/main/res/values/strings.xml
Labels: navigation-ui

#2804 wip updating routeline so the part of the route already passed will n…
  libnavigation-ui/build.gradle
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/FeatureProcessingTask.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteClickListener.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLayerProvider.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListener.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteSourceProvider.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/NavigationMapRoute.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/PrimaryRouteUpdateTask.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/RouteConstants.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteClickListenerTest.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteLineTest.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteLineTest.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListenerTest.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/NavigationMapRouteTest.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/PrimaryRouteUpdateTaskTest.java
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/extensions/AsyncUtil.kt
Labels: navigation-ui

#2787 Add arrival controller for multiple stops
  examples/src/main/java/com/mapbox/navigation/examples/core/MultipleStopsActivity.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/stops/ArrivalController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/stops/ArrivalProgressObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/stops/ArrivalProgressObserverTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: feature

#2850 Reset Navigator state
  examples/src/main/java/com/mapbox/navigation/examples/core/FreeDriveNavigationActivity.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/DirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSessionTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/trip/session/MapboxTripSessionTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: Core SDK v1+, bug, ✓ ready for review

#2852 Resets route and routeBufferGeoJson as part of MapboxNativeNavigatorImpl#reset
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: Core SDK v1+, quick fix, ✓ ready for review

#2862 Clean up MapboxNativeNavigator
  libdirections-hybrid/src/test/java/com/mapbox/navigation/route/hybrid/MapboxHybridRouterTest.kt
  libnavigation-util/src/test/java/com/mapbox/navigation/utils/internal/ThreadControllerTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: Core SDK v1+, quick fix, ✓ ready for review

#2858 examples: idling OnMapReadyCallback
  examples/src/androidTest/java/com/mapbox/navigation/examples/activity/TripServiceActivityKtTest.kt
  examples/src/androidTest/java/com/mapbox/navigation/examples/util/OnMapReadyIdlingResource.kt
Labels: tests

#2874 Add playbackSpeed to handle replay fast forward and pause
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/res/layout/replay_history_example_activity_layout.xml
  examples/src/main/res/values/strings.xml
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayEventSimulator.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistoryPlayer.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/history/ReplayHistoryPlayerTest.kt
Labels: feature

#2866 Updated OnWayNameChangedListener docs
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/OnWayNameChangedListener.java
Labels: UI SDK v1+, topic: documentation, ✓ ready for review
