Repository mapbox/mapbox-navigation-android, pull requests merged in 2020-01, with the labels that each got.

#2347 Remove resources / translations / de.json from libtrip-notification
  libtrip-notification/src/main/resources/translations/de.json
Labels: quick fix, ✓ ready for review

#2348 Add onTripSessionStarted API to TripNotification
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/TripNotification.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/MapboxTripNotification.kt
Labels: ✓ ready for review

#2063 [Android]Accounts - SKU
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/MockNavigationActivity.java
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/OfflineRegionDownloadActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/activity/MockNavigationActivity.java
  examples/src/main/java/com/mapbox/navigation/examples/activity/OfflineRegionDownloadActivity.kt
  gradle/dependencies.gradle
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/VoiceInstructionLoader.java
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/voice/VoiceInstructionLoaderTest.java
  libandroid-navigation/build.gradle
  libandroid-navigation/src/main/AndroidManifest.xml
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/accounts/Billing.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/accounts/MapboxNavigationAccounts.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/accounts/SkuInterceptor.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/provider/MapboxNavigationProvider.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRoute.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OfflineTiles.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteRefresh.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/OfflineTilesTest.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/RouteRefreshTest.java
Labels: SEMVER, high priority, navigation-core

#2351 Remove unnecessary libtrip-session and libtrip-service cache checksums from CI config
  circle.yml
Labels: ✓ ready for review

#2344 Bump mapbox-navigation-native version to 8.2.1
  gradle/dependencies.gradle
Labels: navigation-core, quick fix, ✓ ready for review

#2352 Bumped Java SDK dependency to 5.0.0
  gradle/dependencies.gradle
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/TestRouteBuilder.java
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/map/WaynameFeatureFilterTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/TestRouteBuilder.java
  libdirections-offboard/src/test/java/com/mapbox/navigation/route/offboard/base/BaseTest.kt
Labels: new API(s), ✓ ready for review

#2354 Add network interceptor connection
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRoute.kt
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/router/NavigationRoute.kt
Labels: ✓ ready for review

#2353 Fix memory leak when set observers in MapboxLogger and MapboxMetricsReporter
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/MockNavigationActivity.java
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/ExampleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/activity/MockNavigationActivity.java
  examples/src/main/java/com/mapbox/navigation/examples/activity/OffboardRouterActivityKt.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/MetricsReporter.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/MapboxMetricsReporter.kt
  liblogger/src/main/java/com/mapbox/navigation/logger/MapboxLogger.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/metrics/MetricsReporter.kt
  libnavigation-metrics/src/main/java/com/mapbox/navigation/metrics/MapboxMetricsReporter.kt
Labels: bug, high priority, navigation-core

#2357 Remove libnavigator unnecessary dependencies
  libnavigator/build.gradle
Labels: ✓ ready for review

#2360 Add missing Navigator APIs and implementations
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouter.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/model/Config.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/model/Endpoint.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/network/HttpClient.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/MapboxNativeNavigatorImpl.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/model/EndpointConfig.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/model/RouterConfig.kt
Labels: new API(s), ✓ ready for review

#2362 initializer blocks order matters
  circle.yml
  libnavigator/src/main/java/com/mapbox/navigation/navigator/MapboxNativeNavigatorImpl.kt
Labels: bug, quick fix, ✓ ready for review

#2359 Knn remove mappers
  build.gradle
  examples/src/main/java/com/mapbox/navigation/examples/activity/OffboardRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/activity/OffboardRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/activity/OnboardRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/activity/OnboardRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/utils/extensions/Mappers.kt
  gradle/dependencies.gradle
  libdirections-hybrid/src/main/java/com/mapbox/navigation/route/hybrid/MapboxHybridRouter.kt
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/MapboxOffboardRouter.kt
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/RouteBuilderProvider.kt
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/extension/Mappers.kt
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/router/MapboxDirectionsUtils.kt
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/router/NavigationOffboardRoute.kt
  libdirections-offboard/src/test/java/com/mapbox/navigation/route/offboard/MapboxOffboardRouterTest.kt
  libdirections-offboard/src/test/java/com/mapbox/navigation/route/offboard/router/NavigationRouteTest.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouter.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/OnOfflineRouteFoundCallback.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/task/OfflineRouteRetrievalTask.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/task/OfflineRouteRetrievalTaskTest.kt
  libnavigation-base/build.gradle
  libnavigation-base/src/main/java/com/mapbox/navigation/base/extensions/RouteOptionsUtils.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/Router.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/dto/BannerComponentsNavigationDto.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/dto/BannerInstructionsNavigationDto.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/dto/BannerTextNavigationDto.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/dto/IntersectionLanesNavigationDto.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/dto/LegAnnotationNavigationDto.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/dto/LegStepNavigationDto.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/dto/MaxSpeedNavigationDto.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/dto/RouteDto.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/dto/RouteLegNavigationDto.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/dto/RouteOptionsNavigationDto.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/dto/RoutePointNavigationDto.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/dto/RouteResponseDto.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/dto/StepIntersectionNavigationDto.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/dto/StepManeuverNavigationDto.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/dto/VoiceInstructionsNavigationDto.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/dto/WalkingOptionsNavigationDto.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/BannerComponentsNavigation.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/BannerInstructionsNavigation.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/BannerTextNavigation.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/IntersectionLanesNavigation.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/LegAnnotationNavigation.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/LegStepNavigation.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/MaxSpeedNavigation.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/Route.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/RouteLegNavigation.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/RouteLegProgressNavigation.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/RouteOptionsNavigation.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/RoutePointNavigation.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/RouteProgressNavigation.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/RouteProgressStateNavigation.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/RouteResponse.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/RouteStepProgressNavigation.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/StepIntersectionNavigation.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/StepManeuverNavigation.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/StepManeuverType.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/VoiceInstructionsNavigation.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/WalkingOptionsNavigation.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/route/model/WalkingOptionsNavigationTest.kt
Labels: refactor

#2368 Remove unnecessary Turf dependency from libtrip-notification
  libtrip-notification/build.gradle
Labels: quick fix, ✓ ready for review

#2376 Fix distance notification issue
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/MapboxNavigationNotification.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/MapboxNavigationNotificationTest.java
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/milestone/BannerInstructionMilestoneTest.java
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/MapboxTripNotification.kt
Labels: bug, quick fix, ✓ ready for review

#2377 HttpClient fixes
  gradle/dependencies.gradle
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/HttpClient.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/HttpClientTest.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/network/HttpClient.kt
Labels: bug

#2374 Move MapboxOnboardRouterConfig inside NavigationOptions
  examples/src/main/java/com/mapbox/navigation/examples/activity/OnboardRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/activity/OnboardRouterActivityKt.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouter.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouterTest.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/Endpoint.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/MapboxOnboardRouterConfig.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
Labels: refactor

#2369 Replace AsyncTask with coroutines
  gradle/dependencies.gradle
  libdirections-onboard/build.gradle
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouter.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/task/OfflineRouteRetrievalTask.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/task/RemoveTilesTask.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/MainCoroutineRule.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouterTest.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/task/OfflineRouteRetrievalTaskTest.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/task/RemoveTilesTaskTest.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/task/RemoveTilesTaskTestTest.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/thread/ThreadController.kt
Labels: refactor

#2388 channel exception utils fun
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/thread/ThreadController.kt
Labels: quick fix

#2382 HybridRouter refactoring, tests added
  libdirections-hybrid/build.gradle
  libdirections-hybrid/src/main/java/com/mapbox/navigation/route/hybrid/MapboxHybridRouter.kt
  libdirections-hybrid/src/test/java/com/mapbox/navigation/route/hybrid/MainCoroutineRule.kt
  libdirections-hybrid/src/test/java/com/mapbox/navigation/route/hybrid/MapboxHybridRouterGenerationTest.kt
  libdirections-hybrid/src/test/java/com/mapbox/navigation/route/hybrid/MapboxHybridRouterTest.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/network/NetworkStatusService.kt
Labels: refactor

#2390 Added init() method to ThreadController
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/thread/ThreadController.kt
Labels: quick fix

#2415 Migrate MapboxMetricsReporter to coroutines
  libnavigation-metrics/build.gradle
  libnavigation-metrics/src/main/java/com/mapbox/navigation/metrics/MapboxMetricsReporter.kt
  libnavigation-metrics/src/test/java/com/mapbox/navigation/metrics/MainCoroutineRule.kt
  libnavigation-metrics/src/test/java/com/mapbox/navigation/metrics/MapboxMetricsReporterTest.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/thread/ThreadHandler.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/thread/WorkThreadHandler.kt
Labels: navigation-core, refactor

#2394 MapboxOnboardRouter: fix RouteUrl creating, incorrect waypoints
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouter.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/MainCoroutineRule.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouterTest.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/RouteUrl.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/thread/ThreadController.kt
Labels: quick fix

#2426 RouteUrl: move to internal package
  libdirections-offboard/src/test/java/com/mapbox/navigation/route/offboard/router/NavigationRouteTest.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouter.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/OfflineRoute.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouterTest.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/OfflineRouteTest.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/extensions/RouteOptionsUtils.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/internal/RouteUrl.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/route/RouteUrlTest.kt
Labels: quick fix

#2423 Dokka initial setup
  Makefile
  build.gradle
  circle.yml
  gradle/dependencies.gradle
  libdirections-hybrid/build.gradle
  libdirections-offboard/build.gradle
  libdirections-onboard/build.gradle
  libnavigation-base/build.gradle
  libnavigation-core/build.gradle
  libnavigation-metrics/build.gradle
  libnavigator/build.gradle
  libtrip-notification/build.gradle
  scripts/dokka-validate.sh
Labels: topic: documentation

#2430 Bump mapbox-sdk-services and mapbox-sdk-directions-models version to 5.1.0-beta.1
  gradle/dependencies.gradle
Labels: quick fix, ✓ ready for review

#2431 Release 1.0.0-beta.1
  CHANGELOG.md
Labels: navigation-core, release

#2420 Use generic libtesting with unit and UI tests dependencies
  examples/build.gradle
  examples/src/androidTest/java/com/mapbox/navigation/examples/activity/TripServiceActivityKtTest.kt
  libdirections-hybrid/build.gradle
  libdirections-hybrid/src/test/java/com/mapbox/navigation/route/hybrid/MainCoroutineRule.kt
  libdirections-hybrid/src/test/java/com/mapbox/navigation/route/hybrid/MapboxHybridRouterTest.kt
  libdirections-offboard/build.gradle
  libdirections-onboard/build.gradle
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouterTest.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/task/RemoveTilesTaskTest.kt
  liblogger/build.gradle
  libnavigation-base/build.gradle
  libnavigation-core/build.gradle
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MainCoroutineRule.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigation-metrics/build.gradle
  libnavigation-metrics/src/test/java/com/mapbox/navigation/metrics/MainCoroutineRule.kt
  libnavigation-metrics/src/test/java/com/mapbox/navigation/metrics/MapboxMetricsReporterTest.kt
  libnavigation-util/build.gradle
  libnavigator/build.gradle
  libtesting/.gitignore
  libtesting/build.gradle
  libtesting/consumer-rules.pro
  libtesting/proguard-rules.pro
  libtesting/src/main/AndroidManifest.xml
  libtesting/src/main/java/com/mapbox/navigation/testing/BaseTestRule.kt
  libtesting/src/main/java/com/mapbox/navigation/testing/MainCoroutineRule.kt
  libtesting/src/main/java/com/mapbox/navigation/testing/NotificationTestRule.kt
  libtrip-notification/build.gradle
  settings.gradle
Labels: refactor

#2433 dokka script: remove liblogger
  scripts/dokka-validate.sh
Labels: quick fix, topic: documentation

#2436 Bump Maps SDK and NN versions and add congestions support to Offboard examples
  examples/src/main/java/com/mapbox/navigation/examples/activity/OffboardRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/activity/OffboardRouterActivityKt.kt
  gradle/dependencies.gradle
Labels: ✓ ready for review

#2439 Fix generation and verification license scripts
  LICENSE.md
  Makefile
  circle.yml
  gradle/nitpick.gradle
  libandroid-navigation-ui/build.gradle
  libandroid-navigation/build.gradle
  libdirections-hybrid/build.gradle
  libdirections-offboard/build.gradle
  libdirections-onboard/build.gradle
  liblogger/build.gradle
  libnavigation-base/build.gradle
  libnavigation-core/build.gradle
  libnavigation-metrics/build.gradle
  libnavigator/build.gradle
  libtrip-notification/build.gradle
  scripts/generate-license.py
  scripts/validate-license.py
Labels: release blocker

#2437 Kyv move ui back from app
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/ComponentNavigationActivity.java
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/EmbeddedNavigationActivity.java
  app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationLauncherActivity.java
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/ExampleActivity.kt
  app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/navigation/ExampleMilestoneEventListener.kt
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/MapboxNavigationActivity.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationLauncherOptions.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationView.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewEventDispatcher.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/SoundButton.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/NavigationCamera.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/AbbreviationCreator.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/InstructionView.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/NavigationAlertView.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/maneuver/ManeuverViewMap.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/maneuver/ManeuversStyleKit.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/listeners/SpeechAnnouncementListener.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/NavigationMapboxMap.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/MapRouteArrow.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/MapRouteLine.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/MapRouteProgressChangeListener.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/NavigationMapRoute.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/RouteConstants.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/summary/list/InstructionListPresenter.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/AndroidSpeechPlayer.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/NavigationSpeechListener.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/NavigationSpeechPlayer.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/SpeechAnnouncement.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/SpeechPlayer.java
  libandroid-navigation-ui/src/main/res/drawable-land/turn_lane_background.xml
  libandroid-navigation-ui/src/main/res/layout-land/instruction_layout.xml
  libandroid-navigation-ui/src/main/res/layout-land/instruction_layout_alt.xml
  libandroid-navigation-ui/src/main/res/layout/instruction_view_layout.xml
  libandroid-navigation-ui/src/main/res/values-pt/strings.xml
  libandroid-navigation-ui/src/main/res/values/dimens.xml
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewEventDispatcherTest.java
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/route/MapRouteLineTest.java
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/voice/NavigationSpeechListenerTest.java
  libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/voice/NavigationSpeechPlayerTest.java
Labels: navigation-ui, new API(s)
