Repository mapbox/mapbox-navigation-android, pull requests merged in 2020-09, with the labels that each got.

#3515 Refactored building highlight activities to display highlighting when 250 meters away
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingExtrusionHighlightActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingFootprintHighlightActivity.kt
Labels: UI SDK v1+, refactor, test app, ✓ ready for review

#3520 Updated Nav UI day and night styles to new stable production v1 versions
  libnavigation-ui/src/main/res/values/strings.xml
Labels: UI SDK v1+, ✓ ready for review

#3522 CP: updated nav ui day and night styles to new stable production v1
  libnavigation-ui/src/main/res/values/strings.xml
Labels: UI SDK v1+, quick fix, topic: cartography, ✓ ready for review

#3530 CHANGELOG for 1.0.0-rc.7 release
  CHANGELOG.md
Labels: quick fix, release, ✓ ready for review

#3531 CP: CHANGELOG for 1.0.0-rc.7 release
  CHANGELOG.md
Labels: quick fix, release, ✓ ready for review

#3533 Use raw location samples in telemtry traces
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/TelemetryLocationAndProgressDispatcher.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/TelemetryLocationAndProgressDispatcherTest.kt
Labels: Core SDK v1+, topic: telemetry

#3529 Move post user feedback out of companion
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationFragment.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/DebugMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/FeedbackButtonActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/InstructionViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomUIComponentStyleActivity.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
Labels: SEMVER-MAJOR

#3536 Bumped Java SDK dependency to 5.5.0
  gradle/dependencies.gradle
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/TelemetryLocationAndProgressDispatcher.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/fasterroute/FasterRouteDetectorTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/hybrid/MapboxHybridRouterTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/onboard/MapboxOnboardRouterTest.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListenerTest.kt
Labels: Core SDK v1+, ✓ ready for review

#3535 Simplify CI release process
  circle.yml
  docs/publishing.md
  gradle.properties
  gradle/artifact-settings.gradle
  libnavigation-base/gradle.properties
  libnavigation-core/gradle.properties
  libnavigation-metrics/gradle.properties
  libnavigation-router/gradle.properties
  libnavigation-ui/gradle.properties
  libnavigation-util/gradle.properties
  libnavigator/gradle.properties
  libtrip-notification/gradle.properties
Labels: Core SDK v1+, UI SDK v1+, release

#3537 Add InstructionView attribute to allow developer not showing InstructionListView
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java
  libnavigation-ui/src/main/res/values/attrs.xml
Labels: UI SDK v1+, quick fix, ✓ ready for review

#3534 [CI] fine-grained jobs
  Makefile
  circle.yml
Labels: performance improvement, quick fix

#3548 Fix CI UI Instrumentation tests job typo
  circle.yml
Labels: quick fix, ✓ ready for review

#3547 Update Android Base artifact to v0.3.0
  gradle/dependencies.gradle
  libnavigation-core/src/androidTest/java/com/mapbox/navigation/core/TripServiceActivity.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
Labels: Core SDK v1+

#3542 Bump mapbox-navigation-native version to 20.0.0
  gradle/dependencies.gradle
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/OnboardRouterFiles.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/arrival/ArrivalProgressObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/arrival/ArrivalProgressObserverTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/ActiveGuidanceOptionsMapper.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/NavigatorLoader.kt
  libnavigator/src/test/java/com/mapbox/navigation/navigator/ActiveGuidanceOptionsMapperTest.kt
  libnavigator/src/test/java/com/mapbox/navigation/navigator/NavigationOkHttpServiceTest.kt
Labels: Core SDK v1+

#3441 Junction Snapshotter (POC)
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/CoreActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/JunctionSnapshotActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/junctonssupport/JunctionData.kt
  examples/src/main/java/com/mapbox/navigation/examples/junctonssupport/JunctionsProvider.kt
  examples/src/main/java/com/mapbox/navigation/examples/utils/extensions/LocationPointLatLngEx.kt
  examples/src/main/res/layout/activity_junction_snapshot.xml
  examples/src/main/res/raw/birmingham_junction.geojson
  examples/src/main/res/values/strings.xml
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
Labels: feature, navigation-ui

#3556 Update Metalava docs
  docs/metalava.md
Labels: quick fix, ✓ ready for review

#3552 Add the setRoute event to replay history
  examples/src/main/assets/replay-history-activity.json
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/history/HistoryFilesClient.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayEvents.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistoryMapper.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/history/ReplayHistoryMapperTest.kt
  libnavigation-core/src/test/resources/com.mapbox.navigation.core.replay.history/set_route_event_cleared.txt
  libnavigation-core/src/test/resources/com.mapbox.navigation.core.replay.history/set_route_event_invalid.txt
  libnavigation-core/src/test/resources/com.mapbox.navigation.core.replay.history/set_route_event_valid.txt
Labels: new API(s)

#3557 Fix release CI jobs
  circle.yml
Labels: release, ✓ ready for review

#3560 fix issue #3149: retain the Fragment when screen rotation.
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewFragment.kt
Labels: UI SDK v1+, quick fix, ✓ ready for review

#3422 Replaced the vanishing route line implementation with a location based implementation
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationActivity.kt
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/route/RouteConstants.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/utils/MemoizeUtils.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/utils/RouteLineValueAnimator.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapSettings.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListener.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/NavigationMapRoute.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/internal/utils/MemoizeUtilsTest.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/internal/utils/RouteLineValueAnimatorTest.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/map/NavigationMapboxMapTest.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteLineTest.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListenerTest.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/NavigationMapRouteTest.java
  libnavigation-ui/src/test/resources/vanish_point_test.txt
Labels: UI SDK v1+

#3521 Fine grained customization of route line scaling via the xml style.
  examples/src/main/res/values/styles.xml
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/route/RouteLayerProvider.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapboxRouteLayerProvider.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapboxRouteLayerProviderFactory.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/NavigationMapRoute.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/RouteLineScaleValue.kt
  libnavigation-ui/src/main/res/values/attrs.xml
  libnavigation-ui/src/main/res/values/styles.xml
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteLineTest.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapboxRouteLayerProviderFactoryTest.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapboxRouteLayerProviderTest.kt
Labels: UI SDK v1+

#3579 CP: Bump mapbox-android-telemetry version to 6.1.0
  gradle/dependencies.gradle
Labels: quick fix, release, topic: telemetry, ✓ ready for review

#3591 Reset routeProgress as part of MapboxTripSession setRoute
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
Labels: Core SDK v1+, quick fix, ✓ ready for review

#3594 Expose Common SDK dependency
  examples/build.gradle
  examples/src/main/java/com/mapbox/navigation/examples/core/MapMatchingActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingExtrusionHighlightActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingFootprintHighlightActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomPuckActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewFragment.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/TrafficToggleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/utils/extensions/NullUtils.kt
  gradle/dependencies.gradle
  libnavigation-core/build.gradle
Labels: Core SDK v1+, needs-backporting, release blocker

#3595 CP 3594 to 1.1
  examples/build.gradle
  examples/src/main/java/com/mapbox/navigation/examples/core/MapMatchingActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingExtrusionHighlightActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingFootprintHighlightActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomPuckActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewFragment.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/TrafficToggleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/utils/extensions/NullUtils.kt
  gradle/dependencies.gradle
  libnavigation-core/build.gradle
Labels: Core SDK v1+, release blocker

#3606 Pull in the latest translations from Transifex
  .tx/config
  examples/src/main/res/values-de/strings.xml
  examples/src/main/res/values-vi/strings.xml
  libnavigation-ui/src/main/res/values-es/strings.xml
  libnavigation-ui/src/main/res/values-vi/strings.xml
  libtrip-notification/src/main/res/values-de/strings.xml
  libtrip-notification/src/main/res/values-es/strings.xml
Labels: needs-backporting, quick fix, ✓ ready for review
