Repository mapbox/mapbox-navigation-android, pull requests merged in 2020-07, with the labels that each got.

#3266 Pull in the latest translations from Transifex
  libandroid-navigation-ui/src/main/res/values-el/strings.xml
  libandroid-navigation/src/main/res/values-el/strings.xml
  libnavigation-util/src/main/res/values-el/strings.xml
  libtrip-notification/src/main/res/values-el/strings.xml
Labels: ✓ ready for review

#3271 Cherry-pick EH to 1.1.0 beta.6
  examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/ElectronicHorizon.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/RouteLegProgress.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/RouteProgress.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/EHorizonObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSession.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/TripStatus.kt
Labels: Core SDK v1+, feature, new API(s)

#3274 Fix #3234: take snapshot when showing the FeedbackBottomSheet fragment
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationFragment.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/FeedbackButtonActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/InstructionViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomUIComponentStyleActivity.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewSubscriber.java
Labels: UI SDK v1+, ✓ ready for review

#3270 Unify distance unit between UI/Notification and Voice.
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/instruction/BannerInstructionModel.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/junction/RouteJunctionModel.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/summary/SummaryBottomSheet.java
Labels: SEMVER, UI SDK v1+

#3283 Clean up old PRs: #1970 and #2021
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewActivity.kt
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationUiOptions.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewOptions.java
Labels: SEMVER, UI SDK v1+, ✓ ready for review

#3289 Fix #3286: maintain the SoundButton mute state in screen rotation scenario
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewFragment.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewOptions.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/SoundButton.java
Labels: UI SDK v1+, quick fix, ✓ ready for review

#3307 fill the guidance view to the width of screen in portrait mode.
  libnavigation-ui/src/main/res/layout/instruction_view_layout.xml
Labels: UI SDK v1+, quick fix, ✓ ready for review

#3184 RouteOptionsProvider and RerouteController
  examples/src/main/java/com/mapbox/navigation/examples/core/ReRouteActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayWaypointsActivity.kt
  examples/src/main/res/values/strings.xml
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/arrival/ArrivalController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/FasterRouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/reroute/MapboxRerouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/reroute/RerouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routeoptions/RouteOptionsProvider.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/fasterroute/FasterRouteControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/reroute/MapboxRerouteControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsProviderTest.kt
Labels: new API(s), ✓ ready for review

#3287 Bump NN dependency version to 14.1.6
  gradle/dependencies.gradle
Labels: quick fix, ✓ ready for review

#3295 MapboxNavigationProvider API
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigationProvider.kt
Labels: new API(s)

#3308 Delete onboard router internal file option
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/DebugMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/FreeDriveNavigationActivity.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/internal/MapboxOnboardRouter.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/internal/OnboardRouterFiles.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/internal/MapboxOnboardRouterTest.kt
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/OnboardRouterOptions.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/NavigationOptionsTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/OnboardRouterOptionsTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
Labels: SEMVER

#3327 Cherry-pick EH to 1.1.0 beta.7
  examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/ElectronicHorizon.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/RouteLegProgress.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/RouteProgress.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/EHorizonObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSession.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/TripStatus.kt
Labels: Core SDK v1+, feature, new API(s)

#3337 [ui] fully unwrap the context before instantiating the view model
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationView.java
Labels: UI SDK v1+

#3297 Fix 3216: queue the VoiceInstruction so it just play one at a time.
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/AndroidSpeechPlayer.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/MapboxSpeechPlayer.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/NavigationSpeechPlayer.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/NavigationVoiceListener.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/SpeechPlayerProvider.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/SpeechPlayerState.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/SpeechPlayerStateChangeObserver.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/UtteranceListener.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/VoiceListener.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/voice/NavigationVoiceListenerTest.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/voice/SpeechPlayerProviderTest.java
Labels: UI SDK v1+, bug

#3339 Use feedback event 2.1 with app metadata field
  examples/src/main/java/com/mapbox/navigation/examples/core/FeedbackButtonActivity.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryInterface.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/AppMetadata.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationFeedbackEvent.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/SchemaTest.java
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/SchemaTest.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
Labels: Core SDK v1+, SEMVER-MAJOR

#3209 Added TripService test to core androidTest
  LICENSE.md
  circle.yml
  examples/src/androidTest/java/com/mapbox/navigation/examples/activity/TripServiceActivityKtTest.kt
  examples/src/androidTest/java/com/mapbox/navigation/examples/util/OnMapReadyIdlingResource.kt
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/CoreActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/HybridRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/HybridRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/OffboardRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/OffboardRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/OnboardRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/OnboardRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/TripServiceActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/TripSessionActivityKt.kt
  examples/src/main/res/values/strings.xml
  gradle/dependencies.gradle
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/accounts/MapboxNavigationAccounts.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/accounts/MapboxNavigationAccountsProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/accounts/NavigationAccountsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/service/MapboxTripService.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/service/NavigationNotificationService.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/service/TripService.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/accounts/MapboxNavigationAccountsTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/accounts/NavigationAccountsSessionTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/trip/service/MapboxTripServiceTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/trip/session/MapboxTripSessionTest.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/VoiceInstructionLoader.java
  libnavui-alert/src/main/assets/open_source_licenses.html
  libnavui-base/src/main/assets/open_source_licenses.html
  libnavui-feedback/src/main/assets/open_source_licenses.html
  libnavui-guidance/src/main/assets/open_source_licenses.html
  libnavui-maps/src/main/assets/open_source_licenses.html
  libnavui-summary/src/main/assets/open_source_licenses.html
  libnavui-util/src/main/assets/open_source_licenses.html
  libnavui-voice/src/main/assets/open_source_licenses.html
Labels: navigation-core, tests

#3356 change api to remove setting the access token explicitly
  examples/src/main/java/com/mapbox/navigation/examples/core/GuidanceViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingExtrusionActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingFootprintHighlightActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomCameraActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomPuckActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewFragment.kt
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/RouteStepProgress.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/trip/session/MapboxTripSessionTest.kt
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/junction/RouteJunction.java
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: SEMVER-MAJOR

#3355 Refactor InstructionView landscape UX to move the stepDistanceText to the right of ManeuverIcon
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java
  libnavigation-ui/src/main/res/drawable/instruction_background.xml
  libnavigation-ui/src/main/res/drawable/sub_banner_background.xml
  libnavigation-ui/src/main/res/layout-land/instruction_content_layout.xml
  libnavigation-ui/src/main/res/layout-land/instruction_layout.xml
  libnavigation-ui/src/main/res/layout-land/instruction_layout_alt.xml
  libnavigation-ui/src/main/res/layout-land/instruction_viewholder_layout.xml
  libnavigation-ui/src/main/res/values/dimens.xml
Labels: UI SDK v1+, ✓ ready for review

#3361 Building footprint and extrusion highlighting refactoring
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/UIActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingExtrusionHighlightActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingFootprintHighlightActivity.kt
  examples/src/main/res/layout-land/activity_building_extrusion.xml
  examples/src/main/res/layout/activity_building_extrusion.xml
  examples/src/main/res/layout/activity_final_destination_arrival_building_highlight.xml
  examples/src/main/res/values/strings.xml
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/building/BuildingExtrusionLayer.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/building/BuildingFootprintHighlightLayer.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/building/BuildingExtrusionHighlightLayer.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/building/BuildingFootprintHighlightLayer.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/building/BuildingLayerSupport.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/map/BuildingHighlightTest.kt
Labels: UI SDK v1+, ✓ ready for review

#3386 Fix NavigationFeedbackEventTest
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/NavigationFeedbackEventTest.kt
Labels: bug, quick fix

#3379 Building highlighting layer addition adjustments
  examples/src/main/res/values/strings.xml
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/utils/MapUtils.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/building/BuildingExtrusionHighlightLayer.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/building/BuildingFootprintHighlightLayer.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/map/MapUtilsTest.java
Labels: UI SDK v1+, ✓ ready for review
