Repository mapbox/mapbox-navigation-android, pull requests merged in 2020-03, with the labels that each got.

#2524 ReplayRouteLocationEngine: default init `lastLocation` by own provider
  libnavigation-core/src/main/java/com/mapbox/navigation/core/location/ReplayRouteLocationEngine.kt
Labels: quick fix

#2532 Copy ReplayRouteLocationEngine changes to old version
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/replay/ReplayRouteLocationEngine.kt
Labels: quick fix

#2535 MapboxTripSession: fix add replace by remove observer on call `unregi…
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
Labels: quick fix

#2534 Fix libandroid-navigation and libandroid-navigation-ui Javadoc task
  libandroid-navigation-ui/javadoc.gradle
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/InstructionView.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/NavigationAlertView.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/summary/SummaryBottomSheet.java
  libandroid-navigation/javadoc.gradle
Labels: topic: documentation

#2537 Fix libandroid-navigation and libandroid-navigation-ui javadoc task
  libandroid-navigation-ui/javadoc.gradle
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/InstructionView.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/NavigationAlertView.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/summary/SummaryBottomSheet.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/NavigationSpeechPlayer.java
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/SpeechAnnouncement.java
  libandroid-navigation/javadoc.gradle
Labels: topic: documentation

#2523 Adding destination building highlight UI and onFinalDestinationArrival() to RouteListener
  .editorconfig
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/UIActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/ArrivalUiBuildingExtrusionLayerActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/FinalDestinationBuildingFootprintHighlightActivityKt.kt
  examples/src/main/res/layout/activity_arrival_building_extrusion.xml
  examples/src/main/res/layout/activity_final_destination_arrival_building_highlight.xml
  examples/src/main/res/values/strings.xml
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/MapboxNavigationActivity.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewEventDispatcher.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewOptions.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/arrival/BuildingExtrusionLayer.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/arrival/DestinationBuildingFootprintLayer.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/legacy/NavigationConstants.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/legacy/RouteUtils.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/listeners/RouteListener.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/NavigationViewEventDispatcherTest.java
Labels: navigation-ui, ✓ ready for review

#2542 kdoc fixes to RouteListener onFinalDestinationArrival() method
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/listeners/RouteListener.java
Labels: navigation-ui

#2543 Editorconfig removal and other checkstyle tweaks
  .editorconfig
  examples/src/main/java/com/mapbox/navigation/examples/ui/ArrivalUiBuildingExtrusionLayerActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/FinalDestinationBuildingFootprintHighlightActivityKt.kt
Labels: ✓ ready for review

#2538 Add logic for faster route detector
  examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/FasterRouteDetector.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/fasterroute/FasterRouteDetectorTest.kt
Labels: feature

#2546 Fix Javadoc release issue and improve CI
  circle.yml
  gradle/mvn-push-android.gradle
Labels: release

#2552 Fix broken test
  libnavigation-core/src/test/java/com/mapbox/navigation/core/fasterroute/FasterRouteDetectorTest.kt
Labels: quick fix

#2553 Fix broken test using unmockkObject
  libnavigation-core/src/test/java/com/mapbox/navigation/core/fasterroute/FasterRouteDetectorTest.kt
Labels: ✓ ready for review

#2556 Bump NN version to 9.1.0
  build.gradle
  gradle/dependencies.gradle
Labels: Core SDK v1+, ✓ ready for review

#2558 Update / bump various dependency versions
  gradle/dependencies.gradle
Labels: ✓ ready for review

#2529 Up min SDK to API 19
  gradle/dependencies.gradle
  libandroid-navigation-ui/build.gradle
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/InstructionView.java
  libandroid-navigation/build.gradle
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/MapBatteryMonitor.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/AndroidSpeechPlayer.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/Api14UtteranceListener.java
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/extensions/HandlerThreadEx.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/network/NetworkStatusService.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/SensorMapper.kt
Labels: new API(s)

#2569 Fix faster route units
  libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/FasterRouteDetector.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/fasterroute/FasterRouteDetectorTest.kt
Labels: bug

#2572 Bump NN version to 9.2.1
  gradle/dependencies.gradle
Labels: Core SDK v1+, quick fix, ✓ ready for review

#2571 ReplayRouteLocationConverter: reset cache variables on new route has set
  libnavigation-core/src/main/java/com/mapbox/navigation/core/location/replay/ReplayRouteLocationConverter.kt
Labels: bug, quick fix

#2573 Add missing RouteOptions to DirectionsBuilder
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRoute.java
Labels: bug, topic: directions, ✓ ready for review

#2559 Add null pointer exception to fix the crash
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionModel.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/summary/list/InstructionListPresenter.java
Labels: UI SDK v1+, navigation-ui, quick fix

#2574 ui test: fix flaky
  examples/src/androidTest/java/com/mapbox/navigation/examples/activity/TripServiceActivityKtTest.kt
Labels: quick fix, tests

#2551 Kyv mapbox navigation rebuild route options
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouter.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouterTest.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/OfflineRouteTest.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/internal/RouteUrl.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/route/RouteUrlTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
Labels: quick fix

#2582 Add missing RouteOptions to DirectionsBuilder
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRoute.kt
Labels: bug, topic: directions

#2444 Added docs for MapboxNativeNavigator
  libnavigator/src/main/java/com/mapbox/navigation/navigator/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/MapboxNativeNavigatorImpl.kt
Labels: topic: documentation

#2447 Added docs to libnavigation-base module
  libnavigation-base/src/main/java/com/mapbox/navigation/base/formatter/DistanceFormatter.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/metrics/MetricsObserver.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/MapboxOnboardRouterConfig.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/MapboxNotificationData.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/typedef/RoundingIncrement.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/typedef/TimeFormatType.kt
Labels: topic: documentation

#2450 Fix displaying notification in free drive mode
  examples/src/androidTest/java/com/mapbox/navigation/examples/activity/TripServiceActivityKtTest.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/MapboxTripNotification.kt
  libtrip-notification/src/main/res/layout/collapsed_navigation_notification_layout.xml
  libtrip-notification/src/main/res/layout/expanded_navigation_notification_layout.xml
  libtrip-notification/src/main/res/values/strings.xml
Labels: navigation-ui

#2587 Fix missing event telemetry when Proguard is enabled
  gradle/dependencies.gradle
  libandroid-navigation-ui/proguard-consumer.pro
  libandroid-navigation/proguard-consumer.pro
  libandroid-navigation/src/main/AndroidManifest.xml
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/MetricsLocation.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/Attribute.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/BatteryEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/Counter.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/DoubleCounter.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/FloatCounter.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/InitialGpsEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/IntCounter.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationPerformanceEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationPerformanceMetadata.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/RouteRetrievalEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/FeedbackEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationArriveEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationCancelEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationDepartEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationFeedbackEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationRerouteEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationStepData.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/PhoneState.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/RerouteEvent.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/SessionState.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/MetricsRouteProgress.java
Labels: bug, topic: telemetry

#2595 Release v0.42.6
  CHANGELOG.md
  README.md
Labels: navigation-core, navigation-ui, release

#2596 Update CHANGELOG and README per 0.42.6 release
  CHANGELOG.md
  README.md
Labels: quick fix, ✓ ready for review

#2597 Fix CI release filter pattern triggers
  circle.yml
Labels: quick fix, release, ✓ ready for review

#2588 Use enhanced location as origin for reroutes
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/AdjustedRouteOptionsProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/FasterRouteController.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
Labels: Core SDK v1+, quick fix, ✓ ready for review

#2618 Remove MapboxTripSession route clearing from reset
  examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt
  examples/src/main/res/layout/content_simple_mapbox_navigation.xml
  examples/src/main/res/values/strings.xml
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
Labels: Core SDK v1+, bug, quick fix, ✓ ready for review

#2609 Make sure core is not depending on module's private impl
  examples/src/main/java/com/mapbox/navigation/examples/core/TripServiceActivityKt.kt
  libdirections-hybrid/build.gradle
  libdirections-hybrid/src/test/java/com/mapbox/navigation/route/hybrid/MapboxHybridRouterTest.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/extensions/LocaleEx.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/notification/NotificationAction.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/notification/TripNotification.kt
  libnavigation-core/build.gradle
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxDistanceFormatter.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/service/MapboxTripService.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/service/MapboxTripServiceTest.kt
  libnavigation-util/src/main/res/values-ar/strings.xml
  libnavigation-util/src/main/res/values-bg/strings.xml
  libnavigation-util/src/main/res/values-cs/strings.xml
  libnavigation-util/src/main/res/values-da/strings.xml
  libnavigation-util/src/main/res/values-de/strings.xml
  libnavigation-util/src/main/res/values-es/strings.xml
  libnavigation-util/src/main/res/values-fa/strings.xml
  libnavigation-util/src/main/res/values-fr/strings.xml
  libnavigation-util/src/main/res/values-gl/strings.xml
  libnavigation-util/src/main/res/values-he/strings.xml
  libnavigation-util/src/main/res/values-hu/strings.xml
  libnavigation-util/src/main/res/values-ja/strings.xml
  libnavigation-util/src/main/res/values-ko/strings.xml
  libnavigation-util/src/main/res/values-my/strings.xml
  libnavigation-util/src/main/res/values-pt-rBR/strings.xml
  libnavigation-util/src/main/res/values-pt-rPT/strings.xml
  libnavigation-util/src/main/res/values-ru/strings.xml
  libnavigation-util/src/main/res/values-sv/strings.xml
  libnavigation-util/src/main/res/values-uk/strings.xml
  libnavigation-util/src/main/res/values-uz/strings.xml
  libnavigation-util/src/main/res/values-vi/strings.xml
  libnavigation-util/src/main/res/values-yo/strings.xml
  libnavigation-util/src/main/res/values/strings.xml
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/MapboxTripNotification.kt
  libtrip-notification/src/main/res/values-ar/strings.xml
  libtrip-notification/src/main/res/values-bg/strings.xml
  libtrip-notification/src/main/res/values-cs/strings.xml
  libtrip-notification/src/main/res/values-da/strings.xml
  libtrip-notification/src/main/res/values-de/strings.xml
  libtrip-notification/src/main/res/values-es/strings.xml
  libtrip-notification/src/main/res/values-fa/strings.xml
  libtrip-notification/src/main/res/values-fr/strings.xml
  libtrip-notification/src/main/res/values-gl/strings.xml
  libtrip-notification/src/main/res/values-he/strings.xml
  libtrip-notification/src/main/res/values-hu/strings.xml
  libtrip-notification/src/main/res/values-ja/strings.xml
  libtrip-notification/src/main/res/values-ko/strings.xml
  libtrip-notification/src/main/res/values-my/strings.xml
  libtrip-notification/src/main/res/values-pt-rBR/strings.xml
  libtrip-notification/src/main/res/values-pt-rPT/strings.xml
  libtrip-notification/src/main/res/values-ru/strings.xml
  libtrip-notification/src/main/res/values-sv/strings.xml
  libtrip-notification/src/main/res/values-uk/strings.xml
  libtrip-notification/src/main/res/values-uz/strings.xml
  libtrip-notification/src/main/res/values-vi/strings.xml
  libtrip-notification/src/main/res/values-yo/strings.xml
  libtrip-notification/src/main/res/values/strings.xml
Labels: Core SDK v1+

#2608 Try using the location timestamp provided by Nav Native for animation
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/legacy/NavigationConstants.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java
Labels: navigation-ui

#2623 Feature/ak #2621 automate build process
  Makefile
  circle.yml
  gradle.properties
  gradle/artifact-settings.gradle
  libdirections-hybrid/gradle.properties
  libdirections-offboard/gradle.properties
  libdirections-onboard/gradle.properties
  libnavigation-base/gradle.properties
  libnavigation-core/gradle.properties
  libnavigation-metrics/gradle.properties
  libnavigation-ui/gradle.properties
  libnavigation-util/gradle.properties
  libnavigator/gradle.properties
  libtrip-notification/gradle.properties
Labels: Core SDK v1+, UI SDK v1+, feature, navigation-core, navigation-ui

#2570 Add route refresh
  libdirections-hybrid/src/main/java/com/mapbox/navigation/route/hybrid/MapboxHybridRouter.kt
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/MapboxOffboardRouter.kt
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/RouteBuilderProvider.kt
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/routerefresh/RouteRefreshCallbackMapper.kt
  libdirections-offboard/src/test/java/com/mapbox/navigation/route/offboard/MapboxOffboardRouterTest.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouter.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/RouteRefreshCallback.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/Router.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/DirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshController.kt
Labels: feature

#2628 Bump mapboxMapSdk, mapboxEvents, mapboxCore and mapboxNavigator versions
  LICENSE.md
  gradle/dependencies.gradle
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationOptions.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationConstants.kt
Labels: ✓ ready for review

#2629 Bump mapboxSdkServices and mapboxSdkDirectionsModels versions to 5.1.0-beta.2
  gradle/dependencies.gradle
Labels: quick fix, ✓ ready for review

#2630 Fix ClassNotFoundException in MapboxNavigationTest
  libnavigation-core/build.gradle
Labels: bug

#2637 Expose NavigationSession State internally
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationSessionStateObserver.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/NavigationSessionTest.kt
Labels: Core SDK v1+, ✓ ready for review

#2640 Fix CI job filter tag triggers
  circle.yml
Labels: Core SDK v1+, UI SDK v1+, release

#2626 Show parity b/w activity
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/FasterRouteActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/InstructionViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReRouteActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayActivity.kt
  examples/src/main/res/layout/activity_instruction_view_layout.xml
Labels: Core SDK v1+, UI SDK v1+, navigation-core, navigation-ui, test app

#2649 Adding Transifex support for libnavigation-util strings
  .tx/config
Labels: navigation-core, topic: localization

#2650 Extract the accounts lib logic to a separate class
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/accounts/NavigationAccountsSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/NavigationSessionTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/accounts/NavigationAccountsSessionTest.kt
Labels: Core SDK v1+, refactor, ✓ ready for review

#2657 Add missing MapboxNavigation tests
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
Labels: Core SDK v1+, tests, ✓ ready for review

#2666 Remove unnecessary sdk_versions files
  libandroid-navigation-ui/.gitignore
  libandroid-navigation-ui/src/main/assets/sdk_versions/.gitignore
  libandroid-navigation-ui/src/main/assets/sdk_versions/com.mapbox.services.android.navigation.ui.v5
  libandroid-navigation/.gitignore
  libandroid-navigation/src/main/assets/sdk_versions/.gitignore
  libandroid-navigation/src/main/assets/sdk_versions/com.mapbox.services.android.navigation
  libnavigation-core/.gitignore
  libnavigation-core/src/main/assets/sdk_versions/.gitignore
  libnavigation-core/src/main/assets/sdk_versions/com.mapbox.navigation.core
  libnavigation-ui/.gitignore
  libnavigation-ui/src/main/assets/sdk_versions/.gitignore
  libnavigation-ui/src/main/assets/sdk_versions/com.mapbox.libnavigation.ui
Labels: topic: telemetry, ✓ ready for review

#2673 Update Javadoc year to 2020
  libandroid-navigation-ui/javadoc.gradle
  libandroid-navigation/javadoc.gradle
  libnavigation-ui/javadoc.gradle
Labels: quick fix, ✓ ready for review

#2671 Bump mapboxMapSdk, mapboxEvents, mapboxCore, Kotlin and ktlint versions
  LICENSE.md
  gradle/dependencies.gradle
Labels: ✓ ready for review

#2672 Fix gitignore sdk_versions rules
  libandroid-navigation-ui/.gitignore
  libandroid-navigation-ui/src/main/assets/sdk_versions/.gitignore
  libandroid-navigation/.gitignore
  libandroid-navigation/src/main/assets/sdk_versions/.gitignore
  libnavigation-core/.gitignore
  libnavigation-core/src/main/assets/sdk_versions/.gitignore
  libnavigation-ui/.gitignore
  libnavigation-ui/src/main/assets/sdk_versions/.gitignore
Labels: topic: telemetry, ✓ ready for review

#2679 #2510 follow-up: fix wrong namespace
  libandroid-navigation-ui/src/main/res/layout-land/feedback_viewholder_layout.xml
  libandroid-navigation-ui/src/main/res/layout/feedback_viewholder_layout.xml
  libnavigation-ui/src/main/res/layout-land/feedback_viewholder_layout.xml
  libnavigation-ui/src/main/res/layout/feedback_viewholder_layout.xml
Labels: high priority, navigation-ui, quick fix
