Repository mapbox/mapbox-navigation-android, pull requests merged in 2020-10, with the labels that each got.

#3607 CP: Pull in the latest translations from Transifex
  .tx/config
  examples/src/main/res/values-de/strings.xml
  examples/src/main/res/values-vi/strings.xml
  libnavigation-ui/src/main/res/values-es/strings.xml
  libnavigation-ui/src/main/res/values-vi/strings.xml
  libtrip-notification/src/main/res/values-de/strings.xml
  libtrip-notification/src/main/res/values-es/strings.xml
Labels: quick fix, ✓ ready for review

#3605 Rename BorderCrossingAlert to CountryBorderCrossingAlert
  docs/metalava.md
  examples/src/main/java/com/mapbox/navigation/examples/core/RouteAlertsActivity.kt
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/alert/CountryBorderCrossingAdminInfo.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/alert/CountryBorderCrossingAlert.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/alert/RouteAlert.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/alert/RouteAlertType.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/alert/BorderCrossingAdminInfoTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/alert/CountryBorderCrossingAdminInfoTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/alert/CountryBorderCrossingAlertTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/NavigatorMapper.kt
  libnavigator/src/test/java/com/mapbox/navigation/navigator/NavigatorMapperTest.kt
Labels: Core SDK v1+, SEMVER-MAJOR, needs-backporting, ✓ ready for review

#3608 Bump mapbox-java to 5.7.0
  gradle/dependencies.gradle
Labels: needs-backporting

#3612 Expose TunnelInfo as part of TunnelEntranceAlert
  examples/src/main/java/com/mapbox/navigation/examples/core/RouteAlertsActivity.kt
  examples/src/main/res/drawable/ic_circle_yellow.xml
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/alert/TunnelEntranceAlert.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/alert/TunnelInfo.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/alert/TunnelEntranceAlertTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/alert/TunnelInfoTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/NavigatorMapper.kt
  libnavigator/src/test/java/com/mapbox/navigation/navigator/NavigatorMapperTest.kt
Labels: Core SDK v1+, needs-backporting, ✓ ready for review

#3613 CP: Expose TunnelInfo as part of TunnelEntranceAlert
  examples/src/main/java/com/mapbox/navigation/examples/core/RouteAlertsActivity.kt
  examples/src/main/res/drawable/ic_circle_yellow.xml
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/alert/TunnelEntranceAlert.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/alert/TunnelInfo.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/alert/TunnelEntranceAlertTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/alert/TunnelInfoTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/NavigatorMapper.kt
  libnavigator/src/test/java/com/mapbox/navigation/navigator/NavigatorMapperTest.kt
Labels: Core SDK v1+, quick fix, ✓ ready for review

#3617 Bump NN dependency version to 22.0.1
  gradle/dependencies.gradle
Labels: Core SDK v1+, needs-backporting, quick fix, ✓ ready for review

#3618 CP: Bump NN dependency version to 22.0.1
  gradle/dependencies.gradle
Labels: Core SDK v1+, quick fix, ✓ ready for review

#3616 The default distance remaining when not found in the cache should be the route distance not 0.
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteLineTest.kt
Labels: needs-backporting

#3599 Bumped Maps SDK dependency to 9.5.0
  gradle/dependencies.gradle
Labels: ✓ ready for review

#3625 Bump mapbox-navigation-native dependency version to 22.0.4
  gradle/dependencies.gradle
Labels: quick fix, ✓ ready for review

#3629 1.1.0 release changelog updates
  CHANGELOG.md
Labels: topic: documentation, ✓ ready for review

#3627 mapbox-navigation-ios now defaults to main
  CONTRIBUTING.md
Labels: chore, topic: documentation, ✓ ready for review

#3631 Cherrypick changelog updates for stable 1.1.0 release
  CHANGELOG.md
Labels: topic: documentation, ✓ ready for review

#3621 Bump mapboxEvents dependency to 6.2.0 and mapboxCore dependency to 3.1.0
  gradle/dependencies.gradle
Labels: quick fix, topic: telemetry

#3633 Bump NN dependency version to 24.0.0
  gradle/dependencies.gradle
Labels: quick fix, ✓ ready for review

#3640 IncidentAlert
  gradle/dependencies.gradle
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/alert/IncidentAlert.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/alert/IncidentCongestion.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/alert/IncidentImpact.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/alert/IncidentInfo.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/alert/IncidentType.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/alert/RouteAlertGeometry.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/alert/RouteAlertType.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/alert/IncidentAlertTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/alert/IncidentCongestionTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/alert/IncidentInfoTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/NavigatorMapper.kt
  libnavigator/src/test/java/com/mapbox/navigation/navigator/NavigatorMapperTest.kt
Labels: Core SDK v1+, feature

#3634 1.2.0-alpha.1 changelog updates
  CHANGELOG.md
Labels: topic: documentation, ✓ ready for review

#3644 Fix firebase-robo replay history crash
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayEvents.kt
Labels: bug

#3643 Fix #3642: add NPE protection for the feedbackBottomSheetListener in FeedbackBottomSheet
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/feedback/FeedbackBottomSheet.java
Labels: UI SDK v1+, needs-backporting, quick fix, ✓ ready for review

#3630 Add Electronic Horizon support
  examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt
  gradle/dependencies.gradle
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/EHorizonOptions.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/EHorizon.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/EHorizonPosition.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/EHorizonResultType.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/Edge.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/EdgeVisitor.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/FunctionalRoadClass.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/NameInfo.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/NavigationOptionsTest.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/EHorizonObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/ElectronicHorizonObserverImpl.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSession.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: Core SDK v1+, feature

#3649 Bump mapbox-android-telemetry dependency version to 6.2.1
  gradle/dependencies.gradle
Labels: quick fix, topic: telemetry, ✓ ready for review

#3650 upgrade Common SDK to v7.1.1
  gradle/dependencies.gradle
Labels: needs-backporting

#3653 Fix current horizon, type and position assignment done from 2 threads
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/ElectronicHorizonObserverImpl.kt
Labels: Core SDK v1+, quick fix, ✓ ready for review

#3652 CP: Bump mapboxEvents dependency to 6.2.1 and mapboxCore dependency to 3.1.0
  gradle/dependencies.gradle
Labels: quick fix, topic: telemetry, ✓ ready for review

#3655 Add Electronic Horizon Builder tests
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/EHorizonPosition.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/Edge.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/EHorizonOptionsTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/EHorizonPositionTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/EHorizonTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/EdgeTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/NameInfoTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: Core SDK v1+, SEMVER-MAJOR, tests, ✓ ready for review

#3657 Override common okhttp dependency with 7.1.1
  gradle/dependencies.gradle
  libnavigation-core/build.gradle
Labels: bug

#3663 Include Codecov reports to Github PR checks
  Makefile
  circle.yml
Labels: tests

#3664 MapRouteLine issue fix: keep the selected route as primary after map style has been changed
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationActivity.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteClickListener.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteLineTest.kt
Labels: UI SDK v1+, bug, quick fix, ✓ ready for review

#3661 Refactor vanishing point calculation to use EPSG:3857 projection
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayActivity.kt
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/route/RouteConstants.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/utils/MemoizeUtils.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListener.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/NavigationMapRoute.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/internal/utils/MemoizeUtilsTest.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteLineTest.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListenerTest.kt
Labels: UI SDK v1+

#3668 Bump mapboxSdkServices dependencies version to 5.8.0-beta.2
  gradle/dependencies.gradle
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteLineTest.kt
Labels: quick fix, ✓ ready for review

#3646 Fix firebase robo crash in history selector
  examples/src/main/java/com/mapbox/navigation/examples/history/HistoryFilesClient.kt
Labels: bug

#3675 Bump mapbox-navigation-accounts-android dependency version to 0.4.1
  gradle/dependencies.gradle
Labels: quick fix, ✓ ready for review

#3679 Fix inferred `BannerInstructions#willDisplay` nullability
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomCameraActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomPuckActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/TrafficToggleActivity.kt
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/listeners/BannerInstructionsListener.java
Labels: UI SDK v1+

#3677 Bump mapboxMapSdk, mapboxNavigator and mapboxCommonNative dependencies version to 9.6.0-beta.1, 26.0.0 and 9.0.2 respectively
  gradle/dependencies.gradle
  libnavigation-core/build.gradle
Labels: quick fix, ✓ ready for review

#3686 update default routing tiles version to 2020_10_18-03_00_00
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/OnboardRouterOptions.kt
Labels: Core SDK v1+

#3688 Remove onboard (Offline) legacy never used / exposed internal leftovers
  libnavigation-router/src/main/java/com/mapbox/navigation/route/onboard/OnOfflineRouteFoundCallback.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/onboard/OnOfflineTilesRemovedCallback.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/onboard/model/OfflineError.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/onboard/task/RemoveTilesTask.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/onboard/task/RemoveTilesTaskTest.kt
Labels: Core SDK v1+, needs-backporting, quick fix, ✓ ready for review

#3689 CP: Remove onboard (offline) legacy never used / exposed internal leftovers
  libnavigation-router/src/main/java/com/mapbox/navigation/route/onboard/OnOfflineRouteFoundCallback.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/onboard/OnOfflineTilesRemovedCallback.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/onboard/model/OfflineError.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/onboard/task/RemoveTilesTask.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/onboard/task/RemoveTilesTaskTest.kt
Labels: Core SDK v1+, quick fix, ✓ ready for review

#3691 Add scripts to "manually" publish to sdk-registry
  Makefile
  circle.yml
  gradle/dependencies.gradle
  gradle/publish.gradle
Labels: Core SDK v1+, UI SDK v1+, release, ✓ ready for review

#3692 CP: Add scripts to "manually" publish to sdk-registry
  Makefile
  circle.yml
  gradle/dependencies.gradle
  gradle/publish.gradle
Labels: Core SDK v1+, UI SDK v1+, quick fix, release, ✓ ready for review

#3695 Publish all artifacts in the project in a single PR to SDK Registry
  Makefile
Labels: Core SDK v1+, UI SDK v1+, release, ✓ ready for review

#3696 CP: Publish all artifacts in the project in a single PR to SDK registry
  Makefile
Labels: Core SDK v1+, UI SDK v1+, quick fix, release, ✓ ready for review

#3687 Refactor route's layer below id search
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteLineTest.kt
Labels: UI SDK v1+

#3699 Bump Mapbox SDK Services dependencies version to 5.8.0-beta.3
  gradle/dependencies.gradle
Labels: quick fix, ✓ ready for review

#3693 gradle okhttp dependencies: remove unnecessary `force` block
  examples/build.gradle
  libnavigation-ui/build.gradle
  libnavigator/build.gradle
Labels: ✓ ready for review

#3702 Cover more route line placement edge cases
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteLineTest.kt
Labels: UI SDK v1+

#3540 MapboxNavigationTelemetry refactoring
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/EventLocations.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/ItemAccumulationEventDescriptor.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/LocationsCollector.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/LocationsCollectorImpl.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryInterface.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/RouteAvailable.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/RouteProgressWithTimestamp.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/TelemetryLocationAndProgressDispatcher.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationRerouteEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/RerouteEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/SessionState.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/TelemetryEvent.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/LocationsCollectorTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/TelemetryLocationAndProgressDispatcherTest.kt
Labels: navigation-core, refactor

#3703 Bump coroutines dependencies version to 1.4.0
  gradle/dependencies.gradle
Labels: Core SDK v1+, UI SDK v1+, quick fix, ✓ ready for review

#3708 Fix publish-to-sdk-registry script
  Makefile
Labels: needs-backporting, quick fix, release, ✓ ready for review

#3707 Fix flaky telemetry tests
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
Labels: bug, tests

#3714 CP: Fix publish-to-sdk-registry script
  Makefile
Labels: quick fix, release, ✓ ready for review

#3710 Catch failed attempt to obtain route geometry buffer
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: Core SDK v1+

#3716 Telemetry reroute fix
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
Labels: bug, navigation-core, tests
