Repository mapbox/mapbox-navigation-android, pull requests merged in 2020-08, with the labels that each got.

#3391 Bump play-services-location version to 17.0.0
  gradle/dependencies.gradle
Labels: quick fix, test app, ✓ ready for review

#3374 UX change: put the guidance view to the left of the NavigationView in landscape mode
  examples/src/main/res/layout/activity_summary_bottom_sheet.xml
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationGuidanceViewListener.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationPresenter.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/RecenterButton.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/GuidanceViewListener.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/NavigationContract.java
  libnavigation-ui/src/main/res/drawable/guidance_view_rounded_bg.xml
  libnavigation-ui/src/main/res/drawable/ic_navigation.xml
  libnavigation-ui/src/main/res/drawable/ic_recenter.xml
  libnavigation-ui/src/main/res/layout-land/instruction_layout.xml
  libnavigation-ui/src/main/res/layout-land/navigation_view_layout.xml
  libnavigation-ui/src/main/res/layout-land/summary_content_layout.xml
  libnavigation-ui/src/main/res/layout/navigation_view_layout.xml
  libnavigation-ui/src/main/res/layout/recenter_btn_layout.xml
  libnavigation-ui/src/main/res/layout/recenter_button_layout.xml
  libnavigation-ui/src/main/res/layout/summary_content_layout.xml
  libnavigation-ui/src/main/res/values/colors.xml
  libnavigation-ui/src/main/res/values/dimens.xml
  libnavigation-ui/src/main/res/values/styles.xml
Labels: UI SDK v1+, ✓ ready for review

#3401 Fix when url has invalid access token GuidanceViewImageProvider flaky test
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/GuidanceViewImageProvider.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/instruction/GuidanceViewImageProviderTest.kt
Labels: UI SDK v1+, tests

#3405 Follow up from GuidanceViewImageProviderTest fix
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/instruction/GuidanceViewImageProviderTest.kt
Labels: UI SDK v1+, tests

#3406 GuidanceViewImageProviderTest refactoring
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/GuidanceViewImageProvider.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/instruction/GuidanceViewImageProviderTest.kt
Labels: refactor

#3403 change Feedback option "Incorrect Visual" to "Looks Incorrect" to align with iOS
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/FeedbackEvent.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/feedback/FeedbackBottomSheet.java
  libnavigation-ui/src/main/res/drawable/ic_feedback_incorrect_visual.xml
  libnavigation-ui/src/main/res/drawable/ic_feedback_looks_incorrect.xml
  libnavigation-ui/src/main/res/drawable/ic_feedback_looks_incorrect_circle.xml
  libnavigation-ui/src/main/res/drawable/ic_feedback_looks_incorrect_circle_pressed.xml
  libnavigation-ui/src/main/res/values/strings.xml
Labels: SEMVER-MAJOR, quick fix, ✓ ready for review

#3393 Bumped Java SDK to 5.4.1
  gradle/dependencies.gradle
Labels: Core SDK v1+

#3400 refactored to change the naming from shield to casing
  examples/src/main/res/values/colors.xml
  examples/src/main/res/values/styles.xml
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/route/MapRouteLayerProvider.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/route/RouteConstants.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListener.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/NavigationMapRoute.java
  libnavigation-ui/src/main/res/values/attrs.xml
  libnavigation-ui/src/main/res/values/colors.xml
  libnavigation-ui/src/main/res/values/styles.xml
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteLineTest.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListenerTest.kt
Labels: SEMVER-MAJOR

#3392 remove v1 from ui module
  docs/publishing.md
  gradle/publish.gradle
  libnavigation-ui/gradle.properties
Labels: SEMVER-MAJOR, UI SDK v1+

#3407 Replace temporarily elapsedRealtimeNanos by 0 so legacy getStatus is used
  libnavigator/build.gradle
  libnavigator/src/main/java/com/mapbox/navigation/navigator/LocationEx.kt
Labels: Core SDK v1+, bug, quick fix, ✓ ready for review

#3410 Fix LocationEx toFixLocation test and Makefile
  Makefile
  libnavigator/src/test/java/com/mapbox/navigation/navigator/LocationExTest.kt
Labels: quick fix, ✓ ready for review

#3413 Fix configureRouter sync issue
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/OnboardRouterFiles.kt
Labels: Core SDK v1+, bug, ✓ ready for review

#3414 OnboardRouterTest cleanup
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/internal/MapboxOnboardRouterTest.kt
Labels: refactor

#3420 Bump maps version to 9.4.0-beta.1
  gradle/dependencies.gradle
Labels: UI SDK v1+

#3412 UI quick fix: align the Recenter icon with FeedbackButton
  examples/src/main/res/layout/activity_custom_ui_component_style.xml
  examples/src/main/res/layout/fragment_basic_navigation.xml
  libnavigation-ui/src/main/res/layout/navigation_view_layout.xml
Labels: UI SDK v1+, quick fix

#3415 Fix #1986: expose API to disable TTS fallback when connection is slow.
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationUiOptions.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewOptions.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/SpeechPlayerProvider.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/voice/SpeechPlayerProviderTest.java
Labels: UI SDK v1+, quick fix, ✓ ready for review

#3423 Upgrading Nav UI SDK to v5 day/night guidance styles
  libnavigation-ui/src/main/res/values/colors.xml
  libnavigation-ui/src/main/res/values/strings.xml
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteLineTest.kt
Labels: UI SDK v1+, refactor, ✓ ready for review

#3424 Fix route / isOffRoute race condition
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/trip/session/MapboxTripSessionTest.kt
Labels: Core SDK v1+, ✓ ready for review

#3434 Add ``` backticks to separate source bode blocks
  README.md
Labels: quick fix, topic: documentation, ✓ ready for review

#3431 Update data from navigator status right after a route is set
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/trip/session/MapboxTripSessionTest.kt
Labels: Core SDK v1+, ✓ ready for review

#3203 Added fine grained programatic runtime configuration of route lines w…
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/CoreActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/RuntimeRouteStylingActivity.java
  examples/src/main/res/layout/activity_runtime_route_styling.xml
  examples/src/main/res/values/strings.xml
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/route/MapboxRouteLayerProvider.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/route/MapboxRouteLayerProviderFactory.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/route/RouteConstants.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/route/RouteLayerProvider.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/IdentifiableRoute.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/NavigationMapRoute.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/RouteStyleDescriptor.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/internal/route/MapboxRouteLayerProviderFactoryTest.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/internal/route/MapboxRouteLayerProviderTest.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteLineTest.kt
Labels: UI SDK v1+

#3428 fix #3310: not calling the TTS to play voice guidance when it is not initialized
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/AndroidSpeechPlayer.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/MapboxSpeechPlayer.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/NavigationVoiceListener.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/SpeechPlayerProvider.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/SpeechPlayerState.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/SpeechPlayerStateChangeObserver.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/UtteranceListener.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/VoiceListener.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/voice/NavigationVoiceListenerTest.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/voice/SpeechPlayerProviderTest.java
Labels: SEMVER-MAJOR, quick fix, topic: voice, ✓ ready for review

#3438 Fix Transifex 1.0 issues / regressions
  .tx/config
Labels: quick fix, ✓ ready for review

#3444 Upgrade Nav Native to 18.0.3
  gradle/dependencies.gradle
  libnavigator/build.gradle
Labels: release blocker

#3445 Bumps Kotlin version to 1.4.0 and Coroutines version to 1.3.9
  gradle/dependencies.gradle
Labels: quick fix, ✓ ready for review

#3448 Removed old tokens from hardcoded DirectionsRoute JSON Strings
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomCameraActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomPuckActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewFragment.kt
Labels: UI SDK v1+, refactor

#3447 Nav UI building highlight refactoring for v5 style switch
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingExtrusionHighlightActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingFootprintHighlightActivity.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/building/BuildingExtrusionHighlightLayer.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/building/BuildingFootprintHighlightLayer.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/building/BuildingLayerSupport.kt
Labels: UI SDK v1+, refactor, ✓ ready for review

#3452 Bump mapbox-android-telemetry version to 6.1.0
  gradle/dependencies.gradle
Labels: quick fix, topic: telemetry, ✓ ready for review

#3425 Adding NavigationView v5 style traffic visibility toggle example
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/UIActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/TrafficToggleActivity.kt
  examples/src/main/res/layout/activity_traffic_toggle.xml
  examples/src/main/res/values/strings.xml
Labels: UI SDK v1+, test app, topic: traffic, ✓ ready for review

#3437 MapMatchingActivity
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/CoreActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapMatchingActivity.kt
  examples/src/main/res/layout/activity_map_matching.xml
  examples/src/main/res/values/strings.xml
Labels: topic: directions

#3456 Incorrect telemetry location timestamp format and missing locations from reroute events
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationFeedbackEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationRerouteEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/TelemetryLocation.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/FeedbackLocationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/NavigationFeedbackEventTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/SchemaTest.kt
Labels: Core SDK v1+, bug, topic: telemetry

#3457 Add navigator single thread dispatcher scope to ThreadController
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/ThreadController.kt
  libnavigation-util/src/test/java/com/mapbox/navigation/utils/internal/ThreadControllerTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: Core SDK v1+, ✓ ready for review

#3467 Downgrade the Maps SDK to v9.3.1
  gradle/dependencies.gradle
Labels: UI SDK v1+, release blocker

#3460 Route line related API changes for future updates
  examples/src/main/java/com/mapbox/navigation/examples/core/NavigationMapRouteActivity.java
  examples/src/main/java/com/mapbox/navigation/examples/core/RuntimeRouteStylingActivity.java
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/route/RouteConstants.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapSettings.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/NavigationMapRoute.java
Labels: SEMVER-MAJOR, UI SDK v1+, release blocker

#3470 update feedback icons background color
  libnavigation-ui/src/main/res/drawable/mapbox_ic_feedback_illegal_route_normal.xml
  libnavigation-ui/src/main/res/drawable/mapbox_ic_feedback_illegal_route_pressed.xml
  libnavigation-ui/src/main/res/drawable/mapbox_ic_feedback_positioning_issue_normal.xml
  libnavigation-ui/src/main/res/drawable/mapbox_ic_feedback_positioning_issue_pressed.xml
  libnavigation-ui/src/main/res/drawable/mapbox_ic_feedback_route_quality_normal.xml
  libnavigation-ui/src/main/res/drawable/mapbox_ic_feedback_route_quality_pressed.xml
Labels: UI SDK v1+, quick fix

#3475 Improve replay route error messages
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route/ReplayRouteDriver.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/route/ReplayRouteMapperTest.kt
Labels: user: feedback

#3193 Add Core v1.0.0-rc.x series entries to the CHANGELOG
  CHANGELOG.md
Labels: topic: documentation

#3482 Make examples keys not translatable
  examples/src/main/res/values/strings.xml
Labels: quick fix, test app, ✓ ready for review

#3426 Adjustments to fix Nav UI RTL InstructionView alignment
  examples/src/main/res/layout/activity_core.xml
  examples/src/main/res/layout/activity_replay_history_layout.xml
  examples/src/main/res/layout/activity_traffic_toggle.xml
  examples/src/main/res/layout/activity_ui.xml
  examples/src/main/res/layout/bottom_sheet_faster_route.xml
  libnavigation-ui/src/main/res/layout-land/mapbox_partial_instruction_content.xml
  libnavigation-ui/src/main/res/layout-land/mapbox_partial_instruction_sub_instruction.xml
  libnavigation-ui/src/main/res/layout-land/mapbox_partial_instruction_view.xml
  libnavigation-ui/src/main/res/layout-land/mapbox_partial_instruction_view_alt.xml
  libnavigation-ui/src/main/res/layout/mapbox_alert_view.xml
  libnavigation-ui/src/main/res/layout/mapbox_partial_instruction_content.xml
  libnavigation-ui/src/main/res/layout/mapbox_partial_instruction_sub_instruction.xml
  libnavigation-ui/src/main/res/layout/mapbox_partial_instruction_view.xml
  libnavigation-ui/src/main/res/layout/mapbox_wayname_view.xml
Labels: UI SDK v1+, bug, ✓ ready for review

#3458 fixed wrong casing color for alternative route lines and added tests
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/route/MapRouteLayerProvider.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapboxRouteLayerProvider.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapboxRouteLayerProviderFactory.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/NavigationMapRoute.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapboxRouteLayerProviderFactoryTest.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapboxRouteLayerProviderTest.kt
Labels: UI SDK v1+

#3494 Use AppCompatResources#getDrawable instead of ContextCompat#getDrawable in ThemeSwitcher#retrieveThemeMapMarker
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/ThemeSwitcher.java
Labels: UI SDK v1+, bug, quick fix, ✓ ready for review

#3495 Bumps snapshot version name to 1.1.0-SNAPSHOT
  gradle.properties
Labels: Core SDK v1+, UI SDK v1+

#3496 Cherry pick better RTL support to 1.0 release branch
  examples/src/main/res/layout/activity_core.xml
  examples/src/main/res/layout/activity_replay_history_layout.xml
  examples/src/main/res/layout/activity_traffic_toggle.xml
  examples/src/main/res/layout/activity_ui.xml
  examples/src/main/res/layout/bottom_sheet_faster_route.xml
  libnavigation-ui/src/main/res/layout-land/mapbox_partial_instruction_content.xml
  libnavigation-ui/src/main/res/layout-land/mapbox_partial_instruction_sub_instruction.xml
  libnavigation-ui/src/main/res/layout-land/mapbox_partial_instruction_view.xml
  libnavigation-ui/src/main/res/layout-land/mapbox_partial_instruction_view_alt.xml
  libnavigation-ui/src/main/res/layout/mapbox_alert_view.xml
  libnavigation-ui/src/main/res/layout/mapbox_partial_instruction_content.xml
  libnavigation-ui/src/main/res/layout/mapbox_partial_instruction_sub_instruction.xml
  libnavigation-ui/src/main/res/layout/mapbox_partial_instruction_view.xml
  libnavigation-ui/src/main/res/layout/mapbox_wayname_view.xml
Labels: UI SDK v1+, ✓ ready for review

#3472 separating the geojson sources for the route line and casing line for …
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/route/RouteConstants.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapboxRouteLayerProvider.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteLineTest.kt
Labels: UI SDK v1+

#3499 Changelog for 1.0.0-rc.5 and 1.0.0-rc.6
  CHANGELOG.md
Labels: Core SDK v1+, UI SDK v1+

#3504 Upgrade Maps SDK to 9.4.0
  gradle/dependencies.gradle
Labels: UI SDK v1+

#3492 Reinitializing the primary route on add routes when the routes in map…
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/NavigationMapRoute.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/NavigationMapRouteTest.java
Labels: UI SDK v1+

#3510 Fix annotation of NavigationMapRoute.Builder#build to be NonNull
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/NavigationMapRoute.java
Labels: SEMVER-MAJOR, UI SDK v1+

#3511 Backport 3510 to release-v1.0
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/NavigationMapRoute.java
Labels: SEMVER-MAJOR, UI SDK v1+

#3507 Fix MapboxNavigationTelemetry init logic
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
Labels: Core SDK v1+, bug, topic: telemetry

#3509 Added utility for creating a route based on manually adding points.
  examples/src/main/java/com/mapbox/navigation/examples/utils/RouteDrawingUtil.kt
Labels: UI SDK v1+, test app

#3516 add api to clear markers
  examples/src/main/java/com/mapbox/navigation/examples/core/FeedbackButtonActivity.kt
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationSymbolManager.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/map/NavigationMapboxMapTest.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/map/NavigationSymbolManagerTest.java
Labels: SEMVER-MAJOR, UI SDK v1+, navigation-ui, ✓ ready for review
