Repository mapbox/mapbox-navigation-android, pull requests merged in 2020-05, with the labels that each got.

#2877 Fix issue #2840
  examples/src/main/java/com/mapbox/navigation/examples/core/FeedbackButtonActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/SummaryBottomSheetActivity.kt
Labels: UI SDK v1+, bug, navigation-ui, quick fix, ✓ ready for review

#2879 Bump NN dependency version to 11.0.2
  gradle/dependencies.gradle
Labels: quick fix, ✓ ready for review

#2885 Fix replay crash and push event issue
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayEventSimulator.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistoryPlayer.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/history/ReplayHistoryPlayerTest.kt
Labels: bug

#2887 Bump Maps SDK dependency version to 9.2.0-beta.1
  gradle/dependencies.gradle
Labels: quick fix, ✓ ready for review

#2886 Fix arrival observer not being notified
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistoryMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/stops/ArrivalProgressObserver.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/history/ReplayHistoryMapperTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/stops/ArrivalProgressObserverTest.kt
Labels: bug

#2898 Fix telemetry access token crash
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
Labels: bug

#2897 Refactored BuildingFootprintHighlightLayer and test app activity
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/UIActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingFootprintHighlightActivityKt.kt
  examples/src/main/res/layout/activity_final_destination_arrival_building_highlight.xml
  examples/src/main/res/values/strings.xml
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/BuildingFootprintHighlightLayer.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java
Labels: SEMVER, UI SDK v1+, refactor, test app, ✓ ready for review

#2881 Fix #2867: puck icon inconsistent issue in example activities
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/DebugMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/FasterRouteActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/FeedbackButtonActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/FreeDriveNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/GuidanceViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/InstructionViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MultipleStopsActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReRouteActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/SummaryBottomSheetActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomUIComponentStyleActivity.kt
Labels: bug, navigation-ui, quick fix, test app, ✓ ready for review

#2884 Refactored BuildingExtrusionLayer and test app activity
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/UIActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/ArrivalUiBuildingExtrusionActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingExtrusionActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingFootprintHighlightActivityKt.kt
  examples/src/main/res/layout/activity_building_extrusion.xml
  examples/src/main/res/values/strings.xml
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/BuildingExtrusionLayer.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/BuildingFootprintHighlightLayer.java
Labels: UI SDK v1+, refactor, test app, ✓ ready for review

#2905 Fix Navigator.reset regression
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/trip/session/MapboxTripSessionTest.kt
Labels: Core SDK v1+, bug, ✓ ready for review

#2907 Refactored `examples` test app titles strings
  examples/src/main/res/values/strings.xml
Labels: refactor, test app

#2900 Fix issue #2848
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/camera/NavigationCamera.java
Labels: bug, navigation-ui, quick fix, ✓ ready for review

#2906 support faster route events in NavigationView and supporting classes
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java
Labels: SEMVER

#2890 Multiple requests test
  libdirections-hybrid/src/main/java/com/mapbox/navigation/route/hybrid/MapboxHybridRouter.kt
  libdirections-hybrid/src/test/java/com/mapbox/navigation/route/hybrid/MapboxHybridRouterTest.kt
Labels: tests

#2911 Fix issue #2869 by removing unneccessary LocationObserver.
  examples/src/main/java/com/mapbox/navigation/examples/core/DebugMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomUIComponentStyleActivity.kt
Labels: bug, navigation-ui, quick fix, test app, ✓ ready for review

#2914 Append SKU token to Route Refresh requests
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/MapboxOffboardRouter.kt
Labels: Core SDK v1+, quick fix, ✓ ready for review

#2918 Follow up of PR#2911 to fix issue #2869
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationContract.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationPresenter.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationView.java
Labels: SEMVER, UI SDK v1+, bug, navigation-ui, quick fix, ✓ ready for review

#2925 Ignore test until fixed
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/SchemaTest.java
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/SchemaTest.java
Labels: quick fix

#2802 Route replay with a smarter driver
  examples/src/main/java/com/mapbox/navigation/examples/core/MultipleStopsActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayActivity.kt
  examples/src/main/res/layout/replay_engine_example_activity_layout.xml
  examples/src/main/res/values/strings.xml
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayRouteMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route2/ReplayProgressObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route2/ReplayRouteDriver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route2/ReplayRouteMapper.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/route2/ReplayRouteDriverTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/route2/ReplayRouteMapperTest.kt
Labels: feature

#2929 Remove ArrivalObserver default implementations
  libnavigation-core/src/main/java/com/mapbox/navigation/core/stops/ArrivalObserver.kt
Labels: Core SDK v1+, quick fix, ✓ ready for review

#2926 Add dependency-graph generation for 1.0 modules
  Makefile
  gradle/dependencies-graph.gradle
  gradle/dependencies.gradle
  libdirections-hybrid/build.gradle
  libdirections-offboard/build.gradle
  libdirections-onboard/build.gradle
  libnavigation-base/build.gradle
  libnavigation-core/build.gradle
  libnavigation-metrics/build.gradle
  libnavigation-util/build.gradle
  libnavigator/build.gradle
  libtrip-notification/build.gradle
Labels: topic: documentation

#2928 adopt core sdk ArrivalObserver change to better support waypoint case
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingFootprintHighlightActivityKt.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewEventDispatcher.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewOptions.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/legacy/RouteUtils.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/listeners/RouteListener.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/NavigationViewEventDispatcherTest.java
Labels: SEMVER, UI SDK v1+, navigation-ui, ✓ ready for review

#2903 MapboxNavigation: accessToken is from single source
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavSdkOnlyActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/DebugMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/FasterRouteActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/FeedbackButtonActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/FreeDriveNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/GuidanceViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/HybridRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/InstructionViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MultipleStopsActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/OnboardRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/OnboardRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReRouteActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/SummaryBottomSheetActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomUIComponentStyleActivity.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouter.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouterTest.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/Endpoint.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
Labels: SEMVER, new API(s)

#2921 Replay player api feedback
  examples/src/main/java/com/mapbox/navigation/examples/core/MultipleStopsActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/res/layout/multiple_stops_example_activity_layout.xml
  examples/src/main/res/layout/replay_engine_example_activity_layout.xml
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayEventSimulator.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayEventsObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistoryLocationEngine.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistoryMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistoryPlayer.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route/ReplayRouteLocationEngine.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route2/ReplayProgressObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route2/ReplayRouteMapper.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/history/ReplayHistoryMapperTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/history/ReplayHistoryPlayerTest.kt
Labels: SEMVER, user: feature request

#2932 Add support of the NavigationListener.onNavigationFinished to fix #2931
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingExtrusionActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingFootprintHighlightActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomCameraActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomPuckActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewActivity.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationLauncher.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
Labels: bug, navigation-ui, ✓ ready for review

#2936 Fix replay route floating point error
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route2/ReplayRouteInterpolator.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/route2/ReplayRouteDriverTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/route2/ReplayRouteInterpolatorTest.kt
Labels: bug

#2944 Fix MapboxHybridRouterTest#networkStatusService_cleanup_calledOnChannelClose flaky test
  libdirections-hybrid/src/test/java/com/mapbox/navigation/route/hybrid/MapboxHybridRouterTest.kt
Labels: Core SDK v1+, quick fix, tests, ✓ ready for review

#2940 Update faster route with list of routes
  examples/src/main/java/com/mapbox/navigation/examples/core/FasterRouteActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/FasterRouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/FasterRouteObserver.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/fasterroute/FasterRouteControllerTest.kt
Labels: SEMVER

#2945 Update replay examples to fit in
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/CoreActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayWaypointsActivity.kt
  examples/src/main/res/layout/activity_replay_history_layout.xml
  examples/src/main/res/layout/activity_replay_route_layout.xml
  examples/src/main/res/layout/activity_replay_waypoints_layout.xml
  examples/src/main/res/values/strings.xml
Labels: refactor, test app

#2951 Remove logger from replay
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayWaypointsActivity.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayEventSimulator.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistoryPlayer.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/history/ReplayHistoryPlayerTest.kt
Labels: SEMVER, user: feedback

#2952 Bump Maps SDK dependency version to 9.2.0
  LICENSE.md
  gradle/dependencies.gradle
Labels: UI SDK v1+, quick fix, ✓ ready for review

#2873 2TAP Feedback flow
  examples/src/main/java/com/mapbox/navigation/examples/core/FeedbackButtonActivity.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/NavigationFeedbackEvent.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/metrics/SchemaTest.java
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryInterface.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationFeedbackEvent.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/SchemaTest.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/feedback/FeedbackBottomSheet.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/feedback/FeedbackItem.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/feedback/FeedbackSubTypeAdapter.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/feedback/FeedbackSubTypeItem.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/feedback/FeedbackSubTypeViewHolder.kt
  libnavigation-ui/src/main/res/drawable/feedback_progress_drawable.xml
  libnavigation-ui/src/main/res/drawable/mapbox_feedback_bottom_report_issue_layout_background.xml
  libnavigation-ui/src/main/res/drawable/mapbox_feedback_report_issue_button_background.xml
  libnavigation-ui/src/main/res/layout/mapbox_feedback_bottom_sheet_layout.xml
  libnavigation-ui/src/main/res/layout/mapbox_feedback_bottom_sheet_top_banner.xml
  libnavigation-ui/src/main/res/layout/mapbox_feedback_detail_viewholder_layout.xml
  libnavigation-ui/src/main/res/values-night/colors.xml
  libnavigation-ui/src/main/res/values/colors.xml
  libnavigation-ui/src/main/res/values/dimens.xml
  libnavigation-ui/src/main/res/values/styles.xml
Labels: SEMVER, UI SDK v1+, navigation-ui, ✓ ready for review

#2941 Rename ArrivalObserver methods name to be more clearer. Fix #2933
  examples/src/main/java/com/mapbox/navigation/examples/core/FasterRouteActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayWaypointsActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingFootprintHighlightActivityKt.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/stops/ArrivalObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/stops/ArrivalProgressObserver.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/stops/ArrivalProgressObserverTest.kt
Labels: SEMVER, quick fix, ✓ ready for review

#2948 Showing wordmark and attribution in NavigationView
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingExtrusionActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingFootprintHighlightActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomCameraActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomPuckActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomUIComponentStyleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewActivity.kt
  examples/src/main/res/layout/activity_custom_ui_component_style.xml
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationView.java
  libnavigation-ui/src/main/res/layout/navigation_view_layout.xml
Labels: UI SDK v1+, ✓ ready for review

#2959 Bump mapbox-java to 5.2.0
  gradle/dependencies.gradle
Labels: new API(s)

#2963 Fixes incorrect capitalization of word in feedback reported thank you message
  libnavigation-ui/src/main/res/values/strings.xml
Labels: UI SDK v1+, bug

#2958 Fix 2954: quick fix to add the access token when create the MapboxNavigation in the NavigationViewModel
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingExtrusionActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingFootprintHighlightActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomCameraActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomPuckActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewActivity.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
Labels: bug, navigation-ui, quick fix, ✓ ready for review

#2970 Remove ManeuverModifier and rely on the one exposed in MAS
  gradle/dependencies.gradle
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/maneuver/ManeuverView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/turnlane/TurnLaneViewData.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/MapFpsDelegate.java
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/MapboxTripNotification.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/maneuver/ManeuverIconHelper.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/maneuver/ManeuverModifier.kt
Labels: quick fix, ✓ ready for review

#2955 Add NN SKU token provider
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/OnboardRouterActivityKt.kt
  gradle/dependencies.gradle
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/internal/navigation/MapboxNavigator.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.java
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxOfflineRouter.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NativeSkuTokenProvider.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/OfflineNavigator.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetector.kt
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/RouteProgressStateMap.kt
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetectorTest.java
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/MapboxOffboardRouter.kt
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/RouteBuilderProvider.kt
  libdirections-offboard/src/test/java/com/mapbox/navigation/route/offboard/MapboxOffboardRouterTest.kt
  libdirections-offboard/src/test/java/com/mapbox/navigation/route/offboard/router/NavigationRouteTest.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouter.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/NativeSkuTokenProvider.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouterTest.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/accounts/SkuTokenProvider.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/accounts/UrlSkuTokenProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/accounts/MapboxNavigationAccounts.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: Core SDK v1+, ✓ ready for review

#2962 audit compatible UI SDK code, check TODOs and remove unused code
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/ConnectivityStatusProvider.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationInstructionListListener.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewEventDispatcher.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewOptions.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/RouteComparator.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/ViewRouteListener.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/listeners/RouteListener.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteDrawableProvider.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/OnPrimaryRouteUpdatedCallback.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/OnRouteFeaturesProcessedCallback.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/AndroidSpeechPlayer.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/VoiceInstructionLoader.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/NavigationViewEventDispatcherTest.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/NavigationViewRouteEngineListenerTest.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/NavigationViewRouterTest.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/voice/VoiceInstructionLoaderTest.java
Labels: SEMVER, navigation-ui, ✓ ready for review

#2979 Bump NN dependency version to 12.0.3
  gradle/dependencies.gradle
Labels: quick fix, ✓ ready for review

#2978 add comments for the custom style items for Doc purpose.
  examples/src/main/res/values/styles.xml
Labels: quick fix, test app, ✓ ready for review

#2974 Add auto and handheld settings profile
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/HybridRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/OffboardRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/OnboardRouterActivityKt.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/DeviceProfile.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/NavigatorLoader.kt
Labels: SEMVER

#2984 Added examples test app activity descriptions
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavSdkOnlyActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/DebugMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/FasterRouteActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/FeedbackButtonActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/FreeDriveNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/GuidanceViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/HybridRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/HybridRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/InstructionViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/OffboardRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/OffboardRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/OnboardRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/OnboardRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReRouteActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayWaypointsActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/SummaryBottomSheetActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/TripServiceActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/TripSessionActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingExtrusionActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingFootprintHighlightActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomCameraActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomPuckActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomUIComponentStyleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewActivity.kt
  examples/src/main/res/values/strings.xml
Labels: Core SDK v1+, UI SDK v1+, test app, topic: documentation

#2983 Rename replay core classes
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayWaypointsActivity.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/MapboxReplayer.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/ReplayLocationEngine.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayEventSimulator.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayEvents.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayEventsObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistoryMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route2/ReplayProgressObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route2/ReplayRouteLocation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route2/ReplayRouteMapper.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/history/MapboxReplayerTest.kt
Labels: SEMVER, refactor, user: feedback

#2980 Fix #2965 to catch the NPE and assign a default value.
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/summary/SummaryBottomSheet.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/summary/SummaryModel.java
Labels: bug, navigation-ui, quick fix, ✓ ready for review

#2985 fix #2837: crash in DownloadTask
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/legacy/DownloadTask.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/MapboxSpeechPlayer.java
Labels: bug, quick fix, ✓ ready for review

#2987 Fix replay index out of bound crash
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route2/ReplayRouteSmoother.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/route2/ReplayRouteDriverTest.kt
Labels: bug

#2990 Provide production routing tiles endpoint
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouter.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
Labels: Core SDK v1+, quick fix, ✓ ready for review

#2995 fix #2994 InstructionListView fade edge color
  libnavigation-ui/src/main/res/values/styles.xml
Labels: quick fix, test app

#2999 Bump Maps SDK dependency version to 9.2.1
  build.gradle
  gradle/dependencies.gradle
Labels: quick fix, ✓ ready for review

#2991 Expose android ui library which is required by Nav UI SDK API transitively from UI SDK
  libnavigation-ui/build.gradle
Labels: navigation-ui, ✓ ready for review

#3000 Fix `CustomUIComponentStyleActivity` SummaryBottomSheet reappearance
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomUIComponentStyleActivity.kt
  examples/src/main/res/layout/activity_custom_ui_component_style.xml
Labels: bug, quick fix, test app, ✓ ready for review

#2993 Remove unused default from old replay
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route/ReplayLocationConverter.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route/ReplayRouteLocationConverter.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route/ReplayRouteLocationEngine.kt
Labels: SEMVER, refactor

#3003 Ship with Java 8 bytecode
  LICENSE.md
  build.gradle
  carbon/build.gradle
  gradle/dependencies.gradle
  libdirections-hybrid/build.gradle
  libdirections-offboard/build.gradle
  libdirections-onboard/build.gradle
  libnavigation-base/build.gradle
  libnavigation-core/build.gradle
  libnavigation-metrics/build.gradle
  libnavigation-util/build.gradle
  libnavigator/build.gradle
  libnavui-alert/build.gradle
  libnavui-base/build.gradle
  libnavui-feedback/build.gradle
  libnavui-guidance/build.gradle
  libnavui-maps/build.gradle
  libnavui-summary/build.gradle
  libnavui-util/build.gradle
  libnavui-voice/build.gradle
  libtesting-ui/build.gradle
  libtesting-utils/build.gradle
  libtrip-notification/build.gradle
Labels: Core SDK v1+

#3004 Fix toBuilder for isDebugLoggingEnabled and deviceProfile
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
Labels: SEMVER

#3008 fix issue: the MapboxSpeech offline cache interceptor is overriden and lost by #2962
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/VoiceInstructionLoader.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/voice/VoiceInstructionLoaderTest.java
Labels: bug, navigation-ui, quick fix, ✓ ready for review

#2992 Migrate progress classes to data objects
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/DebugMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingExtrusionActivity.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/RouteLegProgress.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/RouteProgress.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/RouteStepProgress.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/AdjustedRouteOptionsProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/FasterRouteDetector.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/MapboxDistanceFormatter.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route2/ReplayProgressObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/stops/ArrivalProgressObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/TelemetryLocationAndProgressDispatcher.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/MetricsRouteProgress.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/BannerInstructionEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/VoiceInstructionEvent.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/fasterroute/FasterRouteControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/fasterroute/FasterRouteDetectorTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/trip/session/MapboxTripSessionTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/stops/ArrivalProgressObserverTest.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/MapOfflineManager.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/camera/DynamicCamera.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/camera/NavigationCamera.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/camera/SimpleCamera.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionModel.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/MapFpsDelegate.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/MapWayNameChangeObserver.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/puck/NavigationPuckPresenter.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteArrow.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListener.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/summary/SummaryModel.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/summary/list/InstructionListPresenter.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/MapOfflineManagerTest.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/OfflineMetadataProviderTest.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/camera/DynamicCameraTest.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/puck/NavigationPuckPresenterTest.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListenerTest.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/summary/SummaryModelTest.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/MapboxTripNotification.kt
  libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/MapboxTripNotificationTest.kt
Labels: SEMVER

#3015 Migrate option comments to be consistent
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route2/ReplayRouteOptions.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/sensors/SensorOptions.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/stops/ArrivalController.kt
Labels: SEMVER

#3002 When the progress listener is observed in NavigationMapRoute the obse…
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListener.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/NavigationMapRoute.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListenerTest.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/NavigationMapRouteTest.java
Labels: UI SDK v1+

#3019 Fix flaky HybridRouterTest
  libdirections-hybrid/src/main/java/com/mapbox/navigation/route/hybrid/MapboxHybridRouter.kt
  libdirections-hybrid/src/test/java/com/mapbox/navigation/route/hybrid/MapboxHybridRouterTest.kt
Labels: bug

#3010 Added a value animator to the vanishing route line to improve the vis…
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListener.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/RouteConstants.java
Labels: UI SDK v1+

#3017 dokka: - change javadoc to kdoc(default value); - change output dir.
  libdirections-hybrid/build.gradle
  libdirections-offboard/build.gradle
  libdirections-onboard/build.gradle
  libnavigation-base/build.gradle
  libnavigation-core/build.gradle
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/TelemetryLocationAndProgressDispatcher.kt
  libnavigation-metrics/build.gradle
  libnavigation-ui/build.gradle
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/camera/CameraUpdateMode.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/camera/CameraUpdateMode.kt
  libnavigation-util/build.gradle
  libnavigator/build.gradle
  libnavui-alert/build.gradle
  libnavui-alert/src/main/java/com/mapbox/navigation/ui/alert/AlertProcessor.kt
  libnavui-base/build.gradle
  libnavui-feedback/build.gradle
  libnavui-guidance/build.gradle
  libnavui-maps/build.gradle
  libnavui-summary/build.gradle
  libnavui-util/build.gradle
  libnavui-voice/build.gradle
  libtrip-notification/build.gradle
Labels: topic: documentation, ✓ ready for review

#3023 Fix memory leak due to builder with Context in constructor
  examples/src/main/java/com/mapbox/navigation/examples/core/TripServiceActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/TripSessionActivityKt.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/MapboxDistanceFormatter.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/MapboxDistanceFormatterTest.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/summary/SummaryBottomSheet.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/summary/SummaryModelTest.kt
Labels: SEMVER, bug

#3026 fix regression when session is in free drive the vanishing route line…
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListener.kt
Labels: UI SDK v1+, bug, quick fix

#3027 NavigationView: fix LifecycleRegistry calls
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationView.java
Labels: UI SDK v1+, bug, navigation-ui, quick fix, ✓ ready for review

#3035 fix issue #3031: the feedback button and sound button visibility changes in landscape mode
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/UtteranceListener.java
Labels: bug, navigation-ui, quick fix

#3038 Fix stopping location updates when location engine callback on failure
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/trip/session/MapboxTripSessionTest.kt
Labels: Core SDK v1+, bug, quick fix, topic: location, ✓ ready for review

#3020 Update onboard route options
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/DebugMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/FasterRouteActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/FreeDriveNavigationActivity.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouter.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouterTest.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/Endpoint.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/MapboxOnboardRouterConfig.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/OnboardRouterOptions.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/NavigationOptionsTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/OnboardRouterOptionsTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
Labels: SEMVER

#3042 Update arrival package name
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayWaypointsActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/BuildingFootprintHighlightActivityKt.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/arrival/ArrivalController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/arrival/ArrivalObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/arrival/ArrivalProgressObserver.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/arrival/ArrivalProgressObserverTest.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewEventDispatcher.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewOptions.java
Labels: SEMVER

#3043 General cleanup and minor tweaks
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/BaseRouterActivityKt.kt
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/router/ElapsedTime.kt
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/router/MapboxDirectionsUtils.kt
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/router/NavigationRouteEventListener.kt
  libdirections-offboard/src/test/java/com/mapbox/navigation/route/offboard/router/NavigationRouteTest.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouter.kt
  libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/OfflineRoute.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/MapboxOnboardRouterTest.kt
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/OfflineRouteTest.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/extensions/RouteOptionsUtils.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/route/RouteUrl.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/RouteProgressState.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/utils/NullUtils.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/route/internal/RouteUrlTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/MapboxDistanceFormatter.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/trip/service/MapboxTripService.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/trip/service/TripService.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/MapboxReplayer.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route/ReplayLocationDispatcher.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route2/ReplayProgressObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route2/ReplayRouteDriver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route2/ReplayRouteMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route2/ReplayRouteOptions.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/sensors/SensorEventEmitter.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/sensors/SensorOptions.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/NavigationException.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/AsyncEx.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/MapboxTimer.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/NullUtils.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/time/span/SpanEx.kt
Labels: Core SDK v1+, ✓ ready for review

#3044 Example activity demonstrating customization of the route line colors
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/CoreActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/CustomRouteStylingActivity.kt
  examples/src/main/res/values/colors.xml
  examples/src/main/res/values/strings.xml
  examples/src/main/res/values/styles.xml
Labels: ✓ ready for review

#3047 Fix #2764: the view order in layout matters. Move instruction list view to the last view in layout.
  libnavigation-ui/src/main/res/layout-land/feedback_viewholder_layout.xml
  libnavigation-ui/src/main/res/layout-land/instruction_layout.xml
  libnavigation-ui/src/main/res/layout/instruction_view_layout.xml
Labels: bug, navigation-ui, ✓ ready for review
