Repository mapbox/mapbox-navigation-android, pull requests merged in 2020-02, with the labels that each got.

#2451 Move `Camera`, `RouteInformation` and `SimpleCamera` to UI module
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/camera/Camera.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/camera/RouteInformation.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/camera/SimpleCamera.kt
Labels: navigation-ui, new API(s)

#2468 Release v0.42.5
  CHANGELOG.md
  README.md
Labels: navigation-core, navigation-ui, release

#2470 Fix README release v0.42.5 typo
  CHANGELOG.md
Labels: navigation-core, navigation-ui, release

#2471 Update CHANGELOG and README from release v0.42.5
  CHANGELOG.md
  README.md
Labels: navigation-core, navigation-ui, release

#2463 Fix flaky UI tests (#2403)
  examples/build.gradle
  examples/src/androidTest/java/com/mapbox/navigation/examples/activity/TripServiceActivityKtTest.kt
  gradle/testing-dependencies.gradle
  libdirections-hybrid/build.gradle
  libdirections-offboard/build.gradle
  libdirections-onboard/build.gradle
  liblogger/build.gradle
  libnavigation-base/build.gradle
  libnavigation-core/build.gradle
  libnavigation-metrics/build.gradle
  libnavigation-util/build.gradle
  libnavigator/build.gradle
  libtesting-ui/.gitignore
  libtesting-ui/build.gradle
  libtesting-ui/consumer-rules.pro
  libtesting-ui/proguard-rules.pro
  libtesting-ui/src/main/AndroidManifest.xml
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/BaseTestRule.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/NotificationTestRule.kt
  libtesting-utils/.gitignore
  libtesting-utils/build.gradle
  libtesting-utils/consumer-rules.pro
  libtesting-utils/proguard-rules.pro
  libtesting-utils/src/main/AndroidManifest.xml
  libtesting-utils/src/main/java/com/mapbox/navigation/testing/MainCoroutineRule.kt
  libtrip-notification/build.gradle
  settings.gradle
Labels: tests

#2398 Add docs for Logger module
  liblogger/src/main/java/com/mapbox/navigation/logger/LogEntry.kt
  liblogger/src/main/java/com/mapbox/navigation/logger/LogPriority.kt
  liblogger/src/main/java/com/mapbox/navigation/logger/LoggerObserver.kt
  liblogger/src/main/java/com/mapbox/navigation/logger/MapboxLogger.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/logger/Logger.kt
Labels: topic: documentation

#2477 Refactored RouteOptions integration
  gradle/dependencies.gradle
  libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRoute.kt
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/RouteBuilderProvider.kt
  libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/router/MapboxDirectionsUtils.kt
  libdirections-offboard/src/test/java/com/mapbox/navigation/route/offboard/router/NavigationRouteTest.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/extensions/RouteOptionsUtils.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
Labels: refactor

#2500 Refactor examples module
  examples/src/androidTest/java/com/mapbox/navigation/examples/activity/TripServiceActivityKtTest.kt
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/CoreActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ExamplesAdapter.kt
  examples/src/main/java/com/mapbox/navigation/examples/MainActivity.java
  examples/src/main/java/com/mapbox/navigation/examples/MainActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/UIActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/OffboardRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/OffboardRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/OnboardRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/OnboardRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/TripServiceActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/TripSessionActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/settings/NavigationSettingsActivity.java
  examples/src/main/java/com/mapbox/navigation/examples/settings/OfflineRegionDownloadActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/MockNavigationActivity.java
  examples/src/main/java/com/mapbox/navigation/examples/ui/notification/CustomNavigationNotification.java
  examples/src/main/res/layout/activity_core.xml
  examples/src/main/res/layout/activity_main.xml
  examples/src/main/res/layout/activity_mock_navigation.xml
  examples/src/main/res/layout/activity_offline_region_download.xml
  examples/src/main/res/layout/activity_simple_mapbox_navigation.xml
  examples/src/main/res/layout/activity_trip_service.xml
  examples/src/main/res/layout/activity_trip_session.xml
  examples/src/main/res/layout/activity_ui.xml
  examples/src/main/res/layout/content_simple_mapbox_navigation.xml
  examples/src/main/res/layout/item_examples_adapter.xml
  examples/src/main/res/layout/item_main_feature.xml
  examples/src/main/res/values/strings.xml
  examples/src/main/res/xml/fragment_navigation_preferences.xml
Labels: feature, navigation-core, navigation-ui

#2505 Fix Checkstyle compile issues.
  config/checkstyle/checkstyle.xml
  gradle/checkstyle.gradle
  libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/NodeCreator.java
Labels: quick fix

#2506 #248 - Compatability of examples with new ui module
  examples/build.gradle
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/core/OffboardRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/OffboardRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/OnboardRouterActivityJava.java
  examples/src/main/java/com/mapbox/navigation/examples/core/OnboardRouterActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/TripServiceActivityKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/settings/OfflineRegionDownloadActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/MockNavigationActivity.java
  examples/src/main/java/com/mapbox/navigation/examples/ui/notification/CustomNavigationNotification.java
  examples/src/main/res/xml/fragment_navigation_preferences.xml
  libnavigation-core/build.gradle
  libnavigation-ui/build.gradle
Labels: navigation-ui

#2510 Move to androidx and material components
  libandroid-navigation-ui/src/main/res/layout-land/feedback_viewholder_layout.xml
  libandroid-navigation-ui/src/main/res/layout/feedback_viewholder_layout.xml
  libnavigation-ui/src/main/res/layout-land/feedback_viewholder_layout.xml
  libnavigation-ui/src/main/res/layout/feedback_viewholder_layout.xml
  libnavigation-ui/src/main/res/values/styles.xml
Labels: navigation-ui, refactor, ✓ ready for review

#2466 Add sensor data interface
  gradle/dependencies.gradle
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSession.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/MapboxNativeNavigatorImpl.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/SensorMapper.kt
  libnavigator/src/test/java/com/mapbox/navigation/navigator/SensorMapperTest.kt
Labels: feature, ✓ ready for review

#2517 Bump mapbox-android-telemetry version to 4.7.3
  LICENSE.md
  gradle/dependencies.gradle
  libandroid-navigation/build.gradle
  libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/internal/navigation/NavigationEventDispatcherTest.java
Labels: quick fix, topic: telemetry, ✓ ready for review

#2518 ReRoute fix
  libdirections-onboard/src/test/java/com/mapbox/navigation/route/onboard/task/RemoveTilesTaskTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
Labels: bug
