Repository mapbox/mapbox-navigation-android, pull requests merged in 2020-11, with the labels that each got.

#3704 examples RouteAlertActivity: added `IncidentAlert`
  examples/src/main/java/com/mapbox/navigation/examples/core/RouteAlertsActivity.kt
  examples/src/main/res/drawable/ic_circle_black.xml
  examples/src/main/res/raw/mock_response_all_route_alerts_polyline6.json
Labels: test app

#3725 Fix #3713: add null check before using the voiceUnits from routeOptions
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
Labels: navigation-ui, quick fix

#3727 Improve vanishing point's state when completing the leg of a route or going off-route
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayActivity.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/route/RouteConstants.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListener.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/NavigationMapRoute.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteLineTest.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListenerTest.kt
  libnavigation-ui/src/test/resources/vanish_point_test_multi_leg.json
Labels: UI SDK v1+

#3732 Bump maps sdk to 9.6.0
  gradle/dependencies.gradle
Labels: UI SDK v1+

#3730 Exposed MapMatcherResultObserver
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/res/layout/activity_replay_history_layout.xml
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/NavigatorMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapMatcherResult.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapMatcherResultObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/navigator/NavigatorMapperTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/TripStatus.kt
Labels: Core SDK v1+

#3731 Use immediate tracking transition when NN reports teleport
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/map/NavigationMapboxMapTest.java
Labels: UI SDK v1+

#3672 Through the styles an override can be provided for specified road classes
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationActivity.kt
  examples/src/main/res/values/styles.xml
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/route/RouteConstants.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
  libnavigation-ui/src/main/res/values/attrs.xml
  libnavigation-ui/src/main/res/values/styles.xml
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteLineTest.kt
  libnavigation-ui/src/test/resources/build_route_line_expression_multileg_text.txt
  libnavigation-ui/src/test/resources/motorway-route-with-road-classes-mixed.json
  libnavigation-ui/src/test/resources/motorway-route-with-road-classes-unknown-not-on-intersection.json
  libnavigation-ui/src/test/resources/motorway-route-with-road-classes.json
  libnavigation-ui/src/test/resources/motorway-with-road-classes-multi-leg.json
  libnavigation-ui/src/test/resources/route-unique-road-classes.json
  libnavigation-ui/src/test/resources/route-with-missing-road-classes.json
  libnavigation-ui/src/test/resources/route-with-road-classes.txt
  libnavigation-ui/src/test/resources/route-with-traffic-no-street-classes.txt
Labels: UI SDK v1+

#3741 Bump mapbox-navigation-native dependency version to 26.2.0
  gradle/dependencies.gradle
Labels: quick fix, ✓ ready for review

#3740 Update EHorizon mpp functions so they return a list of list of Edges
  examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/EHorizonPosition.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/Edge.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/EdgeVisitor.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/NameInfo.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/EHorizonPositionTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/EHorizonTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/EdgeTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/NameInfoTest.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/model/eh/EHorizon.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/model/eh/EHorizonPosition.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/model/eh/EHorizonResultType.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/model/eh/Edge.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/model/eh/FunctionalRoadClass.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/model/eh/NameInfo.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/EHorizonObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/ElectronicHorizonObserverImpl.kt
Labels: Core SDK v1+, SEMVER-MAJOR

#3742 Add CHANGELOG for 1.2.0-beta.1
  CHANGELOG.md
Labels: quick fix, ✓ ready for review

#3739 gitingore for publish-production
  .gitignore
Labels: topic: documentation

#3744 Fix a bug where `RouteAlertGeometry.toLineString` would not return last geometry segment
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/alert/RouteAlertUtils.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/alert/RouteAlertUtilsTest.kt
  libnavigation-base/src/test/resources/mock_response_multi_leg_route_alerts_restricted_tunnel.json
Labels: Core SDK v1+, needs-backporting

#3745 Introduce `NavigationMapboxMap.Builder` and expose vanishing point update interval
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationFragment.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/DebugMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/FasterRouteActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/FeedbackButtonActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/FreeDriveNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/GuidanceViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/InstructionViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapMatchingActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReRouteActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayWaypointsActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/RouteAlertsActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/SummaryBottomSheetActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomUIComponentStyleActivity.kt
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationConstants.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationView.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/NavigationMapRoute.java
Labels: UI SDK v1+, needs-backporting

#3748 Remove Electronic Horizon experimental note from EHorizonOptions and set EHorizonOptions from NavigationOptions to NavigatorConfig
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/EHorizonOptions.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
Labels: needs-backporting, quick fix, topic: documentation, ✓ ready for review

#3749 CP: Remove Electronic Horizon experimental note from EHorizonOptions and set EHorizonOptions from NavigationOptions to NavigatorConfig
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/EHorizonOptions.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
Labels: quick fix, ✓ ready for review

#3752 Update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: operational excellence, skip changelog

#3754 Validate that changelog is provided for each PR description
  circle.yml
  scripts/validate-changelog.py
Labels: operational excellence, skip changelog

#3759 Use GPS direction for replay history example
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
Labels: skip changelog

#3761 Bump Nav Native to 26.3.0
  gradle/dependencies.gradle
Labels: Core

#3762 Backport #3761 to 1.2
  gradle/dependencies.gradle
Labels: Core

#3751 Send FreeDrive Telemetry events
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/metrics/MetricEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/MetricsLocation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationFreeDriveEvent.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/SchemaTest.kt
  libnavigation-metrics/src/main/java/com/mapbox/navigation/metrics/extensions/MetricEventEx.kt
Labels: feature, needs-backporting

#3769 update snapshot version to 1.3.0-SNAPSHOT
  gradle.properties
Labels: skip changelog

#3768 Improve route comparator interface
  libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/FasterRouteDetector.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/RouteComparator.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/fasterroute/FasterRouteDetectorTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/fasterroute/RouteComparatorTest.kt
Labels: skip changelog

#3770 Fix NPE in Telemetry and avoid dropping events when destroying MapboxNavigation
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
Labels: Core, bug, needs-backporting

#3771 Add unit tests for replay location engine
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/ReplayLocationEngineTest.kt
Labels: operational excellence, skip changelog

#3772 Backport #3770 to 1.2
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
Labels: Core, bug

#3764 add changelog for 1.2.0-rc.1
  CHANGELOG.md
Labels: skip changelog

#3773 adds changelog for 1.2.0-rc.2 nav sdk release
  CHANGELOG.md
Labels: skip changelog

#3774 Backport #3764 to 1.2
  CHANGELOG.md
Labels: skip changelog

#3776 Backport #3773 to release 1.2
  CHANGELOG.md
Labels: skip changelog

#3781 Officially mark the Nav SDK v1 library Android SDK 21 dependency
  gradle/dependencies.gradle
Labels: Core, UI

#3777 Add tests for electronic horizon
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/model/eh/EHorizonMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/model/eh/Edge.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/ElectronicHorizonObserverImpl.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/model/eh/EHorizonMapperTest.kt
  libnavigation-core/src/test/resources/com.mapbox.navigation.core.ehorizon/ehorizon_long_branch.txt
  libnavigation-core/src/test/resources/com.mapbox.navigation.core.ehorizon/ehorizon_small_graph.txt
Labels: needs-backporting, skip changelog

#3782 Cherry-pick test ehorizon
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/model/eh/EHorizonMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/model/eh/Edge.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/ElectronicHorizonObserverImpl.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/model/eh/EHorizonMapperTest.kt
  libnavigation-core/src/test/resources/com.mapbox.navigation.core.ehorizon/ehorizon_long_branch.txt
  libnavigation-core/src/test/resources/com.mapbox.navigation.core.ehorizon/ehorizon_small_graph.txt
Labels: skip changelog

#3783 add changelog for 1.3-alpha.1
  CHANGELOG.md
Labels: skip changelog

#3784 Post code coverage to pull requests
  codecov.yml
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/model/eh/EHorizonMapperTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/model/eh/EHorizonTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/model/eh/EHorizonTestUtil.kt
Labels: skip changelog

#3790 Fix mobile metrics parameters
  scripts/trigger-mobile-metrics.py
Labels: skip changelog

#3793 Bump mapbox-navigation-native dependency version to 26.3.1
  gradle/dependencies.gradle
Labels: needs-backporting, skip changelog

#3795 Backport #3793 to 1.2 release branch
  gradle/dependencies.gradle
Labels: skip changelog

#3791 FreeDrive event location fix
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
Labels: bug, needs-backporting

#3794 Fix mobile metrics jobs
  scripts/trigger-mobile-metrics.py
Labels: skip changelog

#3789 Move route line calculations off of main thread
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteLineTest.kt
  libtesting-utils/src/main/java/com/mapbox/navigation/testing/MainCoroutineRule.kt
Labels: UI, needs-backporting

#3723 click detection working with queryRenderedFeatures
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/CoreActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/CustomAlternativeRouteClickPaddingActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/NavigationMapRouteActivity.java
  examples/src/main/res/layout/activity_alternative_route_click_padding.xml
  examples/src/main/res/values/strings.xml
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/route/RouteConstants.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteClickListener.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/NavigationMapRoute.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteClickListenerTest.java
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/MapRouteLineTest.kt
  libnavigation-ui/src/test/java/com/mapbox/navigation/ui/route/NavigationMapRouteTest.java
Labels: UI

#3796 Backport #3791 to 1.2 release branch
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
Labels: Core, bug

#3799 Update changelog for v1.2 release
  CHANGELOG.md
Labels: skip changelog

#3798 Update changelog for v1.2 release
  CHANGELOG.md
Labels: skip changelog

#3802 Bump routing tiles version to 2020_11_15-03_00_00
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/OnboardRouterOptions.kt
Labels: Core

#3801 Add changelog for 1.3.0-alpha.2
  CHANGELOG.md
Labels: skip changelog

#3803 Increase map-matching to route geometry precision threshold to enable vanishing route line to 3m
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/route/RouteConstants.java
Labels: UI

#3809 Bump mapbox-java to 5.8.0-beta.4
  gradle/dependencies.gradle
Labels: Core

#3724 Expose feedback cache API for Feedback 2.0 UX
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationFragment.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/telemetry/CachedNavigationFeedbackEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/telemetry/MapboxNavigationFeedbackCache.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationFeedbackEvent.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
Labels: Core

#3810 Expose current intersection index
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/RouteStepProgress.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/RouteStepProgressTest.kt
  libnavigator/build.gradle
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/NavigatorMapper.kt
  libnavigator/src/test/java/com/mapbox/navigation/navigator/NavigatorMapperTest.kt
  libnavigator/src/test/resources/multileg_route.json
  libtesting-utils/src/main/java/com/mapbox/navigation/testing/FileUtils.kt
Labels: Core, feature

#3812 Bump routing tiles version to 2020_11_21-03_00_00
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/OnboardRouterOptions.kt
Labels: Core

#3813 Bump Kotlin std lib and plugin version to 1.4.20
  gradle/dependencies.gradle
Labels: skip changelog

#3820 Bump mapboxEvents and mapboxCore dependency versions to 6.2.2 and 3.1.1 respectively
  gradle/dependencies.gradle
Labels: needs-backporting

#3804 Move location polling options
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/LocationPollingOptions.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/LocationPollingOptionsTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/NavigationOptionsTest.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
Labels: needs-backporting

#3824 Changelog for v1.2.1
  CHANGELOG.md
Labels: skip changelog

#3829 changelog for v1.3.0-alpha.3
  CHANGELOG.md
Labels: skip changelog

#3837 Bump mapbox-navigation-native dependency version to 27.0.0
  gradle/dependencies.gradle
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/ElectronicHorizonObserverImpl.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/ActiveGuidanceOptionsMapper.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavigator/src/test/java/com/mapbox/navigation/navigator/ActiveGuidanceOptionsMapperTest.kt
Labels: skip changelog
