Repository mapbox/mapbox-navigation-android, pull requests merged in 2021-01, with the labels that each got.

#3889 Note undocumented SpeedLimitView class
  scripts/undocumented_classes.txt
Labels: UI, skip changelog

#3891 check whether voice file was successfully set to the media player
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/MapboxSpeechPlayer.java
Labels: UI

#3890 dokka: remove plugin from undocumented modules
  build.gradle
  gradle/kdoc-settings.gradle
  gradle/publish.gradle
  libnavigation-base/build.gradle
  libnavigation-core/build.gradle
  libnavigation-metrics/build.gradle
  libnavigation-router/build.gradle
  libnavigation-ui/build.gradle
  libnavigation-util/build.gradle
  libnavigator/build.gradle
  libtrip-notification/build.gradle
Labels: skip changelog

#3899 MapboxRouteOptionsUpdater: fix Bearings combining
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdater.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdaterTest.kt
Labels: bug

#3903 Add CHANGELOG for 1.4.0-rc.1
  CHANGELOG.md
Labels: needs-backporting, skip changelog

#3905 Bump mapbox-navigation-native version to 29.0.0
  gradle/dependencies.gradle
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
Labels: Core, skip changelog

#3909 bump snapshot version to 1.5.0-SNAPSHOT
  gradle.properties
Labels: skip changelog

#3914 bump mapbox-java to v5.8.0
  gradle/dependencies.gradle
Labels: Core, needs-backporting, skip changelog

#3913 Removed ACCESS_BACKGROUND_LOCATION permission requirement
  examples/src/main/java/com/mapbox/navigation/examples/LocationPermissionsHelper.kt
  libnavigation-core/src/main/AndroidManifest.xml
Labels: Core, needs-backporting

#3916 Updating the change log to reflect the 1.4 release.
  CHANGELOG.md
Labels: skip changelog

#3918 Add Nav-Native SDK version to tile endpoint configuration
  libnavigation-core/build.gradle
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
Labels: Core

#3919 Fix stop trip session issue
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
Labels: bug
