Repository mapbox/mapbox-navigation-android, pull requests merged in 2021-05, with the labels that each got.

#4355 refactor the MapboxNavigationActivity
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  examples/src/main/res/layout/layout_activity_navigation.xml
Labels: skip changelog

#4356 Rename `mapbox-access-token` to `mapbox_access_token` in docs.
  CONTRIBUTING.md
Labels: skip changelog

#4318 Bump `kotlinStdLib`, `coroutinesAndroid` and JaCoCo dependency version
  LICENSE.md
  gradle/dependencies.gradle
  gradle/jacoco.gradle
Labels: skip changelog

#4367 changelog for v2.0.0-beta.9
  CHANGELOG.md
Labels: skip changelog

#4381 Bump `compileSdkVersion` and targetSdkVersion and CI `android-ndk` image to `30` and `r21e` respectively
  .circleci/config.yml
  gradle/dependencies.gradle
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/ApplicationLifecycleMonitor.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/NetworkStatusService.kt
Labels: skip changelog

#4384 catch more `MapboxRouteOptionsUpdater` exceptions and print additional data
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdater.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdaterParameterizedTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdaterTest.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/LoggerProvider.kt
Labels: skip changelog

#4373 Add ability to override PlayerAttributes properties
  libnavui-voice/api/current.txt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/AudioFocusDelegateProvider.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceInstructionsPlayer.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/OreoAndLaterAudioFocusDelegate.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/PreOreoAudioFocusDelegate.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsFilePlayer.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsFilePlayerProvider.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsPlayerAttributes.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsPlayerAttributesProvider.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsTextPlayer.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsTextPlayerProvider.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/options/PlayerAttributesProvider.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/options/VoiceInstructionsPlayerOptions.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/AudioFocusDelegateProviderTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceInstructionsPlayerTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/OreoAndLaterAudioFocusDelegateTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/PreOreoAudioFocusDelegateTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsPlayerAttributesProviderTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/options/PlayerAttributesProviderTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/options/VoiceInstructionsPlayerOptionsTest.kt
Labels: bug

#4385 refactor primary secondary and sub maneuver
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/model/ExitStyleGenerator.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/model/ManeuverInstructionGenerator.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/model/RoadShieldGenerator.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/view/MapboxPrimaryManeuver.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/view/MapboxSecondaryManeuver.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/view/MapboxSubManeuver.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/model/ExitStyleGeneratorTest.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/model/ManeuverInstructionGeneratorTest.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/model/RoadShieldGeneratorTest.kt
  libnavui-util/src/main/java/com/mapbox/navigation/ui/utils/internal/extensions/BitmapEx.kt
  libnavui-util/src/main/java/com/mapbox/navigation/ui/utils/internal/extensions/TextViewEx.kt
Labels: skip changelog

#4386 Add `v2.0.0-beta.9.1` and `v2.0.0-beta.10` `CHANGELOG` entries
  CHANGELOG.md
Labels: skip changelog

#4392 check route state before triggering arrival
  gradle/jacoco.gradle
  libnavigation-core/src/main/java/com/mapbox/navigation/core/arrival/ArrivalObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/arrival/ArrivalProgressObserver.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/arrival/ArrivalProgressObserverTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/arrival/RouteStateObserverParametrizedTest.kt
Labels: Core

#4396 updated telemetry to 7.0.1 and location core to 4.0.1
  LICENSE.md
  gradle/dependencies.gradle
Labels: skip changelog

#4411 Bump coroutines version to `1.5.0`
  gradle/dependencies.gradle
Labels: skip changelog

#4390 Fix EH docs and migration guide
  docs/eh_v3.md
  docs/electronic_horizon.md
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/border/CountryBorderCrossing.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/incident/Incident.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/restrictedarea/RestrictedArea.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/reststop/RestStop.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/tollcollection/TollCollection.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/tunnel/Tunnel.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/eh/EHorizonObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/eh/RoadObjectsStore.kt
Labels: nav sdk 2.0 migration, skip changelog

#4415 removed obsolete package.json declaration
  package.json
Labels: skip changelog

#4408 Add TileStore param to RoutingTilesOptions
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/tilestore/TileStoreProvider.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/RoutingTilesOptions.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/NavigationOptionsTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/RoutingTilesOptionsTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
Labels: new API(s)

#4375 Route alternatives (aka FasterRoute v2)
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/idling/RouteAlternativesIdlingResource.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/idling/RouteRequestIdlingResource.kt
  instrumentation-tests/src/main/res/raw/route_response_alternative_during_navigation.json
  instrumentation-tests/src/main/res/raw/route_response_alternative_start.json
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/RouteAlternativesOptions.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/NavigationOptionsTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/route/RouteAlternativesOptionsTest.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/FasterRouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/FasterRouteDetector.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/FasterRouteObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/RouteComparator.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesControllerProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routeoptions/RouteOptionsUpdater.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/alternatives/RouteAlternativesControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/fasterroute/FasterRouteControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/fasterroute/FasterRouteDetectorTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/fasterroute/RouteComparatorTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/ActiveGuidanceOptionsMapper.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavigator/src/test/java/com/mapbox/navigation/navigator/ActiveGuidanceOptionsMapperParameterizedTest.kt
  libnavigator/src/test/java/com/mapbox/navigation/navigator/ActiveGuidanceOptionsMapperTest.kt
Labels: Core, SEMVER-MAJOR, feature

#4416 Mobile metrics: enable benchmarks
  .circleci/config.yml
  scripts/trigger-mobile-metrics.py
Labels: skip changelog

#4417 Upgrade Nav Native to v50.0.0, Maps SDK to 10.0.0-beta.20, and Common SDK to v12.0.0
  LICENSE.md
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/MapboxCameraAnimationsActivity.kt
  gradle/dependencies.gradle
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/roadobject/RoadObjectMapperTest.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/NavigatorMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/eh/RoadObjectMatcher.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/eh/RoadObjectMatcherObserver.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/navigator/NavigatorMapperTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/onboard/MapboxOnboardRouterTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/ActiveGuidanceOptionsMapper.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/NavigatorLoader.kt
  libnavigator/src/test/java/com/mapbox/navigation/navigator/ActiveGuidanceOptionsMapperParameterizedTest.kt
  libnavigator/src/test/java/com/mapbox/navigation/navigator/ActiveGuidanceOptionsMapperTest.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/TurnIconHelperTest.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/PredictiveCacheController.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/debugger/MapboxNavigationViewportDataSourceDebugger.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/guidance/junction/JunctionAction.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/guidance/junction/JunctionProcessor.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/guidance/signboard/SignboardAction.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/guidance/signboard/SignboardProcessor.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/PredictiveCacheControllerTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/arrival/api/MapboxBuildingHighlightApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/common/ShadowValueConverter.java
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/guidance/junction/JunctionProcessorTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/guidance/junction/api/MapboxJunctionApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/guidance/signboard/SignboardProcessorTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/guidance/signboard/api/MapboxSignboardApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/RouteArrowUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/api/MapboxRouteArrowViewTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineViewTest.kt
Labels: ⚠️ DO NOT MERGE

#4434 Changelog 2.0.0-beta.11
  CHANGELOG.md
Labels: skip changelog

#4443 updated telemetry to v7.0.3
  gradle/dependencies.gradle
Labels: skip changelog

#4450 added known issue with `WRITE_SETTINGS` permission to changelog
  CHANGELOG.md
Labels: skip changelog

#4452 added @mapbox/navigation-android as codeowner
  .github/CODEOWNERS
Labels: skip changelog

#4424 `Def`s retention policy review
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/TimeFormat.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/formatter/Rounding.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/metrics/MetricEvent.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/eh/EHorizonResultType.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/eh/OpenLRStandard.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/eh/RoadClass.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/RoadObjectProvider.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/RoadObjectType.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/distanceinfo/RoadObjectDistanceInfoType.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/incident/IncidentImpact.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/incident/IncidentType.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/location/OpenLROrientation.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/location/OpenLRSideOfRoad.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/location/RoadObjectLocationType.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/reststop/RestStopType.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/tollcollection/TollCollectionType.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/FeedbackEvent.kt
Labels: skip changelog, ⚠️ release blocker

#4447 Updated inline documentation.
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/arrow/api/MapboxRouteArrowApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
Labels: skip changelog

#4301 Update to fix compilation error and added internal route line activity.
  examples/src/main/java/com/mapbox/navigation/examples/MainActivity.kt
  examples/src/main/res/values/strings.xml
  qa-test-app/src/main/AndroidManifest.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivitySuite.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxRouteLineActivity.java
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/util/RouteDrawingActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/util/RouteDrawingUtil.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/util/Utils.kt
  qa-test-app/src/main/res/drawable/ic_layers_24dp.xml
  qa-test-app/src/main/res/layout/layout_activity_routeline.xml
  qa-test-app/src/main/res/layout/layout_route_drawing_activity.xml
  qa-test-app/src/main/res/values/strings.xml
Labels: skip changelog

#4427 Add route refresh integration test
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteRefreshTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/http/MockDirectionsRefreshHandler.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/idling/IdlingPolicyTimeoutRule.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/idling/RoutesObserverIdlingResource.kt
  instrumentation-tests/src/main/res/raw/route_response_route_refresh.json
  instrumentation-tests/src/main/res/raw/route_response_route_refresh_annotations.json
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshController.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouter.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouterTest.kt
Labels: tests

#4445 Refactor logic for left side driving roundabouts
  libnavui-maneuver/api/current.txt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/TurnIconHelper.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/model/TurnIconResources.kt
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_continue.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_continue_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_continue_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_continue_slight_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_continue_slight_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_continue_straight.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_continue_uturn.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_flag.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_invalid.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_invalid_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_invalid_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_invalid_slight_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_invalid_slight_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_invalid_straight.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_invalid_uturn.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_merge_straight.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_new_name_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_new_name_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_new_name_sharp_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_new_name_sharp_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_new_name_slight_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_new_name_slight_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_new_name_straight.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_notification_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_notification_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_notification_sharp_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_notification_sharp_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_notification_slight_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_notification_slight_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_notification_straight.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_on_ramp_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_on_ramp_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_on_ramp_sharp_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_on_ramp_sharp_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_on_ramp_slight_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_on_ramp_slight_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_on_ramp_straight.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_traffic_circle.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_traffic_circle_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_traffic_circle_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_traffic_circle_slight_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_traffic_circle_slight_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_updown.xml
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/TurnIconHelperTest.kt
Labels: ⚠️ release blocker

#4456 changelog for v2.0.0-beta.12
  CHANGELOG.md
Labels: skip changelog

#4460 changelog for v2.0.0-beta.9.2
  CHANGELOG.md
Labels: skip changelog
