Repository mapbox/mapbox-navigation-android, pull requests merged in 2021-07, with the labels that each got.

#4569 Expose missing IncidentInfo properties
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/RoadObjectMapper.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/incident/IncidentInfo.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/roadobject/RoadObjectMapperTest.kt
Labels: ⚠️ release blocker

#4570 CHANGELOG: v2.0.0-beta.17
  CHANGELOG.md
Labels: skip changelog, ⚠️ DO NOT MERGE

#4575 Fix NavigationCamera infinite recursion on animation cancel and update device farm config
  .circleci/config.yml
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/SanityUiRouteTest.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/NavigationCamera.kt
Labels: bug

#4580 `IOJobController` cleanup
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigation-metrics/src/main/java/com/mapbox/navigation/metrics/MapboxMetricsReporter.kt
  libnavui-speedlimit/src/test/java/com/mapbox/navigation/ui/speedlimit/view/MapboxSpeedLimitViewTest.kt
Labels: skip changelog

#4579 CHANGELOG 2.0.0-beta.17 missing changes
  CHANGELOG.md
Labels: skip changelog

#4566 Bump `mapboxMapSdk` dependency versions to `10.0.0-rc.3`
  gradle/dependencies.gradle
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/arrow/RouteArrowUtils.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/RouteArrowUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/api/MapboxRouteArrowViewTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineViewTest.kt
Labels: skip changelog

#4577 consolidate RouteRequestCallback and Router.Callback into a single RouterCallback with improved error accessibility
  examples/src/main/java/com/mapbox/navigation/examples/core/IndependentRouteGenerationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxBuildingHighlightActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxCustomStyleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxJunctionActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxManeuverActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineAndArrowActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxSignboardActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxSnapshotActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxTripProgressActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxVoiceActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/MapboxCameraAnimationsActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/util/RouteDrawingActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/util/RouteDrawingUtil.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CoreRerouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxHistoryTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SanityCoreRouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/idling/RouteRequestIdlingResource.kt
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/RouteRefreshCallback.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/Router.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/RouterCallback.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/DirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/RoutesRequestCallback.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/reroute/MapboxRerouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/reroute/RerouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesController.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSessionTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/reroute/MapboxRerouteControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesControllerTest.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/hybrid/HybridRouterHandler.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/hybrid/MapboxHybridRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/onboard/MapboxOnboardRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/util/HttpUrlEx.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/offboard/router/ElapsedTime.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/offboard/router/MapboxDirectionsUtils.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/offboard/router/NavigationRouteEventListener.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/hybrid/MapboxHybridRouterTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouterTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/onboard/MapboxOnboardRouterTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/util/HttpUrlExTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/offboard/router/NavigationRouteEventListenerTest.kt
  libnavigation-util/api/current.txt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/NavigationException.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/RequestMap.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/AlternativeRouteActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxRouteLineActivity.java
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/util/RouteDrawingActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/util/RouteDrawingUtil.kt
Labels: SEMVER-MAJOR

#4587 Bump NN to 56.0.0, common to 14.2.0
  gradle/dependencies.gradle
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxHistoryTest.kt
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/HistoryRecorderOptions.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/HistoryRecorderOptionsTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/NavigationOptionsTest.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/MapboxHistoryRecorder.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/model/HistoryEventPushHistoryRecord.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/history/MapboxHistoryRecorderTest.kt
Labels: SEMVER-MAJOR, ⚠️ release blocker

#4608 move MapboxDistanceFormatter to a public package
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxCustomStyleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxManeuverActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/formatter/DistanceFormatterOptions.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/androidTest/java/com/mapbox/navigation/core/tests/activity/TripServiceActivity.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/formatter/MapboxDistanceFormatter.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/formatter/MapboxDistanceFormatterTest.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/view/MapboxUpcomingManeuverAdapterTest.kt
  libnavui-tripprogress/src/main/java/com/mapbox/navigation/ui/tripprogress/model/DistanceRemainingFormatter.kt
Labels: SEMVER-MAJOR

#4607 use leg index instead of leg instance for maneuvers filtering
  libnavui-maneuver/api/current.txt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/ManeuverAction.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/ManeuverProcessor.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/ManeuverState.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/api/MapboxManeuverApi.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/model/LegIndexToManeuvers.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/model/LegToManeuvers.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/ManeuverProcessorTest.kt
  libnavui-maneuver/src/test/resources/short_multileg_route.json
Labels: SEMVER-MAJOR

#4609 removed redundant ManeuverCallback, the operations were synchronous anyway
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxCustomStyleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxManeuverActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  libnavui-maneuver/api/current.txt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/api/ManeuverCallback.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/api/MapboxManeuverApi.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/api/MapboxManeuverApiTest.kt
Labels: SEMVER-MAJOR

#4610 Bump `mapbox-navigation-native` dependency version to `48.0.7`
  gradle/dependencies.gradle
Labels: ⚠️ release blocker

#4612 Add `2.0.0-beta.9.4` release entry to `CHANGELOG`
  CHANGELOG.md
Labels: skip changelog

#4613 CP: #4612
  CHANGELOG.md
Labels: skip changelog

#4605 Fix PredictiveCache crash
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/PredictiveCache.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/cache/PredictiveCacheTests.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/PredictiveCacheController.kt
Labels: bug

#4615 updated Nav Native to v57.0.0
  gradle/dependencies.gradle
Labels: skip changelog

#4617 Removed v0.x snapshot reference from README
  README.md
Labels: skip changelog

#4618 changelog for v2.0.0-beta.19
  CHANGELOG.md
Labels: skip changelog

#4624 dependencies: move kotlin version to single source
  gradle/dependencies.gradle
Labels: skip changelog

#4636 Fix large timestamp replay example issue
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
Labels: skip changelog

#4644 Telemetry refactor
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
Labels: skip changelog

#4637 Render route in replay history example
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
Labels: skip changelog

#4639 Kyv router origin
  examples/src/main/java/com/mapbox/navigation/examples/core/IndependentRouteGenerationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxBuildingHighlightActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxCustomStyleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxJunctionActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxManeuverActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineAndArrowActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxSignboardActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxSnapshotActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxTripProgressActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxVoiceActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/MapboxCameraAnimationsActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/util/RouteDrawingActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/util/RouteDrawingUtil.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CoreRerouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxHistoryTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SanityCoreRouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/idling/RouteAlternativesIdlingResource.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/idling/RouteRequestIdlingResource.kt
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/Router.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/RouterCallback.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/RouterOrigin.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/reroute/MapboxRerouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/reroute/RerouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSessionTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/reroute/MapboxRerouteControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesControllerTest.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/hybrid/HybridRouterHandler.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/hybrid/MapboxHybridRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/onboard/MapboxOnboardRouter.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/hybrid/MapboxHybridRouterTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouterTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/onboard/MapboxOnboardRouterTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/AlternativeRouteActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxRouteLineActivity.java
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/util/RouteDrawingActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/util/RouteDrawingUtil.kt
Labels: SEMVER-MAJOR, feature, new API(s)

#4649 Pull in the latest translations from Transifex
  libnavui-maps/src/main/res/values-ca/strings.xml
  libnavui-maps/src/main/res/values-de/strings.xml
  libnavui-maps/src/main/res/values-ru/strings.xml
  libnavui-maps/src/main/res/values-vi/strings.xml
  libnavui-speedlimit/src/main/res/values-ca/strings.xml
  libnavui-speedlimit/src/main/res/values-de/strings.xml
  libnavui-speedlimit/src/main/res/values-ru/strings.xml
  libnavui-speedlimit/src/main/res/values-vi/strings.xml
  libtrip-notification/src/main/res/values-de/strings.xml
Labels: skip changelog

#4601 Use HistoryReader for navigation replay
  examples/src/main/assets/replay-history-activity.json
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/replay/HistoryFileLoader.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/replay/HistoryFilesActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/replay/HistoryFilesClient.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/replay/HistoryFilesDirectory.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/replay/HistoryFilesViewController.kt
  examples/src/main/res/layout/history_files_activity.xml
  examples/src/main/res/values/strings.xml
  examples/src/main/res/values/styles.xml
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/model/HistoryEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/model/HistoryEventGetStatus.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/model/HistoryEventMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/model/HistoryEventPushHistoryRecord.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/model/HistoryEventSetRoute.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/model/HistoryEventUpdateLocation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayEvents.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistoryDTO.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistoryMapper.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/history/ReplayHistoryMapperTest.kt
  libnavigation-core/src/test/resources/com.mapbox.navigation.core.replay.history/set_route_event_cleared.txt
  libnavigation-core/src/test/resources/com.mapbox.navigation.core.replay.history/set_route_event_invalid.txt
Labels: SEMVER-MAJOR

#4652 Fix instrumentation tests
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/replay/HistoryFileLoader.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/replay/HistoryFilesActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/replay/HistoryFilesClient.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/replay/HistoryFilesViewController.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxHistoryTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/SetRouteOrderTest.kt
  instrumentation-tests/src/main/assets/set_route_event_cleared.json
  instrumentation-tests/src/main/assets/set_route_event_invalid.json
  instrumentation-tests/src/main/assets/set_route_event_valid.json
  instrumentation-tests/src/main/res/raw/cross_country_route.json
  instrumentation-tests/src/main/res/raw/multiple_routes.txt
  instrumentation-tests/src/main/res/raw/short_route.json
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/MapboxHistoryReader.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/model/HistoryEventMapper.kt
Labels: skip changelog

#4646 Refactor `MapboxSpeechApi`s to make them non-cancelling
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxVoiceActivity.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxSpeechApi.kt
Labels: needs discussion

#4655 Removed RouteRefreshOptions#enabled in favor of respecting RouteOptions#enableRefresh
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteRefreshTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/idling/RoutesObserverIdlingResource.kt
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/extensions/RouteOptionsEx.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/RouteRefreshOptions.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/internal/extensions/RouteRefreshExTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/route/RouteRefreshOptionsTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshController.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routerefresh/RouteRefreshControllerTest.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/hybrid/MapboxHybridRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouter.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouterTest.kt
Labels: SEMVER-MAJOR

#4489 Sb 1000 hide inactive route legs
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/MainActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineAndArrowActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MultiLegRouteExampleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/MapboxCameraAnimationsActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/util/RouteLineUtil.kt
  examples/src/main/res/layout/multileg_route_example_layout.xml
  examples/src/main/res/values/strings.xml
  libnavui-base/api/current.txt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/internal/model/route/RouteConstants.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineApiExtensions.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineView.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLine.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/MapboxRouteLineOptions.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineColorResources.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineExpressionData.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineTrafficExpressionData.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineUpdateValue.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/util/CacheResultUtils.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineViewTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLineTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/model/MapboxRouteLineOptionsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineColorResourcesTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/util/CacheResultUtilsTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxRouteLineActivity.java
Labels: SEMVER-MAJOR, ⚠️ release blocker

#4658 Add `2.0.0-beta.20` `CHANGELOG` release entry
  CHANGELOG.md
  examples/src/main/java/com/mapbox/navigation/examples/core/MultiLegRouteExampleActivity.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLineTest.kt
Labels: skip changelog

#4667 Remove access token from MapboxHistoryReader
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/replay/HistoryFileLoader.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/replay/HistoryFilesActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/replay/HistoryFilesClient.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/replay/HistoryFilesViewController.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxHistoryTest.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/MapboxHistoryReader.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/model/HistoryEventMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/model/HistoryEventSetRoute.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistoryMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistorySetRouteMapper.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/history/ReplayHistoryMapperTest.kt
  libnavigation-core/src/test/resources/multileg_route.json
Labels: SEMVER-MAJOR

#4669 Expose experimental NN api
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: skip changelog

#4671 removes Bintray repo references from build
  build.gradle
Labels: skip changelog

#4670 Removed access token from RouteOptions
  examples/src/main/java/com/mapbox/navigation/examples/core/IndependentRouteGenerationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxBuildingHighlightActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxCustomStyleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxJunctionActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxManeuverActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineAndArrowActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxSignboardActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxSnapshotActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxTripProgressActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxVoiceActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MultiLegRouteExampleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/MapboxCameraAnimationsActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/replay/HistoryFileLoader.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/replay/HistoryFilesActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/replay/HistoryFilesClient.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/replay/HistoryFilesViewController.kt
  gradle/dependencies.gradle
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CoreRerouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxHistoryTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteRefreshTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SanityCoreRouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/SetRouteOrderTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/route/RouteExclusionsJavaTest.java
  libnavigation-base/src/test/java/com/mapbox/navigation/base/route/RouteExclusionsTest.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/MapboxHistoryReader.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/model/HistoryEventMapper.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdateCommonTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdaterParameterizedTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdaterTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routerefresh/RouteRefreshControllerTest.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/hybrid/MapboxHybridRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/onboard/MapboxOnboardRouter.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/hybrid/MapboxHybridRouterTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouterTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/onboard/MapboxOnboardRouterTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/onboard/OfflineRouteTest.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/ManeuverProcessorTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/camera/data/ViewportDataSourceProcessorTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/api/MapboxRouteArrowApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLineTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/snapshotter/SnapshotterProcessorTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/AlternativeRouteActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxRouteLineActivity.java
Labels: SEMVER-MAJOR

#4672 add 2.0.0-beta.21 changelog release entry
  CHANGELOG.md
Labels: skip changelog
