Repository mapbox/mapbox-navigation-android, pull requests merged in 2021-12, with the labels that each got.

#5180 Fix for temporary replay engine support in the drop in UI.
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/MapboxNavigationViewModel.kt
Labels: skip changelog

#5159 improve notification on android 12
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/MapboxTripNotificationView.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotification.kt
  libtrip-notification/src/main/res/layout/mapbox_notification_navigation_collapsed.xml
  libtrip-notification/src/main/res/layout/mapbox_notification_navigation_expanded.xml
  libtrip-notification/src/main/res/values-v31/dimens.xml
  libtrip-notification/src/main/res/values/dimens.xml
  libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/MapboxTripNotificationViewTest.kt
  libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotificationTest.kt
Labels: bug

#5204 Add changelog v2.0.3
  CHANGELOG.md
Labels: skip changelog

#5215 add notes for removed v2.0.3 and v2.1.0
  CHANGELOG.md
Labels: skip changelog

#5217 add notes for removed v2.1.0
  CHANGELOG.md
Labels: skip changelog

#5216 add notes for removed v2.0.3
  CHANGELOG.md
Labels: skip changelog

#5222 Improve notification on Android 12
  gradle/dependencies.gradle
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/MapboxTripNotificationView.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotification.kt
  libtrip-notification/src/main/res/layout/mapbox_notification_navigation_collapsed.xml
  libtrip-notification/src/main/res/layout/mapbox_notification_navigation_expanded.xml
  libtrip-notification/src/main/res/values-v31/dimens.xml
  libtrip-notification/src/main/res/values/dimens.xml
  libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/MapboxTripNotificationViewTest.kt
  libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotificationTest.kt
Labels: bug, Core

#5221 Improve notification on Android 12
  gradle/dependencies.gradle
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/MapboxTripNotificationView.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotification.kt
  libtrip-notification/src/main/res/layout/mapbox_notification_navigation_collapsed.xml
  libtrip-notification/src/main/res/layout/mapbox_notification_navigation_expanded.xml
  libtrip-notification/src/main/res/values-v31/dimens.xml
  libtrip-notification/src/main/res/values/dimens.xml
  libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/MapboxTripNotificationViewTest.kt
  libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotificationTest.kt
Labels: bug, Core

#5220 Add history test for identifying contextual events
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxHistoryTest.kt
Labels: skip changelog

#5224 Add changelog for v2.2.0-alpha.2
  CHANGELOG.md
Labels: skip changelog

#5183 Remove kotlin-android-extensions
  LICENSE.md
  libnavigation-android/build.gradle
  libnavui-speedlimit/build.gradle
Labels: skip changelog

#5164 Replaced delay by stdout reading in instrumentation tests
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/MockLocationUpdatesRule.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/utils/UiAutomationUtils.kt
Labels: skip changelog, improvement

#5233 update tokens usage
  .circleci/config.yml
Labels: skip changelog

#5126 RouteProgress#voiceInstructions property doesn't become null
  libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/NavigatorMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/infra/TestLocationEngine.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/infra/factories/Android.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/infra/factories/DirectionsResponseFactories.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/infra/factories/NativeFactories.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/infra/recorders/RouteProgressObserverRecorder.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/infra/recorders/VoiceInstructionsObserverRecorder.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/navigator/NavigatorMapperTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionNoSetupTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
Labels: bug

#5191 Fix Events `distanceTraveled` not being accumulated
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/NavEventsPopulateUtil.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
Labels: bug, Core, skip changelog

#5243 Fix Events `distanceTraveled` not being accumulated
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/NavEventsPopulateUtil.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
Labels: bug, Core, skip changelog

#5235 update dependencies: maps `10.2.0-rc.1`, common `21.0.0-rc.2`, nn `82.0.0`
  gradle/dependencies.gradle
  libnavigation-core/src/test/java/com/mapbox/navigation/core/infra/factories/NativeFactories.kt
Labels: skip changelog

#5253 changelog 2.2.0-alpha.3
  CHANGELOG.md
Labels: skip changelog

#5240 Fix Events `distanceTraveled` not being accumulated
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/NavEventsPopulateUtil.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
Labels: bug, Core, skip changelog

#5256 fix empty profile in feedback events
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/NavEventsPopulateUtil.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/FeedbackMetadata.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/MetricsDirectionsRoute.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/MetricsRouteProgress.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/FeedbackMetadataTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/FeedbackMetadataWrapperTest.kt
  libnavigation-core/src/test/resources/feedback_metadata.json
Labels: bug, Core, skip changelog

#5192 bump gradle plugin version
  .circleci/config.yml
  examples/build.gradle
  gradle.properties
  gradle/dependencies.gradle
  gradle/jacoco.gradle
  gradle/wrapper/gradle-wrapper.properties
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesControllerTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/RouteArrowUtilsTest.kt
  qa-test-app/build.gradle
Labels: skip changelog

#5260 fix publish script
  gradle/publish.gradle
Labels: skip changelog

#5262 Bump Maps dependency version to `10.0.2`
  gradle/dependencies.gradle
Labels: bug, release blocker

#5263 Bumps Maps dependency version to `10.0.2`
  gradle/dependencies.gradle
Labels: bug, release blocker

#5265 Add `v2.0.4` and `v2.1.1` `CHANGELOG` release entries
  CHANGELOG.md
Labels: skip changelog

#5266 Add `v2.0.4` `CHANGELOG` release entry
  CHANGELOG.md
Labels: skip changelog

#5267 Add `v2.1.1` `CHANGELOG` release entry
  CHANGELOG.md
Labels: skip changelog

#5232 update SDK Registry plugin to v0.7.0
  .circleci/config.yml
  Makefile
  gradle/dependencies.gradle
  gradle/publish.gradle
Labels: skip changelog

#5261 Fixed crashes and waypoints accumulation during rerouting
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/infra/factories/DirectionsResponseFactories.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionNoSetupTest.kt
Labels: bug, needs backporting

#5276 Added reminder of removing the next waypoint index workaround
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
Labels: skip changelog

#5272 Publish API docs during release for 2.0
  .circleci/config.yml
  scripts/publish_api_docs_android.sh
Labels: skip changelog

#5282 fixes snapshot releases
  .circleci/config.yml
Labels: skip changelog

#5278 Bump Maps, NN and `common` dependency versions to `10.2.0`, `82.0.1` and `21.0.1` respectively
  gradle/dependencies.gradle
Labels: skip changelog

#5290 Add `CHANGELOG` for `v2.2.0-beta.1` release
  CHANGELOG.md
Labels: skip changelog

#5292 added reference to the new shields module to changelog
  CHANGELOG.md
Labels: skip changelog

#5293 updated core and telem to `v8.1.1` and `v5.0.1`
  gradle/dependencies.gradle
Labels: skip changelog

#5296 added union merge attribute for CHANGELOG.md
  .gitattributes
Labels: skip changelog

#5279 Adding methods to set or fetch a route using the drop in UI component.
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/MapboxNavigationViewApi.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/MapboxNavigationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/MapboxNavigationViewApiTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/MapboxNavigationViewModelTest.kt
Labels: skip changelog

#5252 Added tests for various view models used by the drop in UI.
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/maneuver/ManeuverProcessorTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/maneuver/ManeuverViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonProcessorTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/recenter/RecenterViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routeoverview/RouteOverviewButtonProcessorTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routeoverview/RouteOverviewViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/sound/SoundButtonViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/speedlimit/SpeedLimitProcessorTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/speedlimit/SpeedLimitViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressProcessorTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressViewModelTest.kt
Labels: skip changelog

#5168 added DropInViewModel abstraction and updated view-based models
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/MapboxNavigationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/DropInViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/maneuver/ManeuverState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/maneuver/ManeuverUIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/maneuver/ManeuverViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/navigationstate/NavigationState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/navigationstate/NavigationStateAction.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/navigationstate/NavigationStateContract.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/navigationstate/NavigationStateProcessor.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/navigationstate/NavigationStateViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonContract.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterUIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routearrow/RouteArrowUIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routearrow/RouteArrowViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routearrow/RouteArrowViewModelFactory.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routeline/RouteLineUIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routeline/RouteLineViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routeoverview/RouteOverviewButtonContract.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routeoverview/RouteOverviewState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routeoverview/RouteOverviewUIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routeoverview/RouteOverviewViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/SoundButtonContract.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/SoundButtonState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/SoundButtonUIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/SoundButtonViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/speedlimit/SpeedLimitContract.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/speedlimit/SpeedLimitState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/speedlimit/SpeedLimitUIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/speedlimit/SpeedLimitViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressContract.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressProcessor.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressUIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressViewModel.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/MapboxNavigationViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/DropInViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/maneuver/ManeuverViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/navigationstate/NavigationStateViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/recenter/RecenterViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routeoverview/RouteOverviewViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/sound/SoundButtonViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/speedlimit/SpeedLimitViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressViewModelTest.kt
Labels: UI, skip changelog

#5298 cleared up the error message when viewport padding is unusable
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/ViewportDataSourceProcessor.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/camera/data/ViewportDataSourceProcessorTest.kt
Labels: UI

#5307 fixed maneuver avoidance calculation for reroutes
  CHANGELOG.md
  libnavigation-core/src/main/java/com/mapbox/navigation/core/reroute/MapboxRerouteController.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/reroute/MapboxRerouteControllerTest.kt
Labels: bug, Core

#5211 Adding support for selecting an alternative route when using the drop…
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routeline/RouteLineUIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routeline/RouteLineViewModel.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routeline/RouteLineUIComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routeline/RouteLineViewModelTest.kt
  libnavui-dropin/src/test/resources/multileg_route.json
Labels: skip changelog

#5254 navigationview instrumentation tests
  instrumentation-tests/build.gradle
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/navigationview/NavigationViewExternalObserversTests.kt
  instrumentation-tests/src/main/AndroidManifest.xml
  instrumentation-tests/src/main/java/com/mapbox/navigation/instrumentation_tests/activity/NavigationViewTestActivity.kt
  instrumentation-tests/src/main/res/layout/activity_dropin_layout.xml
Labels: skip changelog
