Repository mapbox/mapbox-navigation-android, pull requests merged in 2021-09, with the labels that each got.

#4739 add option to select a leg when starting navigation
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/DirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSessionTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
Labels: Core

#4778 Feature/ak #892 support congestion numeric
  libnavui-base/api/current.txt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/internal/model/route/RouteConstants.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLine.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineColorResources.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineResources.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLineTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineColorResourcesTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineResourcesTest.kt
  libnavui-maps/src/test/resources/route-with-congestion-numeric-no-route-options.json
  libnavui-maps/src/test/resources/route-with-congestion-numeric.json
  libnavui-maps/src/test/resources/route-with-no-congestion-annotation.json
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/TrafficGradientActivity.kt
Labels: SEMVER-MAJOR

#4788 changelog for v2.0.0-beta.25
  CHANGELOG.md
Labels: skip changelog

#4790 MapboxSpeechFileProvider: ensure cacheDirectory exists each time
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxSpeechFileProvider.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceApiProvider.kt
Labels: bug

#4796 Bump NN dependency version to `65.0.2`
  gradle/dependencies.gradle
Labels: Core, skip changelog

#4794 update free drive and active navigation feedback events
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/FeedbackEvent.kt
Labels: SEMVER-MAJOR, Core

#4798 update feedback event docs
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/FeedbackEvent.kt
Labels: ⚠️ release blocker, Core, skip changelog

#4792 start foreground service with actual notification
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/service/MapboxTripService.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/service/NavigationNotificationService.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/service/NotificationDataObserver.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/service/MapboxTripServiceTest.kt
Labels: bug

#4666 Session billing integration
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/accounts/UrlSkuTokenProvider.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigationProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/accounts/BillingController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/accounts/BillingServiceWrapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/accounts/TokenGeneratorWrapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/accounts/MapboxNavigationAccounts.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/accounts/NavigationTokenGenerator.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/accounts/TokenGeneratorProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NavigationSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/BillingControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/accounts/MapboxNavigationAccountsTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/offboard/RouteBuilderProvider.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxSpeechProvider.kt
Labels: ⚠️ release blocker

#4805 Add `2.0.0-rc.1` `CHANGELOG`
  CHANGELOG.md
Labels: skip changelog

#4808 Adding readme file for the QA testing app.
  README.md
  qa-test-app/README.md
Labels: skip changelog

#4813 add utilities for feedback types and subtypes
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/telemetry/CachedNavigationFeedbackEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/telemetry/MapboxNavigationFeedbackCache.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/FeedbackEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/FeedbackHelper.kt
Labels: SEMVER-MAJOR, Core, needs-backporting

#4818 add utilities for feedback types and subtypes
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/telemetry/CachedNavigationFeedbackEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/telemetry/MapboxNavigationFeedbackCache.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/FeedbackEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/FeedbackHelper.kt
Labels: SEMVER-MAJOR, Core

#4822 Bump `SNAPSHOT` version name to `2.1.0-SNAPSHOT`
  gradle.properties
Labels: skip changelog

#4817 Refactoring to reduce code duplication and consolidate functions that…
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLine.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/ExtractedRouteData.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineAnnotationExpressionData.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLineTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/InactiveRouteStylingActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/InactiveRouteStylingWithRestrictionsActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/RouteRestrictionsActivity.kt
Labels: skip changelog

#4824 Refactoring to reduce code duplication and consolidate functions that…
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLine.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/ExtractedRouteData.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineAnnotationExpressionData.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLineTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/InactiveRouteStylingActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/InactiveRouteStylingWithRestrictionsActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/RouteRestrictionsActivity.kt
Labels: skip changelog

#4784 cache polyline decode results
  examples/src/main/java/com/mapbox/navigation/examples/core/IndependentRouteGenerationActivity.kt
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/utils/DirectionsRouteEx.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/utils/DecodeUtils.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/internal/utils/DirectionsRouteExTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/NavigatorMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route/ReplayRouteDriver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route/ReplayRouteMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/NavTelemetryUtils.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/route/ReplayRouteDriverTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/ManeuverProcessor.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSource.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/ViewportDataSourceProcessor.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSourceTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/utils/Utils.kt
Labels: needs-backporting

#4826 upgrade Maps SDK to v10.0.0-rc.8 and Nav Native to v66.0.0
  LICENSE.md
  gradle/dependencies.gradle
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/factory/EHorizonFactory.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/eh/EHorizonMapper.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/eh/MatchableTypes.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/eh/EHorizonSubscriptionManagerImpl.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/eh/RoadObjectMatcher.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/EHorizonSubscriptionManagerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: SEMVER-MAJOR, needs-backporting

#4831 Fix route refresh not starting
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routerefresh/RouteRefreshControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
Labels: bug, ⚠️ release blocker, needs-backporting

#4810 Reset offRoute on setRoute before NN method completes
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
Labels: bug, needs-backporting

#4836 bump mapbox java to 6.0.0-alpha.6
  gradle/dependencies.gradle
Labels: skip changelog

#4840 [changelog]v2.0.0-rc.2
  CHANGELOG.md
Labels: skip changelog

#4841 cherry pick #4840
  CHANGELOG.md
Labels: skip changelog

#4825 Enable replay per trip session
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSessionLocationEngine.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/TripSessionLocationEngineTest.kt
Labels: needs-backporting

#4844 updated 2.0.0-rc.2 changelog
  CHANGELOG.md
Labels: skip changelog

#4846 Add expirmental annotation to startReplayTripSession
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
Labels: needs-backporting, skip changelog

#4850 do not cancel job that calls setRoute
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
Labels: bug, Core

#4851 do not cancel job that calls setRoute
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
Labels: bug, Core

#4849 move zLevel to MapMatcherResult
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/factory/RouteProgressFactory.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/RouteProgress.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/NavigatorMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/reroute/MapboxRerouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routeoptions/RouteOptionsUpdater.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapMatcherResult.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/navigator/NavigatorMapperTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/reroute/MapboxRerouteControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/RouteOptionsUpdaterParameterizedTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/RouteOptionsUpdaterTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
Labels: Core

#4827 delay first notification update
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/service/MapboxTripService.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/service/MapboxTripServiceTest.kt
Labels: bug

#4856 Add experimental annotation to mapboxReplayer
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
Labels: needs-backporting, skip changelog

#4860 fix IndexOutOfBoundsException in MapboxRouteLineUtils
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
Labels: bug, ⚠️ release blocker, UI, needs-backporting

#4863 fix IndexOutOfBoundsException in MapboxRouteLineUtils
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
Labels: bug, ⚠️ release blocker, UI

#4858 Fix for soft gradient expression created with extremely small distanc…
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
Labels: needs-backporting

#4867 Making companion private.
  libnavui-maneuver/api/current.txt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/view/MapboxTurnIconManeuver.kt
Labels: needs-backporting, skip changelog

#4870 Making companion private. (#4867)
  libnavui-maneuver/api/current.txt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/view/MapboxTurnIconManeuver.kt
Labels: skip changelog

#4869 Bump nav-native dependency version to `66.0.3`
  gradle/dependencies.gradle
Labels: needs-backporting, skip changelog

#4872 Changelog for 2.0.0-rc.2.1
  CHANGELOG.md
Labels: skip changelog

#4873 [Backport] Changelog for 2.0.0-rc.2.1
  CHANGELOG.md
Labels: skip changelog

#4871 Bump Kotlin dependency version to `1.5.31`
  gradle/dependencies.gradle
Labels: skip changelog

#4874 CP: Bump nav-native dependency version to `66.0.3` (#4869)
  gradle/dependencies.gradle
Labels: skip changelog

#4878 Bug fix for route legs that have a distance array value of 0.
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
  libnavui-maps/src/test/resources/artificially_wrong_two_leg_route.json
  libnavui-maps/src/test/resources/multileg-route-two-legs.json
  libnavui-maps/src/test/resources/two-leg-route-with-restrictions.json
Labels: needs-backporting

#4880 merge location and map matcher result observers
  examples/src/main/java/com/mapbox/navigation/examples/core/IndependentRouteGenerationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxBuildingHighlightActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxCustomStyleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxJunctionActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxManeuverActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineAndArrowActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxSignboardActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxTripProgressActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxVoiceActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MultiLegRouteExampleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/MapboxCameraAnimationsActivity.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/SimpleMapViewNavigationTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/idling/FirstLocationIdlingResource.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/NavigatorMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/reroute/MapboxRerouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routeoptions/RouteOptionsUpdater.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/LocationsCollectorImpl.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/LocationMatcherResult.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/LocationObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapMatcherResultObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/navigator/NavigatorMapperTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/reroute/MapboxRerouteControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/RouteOptionsUpdaterParameterizedTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/RouteOptionsUpdaterTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/LocationsCollectorTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSource.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/location/NavigationLocationProvider.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/AlternativeRouteActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/FeedbackActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/InactiveRouteStylingActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/InactiveRouteStylingWithRestrictionsActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxRouteLineActivity.java
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/RouteRestrictionsActivity.kt
Labels: SEMVER-MAJOR, needs-backporting

#4779 Deferred feedback
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/telemetry/CachedNavigationFeedbackEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/telemetry/MapboxNavigationFeedbackCache.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/utils/CachedNavigationFeedbackEventEx.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/utils/TelemetryEx.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/EventLocations.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/LocationsCollector.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/LocationsCollectorImpl.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/NavEventsPopulateUtil.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/NavTelemetryUtils.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/FeedbackEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/FeedbackMetadata.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationFeedbackEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/PhoneState.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/LocationsCollectorTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/NavigationFeedbackEventTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/FeedbackMetadataTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/FeedbackMetadataWrapperTest.kt
  libnavigation-core/src/test/resources/feedback_metadata.json
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/FeedbackActivity.kt
  qa-test-app/src/main/res/layout/feedback_activity.xml
Labels: feedback, needs-backporting

#4886 merge location and map matcher result observers
  examples/src/main/java/com/mapbox/navigation/examples/core/IndependentRouteGenerationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxBuildingHighlightActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxCustomStyleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxJunctionActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxManeuverActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineAndArrowActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxSignboardActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxTripProgressActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxVoiceActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MultiLegRouteExampleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/MapboxCameraAnimationsActivity.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/SimpleMapViewNavigationTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/idling/FirstLocationIdlingResource.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/NavigatorMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/reroute/MapboxRerouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/LocationsCollectorImpl.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/LocationMatcherResult.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/LocationObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapMatcherResultObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/navigator/NavigatorMapperTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/reroute/MapboxRerouteControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/LocationsCollectorTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSource.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/location/NavigationLocationProvider.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/AlternativeRouteActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/FeedbackActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/InactiveRouteStylingActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/InactiveRouteStylingWithRestrictionsActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxRouteLineActivity.java
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/RouteRestrictionsActivity.kt
Labels: SEMVER-MAJOR

#4887 fixed a regression and restored the vanishing point update distance threshold to 3 meters
  libnavui-base/api/current.txt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/internal/model/route/RouteConstants.kt
Labels: bug, needs-backporting

#4893 Bump `mapbox-java` dependency version to `6.0.0-alpha.7`
  gradle/dependencies.gradle
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/RouteExclusions.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/route/RouteExclusionsJavaTest.java
  libnavigation-base/src/test/java/com/mapbox/navigation/base/route/RouteExclusionsTest.kt
Labels: SEMVER-MAJOR, Core, needs-backporting

#4898 [Backport] Changelog for v2.0.0-rc.3
  CHANGELOG.md
Labels: skip changelog

#4895 Changelog for v2.0.0-rc.3
  CHANGELOG.md
Labels: skip changelog

#4896 Changelog for v2.1.0-alpha.1
  CHANGELOG.md
Labels: skip changelog

#4908 updated 2.1.0-alpha.1 changelog
  CHANGELOG.md
Labels: skip changelog

#4900 Changing log level since error is not useful for developers and has be…
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLine.kt
Labels: needs-backporting

#4914 upgraded mapbox-java to v6.0.0-alpha.8
  gradle/dependencies.gradle
Labels: skip changelog

#4912 upgrade Common SDK to v19.0.0, Maps SDK to v10.0.0-rc.9, and Nav Native to v67.0.0
  gradle/dependencies.gradle
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/MapboxRouteLayerProvider.kt
Labels: needs-backporting

#4917 use MapboxNavigationProvider in examples
  examples/src/main/java/com/mapbox/navigation/examples/core/IndependentRouteGenerationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxBuildingHighlightActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxCustomStyleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxJunctionActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxManeuverActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineAndArrowActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxSignboardActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxTripProgressActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxVoiceActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MultiLegRouteExampleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/MapboxCameraAnimationsActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/AlternativeRouteActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/FeedbackActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/InactiveRouteStylingActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/InactiveRouteStylingWithRestrictionsActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxRouteLineActivity.java
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/RouteRestrictionsActivity.kt
Labels: bug, skip changelog

#4911 Added a thread pool factory for components that need the functionality of ThreadController without being tied to MaboxNavigation.
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxBuildingHighlightActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxCustomStyleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxJunctionActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxManeuverActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineAndArrowActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxSignboardActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxTripProgressActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxVoiceActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MultiLegRouteExampleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/util/RouteLineUtil.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineView.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLine.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/util/InternalJobControlFactory.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineViewTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLineTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivitySuite.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/AlternativeRouteActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/InactiveRouteStylingActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/InactiveRouteStylingWithRestrictionsActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxRouteLineActivity.java
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/RouteRestrictionsActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/RouteTrafficUpdateActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/TrafficGradientActivity.kt
Labels: needs backporting

#4919 Bump nav-native dependency version to `68.0.0`
  gradle/dependencies.gradle
Labels: needs backporting, skip changelog

#4904 add strategy to skip ci jobs for some PR
  .circleci/config.yml
Labels: skip changelog
