Repository mapbox/mapbox-navigation-android, pull requests merged in 2021-03, with the labels that each got.

#4075 Add debug google services json
  test-app/src/debug/google-services.json
Labels: skip changelog

#4051 Added unit tests as part of route line and arrow test audit.
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/arrow/RouteArrowUtils.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineView.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLine.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/api/MapboxRouteArrowApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/api/MapboxRouteArrowViewTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineViewTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLineTest.kt
Labels: skip changelog

#4034 Instrumentation test for navigation-sdks issue 829, route equality
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/SimpleMapViewNavigationTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/AlternativeRouteSelectionTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/routes/MockRoutesProvider.kt
  instrumentation-tests/src/main/res/raw/multiple_routes.txt
  instrumentation-tests/src/main/res/raw/route_response_simple.json
Labels: skip changelog

#4081 Fix banner and voice instructions observers reactive behavior
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/BannerInstructionEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/VoiceInstructionEvent.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/BannerInstructionEventTest.kt
  test-app/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  test-app/src/main/java/com/mapbox/navigation/examples/core/MapboxVoiceActivity.kt
Labels: Core, bug

#4089 Fix merge conflict
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/AlternativeRouteSelectionTest.kt
Labels: bug, skip changelog

#4101 fix for timing issue with test activities.
  test-app/src/main/java/com/mapbox/navigation/examples/util/RouteLine.kt
Labels: skip changelog

#4102 Add log error to voice instructions text player
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsTextPlayer.kt
Labels: UI, skip changelog

#4107 Add predictive cache migration notes to the docs
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/PredictiveCacheController.kt
Labels: Core, skip changelog

#4108 Expose isRightHandTraffic param
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/model/eh/EHorizonEdgeMetadata.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/model/eh/EHorizonMapper.kt
Labels: new API(s)

#4099 fixed an issue where snapshotter failure was not delivered when there was not instructions
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/snapshotter/SnapshotterAction.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/snapshotter/SnapshotterProcessor.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/snapshotter/api/MapboxSnapshotterApi.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/snapshotter/SnapshotterProcessorTest.kt
  libnavui-util/src/main/java/com/mapbox/navigation/ui/utils/internal/extensions/BannerInstructionEx.kt
Labels: UI

#4100 Returning the found route when searching the map for a route
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/ClosestRouteValue.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteNotFound.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
  test-app/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineActivity.java
Labels: UI

#4060 MapboxRouteOptionsUpdate: added more tests for immutable fields
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdateCommonTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdaterParameterizedTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdaterTest.kt
Labels: skip changelog, tests

#4115 [v2.0.0-alpha.12] Fix a issue where origin shows destination icon
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/MapboxRouteLayerProvider.kt
Labels: bug

#4128 Fix issue with traveled route line casing color was incorrect.
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLine.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLineTest.kt
Labels: skip changelog

#4133 fixed check for adding snapshot repo reference
  build.gradle
  gradle/dependencies.gradle
Labels: skip changelog, tests

#4138 Refactor Voice module to use MapboxNavigationConsumer generic callback
  libnavui-voice/api/current.txt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxSpeechApi.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceInstructionsPlayer.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/PlayCallback.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/SpeechCallback.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsPlayerCallback.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/model/SpeechVolume.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/MapboxSpeechApiTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceInstructionsPlayerTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/model/SpeechVolumeTest.kt
  test-app/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  test-app/src/main/java/com/mapbox/navigation/examples/core/MapboxVoiceActivity.kt
Labels: SEMVER-MAJOR, UI

#4154 Bump mapbox-navigation-native version to 45.0.3 and fix banner instruction and route progress mismatch when in multi-leg scenarios
  gradle/dependencies.gradle
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/BannerInstructionEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/BannerInstructionEventTest.kt
Labels: Core, bug, needs-backporting

#4155 Updating changelog for release 2.0.0-beta.2
  CHANGELOG.md
Labels: skip changelog

#4158 Add support for native downloads with snapshots
  gradle/dependencies.gradle
Labels: skip changelog

#4160 TripNotification: default text place holder at the start of the trip
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotification.kt
  libtrip-notification/src/main/res/layout/mapbox_notification_navigation_collapsed.xml
  libtrip-notification/src/main/res/layout/mapbox_notification_navigation_expanded.xml
  libtrip-notification/src/main/res/values/strings.xml
  libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotificationTest.kt
Labels: bug

#4156 Kyv trip notification default placeholder at the start of the tip
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotification.kt
  libtrip-notification/src/main/res/layout/mapbox_notification_navigation_collapsed.xml
  libtrip-notification/src/main/res/layout/mapbox_notification_navigation_expanded.xml
  libtrip-notification/src/main/res/values/strings.xml
  libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotificationTest.kt
Labels: bug

#4166 A couple minor improvements in hopes of getting native stack traces from Firebase
  gradle/dependencies.gradle
  test-app/build.gradle
Labels: skip changelog

#4171 - RouteUrl is removed; - refatored tests and `Router`s.
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/extensions/RouteOptionsUtils.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/route/RouteUrl.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/internal/route/RouteUrlTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdaterParameterizedTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdaterTest.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/hybrid/MapboxHybridRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/onboard/MapboxOnboardRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/util/MapboxDirectionsEx.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/offboard/RouteBuilderProvider.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/onboard/OfflineRoute.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouterTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/onboard/MapboxOnboardRouterTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/offboard/router/NavigationRouteTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/onboard/OfflineRouteTest.kt
  test-app/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineActivity.java
  test-app/src/main/java/com/mapbox/navigation/examples/core/MapboxTripProgressActivity.kt
Labels: bug

#4172 TripNotification view: text `Stop Session` is always present before start of the trip session
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotification.kt
  libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotificationTest.kt
Labels: bug

#4161 SnappingClosures RouteOption
  gradle/dependencies.gradle
  libnavigation-router/src/main/java/com/mapbox/navigation/route/offboard/router/MapboxDirectionsUtils.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/offboard/router/NavigationRouteTest.kt
Labels: feature

#4167 Updating trip progress activity with comments specifcally related to …
  libnavui-tripprogress/api/current.txt
  libnavui-tripprogress/src/main/java/com/mapbox/navigation/ui/tripprogress/model/TimeRemainingFormatter.kt
  test-app/src/main/java/com/mapbox/navigation/examples/core/MapboxTripProgressActivity.kt
Labels: skip changelog

#4177 Bump mapbox-navigation-native version to 47.0.0 and common version to 10.0.2
  LICENSE.md
  gradle/dependencies.gradle
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/http/MockDirectionsRequestHandler.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/http/MockVoiceRequestHandler.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/NavigatorMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/model/eh/EHorizonEdgeMetadata.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/model/eh/EHorizonMapper.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/navigator/NavigatorMapperTest.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/onboard/MapboxOnboardRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/util/MapboxDirectionsEx.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/offboard/RouteBuilderProvider.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/onboard/MapboxOnboardRouterTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/offboard/router/NavigationRouteTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/onboard/OfflineRouteTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavui-speedlimit/src/main/assets/open_source_licenses.html
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxSpeechProvider.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/http/MockWebServerRule.kt
  scripts/generate-license.py
Labels: Core, skip changelog

#4180 Bump Maps SDK version to 10.0.0-beta.16
  LICENSE.md
  gradle/dependencies.gradle
  instrumentation-tests/src/main/java/com/mapbox/navigation/instrumentation_tests/activity/BasicNavigationViewActivity.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/offboard/router/NavigationRouteTest.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/PredictiveCacheController.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/snapshotter/api/MapboxSnapshotterApi.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/PredictiveCacheControllerTest.kt
  test-app/src/main/java/com/mapbox/navigation/examples/core/MapboxManeuverActivity.kt
  test-app/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  test-app/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineActivity.java
  test-app/src/main/java/com/mapbox/navigation/examples/core/MapboxSnapshotActivity.kt
  test-app/src/main/java/com/mapbox/navigation/examples/core/MapboxTripProgressActivity.kt
  test-app/src/main/java/com/mapbox/navigation/examples/core/MapboxVoiceActivity.kt
  test-app/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  test-app/src/main/java/com/mapbox/navigation/examples/core/camera/MapboxCameraAnimationsActivity.kt
Labels: UI, skip changelog

#4181 changelog 2.0.0-beta.3
  CHANGELOG.md
Labels: skip changelog

#4183 changelog 2.0.0-beta.3: crash note
  CHANGELOG.md
Labels: skip changelog

#4190 ktlint: - upgrade to 0.41.0; - removed non-nessusary dependencies
  .editorconfig
  gradle/dependencies.gradle
  instrumentation-tests/build.gradle
  libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/NavigatorMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/model/eh/EHorizonMapper.kt
  libnavui-base/build.gradle
  libnavui-maneuver/build.gradle
  libnavui-maps/build.gradle
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-speedlimit/build.gradle
  libnavui-speedlimit/src/main/java/com/mapbox/navigation/ui/speedlimit/api/MapboxSpeedLimitApi.kt
  libnavui-tripprogress/build.gradle
  libnavui-tripprogress/src/main/java/com/mapbox/navigation/ui/tripprogress/model/TripProgressUpdateFormatter.kt
  libnavui-util/build.gradle
  libnavui-voice/build.gradle
  test-app/build.gradle
Labels: needs-backporting, skip changelog

#4191 ktlint: - upgrade to 0.41.0; - removed non-nessusary dependencies for 1.x
  .editorconfig
  gradle/dependencies.gradle
  instrumentation-tests/build.gradle
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteLine.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/NavigatorMapper.kt
Labels: skip changelog

#4204 Removed the unused Picasso reference
  gradle/dependencies.gradle
Labels: skip changelog

#4169 Fix bearings calculation when reroute
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineActivity.java
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdater.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdaterTest.kt
  test-app/src/main/java/com/mapbox/navigation/examples/core/MapboxVoiceActivity.kt
  test-app/src/main/res/values/mapbox_access_token.xml
Labels: Core, bug, needs-backporting
