Repository mapbox/mapbox-navigation-android, pull requests merged in 2021-02, with the labels that each got.

#3922 Added check for height and width of the drawable since a value below …
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteArrow.java
Labels: UI

#3928 Bump Kotlin stdlib and plugin versions to 1.4.30
  gradle/dependencies.gradle
Labels: skip changelog

#3932 temporarily downgrades routing tiles to 2021_01_24-03_00_00
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/OnboardRouterOptions.kt
Labels: Core

#3933 Backport 3932
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/OnboardRouterOptions.kt
Labels: Core

#3937 missing renaming branch `master` -> `main`
  circle.yml
Labels: operational excellence, skip changelog

#3956 missing fixes docs and settings: rename master to main
  README.md
  circle.yml
  docs/localization.md
  docs/metalava.md
  docs/publishing.md
  scripts/trigger-mobile-metrics.py
Labels: skip changelog

#3962 comments out snapshots repo reference
  build.gradle
Labels: skip changelog

#3963 update Maps SDK to v9.6.1
  gradle/dependencies.gradle
Labels: UI

#3972 fixed an issue where remaining waypoints would always return 0 and break reroute handling
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CoreRerouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/location/MockLocationReplayer.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/routes/MockRoutesProvider.kt
  instrumentation-tests/src/main/res/raw/reroute_response_dc_very_short.json
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdater.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdaterTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/MockLocationUpdatesRule.kt
Labels: Core

#3983 Bump mapbox-navigation-native version to 31.0.1
  gradle/dependencies.gradle
Labels: Core, skip changelog

#3984 RouteRefresh: refactored
  gradle/dependencies.gradle
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/extensions/RouteRefreshEx.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/internal/extensions/RouteRefreshExTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/utils/DirectionsRouteEx.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routerefresh/RouteRefreshControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/offboard/routerefresh/RouteRefreshCallbackMapper.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/offboard/routerefresh/RouteRefreshCallbackMapperTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: bug, ⚠️ release blocker

#3985 Fix RouteProgress toString typo
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/RouteProgress.kt
Labels: Core, skip changelog

#3986 RouteRefresh: refactored(cherry pick)
  gradle/dependencies.gradle
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/extensions/RouteRefreshEx.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/internal/extensions/RouteRefreshExTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/utils/DirectionsRouteEx.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routerefresh/RouteRefreshControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/offboard/routerefresh/RouteRefreshCallbackMapper.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/offboard/routerefresh/RouteRefreshCallbackMapperTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: bug, ⚠️ release blocker

#3988 Add changelog for v1.5.0-alpha.1
  CHANGELOG.md
Labels: skip changelog

#3907 gitignore for publisher-staging
  .gitignore
Labels: skip changelog

#4004 RouteRefreshController: logging fixes
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshController.kt
Labels: needs-backporting, skip changelog

#3995 Rename EHorizonGraphAccessor and EHorizonObjectsStore
  docs/eh_v3.md
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/model/eh/EHorizonObjectType.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/GraphAccessor.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/RoadObjectsStore.kt
Labels: SEMVER-MAJOR

#4030 Dokka: removed from docs free modules `libnavui-util` and `libnavui-resources`
  libnavui-resources/build.gradle
  libnavui-util/build.gradle
Labels: skip changelog

#4025 IncidentsOptions
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/IncidentsOptions.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/IncidentsOptionsTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/NavigationOptionsTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
Labels: feature

#4031 - NativeNavigator fix: upgrade route when refresh route; - TripSession alternative route fix : compare routes along with uuid
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/utils/DirectionsRouteEx.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/utils/DirectionsRouteExTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: bug, needs-backporting

#4032 Upgrade Nav Native to v42, enable automatic tiles version switch and rename OnboardRouterOptions to RoutingTilesOptions
  gradle/dependencies.gradle
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/OnboardRouterOptions.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/RoutingTilesOptions.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/NavigationOptionsTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/OnboardRouterOptionsTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/RoutingTilesOptionsTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/RoutingTilesFiles.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/PredictiveCache.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/onboard/MapboxOnboardRouter.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/PredictiveCacheController.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/PredictiveCacheControllerTest.kt
Labels: Core, SEMVER-MAJOR

#3977 Add Voice instructions feature
  LICENSE.md
  Makefile
  circle.yml
  gradle/publish.gradle
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavui-base/api/current.txt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/api/voice/SpeechApi.kt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/api/voice/SpeechCallback.kt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/api/voice/VoiceInstructionsPlayer.kt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/api/voice/VoiceInstructionsPlayerCallback.kt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/model/voice/Announcement.kt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/model/voice/SpeechState.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/api/MapboxManeuverApiTest.kt
  libnavui-voice/.gitignore
  libnavui-voice/api/current.txt
  libnavui-voice/build.gradle
  libnavui-voice/gradle.properties
  libnavui-voice/proguard-rules.pro
  libnavui-voice/src/main/AndroidManifest.xml
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/VoiceAction.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/VoiceProcessor.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/VoiceResult.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxSpeechApi.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxSpeechFileProvider.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxSpeechProvider.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceApi.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceInstructionsPlayer.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/PlayCallback.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceApi.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceApiProvider.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsFilePlayer.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsTextPlayer.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/model/VoiceState.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/MapboxSpeechApiTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceApiTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceInstructionsPlayerTest.kt
  libnavui-voice/src/test/resources/robolectric.properties
  scripts/generate-license.py
  settings.gradle
  test-app/build.gradle
  test-app/src/main/AndroidManifest.xml
  test-app/src/main/java/com/mapbox/navigation/examples/MainActivity.kt
  test-app/src/main/java/com/mapbox/navigation/examples/core/VoiceActivity.kt
  test-app/src/main/res/layout/layout_voice.xml
  test-app/src/main/res/values/strings.xml
Labels: UI, feature, new API(s)

#4035 Update Metalava to latest available
  gradle/metalava-dependencies.gradle
  libnavigation-base/api/current.txt
  libnavigation-core/api/current.txt
  libnavigation-metrics/api/current.txt
  libnavui-base/api/current.txt
  libnavui-maneuver/api/current.txt
  libnavui-maps/api/current.txt
  libnavui-tripprogress/api/current.txt
  metalava/metalava.jar
Labels: skip changelog

#4040 RouteRefreshCallbackMapper: refactor error logs
  libnavigation-router/src/main/java/com/mapbox/navigation/route/offboard/routerefresh/RouteRefreshCallbackMapper.kt
Labels: skip changelog

#4042 updated changelog for v1.5.0-alpha.2
  CHANGELOG.md
Labels: skip changelog

#4041 RouteRefreshCallbackMapper: added error logs
  libnavigation-router/src/main/java/com/mapbox/navigation/route/offboard/routerefresh/RouteRefreshCallbackMapper.kt
Labels: skip changelog

#4043 updated changelog for v1.5.0-alpha.2
  CHANGELOG.md
Labels: skip changelog

#4045 use a version-less navigation predictive cache controller constructor
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/PredictiveCache.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/PredictiveCacheController.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/PredictiveCacheControllerTest.kt
Labels: Core

#4050 remove dokka from undocumented modules
  libnavui-resources/build.gradle
  libnavui-util/build.gradle
Labels: skip changelog

#4056 Refresh route fix: refresh alternative route when selected
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouter.kt
Labels: bug, needs-backporting

#4057 Refresh route fix: refresh alternative route when selected
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/offboard/RouteBuilderProvider.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouterTest.kt
Labels: bug

#4052 Kyv expose auido focus gain
  examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationFragment.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/DebugMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/InstructionViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt
  examples/src/main/java/com/mapbox/navigation/examples/ui/CustomUIComponentStyleActivity.kt
  libnavigation-ui/api/current.txt
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/Api26AudioFocusDelegate.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/AudioFocusDelegate.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/AudioFocusDelegateProvider.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/SpeechAudioFocusDelegate.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/SpeechAudioFocusManager.java
  libnavigation-ui/src/main/java/com/mapbox/navigation/ui/voice/SpeechPlayerProvider.java
Labels: new API(s)

#4064 Making it so this repository supports the circleci cli
  .circleci/config.yml
Labels: skip changelog

#4068 Bump mapbox-navigation-native version to 43.0.1
  gradle/dependencies.gradle
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/NavigatorLoader.kt
Labels: Core, skip changelog

#4027 Use Common SDK's account lib for SKU management
  LICENSE.md
  gradle/dependencies.gradle
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/accounts/SkuTokenProvider.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/accounts/UrlSkuTokenProvider.kt
  libnavigation-core/build.gradle
  libnavigation-core/src/main/AndroidManifest.xml
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NativeSkuTokenProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/accounts/Billing.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/accounts/MapboxNavigationAccountsProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/accounts/NavigationAccountsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/MapboxNavigationSDK.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/MapboxNavigationSDKInitializer.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/accounts/MapboxNavigationAccounts.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/accounts/NavigationTokenGenerator.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/accounts/TokenGeneratorProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/accounts/BillingTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/accounts/NavigationAccountsSessionTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/accounts/MapboxNavigationAccountsTest.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/offboard/RouteBuilderProvider.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouterTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/offboard/router/NavigationRouteTest.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxSpeechProvider.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceApiProvider.kt
Labels: Core, skip changelog

#4070 Voice follow ups
  libnavui-base/api/current.txt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/api/voice/SpeechApi.kt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/api/voice/SpeechCallback.kt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/model/voice/SpeechState.kt
  libnavui-voice/api/current.txt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/VoiceAction.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/VoiceProcessor.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/VoiceResult.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxSpeechApi.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxSpeechProvider.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceApi.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceApiProvider.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/model/TypeAndAnnouncement.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/model/VoiceState.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/options/MapboxSpeechApiOptions.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/VoiceProcessorTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/MapboxSpeechApiTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceApiTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/options/MapboxSpeechApiOptionsTest.kt
  test-app/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  test-app/src/main/java/com/mapbox/navigation/examples/core/MapboxVoiceActivity.kt
Labels: UI, skip changelog
