Repository mapbox/mapbox-navigation-android, pull requests merged in 2021-04, with the labels that each got.

#4195 Add multiple exclusion criteria and notification of exclusion violations
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/RouteExclusions.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/route/RouteExclusionsJavaTest.java
  libnavigation-base/src/test/java/com/mapbox/navigation/base/route/RouteExclusionsTest.kt
  libnavigation-base/src/test/resources/toll_and_ferry_directions_route.json
Labels: Core, new API(s)

#4148 Display restricted road sections on route line
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/MainActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineActivity.java
  examples/src/main/java/com/mapbox/navigation/examples/util/RouteDrawingActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/util/RouteDrawingUtil.kt
  examples/src/main/java/com/mapbox/navigation/examples/util/RouteLineUtil.kt
  examples/src/main/res/layout/layout_route_drawing_activity.xml
  examples/src/main/res/values/strings.xml
  libnavui-base/api/current.txt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/internal/model/route/RouteConstants.kt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/model/route/RouteLayerConstants.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/MapboxRouteLayerProvider.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineView.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/MapboxRouteLineOptions.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineColorResources.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineResources.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteSetValue.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineViewTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/model/MapboxRouteLineOptionsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineColorResourcesTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineResourcesTest.kt
  libnavui-maps/src/test/resources/another-route-with-restrictions.json
  libnavui-maps/src/test/resources/route-with-restrictions.json
Labels: UI, feature

#4216 Add 2.0.0-beta.4 CHANGELOG
  CHANGELOG.md
Labels: skip changelog

#4230 libnavigation-android: removed dokka
  libnavigation-android/build.gradle
Labels: bug, skip changelog

#4225 fix for enable/disable long press on map and fix for clearing
  examples/src/main/java/com/mapbox/navigation/examples/util/RouteDrawingActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/util/RouteDrawingUtil.kt
Labels: skip changelog

#4224 UnitType in MapboxDistanceFormatter type safe
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/formatter/DistanceFormatterOptions.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/formatter/UnitType.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/VoiceUnit.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/extensions/LocaleEx.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/formatter/DistanceFormatterOptionsTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/internal/extensions/LocaleExTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/NavigationOptionsTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/formatter/MapboxDistanceFormatter.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/formatter/MapboxDistanceFormatterTest.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/offboard/RouteBuilderProvider.kt
  libnavui-tripprogress/src/main/java/com/mapbox/navigation/ui/tripprogress/model/TripProgressUpdateFormatter.kt
  libnavui-tripprogress/src/test/java/com/mapbox/navigation/ui/tripprogress/model/DistanceRemainingFormatterTest.kt
Labels: SEMVER-MAJOR

#4222 Adding result caching for geometry calculation related calls
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/util/CacheResultUtils.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/util/CacheResultUtilsTest.kt
Labels: skip changelog

#4187 Adding route line example activity with inline comments for documentation
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/MainActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineAndArrowActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/internal/MapboxRouteLineActivity.java
  examples/src/main/res/layout/layout_activity_routeline_example.xml
  examples/src/main/res/values/strings.xml
Labels: skip changelog

#4219 MapboxSoundButton allowed clicks when animation is running. Example VoiceActivity: fix sound inverse.
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxVoiceActivity.kt
  libnavui-voice/api/current.txt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/view/MapboxSoundButton.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/view/MapboxSoundButtonTest.kt
Labels: bug

#4151 Add replay and waypoints to the test app
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/waypoints/WaypointsController.kt
Labels: skip changelog

#4184 Request route independently from the navigation session
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/MainActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/IndependentRouteGenerationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxCustomStyleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxJunctionActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxManeuverActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxSignboardActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxSnapshotActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxTripProgressActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxVoiceActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/MapboxCameraAnimationsActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/internal/MapboxRouteLineActivity.java
  examples/src/main/java/com/mapbox/navigation/examples/util/Utils.kt
  examples/src/main/res/layout/layout_activity_independent_route_generation.xml
  examples/src/main/res/values/strings.xml
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CoreRerouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SanityCoreRouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/SanityUiRouteTest.kt
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/Router.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/DirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/RoutesObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/FasterRouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/reroute/MapboxRerouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/reroute/RerouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshController.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSessionTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/fasterroute/FasterRouteControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/reroute/MapboxRerouteControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routerefresh/RouteRefreshControllerTest.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/hybrid/HybridRouterHandler.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/hybrid/MapboxHybridRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/onboard/MapboxOnboardRouter.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/offboard/routerefresh/RouteRefreshCallbackMapper.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/hybrid/MapboxHybridRouterTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouterTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/onboard/MapboxOnboardRouterTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/offboard/routerefresh/RouteRefreshCallbackMapperTest.kt
  libnavigation-util/build.gradle
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/RequestMap.kt
Labels: Core, SEMVER-MAJOR, feature, ⚠️ release blocker

#4242 upgrade mapbox-java to v5.9.0-alpha.5
  gradle/dependencies.gradle
Labels: skip changelog

#4243 update MapboxRouteLineAndArrowActivity.kt with correct route setter
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineAndArrowActivity.kt
Labels: skip changelog

#4241 Support composite tiles in PredictiveCacheController
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/PredictiveCacheLocationOptions.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/PredictiveCache.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/PredictiveCacheController.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/PredictiveCacheControllerTest.kt
Labels: feature

#4246 Adding tailrec keyword to function
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
Labels: skip changelog

#4252 CI fix: add check license
  .circleci/config.yml
  Makefile
Labels: skip changelog

#4258 ExperimentalApi annotation
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/ExperimentalMapboxNavigationAPI.kt
Labels: skip changelog

#4260 Route refresh: check valid uuid, improve logging
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/utils/RouteOptionsEx.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshController.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/utils/RouteOptionsExTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routerefresh/RouteRefreshControllerTest.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouter.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/offboard/MapboxOffboardRouterTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: bug

#4092 QA testing module and app for manual sanity testing of specific use c…
  .gitignore
  qa-test-app/.gitignore
  qa-test-app/build.gradle
  qa-test-app/src/androidTest/java/com/mapbox/navigation/qa_test_app/ExampleInstrumentedTest.kt
  qa-test-app/src/main/AndroidManifest.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/Constants.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivityDescription.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivitySuite.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/utils/Extensions.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/utils/LocationPermissionsHelper.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/utils/Utils.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/AlternativeRouteActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MainActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/adapters/ActivitiesListAdaptersSupport.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/adapters/GenericListAdapter.kt
  qa-test-app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  qa-test-app/src/main/res/drawable/ic_launcher_background.xml
  qa-test-app/src/main/res/layout/activity_main.xml
  qa-test-app/src/main/res/layout/alternative_route_activity_layout.xml
  qa-test-app/src/main/res/layout/test_activity_item_layout.xml
  qa-test-app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  qa-test-app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  qa-test-app/src/main/res/mipmap-hdpi/ic_launcher.png
  qa-test-app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  qa-test-app/src/main/res/mipmap-mdpi/ic_launcher.png
  qa-test-app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  qa-test-app/src/main/res/mipmap-xhdpi/ic_launcher.png
  qa-test-app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  qa-test-app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  qa-test-app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  qa-test-app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  qa-test-app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  qa-test-app/src/main/res/values-night/themes.xml
  qa-test-app/src/main/res/values/colors.xml
  qa-test-app/src/main/res/values/strings.xml
  qa-test-app/src/main/res/values/themes.xml
  qa-test-app/src/test/java/com/mapbox/navigation/qa_test_app/ExampleUnitTest.kt
  settings.gradle
Labels: skip changelog

#4267 Add `CHANGELOG` for `1.6.0` and `1.6.1`
  CHANGELOG.md
Labels: skip changelog

#4266 Add `CHANGELOG` for `1.6.0` and `1.6.1` plus missing entry for `2.0.0-beta.5`
  CHANGELOG.md
Labels: needs-backporting, skip changelog

#4268 Bump `mapboxMapSdk`, `mapboxNavigatorVersion` and `mapboxCommonNative` dependency versions to `10.0.0-beta.17`, `48.0.2` and `11.0.1` respectively
  examples/src/main/java/com/mapbox/navigation/examples/core/IndependentRouteGenerationActivity.kt
  gradle/dependencies.gradle
  gradle/unit-testing-dependencies.gradle
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/PredictiveCacheController.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/PredictiveCacheControllerTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/ShadowTileStore.java
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/ShadowTileStoreManager.java
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/guidance/junction/JunctionProcessorTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/guidance/junction/api/MapboxJunctionApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/guidance/signboard/SignboardProcessorTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/guidance/signboard/api/MapboxSignboardApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
Labels: skip changelog

#4272 Set `TilesConfig` `inMemoryTileCache` size to 1GB (1024 x 1024 x 1024)
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
Labels: Core

#4276 Disable Codecov
  .circleci/config.yml
Labels: needs-backporting, skip changelog

#4277 CP: Disable Codecov
  circle.yml
Labels: skip changelog

#4275 fixes some lateinit vars in activities
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxMultipleArrowActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/util/RouteDrawingActivity.kt
Labels: skip changelog

#4072 ViewportDataSource framing behaviors
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/AnimationAdapter.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/AnimationType.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/MapboxCameraAnimationsActivity.kt
  examples/src/main/res/layout/layout_activity_camera.xml
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/SimpleMapViewNavigationTest.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/NavigationCamera.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSource.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSourceOptions.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/ViewportDataSourceProcessor.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/ViewportProperty.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/debugger/MapboxNavigationViewportDataSourceDebugger.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/lifecycle/NavigationScaleGestureHandler.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/utils/MapboxNavigationCameraUtils.kt
  libnavui-maps/src/main/res/drawable/viewport_debugger_border.xml
  libnavui-maps/src/main/res/drawable/viewport_debugger_border_black.xml
  libnavui-maps/src/main/res/drawable/viewport_debugger_border_green.xml
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSourceOptionsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSourceTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/camera/data/ViewportDataSourceProcessorTest.kt
  libnavui-maps/src/test/resources/multileg_route_all_points_per_step.json
  libnavui-maps/src/test/resources/multileg_route_average_intersection_distances.json
  libnavui-maps/src/test/resources/multileg_route_post_maneuver_framing_geometry.json
Labels: UI

#4280 Bump mapbox-navigation-native dependency version to 48.0.3
  gradle/dependencies.gradle
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: Core, skip changelog

#4281 Add 2.0.0-beta.6 release CHANGELOG entry
  CHANGELOG.md
Labels: skip changelog

#4295 Expose EHorizon isOneWay property
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/model/eh/EHorizonEdgeMetadata.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/model/eh/EHorizonMapper.kt
Labels: new API(s)

#4308 Fix changelog verification
  .circleci/config.yml
Labels: skip changelog

#4307 Add changelog for 2.0.0-beta.7
  CHANGELOG.md
Labels: skip changelog

#4317 Fixes camera padding in the MapboxNavigationActivity
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
Labels: skip changelog

#4324 qa-test-app: fixed bugs, added check ktlint via make
  Makefile
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/AlternativeRouteActivity.kt
Labels: bug, skip changelog

#4327 Refactor building selection to use feature ids
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/arrival/api/MapboxBuildingHighlightApi.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/arrival/api/MapboxBuildingHighlightApiTest.kt
Labels: skip changelog

#4338 Fix replay slow downs by normalizing bearing
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route/ReplayRouteSmoother.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/route/ReplayRouteInterpolatorTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/route/ReplayRouteSmootherTest.kt
  libnavigation-core/src/test/resources/route_with_wide_turns.txt
Labels: bug

#4342 Bump `mapbox-navigation-native` version to `48.0.5`
  gradle/dependencies.gradle
Labels: Core, skip changelog

#4332 Introduced NavigationCameraTransitionOptions
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/AnimationAdapter.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/AnimationType.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/MapboxCameraAnimationsActivity.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/NavigationCamera.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSource.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/transition/MapboxNavigationCameraStateTransition.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/transition/MapboxNavigationCameraTransition.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/transition/NavigationCameraStateTransition.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/transition/NavigationCameraTransition.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/transition/NavigationCameraTransitionOptions.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/utils/MapboxNavigationCameraUtils.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/camera/NavigationCameraTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/camera/transition/MapboxNavigationCameraTransitionTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/camera/transition/NavigationCameraTransitionOptionsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/camera/utils/MapboxNavigationCameraUtilsKtTest.kt
Labels: SEMVER-MAJOR, UI, feature

#4343 improved the behavior of maximizeViewableGeometryWhenPitchZero flag
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/MapboxCameraAnimationsActivity.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSource.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSourceOptions.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSourceTest.kt
Labels: UI

#4278 Voice guidance player customization
  libnavui-voice/api/current.txt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/AudioFocusDelegate.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceInstructionsPlayer.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/OreoAndLaterAudioFocusDelegate.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/PreOreoAudioFocusDelegate.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsFilePlayer.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsFilePlayerProvider.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsTextPlayer.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsTextPlayerProvider.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/options/PlayerAttributes.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/options/PlayerAttributesProvider.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/options/VoiceInstructionsPlayerOptions.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/AudioFocusDelegateProviderTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceInstructionsPlayerTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/OreoAndLaterAudioFocusDelegateTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/PreOreoAudioFocusDelegateTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/options/PlayerAttributesProviderTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/options/VoiceInstructionsPlayerOptionsTest.kt
Labels: feature, new API(s)

#4346 Add changelong for v2.0.0-beta.8
  CHANGELOG.md
Labels: skip changelog
