Repository mapbox/mapbox-navigation-android, pull requests merged in 2021-08, with the labels that each got.

#4692 Bump `mapbox-navigation-native` dependency version to `61.0.0` and `maps` dependency version to `10.0.0-rc.5`
  LICENSE.md
  gradle/dependencies.gradle
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/factory/RoadObjectInstanceFactory.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/eh/EHorizonMapper.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/UpcomingRoadObject.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/distanceinfo/Gate.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/distanceinfo/PolygonDistanceInfo.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/distanceinfo/RoadObjectDistanceInfo.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/distanceinfo/SubGraphDistanceInfo.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/navigator/NavigatorMapperTest.kt
Labels: SEMVER-MAJOR

#4697 support more styling options for map buttons
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/view/MapboxRecenterButton.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/view/MapboxRouteOverviewButton.kt
  libnavui-maps/src/main/res/values/attrs.xml
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/view/MapboxSoundButton.kt
  libnavui-voice/src/main/res/values/attrs.xml
Labels: new API(s), UI

#4698 Bump Maps SDK and NN dependency versions to `10.0.0-rc.6` and `62.0.0` respectively
  gradle/dependencies.gradle
  libnavigation-core/src/test/java/com/mapbox/navigation/core/navigator/NavigatorMapperTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/NavigatorLoader.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxRouteLineActivity.java
Labels: skip changelog

#4701 changelog v2.0.0-beta.22
  CHANGELOG.md
Labels: skip changelog

#4706 RouteAlternativesController fix
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesController.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesControllerTest.kt
Labels: bug

#4718 utils module: removed dokka
  libnavigation-util/build.gradle
Labels: bug, skip changelog

#4604 Added QA activities
  qa-test-app/src/main/AndroidManifest.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivitySuite.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/utils/Utils.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/InactiveRouteStylingActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/RouteRestrictionsActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/RouteTrafficUpdateActivity.kt
  qa-test-app/src/main/res/layout/inactive_route_activity_layout.xml
  qa-test-app/src/main/res/layout/route_restrictions_activity_layout.xml
  qa-test-app/src/main/res/layout/route_traffic_update_activity_layout.xml
  qa-test-app/src/main/res/raw/multileg_route_two_legs.json
  qa-test-app/src/main/res/raw/route_with_restrictions.json
  qa-test-app/src/main/res/values/strings.xml
Labels: skip changelog

#4704 Refactor buildings api
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxBuildingHighlightActivity.kt
  examples/src/main/res/layout/layout_activity_building_highlight.xml
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/arrival/api/BuildingHighlightObserver.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/arrival/api/MapboxBuildingArrivalApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/arrival/api/MapboxBuildingHighlightApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/building/BuildingAction.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/building/BuildingProcessor.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/building/BuildingResult.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/building/api/MapboxBuildingsApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/building/model/BuildingError.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/building/model/BuildingValue.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/building/model/MapboxBuildingHighlightOptions.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/building/view/MapboxBuildingView.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/arrival/api/MapboxBuildingArrivalApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/arrival/api/MapboxBuildingHighlightApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/building/BuildingProcessorTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/building/api/MapboxBuildingsApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/building/model/BuildingHighlightOptionsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/building/view/MapboxBuildingViewTest.kt
Labels: SEMVER-MAJOR

#4728 workaround for the missing instruction if the route is set while the trip session is stopped
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
Labels: skip changelog

#4731 Handle EHorizon SubgraphLocation
  gradle/dependencies.gradle
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/eh/EHorizonMapper.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/location/RoadObjectLocationType.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/location/SubgraphEdge.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/location/SubgraphLocation.kt
Labels: bug

#4712 Add app metadata to all events
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/EventsAppMetadata.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/EventsAppMetadataTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/NavigationOptionsTest.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationSessionStateObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/telemetry/MapboxNavigationFeedbackCache.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/ApplicationLifecycleMonitor.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/AppMetadata.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationCancelEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationFeedbackEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationFreeDriveEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationRerouteEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NavigationSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NavigationSessionStateObserver.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/NavigationSessionTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/NavigationFeedbackEventTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/AppMetadataTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/SchemaTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/NavigationSessionTest.kt
Labels: SEMVER-MAJOR, new API(s), Core

#4735 v2.0.0-beta.23 changelog
  CHANGELOG.md
Labels: skip changelog

#4734 log updated legs
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/DirectionsRouteDiffProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshController.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routerefresh/DirectionsRouteDiffProviderTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routerefresh/RouteRefreshControllerTest.kt
Labels: Core

#4740 bump mapbox-navigation-native dependency version to 48.0.8
  gradle/dependencies.gradle
Labels: ⚠️ release blocker

#4741 fixes missing argument for tripSession.start in unit test
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
Labels: skip changelog

#4743 add 2.0.0-beta.9.5 release entry to changelog
  CHANGELOG.md
Labels: skip changelog

#4742 add 2.0.0-beta.9.5 release entry to changelog
  CHANGELOG.md
Labels: skip changelog
