Repository mapbox/mapbox-navigation-android, pull requests merged in 2021-06, with the labels that each got.

#4463 Removed com.mapbox.navigation.ui.base.model.Expected in favor of com.mapobox.bindgen.Expected
  examples/src/main/java/com/mapbox/navigation/examples/core/IndependentRouteGenerationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxCustomStyleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxJunctionActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxManeuverActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineAndArrowActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxSignboardActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxSnapshotActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxVoiceActivity.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/SimpleMapViewNavigationTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/AlternativeRouteSelectionTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/SetRouteOrderTest.kt
  libnavui-base/api/current.txt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/model/Expected.kt
  libnavui-maneuver/api/current.txt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/api/ManeuverCallback.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/api/MapboxManeuverApi.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/api/StepDistanceRemainingCallback.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/api/UpcomingManeuverListCallback.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/view/MapboxManeuverView.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/api/MapboxManeuverApiTest.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/view/MapboxManeuverViewTest.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/guidance/junction/JunctionProcessor.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/guidance/junction/api/MapboxJunctionApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/guidance/junction/api/MapboxRasterToBitmapParser.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/guidance/junction/view/MapboxJunctionView.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/guidance/signboard/SignboardProcessor.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/guidance/signboard/api/MapboxSignboardApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/guidance/signboard/api/MapboxSvgToBitmapParser.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/guidance/signboard/api/SvgToBitmapParser.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/guidance/signboard/view/MapboxSignboardView.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineApiExtensions.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/arrow/api/MapboxRouteArrowApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/arrow/api/MapboxRouteArrowView.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineView.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/snapshotter/api/MapboxSnapshotterApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/snapshotter/view/MapboxSnapshotView.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/guidance/junction/JunctionProcessorTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/guidance/junction/api/MapboxJunctionApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/guidance/junction/api/MapboxRasterToBitmapParserTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/guidance/junction/view/MapboxJunctionViewTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/guidance/signboard/SignboardProcessorTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/guidance/signboard/api/MapboxSignboardApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/guidance/signboard/view/MapboxSignboardViewTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/api/MapboxRouteArrowApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/api/MapboxRouteArrowViewTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineViewTest.kt
  libnavui-speedlimit/api/current.txt
  libnavui-speedlimit/src/main/java/com/mapbox/navigation/ui/speedlimit/api/MapboxSpeedLimitApi.kt
  libnavui-speedlimit/src/main/java/com/mapbox/navigation/ui/speedlimit/view/MapboxSpeedLimitView.kt
  libnavui-speedlimit/src/test/java/com/mapbox/navigation/ui/speedlimit/api/MapboxSpeedLimitApiTest.kt
  libnavui-speedlimit/src/test/java/com/mapbox/navigation/ui/speedlimit/view/MapboxSpeedLimitViewTest.kt
  libnavui-voice/api/current.txt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxSpeechApi.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/MapboxSpeechApiTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/AlternativeRouteActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxRouteLineActivity.java
Labels: SEMVER-MAJOR

#4472 Add missing `@JvmOverloads` to `MapboxNavigation#postUserFeedback` API
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
Labels: Core

#4478 Bump `mapbox-navigation-native` dependency version to `51.0.0`
  gradle/dependencies.gradle
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/RouteProgress.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/RouteProgressTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/NavigatorMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/navigator/NavigatorMapperTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/NavigatorLoader.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/TripStatus.kt
Labels: Core, SEMVER-MAJOR, needs discussion

#4467 Refactoring to remove the update to primary route method from the rou…
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineAndArrowActivity.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/AlternativeRouteSelectionTest.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineApiExtensions.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/AlternativeRouteActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxRouteLineActivity.java
Labels: SEMVER-MAJOR

#4479 Add `CHANGELOG` for `2.0.0-beta.13` release
  CHANGELOG.md
Labels: skip changelog

#4477 use mbx-ci to authenticate with AWS
  .circleci/config.yml
Labels: skip changelog

#4468 Fix camera bouncing
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/MapboxCameraAnimationsActivity.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/ViewportDataSourceProcessor.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/camera/data/ViewportDataSourceProcessorTest.kt
Labels: ⚠️ DO NOT MERGE

#4490 Mobile metrics: enable binary size and code coverage
  scripts/trigger-mobile-metrics.py
Labels: skip changelog

#4498 Bump `mapbox-android-telemetry` and `mapbox-android-core` dependency versions
  LICENSE.md
  gradle/dependencies.gradle
Labels: Core, skip changelog

#4500 Seth changelog 2.0.0 beta.14
  CHANGELOG.md
Labels: skip changelog

#4503 Add `snappingClosures` to `RouteOptionsUpdater`
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdater.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdaterTest.kt
Labels: Core, bug

#4508 upgrade multidex -> 2.0.1
  gradle/dependencies.gradle
Labels: skip changelog

#4507 Add mapbox history test rule
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxHistoryTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/history/MapboxHistoryTestRule.kt
  instrumentation-tests/src/main/AndroidManifest.xml
  libnavigation-core/api/current.txt
  libnavigation-core/src/androidTest/AndroidManifest.xml
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/BaseTest.kt
Labels: SEMVER-MAJOR

#4514 Test the time to split core and ui tests
  .circleci/config.yml
Labels: skip changelog

#4516 Fix AlternativeRouteSelectionTest
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/AlternativeRouteSelectionTest.kt
Labels: skip changelog

#4519 Removed activity reference in manifest for activity that no longer exists
  examples/src/main/AndroidManifest.xml
Labels: skip changelog

#4518 Update dependencies to prepare for release 2.0.0-beta.15
  LICENSE.md
  examples/src/main/java/com/mapbox/navigation/examples/util/RouteDrawingActivity.kt
  gradle/dependencies.gradle
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/roadobject/RoadObjectMapperTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/navigator/NavigatorMapperTest.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/snapshotter/api/MapboxSnapshotterApi.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/PredictiveCacheControllerTest.kt
Labels: skip changelog

#4521 Changelog for release 2.0.0-beta.15
  CHANGELOG.md
Labels: skip changelog

#4527 RouteAlternativesTest wait for location warm-up
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/idling/FirstLocationIdlingResource.kt
Labels: skip changelog, tests

#4529 Integrate common reachability service
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/ReachabilityService.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/ShadowReachabilityFactory.java
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/hybrid/MapboxHybridRouter.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/hybrid/MapboxHybridRouterTest.kt
  libnavigation-util/build.gradle
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/ConnectivityHandler.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/NetworkStatusService.kt
  libnavigation-util/src/test/java/com/mapbox/navigation/utils/internal/ConnectivityHandlerTest.kt
  libnavigation-util/src/test/java/com/mapbox/navigation/utils/internal/NetworkStatusServiceTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/ShadowTileStore.java
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/common/ShadowValueConverter.java
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/RouteArrowUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/api/MapboxRouteArrowViewTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineViewTest.kt
Labels: Core

#4535 Add `2.0.0-beta.9.3` `CHANGELOG` entry
  CHANGELOG.md
Labels: skip changelog

#4537 CP #4535
  CHANGELOG.md
Labels: skip changelog

#4536 CP #4477
  .circleci/config.yml
Labels: skip changelog

#4531 upgrade Maps SDK to v10.0.0-rc.2
  LICENSE.md
  gradle/dependencies.gradle
Labels: skip changelog

#4448 Refactoring to clean up the MapboxTripNotification class.
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/factory/TripNotificationStateFactory.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/TripNotificationState.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/notification/TripNotification.kt
  libnavigation-core/src/androidTest/java/com/mapbox/navigation/core/tests/activity/TripServiceActivity.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/service/MapboxTripService.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/service/TripService.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/service/MapboxTripServiceTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/MapboxTripNotificationView.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotification.kt
  libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/MapboxTripNotificationViewTest.kt
  libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotificationTest.kt
Labels: skip changelog

#4419 Integrate navigator observer
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CoreRerouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/utils/InternalUtils.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/NavigatorMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/TripStatus.kt
Labels: Core

#4545 Updating change log for release beta 16
  CHANGELOG.md
Labels: skip changelog

#4546 Cherry picking spelling error into change log.
  CHANGELOG.md
Labels: skip changelog

#4549 upgrade telemetry to v8.1.0
  gradle/dependencies.gradle
Labels: skip changelog

#4558 Reset observer on navigator recreation
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
Labels: bug

#4560 Bump Kotlin dependency version to `1.5.20`
  LICENSE.md
  gradle/dependencies.gradle
Labels: skip changelog
