Repository mapbox/mapbox-navigation-android, pull requests merged in 2021-11, with the labels that each got.

#5071 Bumping mapbox java version.
  gradle/dependencies.gradle
Labels: skip changelog

#5072 Updated change log for release 2.1.0 beta 2.
  CHANGELOG.md
Labels: skip changelog

#5074 compare congestionNumeric when printing route diffs
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/DirectionsRouteDiffProvider.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routerefresh/DirectionsRouteDiffProviderTest.kt
Labels: skip changelog

#5068 Predictive cache with descriptors
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/PredictiveCache.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/cache/PredictiveCacheTests.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/PredictiveCacheController.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/PredictiveCacheControllerTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxRouteLineActivity.java
Labels: bug

#5078 Bump NN dependency version to `79.0.2`
  gradle/dependencies.gradle
Labels: skip changelog

#5073 Fixed strings comparison in the docs release script
  scripts/publish_api_docs_android.sh
Labels: bug, skip changelog

#5080 specify layers for route requests
  examples/src/main/java/com/mapbox/navigation/examples/core/IndependentRouteGenerationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxBuildingHighlightActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxCustomStyleActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxManeuverActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineAndArrowActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxTripProgressActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxVoiceActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/MapboxCameraAnimationsActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/AlternativeRouteActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/FeedbackActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxRouteLineActivity.java
Labels: skip changelog

#5089 Predictive cache with descriptors
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/PredictiveCache.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/cache/PredictiveCacheTests.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/PredictiveCacheController.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/PredictiveCacheControllerTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxRouteLineActivity.java
Labels: ⚠️ DO NOT MERGE

#5093 Bump NN dependency version to `63.0.3`
  gradle/dependencies.gradle
Labels: bug, Core

#5094 v2.0.1 changelog
  CHANGELOG.md
Labels: skip changelog

#5095 v2.0.1 changelog
  CHANGELOG.md
Labels: skip changelog

#5097 update makefile to release snapshots
  Makefile
Labels: skip changelog

#5104 bumped mapbox-java to v6.1.0
  gradle/dependencies.gradle
Labels: skip changelog

#5105 Add `PedingIntent` Android 12 flags support
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotification.kt
Labels: release blocker, needs backporting

#5106 changelog for v2.1.0-rc.1
  CHANGELOG.md
Labels: skip changelog

#5108 Fix `2.1.0-rc.1` `CHANGELOG` typo
  CHANGELOG.md
Labels: skip changelog

#5086 Sb dropin poc observers
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxDropInActivity.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInUIMapboxNavigationFactory.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/MapboxNavigationViewApi.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/MapboxNavigationViewModelFactory.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewModelFactory.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/util/MapboxDropInUtils.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/viewmodel/CameraViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/viewmodel/MapboxNavigationViewModel.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/MapboxNavigationViewApiModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/MapboxNavigationViewApiTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/NavigationViewTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/shadows/ShadowLogger.java
  libnavui-util/src/main/java/com/mapbox/navigation/ui/utils/internal/extensions/MapboxDropInExtensions.kt
Labels: skip changelog

#5129 Add changelog v2.1.0 rc.2
  CHANGELOG.md
Labels: skip changelog

#5138 pass null to `avoidManeuverRadius` when there should be no avoidance
  libnavigation-core/src/main/java/com/mapbox/navigation/core/reroute/MapboxRerouteController.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/reroute/MapboxRerouteControllerTest.kt
Labels: bug, skip changelog

#5140 when rerouting add layers and avoid maneuvers parameters only for driving profiles
  libnavigation-core/src/main/java/com/mapbox/navigation/core/reroute/MapboxRerouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routeoptions/RouteOptionsUpdater.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/reroute/MapboxRerouteControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/RouteOptionsUpdaterTest.kt
Labels: bug, needs backporting

#5132 [Cherry pick] Fix route alternative thread issue
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/idling/RouteAlternativesIdlingResource.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesControllerProvider.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesControllerTest.kt
Labels: skip changelog

#5139 verify if the native route response is valid
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/utils/DirectionsResponseUtils.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesController.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/RouterWrapper.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/RouterWrapperTests.kt
Labels: bug

#5143 Add changelog for 1.6.2, 2.0.2, and 2.1.0-rc.2
  CHANGELOG.md
Labels: skip changelog

#5147 Add changelog 2.2.0-alpha.1
  CHANGELOG.md
Labels: skip changelog

#5146 make v1.6.2 on Nov 22
  CHANGELOG.md
Labels: skip changelog

#5149 Added voice instructions observer in the MapboxNavigation view model …
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/MapboxNavigationViewApi.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/viewmodel/MapboxNavigationViewModel.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/MapboxNavigationViewApiTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/MapboxNavigationViewModelTest.kt
Labels: skip changelog

#5134 Adding route line and arrow view models reacting to mapbox navigation…
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewOptions.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/RouteArrowViewModelFactory.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/RouteLineViewModelFactory.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/viewmodel/MapboxNavigationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/viewmodel/RouteArrowViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/viewmodel/RouteLineViewModel.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/NavigationViewTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/viewmodel/RouteArrowViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/viewmodel/RouteLineViewModelTest.kt
  libnavui-dropin/src/test/resources/short_route.json
Labels: skip changelog

#5144 update device farm targets
  .circleci/config.yml
Labels: skip changelog, op-ex

#5154 Adding support for using the replay engine with NavigationView.
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxDropInActivity.kt
  examples/src/main/res/layout/layout_activity_drop_in.xml
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/MapboxNavigationViewApi.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewOptions.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/viewmodel/MapboxNavigationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/viewmodel/RouteLineViewModel.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/MapboxNavigationViewApiTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/viewmodel/RouteLineViewModelTest.kt
Labels: skip changelog

#5156 Added workaround for staging docs publishing
  scripts/publish_api_docs_android.sh
Labels: skip changelog

#5160 Fix for route line not redrawing on device rotation.
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
Labels: skip changelog

#5163 Removed a workaround in connectivity handler.
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/ConnectivityHandler.kt
  libnavigation-util/src/test/java/com/mapbox/navigation/utils/internal/ConnectivityHandlerTest.kt
Labels: skip changelog

#5181 Add changelog v2.1.0 changelog
  CHANGELOG.md
Labels: skip changelog

#5178 Refactoring of formatters.
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewOptions.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/maneuver/ManeuverViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/speedlimit/SpeedLimitViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressViewModel.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/NavigationViewOptionsTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/shadows/ShadowLogger.java
Labels: skip changelog
