Repository mapbox/mapbox-navigation-android, pull requests merged in 2021-10, with the labels that each got.

#4915 send routes to nav native only when trip session is started
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
Labels: bug, needs backporting, skip changelog

#4726 Fix flaky instrumentation tests
  .circleci/config.yml
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CoreRerouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxHistoryTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SanityCoreRouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/AlternativeRouteSelectionTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/history/MapboxHistoryTestRule.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/http/MockDirectionsRequestHandler.kt
Labels: Core, skip changelog, op-ex

#4930 send routes to nav native only when trip session is started
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
Labels: bug, skip changelog

#4931 Fix flaky instrumentation tests (#4726)
  .circleci/config.yml
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CoreRerouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxHistoryTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SanityCoreRouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/AlternativeRouteSelectionTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/history/MapboxHistoryTestRule.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/http/MockDirectionsRequestHandler.kt
Labels: skip changelog, op-ex

#4881 Async native methods
  gradle/dependencies.gradle
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/arrival/ArrivalProgressObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/LegIndexUpdatedCallback.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/SensorEventUpdatedCallback.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/arrival/ArrivalProgressObserverTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: backwards incompatible, needs backporting

#4928 remove hardcoded color references
  libnavui-maneuver/src/main/res/drawable/mapbox_lane_opposite_slight_turn_or_straight_or_slight_turn_using_straight.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_lane_opposite_slight_turn_or_straight_or_turn_using_straight.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_lane_opposite_turn_or_straight_or_slight_turn_using_slight_turn.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_lane_opposite_turn_or_straight_or_turn_using_straight.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_lane_opposite_turn_or_straight_or_turn_using_turn.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_lane_opposite_turn_or_turn_using_turn.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_lane_slight_turn_or_sharp_turn_using_slight_turn.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_lane_slight_turn_or_uturn_using_uturn.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_lane_straight_or_sharp_turn_using_sharp_turn.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_lane_straight_or_turn_or_uturn_using_straight.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_lane_straight_or_turn_using_straight.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_lane_turn_or_sharp_turn_using_sharp_turn.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_lane_turn_or_uturn_using_turn.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_lane_turn_or_uturn_using_uturn.xml
Labels: needs backporting

#4913 Hide unnecessarily exposed Route Line implementation details
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineAndArrowActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/SetRouteOrderTest.kt
  libnavui-base/api/current.txt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/internal/model/route/RouteConstants.kt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/model/route/RouteLayerConstants.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/RouteLayerConstants.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/arrow/RouteArrowUtils.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/arrow/api/MapboxRouteArrowApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/arrow/api/MapboxRouteArrowView.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/arrow/model/RouteArrowOptions.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/MapboxRouteLayerProvider.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineView.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLine.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/MapboxRouteLineOptions.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineClearValue.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineColorResources.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineData.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineDynamicData.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineResources.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineUpdateValue.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteSetValue.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteStyleDescriptor.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/VanishingRouteLineExpressions.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/RouteArrowUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/api/MapboxRouteArrowApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/api/MapboxRouteArrowViewTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/model/RouteArrowOptionsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineViewTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLineTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/model/RouteSetValueTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxRouteLineActivity.java
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/RouteRestrictionsActivity.kt
Labels: backwards incompatible, needs backporting

#4938 Async NN methods, bump mapbox-java to 6.0.0-alpha.9
  gradle/dependencies.gradle
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/arrival/ArrivalProgressObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/LegIndexUpdatedCallback.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/SensorEventUpdatedCallback.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/arrival/ArrivalProgressObserverTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: backwards incompatible

#4934 Fix `verify_history_files_are_recorded_and_readable` `MapboxHistoryTest`
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxHistoryTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt
Labels: skip changelog, op-ex

#4944 CP: #4934
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxHistoryTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt
Labels: skip changelog, op-ex

#4945 Make setup location required for instrumenation tests
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CoreRerouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxHistoryTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteRefreshTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SanityCoreRouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/SimpleMapViewNavigationTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/AlternativeRouteSelectionTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/SetRouteOrderTest.kt
  libnavigation-core/src/androidTest/java/com/mapbox/navigation/core/trip/service/TripServiceTest.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/BaseTest.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/NotificationTest.kt
Labels: needs backporting, skip changelog, op-ex

#4946 CP: #4945
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CoreRerouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxHistoryTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteRefreshTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SanityCoreRouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/SimpleMapViewNavigationTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/AlternativeRouteSelectionTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/SetRouteOrderTest.kt
  libnavigation-core/src/androidTest/java/com/mapbox/navigation/core/trip/service/TripServiceTest.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/BaseTest.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/NotificationTest.kt
Labels: skip changelog, op-ex

#4947 Removed IO dispatcher to fix flakey test
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineView.kt
Labels: needs backporting, skip changelog

#4948 cherry pick of PR 4947
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineView.kt
Labels: skip changelog

#5060 Fix for array index error.
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
Labels: skip changelog
