Repository mapbox/mapbox-navigation-android, pull requests merged in 2022-07, with the labels that each got.

#5987 update versions: - maps 10.7.0-beta.1; - NN 108.0.0; - common 22.1.0-beta.1
  gradle/dependencies.gradle
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/roadobject/RoadObjectMapperTest.kt
Labels: skip changelog

#5989 Trim offset calls do not get applied to trail related layers.
  CHANGELOG.md
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineView.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineDynamicData.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineViewTest.kt
Labels: skip changelog

#5993 bump navigation mapbox-java v6.6.0
  gradle/dependencies.gradle
Labels: skip changelog

#5999 Add `2.7.0-alpha.2` `CHANGELOG` entry
  CHANGELOG.md
Labels: skip changelog

#6001 Increase release CI resources to `medium+`
  .circleci/config.yml
Labels: skip changelog, op-ex

#6012 [Drop-In UI] Fixed attribution icon left margin.
  CHANGELOG.md
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/logo/LogoAttributionComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/logo/LogoAttributionComponentTest.kt
Labels: UI

#6009 use coroutines for SetRoutesTest
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SetRoutesTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/coroutines/Adapters.kt
Labels: skip changelog

#6013 updated 2.7.0-alpha.2 changelog with log level info
  CHANGELOG.md
Labels: skip changelog

#6010 improve MapboxVoiceActivity
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxVoiceActivity.kt
Labels: skip changelog

#6015 CP #5962
  CHANGELOG.md
  LICENSE.md
  libnavui-base/api/current.txt
  libnavui-base/build.gradle
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/view/MapboxExtendableButton.kt
  libnavui-base/src/main/res/layout/mapbox_extendable_button_layout.xml
  libnavui-base/src/main/res/values/attrs.xml
  libnavui-base/src/main/res/values/dimens.xml
  libnavui-base/src/main/res/values/styles.xml
  libnavui-base/src/test/java/com/mapbox/navigation/ui/base/view/MapboxExtendableButtonTest.kt
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewStyleCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/cameramode/CameraModeButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonComponent.kt
  libnavui-dropin/src/main/res/layout/mapbox_action_buttons_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_header_layout.xml
  libnavui-dropin/src/main/res/values/attrs.xml
  libnavui-dropin/src/main/res/values/dimens.xml
  libnavui-dropin/src/main/res/values/styles.xml
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/cameramode/CameraModeButtonComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonComponentTest.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/view/MapboxCameraModeButton.kt
  libnavui-maps/src/main/res/drawable/mapbox_ic_camera_follow.xml
  libnavui-maps/src/main/res/drawable/mapbox_ic_camera_overview.xml
  libnavui-maps/src/main/res/layout/mapbox_camera_mode_button_layout.xml
  libnavui-maps/src/main/res/values/attrs.xml
  libnavui-maps/src/main/res/values/styles.xml
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/view/MapboxCameraModeButtonTest.kt
  libnavui-resources/src/main/res/drawable/mapbox_bg_circle_outline.xml
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/view/MapboxAudioGuidanceButton.kt
  libnavui-voice/src/main/res/layout/mapbox_audio_guidance_button_layout.xml
  libnavui-voice/src/main/res/values/styles.xml
  qa-test-app/src/main/AndroidManifest.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivitySuite.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/DropInButtonsActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/base/BaseNavigationActivity.kt
  qa-test-app/src/main/res/drawable/bg_custom_button.xml
  qa-test-app/src/main/res/drawable/bg_custom_circle_button.xml
  qa-test-app/src/main/res/layout/layout_activity_dropin_buttons.xml
  qa-test-app/src/main/res/values/strings.xml
  qa-test-app/src/main/res/values/styles.xml
Labels: UI

#6016 CP #6012
  CHANGELOG.md
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/logo/LogoAttributionComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/logo/LogoAttributionComponentTest.kt
Labels: UI

#6014 [Drop-In UI] Camera Mode button fix
  CHANGELOG.md
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/camera/CameraAction.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/camera/CameraState.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/CameraStateController.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/internal/controller/CameraStateControllerTest.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/cameramode/CameraModeButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/camera/CameraComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/cameramode/CameraModeButtonComponentTest.kt
Labels: UI, needs backporting

#6011 [Drop-In UI] Added ability to show Info Panel in Free Drive mode.
  CHANGELOG.md
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewOptions.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewOptionsCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/InfoPanelCoordinator.kt
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_header_layout.xml
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/NavigationViewOptionsTest.kt
  qa-test-app/src/main/AndroidManifest.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivitySuite.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxNavigationViewActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxNavigationViewCustomizedActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/base/DrawerActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomInfoPanelDetailsFragment.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomSpeedLimitViewBinder.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomizedViewModel.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/LoggingNavigationViewListener.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/Utils.kt
  qa-test-app/src/main/res/drawable/ic_baseline_menu_24.xml
  qa-test-app/src/main/res/drawable/menu_button_bg.xml
  qa-test-app/src/main/res/drawable/surface_ripple.xml
  qa-test-app/src/main/res/layout/layout_activity_drawer_activity.xml
  qa-test-app/src/main/res/layout/layout_activity_navigation_view_customized.xml
  qa-test-app/src/main/res/layout/layout_drawer_menu_nav_view.xml
  qa-test-app/src/main/res/layout/layout_drawer_menu_nav_view_custom.xml
  qa-test-app/src/main/res/layout/layout_fragment_info_panel_details.xml
  qa-test-app/src/main/res/layout/layout_info_panel_header.xml
Labels: UI

#6024 CP #6011
  CHANGELOG.md
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewOptions.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewOptionsCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/InfoPanelCoordinator.kt
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_header_layout.xml
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/NavigationViewOptionsTest.kt
  qa-test-app/src/main/AndroidManifest.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivitySuite.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxNavigationViewActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxNavigationViewCustomizedActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/base/DrawerActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomInfoPanelDetailsFragment.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomSpeedLimitViewBinder.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomizedViewModel.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/LoggingNavigationViewListener.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/Utils.kt
  qa-test-app/src/main/res/drawable/ic_baseline_menu_24.xml
  qa-test-app/src/main/res/drawable/menu_button_bg.xml
  qa-test-app/src/main/res/drawable/surface_ripple.xml
  qa-test-app/src/main/res/layout/layout_activity_drawer_activity.xml
  qa-test-app/src/main/res/layout/layout_activity_navigation_view_customized.xml
  qa-test-app/src/main/res/layout/layout_drawer_menu_nav_view.xml
  qa-test-app/src/main/res/layout/layout_drawer_menu_nav_view_custom.xml
  qa-test-app/src/main/res/layout/layout_fragment_info_panel_details.xml
  qa-test-app/src/main/res/layout/layout_info_panel_header.xml
Labels: UI

#6025 Add `2.6.0` `CHANGELOG` entry
  CHANGELOG.md
Labels: skip changelog

#6027 CP #6025
  CHANGELOG.md
Labels: skip changelog

#6028 CP #6001
  .circleci/config.yml
Labels: skip changelog, op-ex

#6033 replaced info by debug logs
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/NavigationRoute.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/RouterWrapper.kt
Labels: skip changelog

#6019 fix language descriptions in docs
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxSpeechApi.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceInstructionsPlayer.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsTextPlayer.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/internal/MapboxAudioGuidanceVoice.kt
Labels: skip changelog

#6026 Bump `mapboxEvents` and `mapboxCore` dependency versions to `8.1.4` and `5.0.2` respectively
  LICENSE.md
  gradle/dependencies.gradle
  libnavigation-metrics/build.gradle
Labels: Core, skip changelog

#6034 Upgrade Nav Native to `v108.0.1`
  CHANGELOG.md
  gradle/dependencies.gradle
Labels: Core, bug :beetle:

#6036 Add `v2.7.0-alpha.3` `CHANGELOG` entry
  CHANGELOG.md
Labels: skip changelog

#6042 bump search sdk to 1.0.0-beta.33
  LICENSE.md
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/build.gradle
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainCarContext.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/FavoritesApi.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/SearchCarContext.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/search/FavoritesApiTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/QaTestApplication.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/car/MainCarSession.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/car/search/MapboxCarSearchApp.kt
Labels: Android Auto

#6046 Bump MME dependency version to `8.1.5`
  gradle/dependencies.gradle
  libnavigation-metrics/build.gradle
Labels: Core, skip changelog

#6041 Refactor Events `AppMetadata to include EventsAppMetadata.sessionId` instead of `NavigationSessionState.sessionId`
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
Labels: Core, skip changelog

#6043 Revert "Refactor car screen manager"
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/CarAppState.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/MapboxCarNavigationManager.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainScreenManager.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MapboxScreenManager.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MapboxScreenProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/placeslistonmap/PlacesListOnMapScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/SearchScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/deeplink/GeoDeeplinkNavigateAction.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/MapboxCarNavigationManagerTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/MapboxScreenManagerTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/car/MainCarSession.kt
Labels: Android Auto

#6048 add changelog for androidauto-v0.4.0
  libnavui-androidauto/CHANGELOG.md
Labels: Android Auto

#6050 changed `RouteOptionsUpdater` to use `snapping_include_closures=true` for origin of each re-route request
  CHANGELOG.md
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routeoptions/RouteOptionsUpdater.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/RouteOptionsUpdaterTest.kt
Labels: improvement

#6039 [Drop-In UI] Reset SharedApp state when MapboxNavigation is destroyed
  CHANGELOG.md
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/extensions/MapboxFlowableExtensions.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/SharedApp.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/Store.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/StateResetController.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/TripSessionStarterStateController.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/internal/controller/StateResetControllerTest.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/internal/controller/TripSessionStarterStateControllerTest.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripsession/ReplayRouteTripSession.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripsession/TripSessionComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/tripsession/TripSessionComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/model/StoreTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/util/TestStore.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
Labels: UI

#6052 Fix routeRefreshesWorksAfterSettingsNewRoutes flakiness
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteRefreshTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/coroutines/TestUtils.kt
Labels: skip changelog

#6063 ensure Common SDK pre-release versions are the same across deps
  gradle/verify-common-sdk-version.gradle
Labels: skip changelog, op-ex

#6064 redraw speed limit when map is attached
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/speedlimit/CarSpeedLimitRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/speedlimit/SpeedLimitWidget.kt
Labels: bug, Android Auto

#6053 Make `RouteArrowComponent` compatible with android auto
  CHANGELOG.md
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/MapBinder.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/installer/ComponentInstaller.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteArrowComponent.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/RouteArrowComponentTest.kt
Labels: UI, Android Auto

#6072 update v2.5.0 changelog to remove a fix included in earlier v2.4.1
  CHANGELOG.md
Labels: skip changelog

#6054 Added annotation to indicate tests should run in UI thread.
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/RouteLineLayersTest.kt
Labels: skip changelog

#6049 [Drop-In UI] Added support for Info Panel layout customization.
  CHANGELOG.md
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/extensions/MapboxNavigationObserverEx.kt
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewStyles.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewBinderCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewStyleCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/InfoPanelBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/infopanel/InfoPanelComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/InfoPanelCoordinator.kt
  libnavui-dropin/src/main/res/layout-land/mapbox_navigation_view_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_header_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_navigation_view_layout.xml
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/ViewBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/binder/infopanel/InfoPanelBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/binder/infopanel/MapboxInfoPanelBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/infopanel/InfoPanelComponentTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomInfoPanelBinder.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomizedViewModel.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
  qa-test-app/src/main/res/drawable/bg_custom_info_panel.xml
  qa-test-app/src/main/res/drawable/bg_custom_info_panel2.xml
  qa-test-app/src/main/res/layout/layout_drawer_menu_nav_view_custom.xml
  qa-test-app/src/main/res/layout/layout_info_panel.xml
  qa-test-app/src/main/res/layout/layout_info_panel_header.xml
Labels: UI

#6078 [build] restore providing module version through command line
  gradle/artifact-settings.gradle
Labels: skip changelog

#6076 use built-in widgets in android auto
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/src/androidTest/java/com/mapbox/androidauto/car/navigation/speedlimit/SpeedLimitRendererTest.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/map/widgets/ImageOverlayHost.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/map/widgets/WidgetPosition.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/map/widgets/compass/CarCompassSurfaceRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/map/widgets/compass/CompassWidget.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/map/widgets/logo/CarLogoSurfaceRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/map/widgets/logo/LogoWidget.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/speedlimit/CarSpeedLimitRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/speedlimit/SpeedLimitWidget.kt
Labels: Android Auto

#6074 introduce HistoryRecordingStateChangeObserver
  instrumentation-tests/build.gradle
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/HistoryRecordingStateChangeObserverTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/coroutines/TestUtils.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/routes/NavigationRoutesProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/HistoryRecordingStateHandler.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/HistoryRecordingStateChangeObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/extensions/MapboxNavigationExtensions.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NavigationSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NavigationSessionUtils.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationBaseTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationSetNavigationRoutesHistoryRecordingTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/HistoryRecordingStateHandlerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/NavigationSessionTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/NavigationSessionUtilsGetNewStateTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/NavigationSessionUtilsIsDrivingTest.kt
Labels: skip changelog

#6087 bump mapbox-java to 6.7.0-beta.1
  gradle/dependencies.gradle
Labels: skip changelog

#6084 [Android Auto] Add telemetry to determine when head unit is started and stopped
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/MapboxCarNavigationManager.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/telemetry/MapboxCarTelemetry.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/MapboxCarNavigationManagerTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/car/MainCarSession.kt
Labels: Android Auto

#6086 add changelog for androidauto-v0.5.0
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/build.gradle
Labels: Android Auto

#6088 clean up HistoryRecordingStateChangeObserver tests
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CoreRerouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/HistoryRecordingStateChangeObserverTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxHistoryTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SanityCoreRouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SetRoutesTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/SimpleMapViewNavigationTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/AlternativeRouteSelectionTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/RouteLineLayersTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/routes/NavigationRoutesProvider.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/routes/RoutesProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/HistoryRecordingStateChangeObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/extensions/MapboxNavigationExtensions.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
Labels: skip changelog

#6092 improve onRoutesChanged docs
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/RoutesObserver.kt
Labels: skip changelog

#6095 Bump NN dependency version to `110.0.0`
  gradle/dependencies.gradle
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/eh/EHorizonMapper.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/roadobject/RoadObjectMapperTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/eh/RoadObjectMatcher.kt
Labels: Core, skip changelog

#6098 remove unnecessary comments from test
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/HistoryRecordingStateChangeObserverTest.kt
Labels: skip changelog

#6100 add option to hide or show alternative routes
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainCarContext.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/speedlimit/CarSpeedLimitRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRouteLine.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/routes/NavigationRoutesProvider.kt
Labels: Android Auto

#6096 Introduced new `RoutePreviewController` to allow for setting route to mapbox navigation only in active guidance.
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/SharedApp.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/State.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RoutePreviewStateController.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteStateController.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/StateResetController.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/routefetch/RoutePreviewAction.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/routefetch/RoutePreviewState.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/routefetch/RoutesAction.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/internal/controller/RoutePreviewStateControllerTest.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/internal/controller/RouteStateControllerTest.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/internal/controller/StateResetControllerTest.kt
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewApi.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewListenerRegistry.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/InfoPanelTripProgressBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/MapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/backpress/OnKeyListenerComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/infopanel/InfoPanelHeaderComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/marker/FreeDriveLongPressMapComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/marker/RoutePreviewLongPressMapComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/NavigationViewListenerRegistryTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/backpress/OnKeyListenerComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/camera/CameraComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/infopanel/InfoPanelHeaderComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/location/LocationPermissionComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/marker/FreeDriveLongPressMapComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/marker/RoutePreviewLongPressMapComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/model/StoreTest.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteLineComponent.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/RouteLineComponentTest.kt
Labels: skip changelog

#6105 Add an empty line to the ci config
  .circleci/config.yml
Labels: skip changelog

#6111 add changelog for androidauto-v0.6.0
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/build.gradle
Labels: Android Auto

#6114 Fix changelog
  CHANGELOG.md
Labels: skip changelog
