Repository mapbox/mapbox-navigation-android, pull requests merged in 2022-02, with the labels that each got.

#5435 fixed coupling of vanishing route lines route progress and location point update intervals
  CHANGELOG.md
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
Labels: bug, UI

#5426 fix route shield comparison
  CHANGELOG.md
  libnavui-shield/src/main/java/com/mapbox/navigation/ui/shield/model/RouteShield.kt
  libnavui-shield/src/test/java/com/mapbox/navigation/ui/shield/model/RouteShieldTest.kt
Labels: bug, UI, needs backporting

#5436 fix route shield comparison
  CHANGELOG.md
  libnavui-shield/src/main/java/com/mapbox/navigation/ui/shield/model/RouteShield.kt
  libnavui-shield/src/test/java/com/mapbox/navigation/ui/shield/model/RouteShieldTest.kt
Labels: bug, UI

#5437 Bump NN, `common` and Maps dependency versions to `87.0.2`, `10.3.0-rc.1` and `21.1.0-rc.1` respectively
  gradle/dependencies.gradle
Labels: skip changelog

#5430 Issue-#5382: Revamp the turn icons used in Mapbox Android Nav SDK
  CHANGELOG.md
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_arrive.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_arrive_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_arrive_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_arrive_straight.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_fork.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_fork_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_fork_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_fork_slight_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_fork_slight_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_fork_straight.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_merge_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_merge_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_merge_slight_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_merge_slight_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_off_ramp.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_off_ramp_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_off_ramp_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_off_ramp_slight_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_off_ramp_slight_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_turn_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_turn_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_turn_sharp_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_turn_sharp_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_turn_slight_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_turn_slight_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_turn_straight.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_uturn.xml
  qa-test-app/build.gradle
  qa-test-app/gradle/task_generate_icons_preview.gradle
  qa-test-app/src/main/AndroidManifest.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivitySuite.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/IconsPreviewActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/widget/IconPreview.kt
  qa-test-app/src/main/res/drawable/bg_rect_black.xml
  qa-test-app/src/main/res/layout/gen_icon_previews.xml
  qa-test-app/src/main/res/layout/layout_activity_icons_preview.xml
  qa-test-app/src/main/res/layout/widget_icon_preview.xml
  qa-test-app/src/main/res/values-night/themes.xml
  qa-test-app/src/main/res/values/attrs.xml
  qa-test-app/src/main/res/values/strings.xml
  qa-test-app/src/main/res/values/themes.xml
Labels: UI, improvement

#5439 Add `v2.3.0-beta.2` `CHANGELOG`
  CHANGELOG.md
Labels: skip changelog

#5441 Add `CHANGELOG` for `v2.2.2`
  CHANGELOG.md
Labels: skip changelog

#5445 prefer new shields to legacy ones when both are available
  CHANGELOG.md
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/model/ManeuverInstructionGenerator.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/model/ManeuverInstructionGeneratorTest.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/roadname/view/MapboxRoadNameView.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/roadname/view/MapboxRoadNameViewTest.kt
Labels: UI

#5438 Refactored the cache to an LRUCache.
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/view/MapboxManeuverView.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/roadname/view/MapboxRoadNameView.kt
  libnavui-shield/src/main/java/com/mapbox/navigation/ui/shield/RoadShieldDownloader.kt
  libnavui-shield/src/main/java/com/mapbox/navigation/ui/shield/ShieldsCache.kt
  libnavui-shield/src/test/java/com/mapbox/navigation/ui/shield/ShieldByteArrayCacheTest.kt
  libnavui-shield/src/test/java/com/mapbox/navigation/ui/shield/ShieldResultCacheTest.kt
Labels: skip changelog

#5456 Followup to PR comments for maneuver related caching
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/view/MapboxManeuverView.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/roadname/view/MapboxRoadNameView.kt
  libnavui-shield/src/main/java/com/mapbox/navigation/ui/shield/RoadShieldDownloader.kt
Labels: skip changelog

#5449 Update the maneuver icons for notifications
  CHANGELOG.md
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/maneuver/TurnIconHelper.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/maneuver/model/BaseTurnIconResources.kt
  libnavui-maneuver/api/current.txt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/TurnIconHelper.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/api/MapboxTurnIconsApi.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/model/TurnIconResources.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/view/MapboxTurnIconManeuver.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/TurnIconHelperTest.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/view/MapboxTurnIconManeuverTest.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotification.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/NotificationTurnIconHelper.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/NotificationTurnIconResources.kt
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_arrive.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_arrive_left.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_arrive_right.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_arrive_straight.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_fork.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_fork_left.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_fork_right.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_fork_slight_left.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_fork_slight_right.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_fork_straight.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_merge_left.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_merge_right.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_merge_slight_left.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_merge_slight_right.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_off_ramp.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_off_ramp_left.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_off_ramp_right.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_off_ramp_slight_left.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_off_ramp_slight_right.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_turn_left.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_turn_right.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_turn_sharp_left.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_turn_sharp_right.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_turn_slight_left.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_turn_slight_right.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_turn_straight.xml
  libtrip-notification/src/main/res/drawable/mapbox_ic_notification_uturn.xml
  libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/internal/NotificationTurnIconHelperTest.kt
Labels: UI, improvement

#5463 Fixing the method documentation indicating the input parameter.
  libnavui-tripprogress/src/main/java/com/mapbox/navigation/ui/tripprogress/view/MapboxTripProgressView.kt
Labels: skip changelog

#5464 Add `CHANGELOG` for `v2.3.0-beta.3` release
  CHANGELOG.md
Labels: skip changelog

#5468 DropInUI : Refactor files
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/UIBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/screen/ActiveGuidanceScreenBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/screen/ArrivalScreenBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/screen/EmptyScreenBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/screen/FreeDriveScreenBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/screen/RoutePreviewScreenBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/DropInNavigationCamera.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/replay/DropInReplayButton.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/speedlimit/DropInSpeedLimitComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/extensions/MapboxFlowableExtensions.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/extensions/MapboxLifecycleExtensions.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/lifecycle/UIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/lifecycle/UICoordinator.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/lifecycle/DropInNavigationCamera.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/lifecycle/DropInNavigationView.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/lifecycle/DropInStartReplayButton.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/lifecycle/bottomsheet/BottomSheetCoordinator.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/lifecycle/bottomsheet/DropInRoutePreview.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/lifecycle/bottomsheet/DropInTripProgress.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/lifecycle/bottomsheet/RoutePreviewViewBinder.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/lifecycle/bottomsheet/TripProgressViewBinder.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/lifecycle/topbanner/DropInManeuver.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/lifecycle/topbanner/ManeuverViewViewBinder.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/lifecycle/topbanner/TopBannerCoordinator.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/AppLifecycleActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/RetainedActiveGuidanceFragment.kt
Labels: skip changelog

#5470 [DropIn] Rename screen layout files
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/screen/ActiveGuidanceScreenBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/screen/FreeDriveScreenBinder.kt
  libnavui-dropin/src/main/res/layout/mapbox_screen_active_guidance_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_screen_free_drive_layout.xml
Labels: skip changelog

#5473 [DropIn] Add a sound button
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewProvider.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/action/ActiveGuidanceActionBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/screen/ActiveGuidanceScreenBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/screen/FreeDriveScreenBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/MapboxAudioBehavior.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/MapboxAudioState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/SoundButtonAction.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/SoundButtonContract.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/SoundButtonProcessor.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/SoundButtonState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/SoundButtonUIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/SoundButtonViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/extensions/MapboxFlowableExtensions.kt
  libnavui-dropin/src/main/res/layout/mapbox_action_active_guidance_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_screen_active_guidance_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_screen_free_drive_layout.xml
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/sound/SoundButtonViewModelTest.kt
Labels: skip changelog

#5472 Camera Mode Button
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/view/MapboxCameraModeButton.kt
  libnavui-dropin/src/main/res/drawable/mapbox_bg_button.xml
  libnavui-dropin/src/main/res/drawable/mapbox_ic_camera_follow.xml
  libnavui-dropin/src/main/res/drawable/mapbox_ic_camera_overview.xml
  libnavui-dropin/src/main/res/layout/mapbox_camera_mode_button_layout.xml
  libnavui-dropin/src/main/res/values-night/colors.xml
  libnavui-dropin/src/main/res/values/attrs.xml
  libnavui-dropin/src/main/res/values/colors.xml
  libnavui-dropin/src/main/res/values/dimens.xml
  libnavui-dropin/src/main/res/values/styles.xml
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/view/MapboxCameraModeButtonTest.kt
  libnavui-maps/src/main/res/values/strings.xml
  libnavui-util/src/main/java/com/mapbox/navigation/ui/utils/internal/ExtendableButtonHelper.kt
  qa-test-app/src/main/AndroidManifest.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivitySuite.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/DropInButtonsActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/base/BaseNavigationActivity.kt
  qa-test-app/src/main/res/drawable/bg_custom_button.xml
  qa-test-app/src/main/res/layout/layout_activity_base_navigation.xml
  qa-test-app/src/main/res/layout/layout_activity_dropin_buttons.xml
  qa-test-app/src/main/res/values/strings.xml
  qa-test-app/src/main/res/values/styles.xml
Labels: UI, skip changelog

#5475 Refactored drop-in related route line component
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationViewCustomizedActivity.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewContext.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/screen/ActiveGuidanceScreenBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/screen/FreeDriveScreenBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routeline/DropInRouteLine.kt
Labels: skip changelog

#5471 Ak #1438 info panel
  libnavui-dropin/build.gradle
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInInfoPanelCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewContext.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/ActiveGuidanceInfoPanelBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/ArrivalInfoPanelBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/EmptyInfoPanelBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/FreeDriveInfoPanelBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/RoutePreviewInfoPanelBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/infopanel/activeguidance/InfoPanelActiveGuidanceComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/infopanel/arrival/InfoPanelArrivalComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/infopanel/freedrive/InfoPanelFreeDriveComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/infopanel/routepreview/InfoPanelRoutePreviewComponent.kt
  libnavui-dropin/src/main/res/drawable/mapbox_bg_info_panel.xml
  libnavui-dropin/src/main/res/drawable/mapbox_bg_info_panel_shadow.xml
  libnavui-dropin/src/main/res/layout/drop_in_navigation_view.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_active_guidance_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_arrival_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_free_drive_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_route_preview_layout.xml
Labels: skip changelog

#5469 Creating drop in component for the road label view component.
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationUIBinders.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/screen/ActiveGuidanceScreenBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/screen/FreeDriveScreenBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/roadlabel/RoadNameComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/roadlabel/RoadNameViewBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/extensions/MapboxFlowableExtensions.kt
  libnavui-dropin/src/main/res/drawable/mapbox_road_name_view_background.xml
  libnavui-dropin/src/main/res/layout/mapbox_road_name_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_screen_active_guidance_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_screen_free_drive_layout.xml
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/roadlabel/RoadNameComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/roadlabel/RoadNameViewBinderTest.kt
Labels: skip changelog

#5476 Added route arrow drop in component.
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationViewCustomizedActivity.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewContext.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routearrow/RouteArrowComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routearrow/RouteArrowComponentTest.kt
Labels: skip changelog

#5487 Refactored some files and removed the term DropIn
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/ActiveGuidanceMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/FreeDriveMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/location/LocationPuck.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/replay/ReplayComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routearrow/RouteArrowUIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routearrow/RouteArrowViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routearrow/RouteArrowViewModelFactory.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routeline/RouteLineComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routeline/RouteLineUIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routeline/RouteLineViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routeline/RouteLineViewModelFactory.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/SpeedLimitCoordinator.kt
  libnavui-dropin/src/main/res/layout/drop_in_navigation_view.xml
  libnavui-dropin/src/main/res/values/dimens.xml
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routearrow/RouteArrowViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routeline/RouteLineUIComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routeline/RouteLineViewModelTest.kt
  libnavui-speedlimit/src/main/java/com/mapbox/navigation/ui/speedlimit/view/MapboxSpeedLimitView.kt
Labels: skip changelog

#5484 Update all Copyright to 2022
  LICENSE.md
  gradle/dependencies.gradle
  scripts/generate-license.py
Labels: skip changelog

#5477 Decouple route fetching from the drop in route line component
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/ActiveGuidanceMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/FreeDriveMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routefetch/MapboxDropInRouteRequester.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routefetch/RouteFetchComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routeline/RouteLineComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routefetch/MapboxDropInRouteRequesterTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routefetch/RouteFetchComponentTest.kt
Labels: skip changelog

#5494 Split modules to released and not released
  Makefile
Labels: skip changelog

#5489 [DropIn] New Camera Mode, Voice Instructions & Recenter Button
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/action/ActiveGuidanceActionBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/action/FreeDriveActionBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/ActiveGuidanceMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/FreeDriveMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/DropInCameraState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/DropInNavigationCamera.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/cameramode/CameraModeButtonBehaviour.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/cameramode/CameraModeButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonBehaviour.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/MapboxAudioBehavior.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/SoundButtonAction.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/extensions/NavigationCameraFlowable.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/view/MapboxExtendableButton.kt
  libnavui-dropin/src/main/res/drawable/mapbox_ic_camera_recenter.xml
  libnavui-dropin/src/main/res/layout/drop_in_navigation_view.xml
  libnavui-dropin/src/main/res/layout/mapbox_action_active_guidance_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_action_free_drive_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_extendable_button_layout.xml
  libnavui-dropin/src/main/res/values/attrs.xml
  libnavui-dropin/src/main/res/values/dimens.xml
  libnavui-dropin/src/main/res/values/styles.xml
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/view/MapboxExtendableButtonTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/DropInButtonsActivity.kt
  qa-test-app/src/main/res/layout/layout_activity_dropin_buttons.xml
Labels: UI, skip changelog

#5498 updated mapbox-java to v6.3.0
  gradle/dependencies.gradle
Labels: needs backporting, skip changelog

#5499 Backport #5498 to release-v2.3
  gradle/dependencies.gradle
Labels: skip changelog

#5502 Updating change log for release of version 2.3.0-rc.2
  CHANGELOG.md
Labels: skip changelog

#5460 Refactoring of route line related tests
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsRoboTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/RouteArrowUtilsRoboTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/RouteArrowUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/api/MapboxRouteArrowViewTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/model/RouteArrowOptionsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiRoboTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineViewTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLineRoboTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLineTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/model/MapboxRouteLineOptionsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/testing/TestingUtil.kt
Labels: skip changelog

#5490 allow creating mapbox navigation with new options every time
  CHANGELOG.md
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/lifecycle/MapboxNavigationApp.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/lifecycle/MapboxNavigationAppDelegate.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/lifecycle/MapboxNavigationOwner.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/lifecycle/NavigationOptionsProvider.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/lifecycle/MapboxNavigationAppDelegateTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/lifecycle/MapboxNavigationOwnerTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/MapboxNavigationViewModelTest.kt
Labels: needs backporting, improvement

#5495 [DropIn] Add Trip Progress Component
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/ActiveGuidanceInfoPanelBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressContract.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressProcessor.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressUIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/RoadNameLabelCoordinator.kt
  libnavui-dropin/src/main/res/layout/drop_in_navigation_view.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_active_guidance_layout.xml
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressProcessorTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressViewModelTest.kt
Labels: UI, skip changelog

#5488 [DropIn] Change a custom speed limit at runtime
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationViewCustomizedActivity.kt
  examples/src/main/res/layout/layout_activity_navigation_view_customized.xml
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewContext.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/location/LocationPuck.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/speedlimit/SpeedLimitViewBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/ActionListCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/GuidanceCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/RoadNameLabelCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/SpeedLimitCoordinator.kt
Labels: UI, skip changelog
