Repository mapbox/mapbox-navigation-android, pull requests merged in 2022-03, with the labels that each got.

#5518 fix unexpected MapboxNavigation destroy
  CHANGELOG.md
  libnavigation-core/src/main/java/com/mapbox/navigation/core/lifecycle/CarAppLifecycleOwner.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/lifecycle/CarAppLifecycleOwnerTest.kt
Labels: bug

#5522 fix unexpected MapboxNavigation destroy
  CHANGELOG.md
  libnavigation-core/src/main/java/com/mapbox/navigation/core/lifecycle/CarAppLifecycleOwner.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/lifecycle/CarAppLifecycleOwnerTest.kt
Labels: bug

#5521 Create a `UIViewModel`
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/ActiveGuidanceMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/FreeDriveMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routefetch/MapboxDropInRouteRequester.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routefetch/RoutesViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/lifecycle/UICoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/lifecycle/UIViewModel.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routefetch/MapboxDropInRouteRequesterTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routefetch/RouteFetchComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routefetch/RoutesBehaviorTest.kt
Labels: UI, skip changelog

#5527 add changelog for v2.3.0
  CHANGELOG.md
Labels: skip changelog

#5526 add changelog for v2.3.0
  CHANGELOG.md
Labels: skip changelog

#5532 [DropIn] Refactor replay and audio guidance use UIViewModel
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/replay/ReplayViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/MapboxAudioApi.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/MapboxAudioBehavior.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/MapboxAudioState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/MapboxAudioViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/SoundButtonAction.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/lifecycle/UIViewModel.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/sound/MapboxAudioViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/lifecycle/UIViewModelTest.kt
Labels: UI, skip changelog

#5534 refactor camera to use view model
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationUIBinders.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/action/ActiveGuidanceActionBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/action/FreeDriveActionBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/ActiveGuidanceMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/FreeDriveMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraAnimate.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraMode.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/DropInCameraMode.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/DropInCameraState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/DropInNavigationCamera.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/cameramode/CameraModeButtonBehaviour.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/cameramode/CameraModeButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonBehaviour.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonContract.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonProcessor.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterUIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/ActionListCoordinator.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonProcessorTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/recenter/RecenterViewModelTest.kt
Labels: skip changelog

#5533 [DropIn] Migrate location to the UIViewModel
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/ActiveGuidanceMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/FreeDriveMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/location/LocationPuck.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/location/LocationViewModel.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/location/LocationViewModelTest.kt
Labels: UI, skip changelog

#5549 Adding default speed limit sign type based on locale to view.
  libnavui-speedlimit/src/main/java/com/mapbox/navigation/ui/speedlimit/view/MapboxSpeedLimitView.kt
  libnavui-speedlimit/src/test/java/com/mapbox/navigation/ui/speedlimit/view/MapboxSpeedLimitViewTest.kt
Labels: skip changelog

#5543 [DropInUI] Make audio guidance work
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/action/ActiveGuidanceActionBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/audioguidance/AudioGuidanceApi.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/audioguidance/AudioGuidanceButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/audioguidance/AudioGuidanceServices.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/audioguidance/AudioGuidanceState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/audioguidance/AudioGuidanceViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/audioguidance/AudioGuidanceVoice.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routefetch/RoutesViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/MapboxAudioApi.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/MapboxAudioState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/extensions/MapboxFlowableExtensions.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/audioguidance/AudioGuidanceApiTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/audioguidance/AudioGuidanceViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/audioguidance/AudioGuidanceVoiceTest.kt
Labels: UI, skip changelog

#5553 [DropInUi] Attach all top level UICoordinators with the onCreate event
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
Labels: UI, skip changelog

#5561 [DropIn] Do not remove all views when coordinator is detached
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/lifecycle/UICoordinator.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/lifecycle/UICoordinatorTest.kt
Labels: UI, skip changelog

#5559 [DropIn] Remove flow parameter from UIViewModel
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routefetch/RoutesViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/lifecycle/UIViewModel.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routefetch/RoutesViewModelTest.kt
Labels: UI, skip changelog

#5545 [Drop-In UI] Camera integration
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/ActiveGuidanceMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/FreeDriveMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/RoutePreviewMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraAnimate.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraMode.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/TargetCameraMode.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/cameramode/CameraModeButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/extensions/NavigationCameraFlowable.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/camera/CameraComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/camera/CameraViewModelTest.kt
Labels: skip changelog

#5554 DropIn render route shields
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxManeuverActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationViewCustomizedActivity.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewContext.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationUIBinders.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/maneuver/ManeuverComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/maneuver/ManeuverViewBinder.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/binder/infopanel/InfoPanelHeaderBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/maneuver/ManeuverComponentTest.kt
Labels: skip changelog

#5562 [DropIn] Add tests for UIComponent
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/lifecycle/UIComponentTest.kt
Labels: UI, skip changelog

#5563 add changelog for v2.4.0-beta.1
  CHANGELOG.md
Labels: skip changelog

#5555 [DropIn] Fix location puck on app open
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/ActiveGuidanceMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/FreeDriveMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/RoutePreviewMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/location/LocationComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/location/LocationPuck.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/location/LocationViewModel.kt
Labels: UI, skip changelog

#5564 [DROP-IN] DestinationViewModel
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewContext.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/destination/DestinationAction.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/destination/DestinationState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/destination/DestinationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/marker/LongPressMapComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/marker/MapMarkersComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/navigation/NavigationStateComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routefetch/RoutesAction.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routefetch/RoutesState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routefetch/RoutesViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/BackPressManager.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/InfoPanelCoordinator.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/marker/LongPressMapComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/marker/MapMarkersComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/navigation/NavigationStateComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routefetch/RoutesViewModelTest.kt
Labels: UI, skip changelog

#5550 [DropInUI] Updating route line component.
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/ActiveGuidanceMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/RoutePreviewMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routearrow/RouteArrowComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routeline/RouteLineComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routearrow/RouteArrowComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routeline/RouteLineComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/util/TestingUtil.kt
Labels: skip changelog

#5570 [Drop-In UI] Update state when click on end navigation
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routefetch/RoutesAction.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routefetch/RoutesViewModel.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routefetch/RoutesViewModelTest.kt
Labels: skip changelog

#5577 DropIn Added route shields to road name label component.
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/roadlabel/RoadNameLabelComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/roadlabel/RoadNameViewBinder.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/roadlabel/RoadNameComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/roadlabel/RoadNameLabelComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/roadlabel/RoadNameViewBinderTest.kt
Labels: skip changelog

#5576 [DROP-IN] tests for LocationComponent
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/location/LocationComponentTest.kt
Labels: UI, skip changelog

#5569 Improve Location#getExtras conversion
  libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/LocationEx.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/navigator/LocationExTest.kt
Labels: skip changelog

#5551 Allow VERSION_NAME to be used as name for publishing artifacts
  .circleci/config.yml
  gradle.properties
  gradle/artifact-settings.gradle
Labels: skip changelog

#5578 update action list to use one binder
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationUIBinders.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/ActionButtonBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/action/EmptyActionBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/action/FreeDriveActionBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/audioguidance/AudioGuidanceButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/cameramode/CameraModeButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/ActionButtonsCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/ActionListCoordinator.kt
  libnavui-dropin/src/main/res/layout/drop_in_navigation_view.xml
  libnavui-dropin/src/main/res/layout/mapbox_action_buttons_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_action_free_drive_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_screen_active_guidance_layout.xml
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/cameramode/CameraModeButtonComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonComponentTest.kt
Labels: skip changelog

#5571 [DROP-IN] Reverse-geocoding destination.
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/FreeDriveMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/RoutePreviewMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/destination/DestinationAction.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/destination/DestinationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/infopanel/InfoPanelHeaderComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/marker/GeocodingComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/marker/MapMarkersComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/model/Destination.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/util/Geocoder.kt
  libnavui-dropin/src/main/res/values/strings.xml
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/infopanel/InfoPanelHeaderComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/marker/GeocodingComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/util/GeocoderTest.kt
Labels: UI, skip changelog

#5580 [DROP-IN] Flattened UIBinders in NavigationUIBinders.
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewContext.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationUIBinders.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewBinderCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/UIBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/InfoPanelHeaderBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/ActionButtonsCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/InfoPanelCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/ManeuverCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/RoadNameLabelCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/SpeedLimitCoordinator.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/NavigationUIBindersTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/binder/infopanel/InfoPanelHeaderBinderTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxNavigationViewCustomizedActivity.kt
Labels: UI, skip changelog

#5593 fixed publisher production auto trigger
  scripts/publish_api_docs_android.sh
Labels: skip changelog

#5582 [DROP-IN] Fixed route line clearing.
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/ActiveGuidanceMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/FreeDriveMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routeline/RouteLineComponent.kt
Labels: UI, skip changelog

#5592 [DropIn] Remove back press functions from DropInNavigationView
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewContext.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/backpress/OnKeyListenerComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/BackPressManager.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/backpress/OnKeyListenerComponentTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxNavigationViewActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxNavigationViewCustomizedActivity.kt
Labels: UI, skip changelog

#5595 [Drop-In UI] Define colors and styles for day and night mode
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/maneuver/ManeuverComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/MapCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/view/MapboxCameraModeButton.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/view/MapboxExtendableButton.kt
  libnavui-dropin/src/main/res/drawable/mapbox_bg_button.xml
  libnavui-dropin/src/main/res/drawable/mapbox_bg_button_primary.xml
  libnavui-dropin/src/main/res/drawable/mapbox_bg_handle.xml
  libnavui-dropin/src/main/res/drawable/mapbox_bg_info_panel_shadow.xml
  libnavui-dropin/src/main/res/drawable/mapbox_ic_camera_follow.xml
  libnavui-dropin/src/main/res/drawable/mapbox_ic_camera_overview.xml
  libnavui-dropin/src/main/res/drawable/mapbox_ic_camera_recenter.xml
  libnavui-dropin/src/main/res/drawable/mapbox_ic_close.xml
  libnavui-dropin/src/main/res/drawable/mapbox_ic_puck.xml
  libnavui-dropin/src/main/res/drawable/mapbox_ic_route.xml
  libnavui-dropin/src/main/res/drawable/mapbox_map_pin.xml
  libnavui-dropin/src/main/res/drawable/mapbox_road_name_view_background.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_header_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_trip_progress_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_maneuver_guidance_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_road_name_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_speed_limit_layout.xml
  libnavui-dropin/src/main/res/values-night/colors.xml
  libnavui-dropin/src/main/res/values/attrs.xml
  libnavui-dropin/src/main/res/values/colors.xml
  libnavui-dropin/src/main/res/values/dimens.xml
  libnavui-dropin/src/main/res/values/styles.xml
  qa-test-app/src/main/AndroidManifest.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxNavigationViewCustomizedActivity.kt
  qa-test-app/src/main/res/layout/layout_activity_navigation_view_customized.xml
Labels: skip changelog

#5598 Added max height/width to certain UI component containers.
  libnavui-dropin/src/main/res/layout/drop_in_navigation_view.xml
Labels: skip changelog

#5599 [DROP-IN] Expose option settings for Drop-In UI
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewContext.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/LegacyNavigationViewOptions.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/MapboxNavigationViewApi.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewOptions.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewBinderCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewOptionsCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/ActiveGuidanceMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/FreeDriveMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/RoutePreviewMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/lifecycle/UIComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/LegacyNavigationViewOptionsTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/NavigationViewOptionsTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/lifecycle/UIComponentTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxNavigationViewCustomizedActivity.kt
Labels: UI, skip changelog

#5604 Adopt Common SDK logging parsing logic
  CHANGELOG.md
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxBuildingHighlightActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxManeuverActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CoreRerouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/SetRouteOrderTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/history/MapboxHistoryTestRule.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/RoutingTilesFiles.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/accounts/BillingController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/HistoryFiles.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/MapboxHistoryRecorder.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/lifecycle/CarAppLifecycleOwner.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/lifecycle/MapboxNavigationAppDelegate.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/lifecycle/MapboxNavigationOwner.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/LocationEx.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistoryMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route/ReplayRouteMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/reroute/MapboxRerouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routeoptions/RouteOptionsUpdater.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/LocationsCollectorImpl.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/NavEventsPopulateUtil.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/service/MapboxTripService.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSessionLocationEngine.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/history/MapboxHistoryRecorderTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routerefresh/RouteRefreshControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/service/MapboxTripServiceTest.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/RouterWrapper.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/ConnectivityHandler.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/LoggerProvider.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/RequestMap.kt
  libnavigation-util/src/test/java/com/mapbox/navigation/utils/internal/ConnectivityHandlerTest.kt
  libnavigation-util/src/test/java/com/mapbox/navigation/utils/internal/LoggerProviderFormatTest.kt
  libnavigation-util/src/test/java/com/mapbox/navigation/utils/internal/LoggerProviderTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/NavigatorLoader.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/location/LocationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/marker/GeocodingComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/location/LocationViewModelTest.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/view/MapboxManeuverView.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/PredictiveCacheController.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSource.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/ViewportDataSourceProcessor.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/guidance/signboard/api/MapboxExternalFileResolver.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/arrow/api/MapboxRouteArrowView.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLine.kt
  libnavui-util/src/main/java/com/mapbox/navigation/ui/utils/internal/SvgUtil.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsFilePlayer.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsTextPlayer.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/lifecycle/backstack/BackStackBinding.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/lifecycle/viewmodel/DropInLocationViewModel.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/StatusActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/base/BaseNavigationActivity.kt
Labels: release blocker, Core

#5603 [DROP-IN] Reverse geocode Destination only once.
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/marker/GeocodingComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/marker/GeocodingComponentTest.kt
Labels: UI, skip changelog

#5602 Add debug log if location coming from location provider is not fresh enough
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSessionLocationEngine.kt
Labels: skip changelog

#5605 [DROP-IN] Added haptic feedback for map long press.
  libnavui-dropin/src/main/AndroidManifest.xml
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/marker/FreeDriveLongPressMapComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/marker/RoutePreviewLongPressMapComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/util/HapticFeedback.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/marker/FreeDriveLongPressMapComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/marker/RoutePreviewLongPressMapComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/util/HapticFeedbackTest.kt
Labels: UI, skip changelog

#5610 changelog for v2.4.0-beta.3
  CHANGELOG.md
Labels: skip changelog

#5609 [DropInUi] Create lifecycle to survive configuration changes
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewModel.kt
Labels: UI, skip changelog

#5614 Fix `HistoryEventMapper#mapNavigationRoute` for when `SetRouteHistoryRecord` has empty `routeRequest`
  CHANGELOG.md
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/model/HistoryEventMapper.kt
Labels: bug, Core

#5615 Update permission flow for qa-test-app
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivityDescription.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivitySuite.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/utils/LocationPermissionsHelper.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/utils/PermissionsHelper.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MainActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/adapters/GenericListAdapter.kt
Labels: skip changelog

#5617 catch exceptions when parsing DirectionsRefreshResponse
  CHANGELOG.md
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/RouterWrapper.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/util/DirectionsRouteRefreshUtils.kt
Labels: bug

#5623 [DropInUi] Fix audio guidance
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/audioguidance/AudioGuidanceViewModel.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/audioguidance/AudioGuidanceViewModelTest.kt
Labels: bug, UI, skip changelog

#5548 [DropInUi] Allow for swapping in custom map
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewContext.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/MapCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/MapLayoutCoordinator.kt
  libnavui-dropin/src/main/res/layout/drop_in_navigation_view.xml
  libnavui-dropin/src/main/res/layout/mapbox_mapview_layout.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxNavigationViewCustomizedActivity.kt
  qa-test-app/src/main/res/layout/layout_activity_navigation_view_customized.xml
Labels: UI, skip changelog

#5627 Add empty waypoint names to `HistoryEventMapper#mapNavigationRoute` as old records may not include them
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/model/HistoryEventMapper.kt
Labels: bug, Core, skip changelog

#5621 [DROP-IN] Add ability for interested UIComponents to observe changes to map styles.
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationViewContext.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/MapStyleLoader.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationUIBinders.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/ActiveGuidanceMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/FreeDriveMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/RoutePreviewMapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/maneuver/ManeuverComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/maneuver/ManeuverViewBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/roadlabel/RoadNameLabelComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/roadlabel/RoadNameViewBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/ManeuverCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/MapLayoutCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/RoadNameLabelCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/extensions/MapboxStyleExtensions.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/lifecycle/UIComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/MapStyleLoaderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/NavigationUIBindersTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/maneuver/ManeuverComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/roadlabel/RoadNameLabelComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/roadlabel/RoadNameViewBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/extensions/MapboxStyleExtensionsKtTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxNavigationViewCustomizedActivity.kt
Labels: UI, skip changelog

#5622 [DropInUi] Request location permissions by default
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripsession/LocationPermissionComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripsession/TripSessionStarterViewModel.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/tripsession/LocationPermissionComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/tripsession/TripSessionStarterViewModelTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivitySuite.kt
Labels: UI, skip changelog

#5625 Add more logs to MapboxTripSession
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionNoSetupTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
Labels: skip changelog

#5632 Bump `mapboxSdkServices` dependency version to `6.4.0-beta.4`
  gradle/dependencies.gradle
Labels: Core, skip changelog

#5636 Add `v2.4.0-rc.1` `CHANGELOG` entry
  CHANGELOG.md
Labels: skip changelog

#5607 Added fix to stop the camera from setting itself to idle when an ongoing transition is canceled.
  CHANGELOG.md
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/NavigationCamera.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/camera/NavigationCameraTest.kt
Labels: ⚠️ DO NOT MERGE
