Repository mapbox/mapbox-navigation-android, pull requests merged in 2022-10, with the labels that each got.

#5951 Default IO dispatcher
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/ThreadController.kt
Labels: skip changelog

#6431 add known issue warning about a crash in telemetry settings dialog
  CHANGELOG.md
Labels: skip changelog

#6402 better control coroutine scopes in MapboxNavigation test
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationBaseTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libtesting-utils/src/main/java/com/mapbox/navigation/testing/MainCoroutineRule.kt
Labels: skip changelog

#6214 Alternatives: adopt new NN handling alternatives route flow
  CHANGELOG.md
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/idling/RouteAlternativesIdlingResource.kt
  instrumentation-tests/src/main/res/raw/route_response_alternative_continue.json
  instrumentation-tests/src/main/res/raw/route_response_alternative_start.json
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesController.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesControllerTest.kt
Labels: skip changelog

#6436 bump search sdk version to 1.0.0-beta.37
  gradle/dependencies.gradle
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainActionStrip.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/PlaceRecordMapper.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/car/search/CarPlaceSearchImpl.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/internal/car/search/CarPlaceSearchImplTest.kt
Labels: skip changelog, Android Auto

#6447 Cleanup lazy logs
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/LoggerProvider.kt
Labels: skip changelog

#6423 Core telemetry migration
  LICENSE.md
  gradle/dependencies.gradle
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/metric/MetricEventInternal.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/metrics/MetricEvent.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/metrics/MetricsReporter.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/NavEventsPopulateUtil.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/NavTelemetryUtils.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/CoreTelemetryEventUtils.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationAppUserTurnstileEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationArriveEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationCancelEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationCustomEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationDepartEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationFeedbackEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationFreeDriveEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationRerouteEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/PhoneState.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationBaseTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationRerouteInterruptionTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/ShadowEventsService.java
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/CoreTelemetryEventUtilsTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/EventsTestHelper.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/NavigationArriveEventTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/NavigationCancelEventTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/NavigationCustomEventTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/NavigationDepartEventTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/NavigationFeedbackEventTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/NavigationFreeDriveEventTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/NavigationRerouteEventTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/testutil/EventsProvider.kt
  libnavigation-metrics/api/current.txt
  libnavigation-metrics/build.gradle
  libnavigation-metrics/src/main/java/com/mapbox/navigation/metrics/MapboxMetricsReporter.kt
  libnavigation-metrics/src/main/java/com/mapbox/navigation/metrics/extensions/MetricEventEx.kt
  libnavigation-metrics/src/main/java/com/mapbox/navigation/metrics/internal/EventsServiceProvider.kt
  libnavigation-metrics/src/main/java/com/mapbox/navigation/metrics/internal/TelemetryServiceProvider.kt
  libnavigation-metrics/src/main/java/com/mapbox/navigation/metrics/internal/TelemetryUtilsDelegate.kt
  libnavigation-metrics/src/main/java/com/mapbox/navigation/metrics/internal/event/NavigationAppUserTurnstileEvent.kt
  libnavigation-metrics/src/test/java/com/mapbox/navigation/metrics/MapboxMetricsReporterTest.kt
Labels: release blocker, skip changelog

#6449 use non-immediate dispatcher in camera component
  CHANGELOG.md
  libnavui-base/api/current.txt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/lifecycle/UIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/camera/CameraComponent.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/CameraModeButtonComponent.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RecenterButtonComponent.kt
Labels: bug, UI

#6454 [Android Auto] Prepare androidauto-v0.13.0
  LICENSE.md
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/build.gradle
Labels: skip changelog, Android Auto

#6458 MapboxMetricsReporter: logging fix
  libnavigation-metrics/src/main/java/com/mapbox/navigation/metrics/MapboxMetricsReporter.kt
Labels: skip changelog

#6473 add INTERNET and ACCESS_NETWORK_STATE permissions
  libnavigation-core/src/main/AndroidManifest.xml
Labels: skip changelog

#6463 [Drop-In UI] update guideline position every time info panel top changes
  CHANGELOG.md
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/infopanel/InfoPanelCoordinator.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomInfoPanelBinder.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomInfoPanelBinderWithFixedHeight.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomizedViewModel.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
  qa-test-app/src/main/res/layout/layout_drawer_menu_nav_view_custom.xml
  qa-test-app/src/main/res/values/strings.xml
Labels: bug, UI

#6477 NAVAND-750: introduce HistoryRecordingSessionState
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CopilotIntegrationTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/HistoryRecordingStateChangeObserverTest.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/CopilotSessionObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/DeveloperMetadataAggregator.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/HistoryRecordingStateHandler.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/HistoryRecordingSessionState.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/HistoryRecordingStateChangeObserver.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NavigationSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NavigationSessionUtils.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/DeveloperMetadataAggregatorTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/NavigationComponentProviderTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/HistoryRecordingSessionStateTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/HistoryRecordingStateHandlerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/NavigationSessionUtilsGetNewHistoryRecordingSessionStateTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/NavigationSessionUtilsGetNewNavigationSessionStateTest.kt
Labels: skip changelog

#6472 [Drop-In UI] do not reset navigation camera state after view recreation
  CHANGELOG.md
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/CameraStateController.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/internal/controller/CameraStateControllerTest.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/camera/CameraComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/camera/CameraComponentTest.kt
Labels: UI, improvement

#6479 Add changelog for androidauto-v0.14.0
  libnavui-androidauto/CHANGELOG.md
Labels: skip changelog, Android Auto

#6433 [Drop-In] Introduce MapViewBinder
  CHANGELOG.md
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewBinderCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/map/BoundMapViewProvider.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/map/MapLayoutCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/map/MapViewBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/map/MapboxMapViewBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/map/RouteLineComponentContractImpl.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/navigationview/NavigationViewBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/navigationview/NavigationViewContext.kt
  libnavui-dropin/src/main/res/layout/mapbox_mapview_layout.xml
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/map/MapLayoutCoordinatorTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/map/MapViewBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/map/MapboxMapViewBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/map/ShadowMapView.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/navigationview/NavigationViewBinderTest.kt
  libnavui-dropin/src/test/res/values/mapbox_access_token.xml
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteLineComponent.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomMapViewBinder.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
Labels: skip changelog

#6488 invoke HistoryRecordingStateChangeObserver#onShouldStartRecording with current state
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/HistoryRecordingStateChangeObserverTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/HistoryRecordingStateHandler.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/extensions/MapboxNavigationExtensions.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/HistoryRecordingStateHandlerCopilotTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/HistoryRecordingStateHandlerObserverRegisterTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/HistoryRecordingStateHandlerTest.kt
Labels: skip changelog

#6483 [Drop-In UI] Use OnBackPressedDispatcher for back press handling
  CHANGELOG.md
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/backpress/BackPressedComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/backpress/OnKeyListenerComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/extensions/ContextEx.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/navigationview/NavigationViewListener.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/navigationview/NavigationViewListenerRegistry.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/permission/LocationPermissionComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/backpress/BackPressedComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/backpress/OnKeyListenerComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/navigationview/NavigationViewListenerRegistryTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/permission/LocationPermissionComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/testutil/TestLifecycleOwner.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
Labels: UI

#6489 [Drop-In UI] check if location permissions are granted on inResume
  CHANGELOG.md
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/permission/LocationPermissionComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/permission/LocationPermissionComponentTest.kt
Labels: bug, UI

#6478 [Android Auto] Make the `MapboxCarContext` forwards compatible
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/MapboxCarNavigationManager.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MapboxCarContext.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MapboxCarOptions.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MapboxCarOptionsCustomization.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/core/CarFeedbackOptions.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/core/CarFeedbackScreenFactory.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/speedlimit/CarSpeedLimitRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/placeslistonmap/PlacesListOnMapScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRoutePreviewRequest.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRoutePreviewScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/RoutePreviewCarContext.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/PlaceSearchScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/SearchCarContext.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/settings/CarSettingsScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/settings/MapboxCarStorage.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/car/context/MapboxCarContextOwner.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/car/context/MapboxCarServiceDelegate.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/car/search/CarPlaceSearchImpl.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/notification/CarPendingIntentFactory.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/notification/MapboxCarNotification.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/notification/MapboxCarNotificationOptions.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/screenmanager/MapboxScreenGraph.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/screenmanager/MapboxScreenManager.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/screenmanager/factories/ActiveGuidanceFeedbackScreenFactory.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/screenmanager/factories/ArrivalScreenFactory.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/screenmanager/factories/FavoritesFeedbackScreenFactory.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/screenmanager/factories/FreeDriveFeedbackScreenFactory.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/screenmanager/factories/RoutePreviewFeedbackScreenFactory.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/screenmanager/factories/RoutePreviewScreenFactory.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/screenmanager/factories/SearchPlacesFeedbackScreenFactory.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/MapboxCarContextTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/navigation/speedlimit/CarSpeedLimitRendererTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/preview/CarRouteRequestTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/settings/CarSettingsScreenTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/internal/car/search/CarPlaceSearchImplTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/internal/car/search/PlaceSearchScreenTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/notification/MapboxCarNotificationOptionsTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/notification/MapboxCarNotificationTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/screenmanager/MapboxScreenManagerTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/car/MainCarSession.kt
Labels: skip changelog, Android Auto

#6494 [Android Auto] Simplify action provider
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/action/MapboxActionProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/ui/CarFeedbackAction.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/ActiveGuidanceScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/placeslistonmap/PlacesListOnMapScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/CarAudioGuidanceUi.kt
Labels: Android Auto

#6487 [Drop-In UI] synchronize drop-in navigation routes with mapbox navigation
  CHANGELOG.md
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteStateController.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/routefetch/RoutesAction.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/internal/controller/RouteStateControllerTest.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/camera/CameraComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/camera/CameraComponentTest.kt
Labels: UI

#6492 Remove MapboxCarApp
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/MapboxCarApp.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/location/CarLocationProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/location/CarLocationRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/placeslistonmap/PlacesListOnMapManager.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRoutePreviewRequest.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/deeplink/GeoDeeplinkPlacesListOnMapProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/location/CarAppLocation.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/location/impl/CarAppLocationImpl.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/preview/CarRoutePreviewRequestTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/deeplink/GeoDeeplinkPlacesListOnMapProviderTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/car/MainCarSession.kt
Labels: Android Auto

#6504 [Android Auto] Prepare androidauto-v0.15.0
  gradle/dependencies.gradle
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/build.gradle
Labels: skip changelog, Android Auto

#6505 Improve voiceInstructionsPlayer tests
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/navigationview/MapboxNavigationViewApiTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/MapboxAudioGuidanceTest.kt
Labels: skip changelog, improvement

#6499 updated mapbox-java to v6.9.0-beta.1
  gradle/dependencies.gradle
  libnavigation-base/src/test/java/com/mapbox/navigation/base/internal/route/NavigationRouteExTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/route/NavigationRouteTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSessionTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/reroute/MapboxRerouteControllerTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/preview/CarRoutePreviewRequestTest.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/internal/routefetch/RouteOptionsProviderTest.kt
  libtesting-navigation-util/src/main/java/com/mapbox/navigation/testing/MapboxJavaObjectsFactory.kt
Labels: skip changelog

#6508 [Drop-In UI] fix road label position not updating in some cases
  CHANGELOG.md
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/infopanel/InfoPanelCoordinator.kt
Labels: bug, UI

#6509 Add multiple `MapboxHistoryRecorder`s support (needed for Copilot)
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/HistoryFiles.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/MapboxHistoryRecorder.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/extensions/MapboxNavigationExtensions.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationBaseTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/NavigatorLoader.kt
Labels: Core, skip changelog

#6005 NAVAND-714 - Added Waypoints to NavigationRoute; - RouteOptionsUpdater refactored;
  CHANGELOG.md
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/extensions/WaypointEx.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/route/Waypoint.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/utils/DirectionsRouteEx.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/utils/RouterEx.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/utils/WaypointFactory.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/NavigationRoute.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/RouteProgress.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/internal/extensions/WaypointExTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/internal/route/NavigationRouteExTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/route/NavigationRouteTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/route/RouteExclusionsTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/accounts/BillingController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/model/HistoryEventMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routeoptions/RouteOptionsUpdater.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/RouteOptionsUpdaterParameterizedTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/RouteOptionsUpdaterTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/utils/TripStatusEx.kt
  libnavigator/src/test/java/com/mapbox/navigation/navigator/internal/router/utils/TripStatusExTest.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/building/BuildingProcessor.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/building/BuildingProcessorTest.kt
  libtesting-navigation-base/src/main/java/com/mapbox/navigation/testing/factories/NavigationRouteFactory.kt
  libtesting-thirdparty/src/main/java/com/mapbox/navigation/testing/factories/NativeFactories.kt
Labels: skip changelog

#6498 [Drop-In UI] Fix issue with `MapboxExtendableButton` so it can be rendered in any shape possible.
  CHANGELOG.md
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/MapboxExtendableButtonParams.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewOptionsCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewStyleCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/actionbutton/ActionButtonsBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/actionbutton/AudioGuidanceButtonBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/actionbutton/CameraModeButtonBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/actionbutton/CompassButtonBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/actionbutton/RecenterButtonBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/extendablebutton/EndNavigationButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/extendablebutton/RoutePreviewButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/extendablebutton/StartNavigationButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/infopanel/InfoPanelEndNavigationButtonBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/infopanel/InfoPanelRoutePreviewButtonBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/infopanel/InfoPanelStartNavigationButtonBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/extensions/NavigationViewContextEx.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/extensions/ViewGroupEx.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/navigationview/NavigationViewOptions.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/navigationview/NavigationViewStyles.kt
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_header_destination_preview_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_header_route_preview_layout.xml
  libnavui-dropin/src/main/res/values/styles.xml
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/actionbutton/ActionButtonsBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/actionbutton/AudioGuidanceButtonBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/actionbutton/CameraModeButtonBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/actionbutton/CompassButtonBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/actionbutton/RecenterButtonBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/extendablebutton/EndNavigationButtonComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/extendablebutton/RoutePreviewButtonComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/extendablebutton/StartNavigationButtonComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/infopanel/InfoPanelEndNavigationButtonBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/infopanel/InfoPanelRoutePreviewButtonBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/infopanel/InfoPanelStartNavigationButtonBinderTest.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/CompassButtonComponent.kt
  libnavui-maps/src/main/res/drawable/mapbox_ic_compass.xml
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/CompassButtonComponentTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomizedViewModel.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
  qa-test-app/src/main/res/layout/layout_drawer_menu_nav_view_custom.xml
  qa-test-app/src/main/res/values/styles.xml
  qa-test-app/src/main/res/values/styles_custom_nav_view.xml
Labels: UI

#6506 [Drop-In UI] Add support to show/hide views spawned by Drop-In UI
  CHANGELOG.md
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewOptionsCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/actionbutton/ActionButtonsCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/extensions/NavigationViewContextEx.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/maneuver/ManeuverCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/navigationview/NavigationViewOptions.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/roadname/RoadNameCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/speedlimit/SpeedLimitCoordinator.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/actionbutton/ActionButtonsBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/actionbutton/ActionButtonsCoordinatorTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/infopanel/InfoPanelHeaderActiveGuidanceBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/infopanel/InfoPanelHeaderArrivalBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/infopanel/InfoPanelHeaderDestinationPreviewBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/infopanel/InfoPanelHeaderRoutesPreviewBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/maneuver/ManeuverCoordinatorTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/navigationview/NavigationViewOptionsTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/roadname/RoadNameCoordinatorTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/speedlimit/SpeedLimitCoordinatorTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomizedViewModel.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
  qa-test-app/src/main/res/layout/layout_drawer_menu_nav_view_custom.xml
Labels: UI
