Repository mapbox/mapbox-navigation-android, pull requests merged in 2022-01, with the labels that each got.

#5313 updated README.md
  README.md
Labels: skip changelog

#5306 Call location update immediately
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
Labels: skip changelog

#5312 Run linter for each contribution
  .circleci/config.yml
  Makefile
  libnavigation-base/src/main/res/values-fa/strings.xml
  libnavigation-base/src/main/res/values-fr/strings.xml
  libnavigation-base/src/main/res/values-pt-rBR/strings.xml
  libnavigation-base/src/main/res/values-pt-rPT/strings.xml
  libnavigation-base/src/main/res/values-ru/strings.xml
  libnavigation-base/src/main/res/values-uk/strings.xml
  libnavigation-base/src/main/res/values-uz/strings.xml
  libnavigation-core/api/current.txt
  libnavigation-core/lint.xml
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/MapboxReplayer.kt
  libnavigation-util/src/main/res/values-he/strings.xml
  libnavigation-util/src/main/res/values/strings.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_arrive.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_arrive_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_arrive_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_arrive_straight.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_depart.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_depart_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_depart_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_depart_straight.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_fork.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_rotary.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_roundabout.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_turn_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_turn_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_turn_sharp_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_turn_sharp_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_turn_slight_left.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_turn_slight_right.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_turn_straight.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_uturn.xml
  libnavui-maps/src/main/res/values/strings.xml
  libtrip-notification/src/main/res/values/strings.xml
Labels: skip changelog, op-ex

#5323 Kyv alternatives cache limit to 3 portion
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesCacheManager.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesCacheManagerTest.kt
Labels: bug

#5325 Fixed build in main branch
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/navigationview/NavigationViewExternalObserversTests.kt
Labels: skip changelog

#5324 bump snapshot to 2.2.0-SNAPSHOT
  gradle.properties
Labels: skip changelog

#5318 MapboxTripProgress layout fix
  CHANGELOG.md
  libnavui-tripprogress/src/main/res/layout-land/mapbox_trip_progress_layout.xml
Labels: bug

#5329 Fix attachAllActivities foregrounding case
  CHANGELOG.md
  libnavigation-core/src/main/java/com/mapbox/navigation/core/lifecycle/CarAppLifecycleOwner.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/lifecycle/CarAppLifecycleOwnerTest.kt
Labels: bug

#5331 refactored ci config, `release-snapshot` job: - enable for `release-v*` branches; - remove overkilled documentation generation.
  .circleci/config.yml
Labels: needs backporting, skip changelog

#5322 RouteOptions extensions: refactor default params
  CHANGELOG.md
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/extensions/RouteOptionsEx.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/extensions/RouteOptionsExTest.kt
Labels: bug, Core

#5333 ktlint: upgrade to 0.43.2
  gradle/dependencies.gradle
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/TurnIconHelper.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/NotificationTurnIconHelper.kt
Labels: skip changelog

#5339 Add `CHANGELOG` for `2.0.5` release
  CHANGELOG.md
Labels: skip changelog, v2.x

#5340 Add `CHANGELOG` for `2.0.5` release
  CHANGELOG.md
Labels: skip changelog, v2.x

#5327 Updated naming of next waypoint index fallback to make its purpose clear
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionNoSetupTest.kt
Labels: skip changelog

#5336 Added cancellation of the coroutines when setRoutes is called.
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/SetRouteOrderTest.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
Labels: skip changelog

#5335 Remove unused `undocumented_classes.txt` and refactored `dokka-validate.sh`
  scripts/dokka-validate.sh
  scripts/undocumented_classes.txt
Labels: skip changelog

#5342 Use medium+ resource class for documentation publishing
  .circleci/config.yml
Labels: skip changelog

#5347 avoid crash in MapboxNavigationViewportDataSourceDebugger
  CHANGELOG.md
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/debugger/MapboxNavigationViewportDataSourceDebugger.kt
Labels: bug

#5332 separated NavigationView lifecycle from hosting context's lifecycle
  examples/src/main/AndroidManifest.xml
  examples/src/main/java/com/mapbox/navigation/examples/MainActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationViewActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationViewFragmentActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/NavigationViewFragment.kt
  examples/src/main/res/layout/fragment_navigation_view.xml
  examples/src/main/res/layout/layout_activity_navigation_view.xml
  examples/src/main/res/layout/layout_activity_navigation_view_fragment.xml
  examples/src/main/res/values/strings.xml
  gradle/dependencies.gradle
  instrumentation-tests/build.gradle
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/navigationview/NavigationViewExternalObserversTests.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/navigationview/lifecycle/ViewLifecycleRegistryTest.kt
  instrumentation-tests/src/main/java/com/mapbox/navigation/instrumentation_tests/activity/EmptyTestActivity.kt
  libnavui-dropin/build.gradle
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/LifeCycleOwnerNotFoundException.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/maneuver/ManeuverUIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterUIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routeoverview/RouteOverviewUIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/sound/SoundButtonUIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/speedlimit/SpeedLimitUIComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripprogress/TripProgressUIComponent.kt
  libnavui-util/build.gradle
  libnavui-util/src/main/java/com/mapbox/navigation/ui/utils/internal/extensions/ActivityContextEx.kt
  libnavui-util/src/main/java/com/mapbox/navigation/ui/utils/internal/lifecycle/ViewLifecycleRegistry.kt
  libnavui-util/src/test/java/com/mapbox/navigation/ui/utils/internal/lifecycle/ViewLifecycleRegistryTest.kt
Labels: UI, skip changelog

#5356 Bump NN dependency version to `83.0.0`
  gradle/dependencies.gradle
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/extensions/ShieldEx.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/factory/RoadFactory.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/road/model/Road.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/road/model/RoadComponent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/NavigatorMapper.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/infra/factories/NativeFactories.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/navigator/NavigatorMapperTest.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/roadname/RoadNameProcessor.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/roadname/RoadNameProcessorTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/roadname/api/MapboxRoadNameLabelApiTest.kt
  libnavui-shield/src/main/java/com/mapbox/navigation/ui/shield/api/MapboxRouteShieldApi.kt
  libnavui-shield/src/test/java/com/mapbox/navigation/ui/shield/api/MapboxRouteShieldApiTest.kt
Labels: release blocker, skip changelog

#5359 Add changelog for v2.2.0-rc.1
  CHANGELOG.md
Labels: skip changelog

#5360 Fix changelog
  CHANGELOG.md
Labels: skip changelog

#5363 Bump NN, Maps and common dependency versions to `86.0.2`, `10.3.0-beta.1` and `21.1.0-beta.1` respectively
  gradle/dependencies.gradle
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/infra/factories/NativeFactories.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/navigator/NavigatorMapperTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/NavigatorLoader.kt
Labels: release blocker, skip changelog

#5365 Changelog for v2.3.0-alpha.1
  CHANGELOG.md
Labels: skip changelog

#5370 fixed 2.3.0-alpha.1 changelog
  CHANGELOG.md
Labels: skip changelog

#5310 refactor road name label to use shields
  CHANGELOG.md
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/model/ManeuverInstructionGenerator.kt
  libnavui-maps/api/current.txt
  libnavui-maps/build.gradle
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/roadname/RoadNameAction.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/roadname/RoadNameProcessor.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/roadname/RoadNameResult.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/roadname/api/MapboxRoadNameLabelApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/roadname/model/RoadLabel.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/roadname/view/MapboxRoadNameLabelView.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/roadname/view/MapboxRoadNameView.kt
  libnavui-maps/src/main/res/values-night/colors.xml
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/roadname/RoadNameProcessorTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/roadname/api/MapboxRoadNameLabelApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/roadname/view/MapboxRoadNameViewTest.kt
  libnavui-shield/api/current.txt
  libnavui-shield/src/main/java/com/mapbox/navigation/ui/shield/api/RouteShieldEx.kt
  libnavui-shield/src/main/java/com/mapbox/navigation/ui/shield/model/RouteShield.kt
  libnavui-shield/src/main/java/com/mapbox/navigation/ui/shield/model/RouteShieldCallback.kt
  libnavui-shield/src/test/java/com/mapbox/navigation/ui/shield/api/RouteShieldExTest.kt
  libnavui-shield/src/test/java/com/mapbox/navigation/ui/shield/model/RouteShieldTest.kt
Labels: needs backporting

#5357 Add options to allow users to specify exit drawables based on MUTCD/VIENNA convention and specify fallbacks
  CHANGELOG.md
  libnavui-maneuver/api/current.txt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/model/ManeuverExitOptions.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/model/ManeuverPrimaryOptions.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/model/ManeuverSecondaryOptions.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/model/ManeuverSubOptions.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/model/ManeuverViewOptions.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/model/MapboxExitProperties.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/view/MapboxExitText.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/view/MapboxManeuverView.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/view/MapboxPrimaryManeuver.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/view/MapboxSecondaryManeuver.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/view/MapboxSubManeuver.kt
  libnavui-maneuver/src/main/res/drawable/mapbox_exit_board_background.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_exit_arrow_left_mutcd.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_exit_arrow_left_vienna.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_exit_arrow_right_mutcd.xml
  libnavui-maneuver/src/main/res/drawable/mapbox_ic_exit_arrow_right_vienna.xml
  libnavui-maneuver/src/main/res/values/colors.xml
  libnavui-maneuver/src/main/res/values/styles.xml
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/model/ManeuverExitOptionsTest.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/model/ManeuverOptionsTest.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/model/ManeuverPrimaryOptionsTest.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/model/ManeuverSecondaryOptionsTest.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/model/ManeuverSubOptionsTest.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/model/ManeuverViewOptionsTest.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/view/MapboxExitTextTest.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/view/MapboxPrimaryManeuverTest.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/view/MapboxSecondaryManeuverTest.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/view/MapboxSubManeuverTest.kt
Labels: release blocker, needs backporting

#5386 remove jcenter
  build.gradle
  gradle/dependency-updates.gradle
  gradle/script-git-version.gradle
  gradle/track-public-apis.gradle
Labels: skip changelog

#5388 Bump `mapbox-java` dependency version to `6.2.0`
  gradle/dependencies.gradle
Labels: needs backporting, skip changelog

#5396 bring back `Road`'s legacy fields values
  CHANGELOG.md
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/factory/RoadFactory.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/road/model/Road.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/internal/factory/RoadFactoryTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/NavigatorMapper.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/navigator/NavigatorMapperTest.kt
Labels: release blocker, needs backporting

#5397 bring back `Road`'s legacy fields values (cherry-pick)
  CHANGELOG.md
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/factory/RoadFactory.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/road/model/Road.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/internal/factory/RoadFactoryTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/NavigatorMapper.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/navigator/NavigatorMapperTest.kt
Labels: skip changelog

#5402 Replace docs `CODEOWNERS` from `colleenmcginnis` to `domlet`
  .github/CODEOWNERS
Labels: skip changelog

#5405 upgraded Nav Native to v83.0.1
  gradle/dependencies.gradle
Labels: skip changelog

#5406 changelog for v2.2.1
  CHANGELOG.md
Labels: skip changelog

#5407 changelog for v2.2.1
  CHANGELOG.md
Labels: skip changelog

#5408 added a note about failing alternatives in 2.3.0-alpha.1
  CHANGELOG.md
Labels: skip changelog

#5415 Update replay example to use NavigationCamera
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
Labels: skip changelog

#5394 Add avoidManeuverSeconds to RouteAlternativesOptions
  CHANGELOG.md
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/RouteAlternativesOptions.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/route/RouteAlternativesOptionsTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesController.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesControllerTest.kt
Labels: feature

#5416 RouteAlternativesController refactoring
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesController.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesControllerTest.kt
Labels: skip changelog

#5409 Added icon offset and icon anchor options for the symbol layer
  CHANGELOG.md
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/MapboxRouteLayerProvider.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/MapboxRouteLineOptions.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/model/MapboxRouteLineOptionsTest.kt
Labels: release blocker

#5403 StatusView component for exposing SDK status messages
  CHANGELOG.md
  Makefile
  gradle/publish.gradle
  libnavigation-android/build.gradle
  libnavui-status/.gitignore
  libnavui-status/api/current.txt
  libnavui-status/build.gradle
  libnavui-status/gradle.properties
  libnavui-status/proguard-rules.pro
  libnavui-status/src/main/AndroidManifest.xml
  libnavui-status/src/main/java/com/mapbox/navigation/ui/status/internal/extensions/Animator.kt
  libnavui-status/src/main/java/com/mapbox/navigation/ui/status/model/Status.kt
  libnavui-status/src/main/java/com/mapbox/navigation/ui/status/view/MapboxStatusView.kt
  libnavui-status/src/main/res/drawable/mapbox_bg_rounded.xml
  libnavui-status/src/main/res/layout/mapbox_status_view_layout.xml
  libnavui-status/src/main/res/values/attrs.xml
  libnavui-status/src/main/res/values/colors.xml
  libnavui-status/src/main/res/values/dimens.xml
  libnavui-status/src/main/res/values/styles.xml
  libnavui-status/src/test/java/com/mapbox/navigation/ui/status/view/MapboxStatusViewTest.kt
  qa-test-app/build.gradle
  qa-test-app/src/main/AndroidManifest.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivitySuite.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/StatusActivity.kt
  qa-test-app/src/main/res/animator/scale_in.xml
  qa-test-app/src/main/res/animator/scale_out.xml
  qa-test-app/src/main/res/layout/layout_activity_status.xml
  qa-test-app/src/main/res/values/strings.xml
  qa-test-app/src/main/res/values/styles.xml
  settings.gradle
Labels: feature, UI

#5423 changelog for v2.3.0-beta.1
  CHANGELOG.md
Labels: skip changelog

#5431 Fix `ReplayHistoryActivity` `navigationCamera` `UninitializedPropertyAccessException`
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
Labels: bug, skip changelog
