Repository mapbox/mapbox-navigation-android, pull requests merged in 2022-11, with the labels that each got.

#6528 NAVAND-838 Changed map syntax used for updating gradient and trim offset
  CHANGELOG.md
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineView.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineViewTest.kt
Labels: needs backporting

#6524 stabilize EV route refresh test
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/EVRouteRefreshTest.kt
Labels: skip changelog

#6531 [Drop-In UI] fix road label position not updating in some cases
  CHANGELOG.md
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/infopanel/InfoPanelCoordinator.kt
Labels: bug, UI, needs backporting

#6467 NAVAND-552: calculate the number of instructions to download
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/NextVoiceInstructionsProvider.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/TimeBasedNextVoiceInstructionsProvider.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/TimeBasedNextVoiceInstructionsProviderTest.kt
  libnavui-voice/src/test/resources/multileg_route.json
Labels: skip changelog

#6538 [Drop-In UI] fix road label position not updating in some cases
  CHANGELOG.md
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/infopanel/InfoPanelCoordinator.kt
Labels: bug, UI

#6548 Expose LocationMatcherResult::inTunnel
  CHANGELOG.md
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/NavigatorMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/LocationMatcherResult.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/navigator/NavigatorMapperTest.kt
Labels: improvement

#6544 Fixed issue with custom route scaling not being reapplied to layers w…
  CHANGELOG.md
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineView.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineViewTest.kt
  qa-test-app/src/main/AndroidManifest.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivitySuite.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/RouteLineScalingActivity.kt
  qa-test-app/src/main/res/layout/route_line_scaling_activity_view.xml
  qa-test-app/src/main/res/values/strings.xml
Labels: needs backporting

#6543 NAVAND-842: use route's options as fallback EV data
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/RouteRefreshRequestData.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/RouteProgressDataProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/SetRoutesInfo.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RefreshedRouteInfo.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshControllerProvider.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationBaseTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/RouteProgressDataProviderTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/SetRoutesInfoTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routerefresh/RouteRefreshControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routerefresh/RouteRefreshStub.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libtesting-thirdparty/src/main/java/com/mapbox/navigation/testing/factories/DirectionsResponseFactories.kt
Labels: skip changelog

#6530 [Android Auto] Add MapboxCarMapLoader
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/map/MapboxCarMapLoader.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/map/MapboxCarMapLoaderTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/car/MainCarMapLoader.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/car/MainCarSession.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/testing/JavaInterfaceChecker.java
Labels: Android Auto

#6546 do not inherit internal class in public RoadLabelSurfaceLayer
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/src/androidTest/java/com/mapbox/androidauto/car/navigation/roadlabel/RoadLabelRendererTest.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/freedrive/FreeDriveCarScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/ActiveGuidanceScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/roadlabel/RoadLabelRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/roadlabel/RoadLabelSurfaceLayer.kt
Labels: skip changelog, Android Auto

#6541 convert android auto road label to a bitmap widget
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/surfacelayer/CarSurfaceLayer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/surfacelayer/EmptyLayerHost.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/surfacelayer/GLUtils.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/surfacelayer/textview/CarCamera2d.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/surfacelayer/textview/CarScene2d.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/surfacelayer/textview/CarTextLayerHost.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/surfacelayer/textview/CarTextModel2d.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/map/MapboxCarMapLoader.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/roadlabel/RoadLabelSurfaceLayer.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/map/MapboxCarMapLoaderTest.kt
Labels: Android Auto

#6562 update Nav Native to v119.0.1
  CHANGELOG.md
  gradle/dependencies.gradle
Labels: needs backporting

#6568 [Android Auto] Bump nav-sdk version
  gradle/dependencies.gradle
  libnavui-androidauto/build.gradle
Labels: skip changelog, Android Auto

#6576 clarify onEVDataUpdated docs
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
Labels: skip changelog

#6578 Bump mapbox-java v6.10.0-beta.1
  gradle/dependencies.gradle
Labels: skip changelog

#6583 Refactor the usage of default puck
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/puck/LocationPuckOptions.kt
Labels: skip changelog

#6587 Fix changelog
  CHANGELOG.md
Labels: skip changelog

#6586 Bump NN, Common, Maps
  CHANGELOG.md
  gradle/dependencies.gradle
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/RouterWrapper.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/RouterWrapperTests.kt
  libnavigator/src/androidTest/java/com/mapbox/navigation/navigator/internal/NavigatorTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/router/RouterInterfaceAdapter.kt
  libnavigator/src/test/java/com/mapbox/navigation/navigator/internal/router/RouterInterfaceAdapterTest.kt
Labels: skip changelog

#6572 Add Copilot feature
  CHANGELOG.md
  Makefile
  gradle/dependencies.gradle
  gradle/publish.gradle
  libnavigation-android/build.gradle
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/extensions/NavigationOptionsEx.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/CopilotOptions.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/internal/CopilotOptionsTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/NavigationOptionsTest.kt
  libnavigation-copilot/.gitignore
  libnavigation-copilot/api/current.txt
  libnavigation-copilot/build.gradle
  libnavigation-copilot/gradle.properties
  libnavigation-copilot/proguard-rules.pro
  libnavigation-copilot/src/main/AndroidManifest.xml
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/AttachmentMetadata.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/DriveEnds.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/DriveEndsType.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/GoingToBackground.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/GoingToForeground.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistoryAttachmentsUtils.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistoryEventDTO.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistoryEvents.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistoryPoint.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistoryRoutablePoint.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistorySearchResult.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistoryUploadWorker.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/InitRoute.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilot.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/NavFeedbackSubmitted.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/SearchResultUsed.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/SearchResults.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/UploadServiceInterfaceFactory.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/internal/CopilotMetadata.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/internal/MapboxCopilotExtensions.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/internal/PushStatus.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/internal/PushStatusObserver.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/HistoryAttachmentsUtilsTest.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/HistoryUploadWorkerTest.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/MapboxCopilotImplTest.kt
  libnavigation-copilot/src/test/resources/robolectric.properties
  settings.gradle
Labels: feature, release blocker, Core, needs backporting

#6590 Bump mapbox-java 6.10.0-beta.2
  gradle/dependencies.gradle
Labels: skip changelog

#6589 Backport #6572 to `release-v2.9`
  CHANGELOG.md
  Makefile
  gradle/dependencies.gradle
  gradle/publish.gradle
  libnavigation-android/build.gradle
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/extensions/NavigationOptionsEx.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/CopilotOptions.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/internal/CopilotOptionsTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/NavigationOptionsTest.kt
  libnavigation-copilot/.gitignore
  libnavigation-copilot/api/current.txt
  libnavigation-copilot/build.gradle
  libnavigation-copilot/gradle.properties
  libnavigation-copilot/proguard-rules.pro
  libnavigation-copilot/src/main/AndroidManifest.xml
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/AttachmentMetadata.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/DriveEnds.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/DriveEndsType.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/GoingToBackground.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/GoingToForeground.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistoryAttachmentsUtils.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistoryEventDTO.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistoryEvents.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistoryPoint.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistoryRoutablePoint.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistorySearchResult.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistoryUploadWorker.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/InitRoute.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilot.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/NavFeedbackSubmitted.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/SearchResultUsed.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/SearchResults.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/UploadServiceInterfaceFactory.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/internal/CopilotMetadata.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/internal/MapboxCopilotExtensions.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/internal/PushStatus.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/internal/PushStatusObserver.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/HistoryAttachmentsUtilsTest.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/HistoryUploadWorkerTest.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/MapboxCopilotImplTest.kt
  libnavigation-copilot/src/test/resources/robolectric.properties
  settings.gradle
Labels: feature, Core

#6591 Improve Copilot docs
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilot.kt
Labels: Core, skip changelog, improvement

#6596 Backport #6591 to `release-v2.9`
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilot.kt
Labels: Core, skip changelog, improvement

#6595 Bump NN dependency version to `119.0.2`
  gradle/dependencies.gradle
Labels: Core, skip changelog

#6601 Fix `CHANGELOG` formatting issue
  CHANGELOG.md
Labels: skip changelog

#6602 Fix `2.9.0` `CHANGELOG` formatting issue
  CHANGELOG.md
Labels: skip changelog

#6609 Use `MapboxNavigationApp.lifecycleOwner` instead of `ProcessLifecycleOwner` to support AA
  gradle/dependencies.gradle
  libnavigation-copilot/build.gradle
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/MapboxCopilotImplTest.kt
Labels: Core, needs backporting, skip changelog, improvement

#6571 [Android Auto] Add getStyleExtension to MapboxCarMapLoader
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/map/MapboxCarMapLoader.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/map/MapboxCarMapLoaderTest.kt
Labels: Android Auto

#6605 [Android Auto] App for testing stable versions
  LICENSE.md
  android-auto-app/.gitignore
  android-auto-app/README.md
  android-auto-app/build.gradle
  android-auto-app/proguard-rules.pro
  android-auto-app/src/main/AndroidManifest.xml
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/CarAppSyncComponent.kt
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/ExampleApplication.kt
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/ReplayRouteTripSession.kt
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/app/MainActivity.kt
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/car/MainCarAppService.kt
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/car/MainCarSession.kt
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/testing/CarJavaInterfaceChecker.java
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/testing/JavaFlow.kt
  android-auto-app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android-auto-app/src/main/res/drawable/ic_launcher_background.xml
  android-auto-app/src/main/res/layout/activity_main.xml
  android-auto-app/src/main/res/layout/mapbox_activity_navigation_view.xml
  android-auto-app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android-auto-app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android-auto-app/src/main/res/mipmap-hdpi/ic_launcher.png
  android-auto-app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android-auto-app/src/main/res/mipmap-mdpi/ic_launcher.png
  android-auto-app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android-auto-app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android-auto-app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android-auto-app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android-auto-app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android-auto-app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android-auto-app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android-auto-app/src/main/res/values-night/themes.xml
  android-auto-app/src/main/res/values/colors.xml
  android-auto-app/src/main/res/values/strings.xml
  android-auto-app/src/main/res/values/themes.xml
  gradle/dependencies.gradle
  libnavui-androidauto/build.gradle
  qa-test-app/build.gradle
  qa-test-app/src/main/AndroidManifest.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/car/MainCarSession.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/testing/JavaInterfaceChecker.java
  settings.gradle
Labels: skip changelog, Android Auto

#6588 [Android Auto] Bump maps version and remove `@MapboxExperimental`
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/car/MainCarSession.kt
  gradle/dependencies.gradle
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/src/androidTest/java/com/mapbox/androidauto/car/navigation/roadlabel/RoadLabelBitmapRendererTest.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/MapboxCarContext.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/deeplink/GeoDeeplinkNavigateAction.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/freedrive/FreeDriveCarScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/extensions/MapboxCarMapSurfaceExtensions.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/search/CarSearchLocationProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/location/CarLocationRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/map/MapboxCarMapLoader.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/map/compass/CarCompassRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/map/logo/CarLogoRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/ActiveGuidanceScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/CarActiveGuidanceMarkers.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/CarLocationsOverviewCamera.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/CarNavigationCamera.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/CarNavigationInfoProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/MapUserStyleObserver.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/roadlabel/CarRoadLabelBitmapRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/roadlabel/CarRoadLabelOptions.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/roadlabel/CarRoadLabelRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/roadlabel/CarRoadNameObserver.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/speedlimit/CarSpeedLimitServices.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/speedlimit/SpeedLimitWidget.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/permissions/NeedsLocationPermissionsScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/placeslistonmap/PlacesListOnMapManager.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/placeslistonmap/PlacesListOnMapScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/preview/CarRouteLineRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/preview/CarRoutePreviewScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/preview/PreviewCarRoutesProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/routes/CarRoutesProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/search/PlaceRecordMapper.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/search/PlaceSearchScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/settings/CarSettingsScreen.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/MapboxCarContextTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/map/MapboxCarMapLoaderTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/CarLocationsOverviewCameraTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/CarNavigationInfoProviderTest.kt
Labels: Android Auto

#6611 Backport #6609 to `release-v2.9`
  gradle/dependencies.gradle
  libnavigation-copilot/build.gradle
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/MapboxCopilotImplTest.kt
Labels: Core, skip changelog

#6612 [Android Auto] Fix example issues
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/CarAppSyncComponent.kt
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/car/MainCarSession.kt
Labels: skip changelog, Android Auto

#6608 [Drop-In UI] Avoid playback of duplicate voice instructions when un-muting
  CHANGELOG.md
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxAudioGuidance.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/MapboxAudioGuidanceTest.kt
Labels: UI

#6630 ci config: shift android-lint check to the latest step
  .circleci/config.yml
Labels: skip changelog

#6620 NAVAND-856 NN: adopt set route reason
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/SetRoutes.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/SetRoutesInfo.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/DirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/utils/SetRoutesEx.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationBaseTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationSetNavigationRoutesCallbackTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationSetNavigationRoutesHistoryRecordingTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/SetRoutesInfoTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSessionTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionNoSetupTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/RouterWrapper.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/router/RouterInterfaceAdapter.kt
Labels: skip changelog

#6619 NAVAND-583: mock fused location when has GPL dependency
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/EVRouteRefreshTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/HistoryRecordingStateChangeObserverTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/location/MockLocationReplayer.kt
  libtesting-ui/build.gradle
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/BaseTest.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/FusedLocationMocker.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/LocationMocker.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/MockLocationUpdatesRule.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/SystemLocationMocker.kt
Labels: skip changelog

#6647 stabilize reroute_is_cancelled_when_the_user_returns_to_route
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CoreRerouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/DelayedResponseModifier.kt
Labels: skip changelog

#6649 remove unnecessary turf distance check from MapboxRouteLineApi#updateTraveledRouteLine
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
Labels: skip changelog

#6653 Bump AA maps to 0.5.0
  LICENSE.md
  gradle/dependencies.gradle
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/surfacelayer/EmptyLayerHost.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/map/MapboxCarMapLoader.kt
Labels: skip changelog, Android Auto

#6654 Bump AA nav sdk
  LICENSE.md
  libnavui-androidauto/build.gradle
Labels: skip changelog, Android Auto

#6651 [Drop-In UI] Building Hightligth on Arrival
  CHANGELOG.md
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/extensions/NavigationRouteEx.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/extensions/MapboxNavigationExtensions.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/extensions/MapboxNavigationExtensionsTest.kt
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewOptionsCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/extensions/NavigationViewContextEx.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/map/MapViewBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/navigationview/MapboxNavigationViewApi.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/navigationview/NavigationViewOptions.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/map/MapViewBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/navigationview/NavigationViewOptionsTest.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/ComponentInstaller.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/building/model/BuildingError.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/extensions/MapboxBuildingsApiExtensions.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/BuildingHighlightComponent.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/extensions/MapboxBuildingsApiExtensionsKtTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/BuildingHighlightComponentTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/componentinstaller/ComponentsActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/componentinstaller/ComponentsAltActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomizedViewModel.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
  qa-test-app/src/main/res/layout/layout_drawer_menu_nav_view_custom.xml
Labels: UI

#6655 [copilot] `startRecording` as soon as `onShouldStartRecording` is called
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/MapboxCopilotImplTest.kt
Labels: Core, skip changelog, bug :beetle:

#6657 Backport #6655 to `release-v2.9`
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/MapboxCopilotImplTest.kt
Labels: Core, skip changelog

#6656 Bump NN dependency version to `119.0.4`
  gradle/dependencies.gradle
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt
Labels: Core, skip changelog

#6660 [copilot] Make sure `created` from Attachments API is the same as `startedAt`
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistoryUploadWorker.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/CopilotTestUtils.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/HistoryAttachmentsUtilsTest.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/HistoryUploadWorkerTest.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/MapboxCopilotImplTest.kt
Labels: Core, needs backporting, skip changelog, bug :beetle:

#6661 [Android Auto] Fix trip session state race condition
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/CarAppSyncComponent.kt
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/app/MainActivity.kt
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/MapboxCarNavigationManager.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/MapboxCarNavigationManagerTest.kt
Labels: Android Auto

#6569 [Android Auto] Working on android auto docs
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/screenmanager/MapboxScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/screenmanager/MapboxScreenGraph.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/screenmanager/MapboxScreenManager.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/screenmanager/factories/GeoDeeplinkPlacesCarScreenFactory.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/screenmanager/factories/GeoDeeplinkPlacesFeedbackScreenFactory.kt
Labels: skip changelog
