Repository mapbox/mapbox-navigation-android, pull requests merged in 2022-04, with the labels that each got.

#5644 [DropInUI] Start camera in overview mode in free drive upon theme changes
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraState.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraViewModel.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/camera/CameraComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/camera/CameraViewModelTest.kt
Labels: skip changelog

#5643 [DropInUi] Fix location permission crash and launch race condition
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/location/LocationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripsession/LocationPermissionComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/location/LocationViewModelTest.kt
Labels: bug, UI, skip changelog

#5640 [DROP-IN] Keep the device awake when using DropInNavigationView.
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/DropInNavigationView.kt
Labels: UI, skip changelog

#5642 Updated test to use non-deprecated route line calls.
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/SetRouteOrderTest.kt
Labels: skip changelog

#5648 Add `v2.5.0-alpha.1` `CHANGELOG` entry
  CHANGELOG.md
Labels: skip changelog

#5651 Codecov is back
  .circleci/config.yml
  codecov.yml
Labels: skip changelog

#5656 [DROP-IN] Fix: Maneuver arrow remains on map after navigation terminated
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/routearrow/RouteArrowComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routearrow/RouteArrowComponentTest.kt
Labels: UI, skip changelog

#5645 RerouteController: switch to alternative if exist
  CHANGELOG.md
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/factory/RouteProgressFactory.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/route/NavigationRouteEx.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/utils/RouteProgressEx.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/RouteProgress.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/route/RouteExclusionsJavaTest.java
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/NavigatorMapper.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/reroute/MapboxRerouteController.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/navigator/NavigatorMapperTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/reroute/MapboxRerouteControllerTest.kt
Labels: Core

#5628 Removed redundant calls of gradle in make file
  Makefile
Labels: skip changelog

#5654 Codecov: added check sum of uploader
  .circleci/config.yml
  scripts/coverage.sh
Labels: skip changelog

#5657 [DROP-IN] Fixed location puck placement for customized activity
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxNavigationViewCustomizedActivity.kt
Labels: UI, skip changelog

#5660 [DROP-IN] RoadNameView visibility fix
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/roadlabel/RoadNameViewBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/location/LocationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/roadlabel/RoadNameLabelComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/RoadNameLabelCoordinator.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/camera/CameraComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/location/LocationViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/roadlabel/RoadNameLabelComponentTest.kt
Labels: UI, skip changelog

#5652 Add tts focus
  libnavui-voice/api/current.txt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/AsyncAudioFocusDelegate.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/AudioFocusDelegateProvider.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/AudioFocusRequestCallback.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceInstructionsPlayer.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/OreoAndLaterAudioFocusDelegate.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/PreOreoAudioFocusDelegate.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsPlayerAttributes.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/model/AudioFocusOwner.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/options/VoiceInstructionsPlayerOptions.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/AudioFocusDelegateProviderTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceInstructionsPlayerTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/OreoAndLaterAudioFocusDelegateTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/PreOreoAudioFocusDelegateTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsPlayerAttributesTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/options/VoiceInstructionsPlayerOptionsTest.kt
Labels: skip changelog

#5667 [DROP-IN] Fixed camera padding calculation when in FreeDrive mode
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraLayoutObserver.kt
Labels: UI, skip changelog

#5670 Add missing `CHANGELOG` entries from #5652 PR
  CHANGELOG.md
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/model/AudioFocusOwner.kt
Labels: needs backporting, skip changelog

#5544 Added feature to reset the route line related cache.
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/util/CacheResultUtils.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsRoboTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/util/CacheResultUtilsTest.kt
Labels: skip changelog

#5675 add changelog for v2.4.0-rc.2
  CHANGELOG.md
Labels: skip changelog

#5666 Fixed MapboxSpeedLimitView sizing when rendering Errors.
  CHANGELOG.md
  libnavui-speedlimit/src/main/java/com/mapbox/navigation/ui/speedlimit/view/MapboxSpeedLimitView.kt
Labels: UI

#5661 [DropInUi] Make `UIViewModel` invoke happen synchronously
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/lifecycle/UICoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/lifecycle/UIViewModel.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/audioguidance/AudioGuidanceViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/camera/CameraComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/camera/CameraViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/infopanel/InfoPanelHeaderComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/location/LocationViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/navigation/NavigationStateViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/routefetch/RoutesViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/tripsession/TripSessionStarterViewModelTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/lifecycle/UIViewModelTest.kt
Labels: bug, UI, skip changelog

#5679 Changelog for `v2.5.0-alpha.2`
  CHANGELOG.md
Labels: skip changelog

#5678 [DROP-IN] Fixed: Camera viewport padding gets messed up when toggling the theme
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/InfoPanelCoordinator.kt
Labels: UI, skip changelog

#5685 Do not clear the route when trip session is stopped
  CHANGELOG.md
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
Labels: bug

#5669 Add a notification interceptor
  CHANGELOG.md
  LICENSE.md
  libnavigation-base/api/current.txt
  libnavigation-base/build.gradle
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/trip/notification/TripNotificationInterceptorOwner.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/notification/TripNotificationInterceptor.kt
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/utils/ModulesUtils.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/NavigationNotificationProvider.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotification.kt
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/NotificationBuilderProvider.kt
  libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotificationTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/AppLifecycleActivity.kt
Labels: Android Auto

#5699 Add missing notification test argument
  libnavigation-core/src/androidTest/java/com/mapbox/navigation/core/tests/activity/TripServiceActivity.kt
Labels: skip changelog, op-ex

#5695 [DROP-IN] Fixed alternative route selection.
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/infopanel/InfoPanelHeaderComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/infopanel/InfoPanelHeaderComponentTest.kt
Labels: UI, skip changelog

#5691 fix an issue where route refresh would clear the alternatives metadata
  CHANGELOG.md
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/AlternativeRouteInfo.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NativeSetRouteResult.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
Labels: bug

#5702 Remove incorrect MapboxTripNotification comment
  libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/internal/MapboxTripNotification.kt
Labels: skip changelog

#5696 [DROP-IN] Updated TripProgressView alignment
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_header_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_trip_progress_layout.xml
Labels: UI, skip changelog

#5707 Bump MapsSDK v10.4.2, mapbox-java v6.4.0, common v21.2.1
  gradle/dependencies.gradle
Labels: skip changelog

#5712 [DROP-IN] Added FinalDestinationArrival detection
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/navigation/NavigationStateViewModel.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/navigation/NavigationStateViewModelTest.kt
Labels: UI, skip changelog

#5630 change deprecated "flame" device to "oriole" (Pixel 6, 31) on Firebase
  .circleci/config.yml
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CoreRerouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxHistoryTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteRefreshTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SanityCoreRouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/SimpleMapViewNavigationTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/camera/NavigationCameraTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/AlternativeRouteSelectionTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/history/MapboxHistoryTestRule.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/idling/RouteAlternativesIdlingResource.kt
  libnavigation-core/src/androidTest/java/com/mapbox/navigation/core/trip/service/TripServiceTest.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/NotificationTest.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/utils/ViewTestUtils.kt
Labels: skip changelog

#5720 updated Nav Native to v96.0.0, Maps SDK to v10.5.0-beta.1, and Common SDK to v21.3.0-rc.2
  LICENSE.md
  gradle/dependencies.gradle
Labels: skip changelog

#5717 Exclude certain maneuver types from the 'pitch to 0 near maneuvers' feature
  CHANGELOG.md
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/MapboxCameraAnimationsActivity.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSource.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSourceOptions.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/ViewportDataSourceProcessor.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSourceTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/camera/data/ViewportDataSourceProcessorTest.kt
Labels: feature, UI

#5734 - changelog 2.5.0-beta.1; - mapbox-java bump v6.5.0-beta.2.
  CHANGELOG.md
  gradle/dependencies.gradle
Labels: skip changelog

#5739 added a known issue about exceptions when replacing Logger in 2.5.0-alpha.3 and 2.5.0-beta.1
  CHANGELOG.md
Labels: skip changelog

#5742 bump mapbox-base-android to v0.7.0
  gradle/dependencies.gradle
Labels: Core, skip changelog

#5754 gradle.properties: update version name to `2.5.0-SNAPSHOT`
  gradle.properties
Labels: skip changelog, op-ex

#5752 Fixed unit tests
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/utils/DirectionsResponseUtils.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/infra/factories/DirectionsResponseFactories.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/RouterWrapperTests.kt
Labels: skip changelog

#5755 Fixed an issue where route refresh was not updating the ETA in RouteProgress
  CHANGELOG.md
  gradle/dependencies.gradle
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteRefreshTest.kt
  instrumentation-tests/src/main/res/raw/route_response_route_refresh_annotations.json
  libnavigator/build.gradle
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: bug, release blocker, Core, needs backporting

#5757 Add `v2.5.0-beta.2` `CHANGELOG` release notes
  CHANGELOG.md
Labels: skip changelog

#5761 Fix update `LICENSE` conflict
  LICENSE.md
Labels: skip changelog

#5762 Add `v2.4.1` `CHANGELOG` release notes
  CHANGELOG.md
Labels: skip changelog

#5763 CP #5762
  CHANGELOG.md
Labels: skip changelog
