Repository mapbox/mapbox-navigation-android, pull requests merged in 2022-08, with the labels that each got.

#5719 Got rid of banner instruction workaround
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/BannerAndVoiceInstructionsTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/coroutines/Adapters.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/coroutines/TestUtils.kt
  instrumentation-tests/src/main/res/raw/route_response_dc_very_short.json
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionNoSetupTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigator.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
  libtesting-thirdparty/src/main/java/com/mapbox/navigation/testing/factories/NativeFactories.kt
Labels: skip changelog

#5875 Following camera Focal Point offset
  CHANGELOG.md
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/AnimationAdapter.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/AnimationType.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/camera/MapboxCameraAnimationsActivity.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSource.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSourceOptions.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/ViewportDataSourceProcessor.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSourceTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/camera/data/ViewportDataSourceProcessorTest.kt
Labels: feature

#6121 do not crash process on unexpected requests
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/http/MockWebServerRule.kt
Labels: skip changelog

#6069 [Drop-In UI] Suspending actions support
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/Store.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/ThunkActions.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RoutePreviewStateController.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/StateResetController.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/extension/StoreSaga.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/extension/StoreThunk.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/routefetch/RoutePreviewAction.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/internal/StoreTest.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/internal/controller/RoutePreviewStateControllerTest.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/internal/extension/StoreSagaKtTest.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/internal/extension/StoreThunkKtTest.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/testing/TestMiddleware.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/testing/TestReducer.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/testing/TestStore.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewListenerRegistry.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/infopanel/InfoPanelHeaderComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/extensions/ViewEx.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/NavigationViewListenerRegistryTest.kt
Labels: UI, skip changelog

#6132 [Drop-In UI] Add support for programmatically changing Info Panel state
  CHANGELOG.md
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewContext.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewOptions.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewOptionsCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/InfoPanelCoordinator.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/NavigationViewOptionsTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/coordinator/InfoPanelCoordinatorTest.kt
  libnavui-util/src/main/java/com/mapbox/navigation/ui/utils/internal/Provider.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomizedViewModel.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
  qa-test-app/src/main/res/layout/layout_drawer_menu_nav_view_custom.xml
  qa-test-app/src/main/res/values/strings.xml
Labels: UI

#6136 code cleanup
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
Labels: skip changelog

#6130 [Android Auto] Enable metalava
  .circleci/config.yml
  Makefile
  docs/metalava.md
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/build.gradle
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/MapboxCarNavigationManager.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainCarScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainScreenManager.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/location/CarLocationRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/ActiveGuidanceScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarLocationsOverviewCamera.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarNavigationCamera.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarNavigationInfoObserver.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/lanes/CarLaneIconRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/maneuver/CarManeuverIconRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/roadlabel/RoadLabelSurfaceLayer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/speedlimit/CarSpeedLimitRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/speedlimit/SpeedLimitWidget.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/placeslistonmap/PlaceMarkerRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/placeslistonmap/PlacesListOnMapScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRouteLine.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRoutePreviewScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRouteRequest.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/CarSearchEngine.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/SearchScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/deeplink/GeoDeeplinkNavigateAction.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/AndroidAutoLog.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/car/RendererUtils.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/car/extensions/MapboxCarMapSurfaceExtensions.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/location/impl/CarAppLocationImpl.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/surfacelayer/textview/CarScene2d.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/surfacelayer/textview/CarTextLayerHost.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/testing/CarAppTestRule.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/car/MainCarMapLoader.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/car/MainCarSession.kt
Labels: skip changelog

#6139 [Android Auto] Bump map extension to fix screen issue
  LICENSE.md
  gradle/dependencies.gradle
  libnavui-androidauto/CHANGELOG.md
Labels: Android Auto

#6142 [DropInUi] Remove replayer speed up
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripsession/ReplayRouteTripSession.kt
Labels: skip changelog

#6140 [Drop-In UI] Fixed: Drop-In UI goes back to Free drive state when the device is rotated in active guidance with replay enabled.
  CHANGELOG.md
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/SharedApp.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/StateResetController.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/internal/controller/StateResetControllerTest.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/tripsession/TripSessionComponent.kt
Labels: UI

#6144 allow users to inject custom options for the feedback screen
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainActionStrip.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainCarContext.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainScreenManager.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/core/CarFeedbackItemProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/core/CarFeedbackPollProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/core/CarFeedbackSearchOptions.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/core/CarFeedbackSearchOptionsProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/core/CarFeedbackSender.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/ui/CarFeedbackAction.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/ui/CarFeedbackIcon.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/ui/CarFeedbackItem.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/ui/CarFeedbackOption.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/ui/CarFeedbackPoll.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/ui/CarGridFeedbackScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRoutePreviewScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/RoutePreviewCarContext.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/FavoritesApi.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/SearchCarContext.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/SearchScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/deeplink/GeoDeeplinkNavigateAction.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/deeplink/GeoDeeplinkPlacesListOnMapProvider.kt
  libnavui-androidauto/src/main/res/drawable/mapbox_car_ic_feedback.xml
  libnavui-androidauto/src/main/res/values/strings.xml
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/search/FavoritesApiTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/deeplink/GeoDeeplinkPlacesListOnMapProviderTest.kt
Labels: Android Auto

#6146 Do not apply snapping include closure for profiles other than driving traffic
  CHANGELOG.md
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routeoptions/RouteOptionsUpdater.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/RouteOptionsUpdaterTest.kt
Labels: needs backporting

#6150 Backport 6148
  CHANGELOG.md
Labels: skip changelog

#6153 add an option to override route options used by android auto
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainCarContext.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRouteLine.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRouteOptionsInterceptor.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRouteRequest.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/SearchCarContext.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/preview/CarRouteRequestTest.kt
Labels: Android Auto

#6155 add changelog for androidauto-v0.7.0
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/build.gradle
Labels: Android Auto

#6156 updated mapbox-java to v6.7.0
  gradle/dependencies.gradle
Labels: skip changelog

#6160 fixed v2.7.0-beta.3 changelog
  CHANGELOG.md
Labels: skip changelog

#6166 Bump NN dependency version to `111.0.1`
  gradle/dependencies.gradle
Labels: Core, skip changelog

#6170 Revert "bump mapbox navigator dependency version to 111.0.1 (#6166)"
  gradle/dependencies.gradle
Labels: Core, skip changelog

#6145 [Drop-In UI] Added support for drawing info panel behind the navigation bar.
  CHANGELOG.md
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewContext.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/InfoPanelBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/InfoPanelCoordinator.kt
  libnavui-dropin/src/main/res/layout/mapbox_navigation_view_layout.xml
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/binder/infopanel/MapboxInfoPanelBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/coordinator/InfoPanelCoordinatorTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomInfoPanelBinder.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomizedViewModel.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
  qa-test-app/src/main/res/layout/layout_drawer_menu_nav_view_custom.xml
Labels: UI

#6173 keep snapshot name matching latest pre-release name
  gradle/artifact-settings.gradle
Labels: skip changelog, op-ex

#6169 optimize vanishing line updates when going through restrictions and legs aren't styled independently
  CHANGELOG.md
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/MapboxRouteLineOptions.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiRoboTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/AlternativeRouteActivity.kt
Labels: UI

#6163 more logs for route refresh
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: skip changelog

#6177 more logs for route refresh
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: skip changelog

#6168 Bump NN, Maps and Common dependency versions to `112.0.0`, `10.8.0-beta.1` and `23.0.0-beta.1` respectively
  CHANGELOG.md
  LICENSE.md
  gradle/dependencies.gradle
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteRefreshTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/roadobject/RoadObjectMapperTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/navigator/NavigatorMapperTest.kt
Labels: Core

#6171 optimized cache management when switching between routes
  CHANGELOG.md
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsRoboTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
Labels: UI

#6165 [Android Auto] Simplify search implementation
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainActionStrip.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainCarContext.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/CarPlaceSearchOptions.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/CarSearchEngine.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/PlaceSearchScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/SearchCarContext.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/car/search/CarPlaceSearch.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/car/search/CarPlaceSearchImpl.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/car/search/CarSearchLocationProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/location/CarAppLocation.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/search/CarPlaceSearchOptionsTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/search/SearchScreenTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/internal/car/search/CarPlaceSearchImplTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/internal/car/search/PlaceSearchScreenTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/QaTestApplication.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/car/MainCarSession.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/car/search/MapboxCarSearchApp.kt
Labels: Android Auto

#6178 - RoadObject: added `isUrban` flag; - EHorizonEdgeMetadata: added `isUrban` flag.
  CHANGELOG.md
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/eh/EHorizonEdgeMetadata.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/eh/EHorizonMapper.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/RoadObject.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/RoadObjectMapper.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/border/CountryBorderCrossing.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/bridge/Bridge.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/custom/Custom.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/incident/Incident.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/railwaycrossing/RailwayCrossing.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/restrictedarea/RestrictedArea.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/reststop/RestStop.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/tollcollection/TollCollection.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/tunnel/Tunnel.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/trip/model/roadobject/RoadObjectMapperTest.kt
Labels: feature

#6181 Bump `mapboxSearchSdk` dependency version to `1.0.0-beta.35` to fix broken `qa-test-app`
  gradle/dependencies.gradle
Labels: skip changelog

#6185 Fix `CHANGELOG` in the `2.7.0` release branch
  CHANGELOG.md
Labels: skip changelog

#6158 [Drop-In UI] Moved RecenterButtonComponent outside Drop-In UI
  CHANGELOG.md
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/extensions/MapboxNavigationObserverEx.kt
  libnavui-base/api/current.txt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/installer/ComponentInstaller.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/ActionButtonBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonComponentContractImpl.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonComponentTest.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/installer/ComponentInstaller.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RecenterButtonComponent.kt
  libnavui-maps/src/main/res/drawable/mapbox_ic_camera_recenter.xml
  libnavui-maps/src/main/res/values/styles.xml
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/MapboxRecenterButtonComponentContractTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/RecenterButtonComponentTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/lifecycle/viewmodel/DropInNavigationViewModel.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/ComponentsActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/ComponentsAltActivity.kt
  qa-test-app/src/main/res/layout/components_activity_layout.xml
Labels: UI

#6189 fix save cache problem
  .circleci/config.yml
  scripts/gradle-files-checksum.py
Labels: skip changelog

#6083 6080 improve changelog verification
  scripts/test_resources/test_changelog.md
  scripts/test_resources/test_changelog_single_line_repeats_stable_version.md
  scripts/test_resources/test_changelog_single_line_repeats_unstable_version.md
  scripts/validate-changelog-tests.py
  scripts/validate-changelog.py
  scripts/validate_changelog_utils.py
Labels: skip changelog

#6190 introduce NavigationRouterV2 interface
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/CurrentIndices.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/CurrentIndicesFactory.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/CurrentIndicesSnapshot.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/NavigationRouterV2.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/route/CurrentIndicesSnapshotTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/CurrentIndicesProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/CurrentIndicesSnapshotProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationComponentProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/SetRoutesInfo.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/LegacyNavigationRouterAdapter.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/RouteRefresh.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/utils/ModulesUtils.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RefreshedRouteInfo.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshControllerProvider.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/CurrentIndicesProviderTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationBaseTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/SetRoutesInfoTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/directions/LegacyNavigationRouterAdapterTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSessionTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routerefresh/RouteRefreshControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routerefresh/RouteRefreshStub.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/RouterWrapper.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/RouterWrapperTests.kt
Labels: skip changelog

#6218 [Android Auto] Remove app name string
  libnavui-androidauto/src/main/res/values/strings.xml
Labels: skip changelog, Android Auto

#6216 Fix docs
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/NavigationRouteAlternativesRequestCallback.kt
Labels: skip changelog

#6202 [Drop-In UI] Moved CameraModeButtonComponent outside Drop-In UI
  CHANGELOG.md
  libnavui-base/api/current.txt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/installer/ComponentInstaller.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/ActionButtonBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/cameramode/CameraModeButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/cameramode/CameraModeButtonComponentContractImpl.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/cameramode/CameraModeButtonComponentContractImplTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/cameramode/CameraModeButtonComponentTest.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/installer/ComponentInstaller.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/CameraModeButtonComponent.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/NavigationCameraComponent.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/NavigationCameraGestureComponent.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/CameraModeButtonComponentTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/MapboxCameraModeButtonComponentContractTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/NavigationCameraComponentTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/NavigationCameraGestureComponentTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/ComponentsActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/ComponentsAltActivity.kt
  qa-test-app/src/main/res/layout/components_activity_layout.xml
Labels: UI

#6221 fix changelog validation
  scripts/validate-changelog-tests.py
  scripts/validate-changelog.py
  scripts/validate_changelog_utils.py
Labels: skip changelog

#6224 [Android Auto] Remove mapbox navigation from road name observer
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/build.gradle
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainCarScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/ActiveGuidanceScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/roadlabel/RoadLabelSurfaceLayer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/roadlabel/RoadNameObserver.kt
Labels: skip changelog, Android Auto

#6225 [Android Auto] Remove `MapboxNavigation` from `CarLocationsOverviewCamera` constructor
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarLocationsOverviewCamera.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/placeslistonmap/PlacesListOnMapScreen.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/CarLocationsOverviewCameraTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/testing/CarAppTestRule.kt
Labels: Android Auto

#6219 [Android Auto] Remove `MapboxNavigation` from `CarNavigationCamera` and `CarRouteLine`
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainCarScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/ActiveGuidanceScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarNavigationCamera.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRouteLine.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRoutePreviewScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/PreviewCarRoutesProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/PreviewRoutesProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/routes/CarRoutesProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/routes/NavigationCarRoutesProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/routes/NavigationRoutesProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/routes/RoutesListener.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/routes/RoutesProvider.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/routes/NavigationCarRoutesProviderTest.kt
Labels: Android Auto

#6174 [Drop-In UI] Expose public APIs via NavigationViewApi
  CHANGELOG.md
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewApi.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/MapboxNavigationViewApi.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/internal/MapboxNavigationViewApiTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxNavigationViewActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
Labels: UI

#6226 [Android Auto] Remove `MapboxNavigation` from `RoutePreviewCarContext`
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/speedlimit/CarSpeedLimitRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRoutePreviewScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/RoutePreviewCarContext.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/deeplink/GeoDeeplinkNavigateAction.kt
Labels: skip changelog, Android Auto

#6227 support remote icons in feedback screen
  LICENSE.md
  Makefile
  gradle/dependencies.gradle
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/build.gradle
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/core/CarFeedbackPollProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/ui/CarFeedbackIcon.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/ui/CarFeedbackIconDownloader.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/ui/CarFeedbackOption.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/ui/CarGridFeedbackScreen.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/feedback/ui/CarFeedbackIconDownloaderTest.kt
  libnavui-dropin/api/current.txt
  libnavui-maneuver/api/current.txt
  scripts/generate-license.py
Labels: Android Auto, improvement

#6241 [Android Auto] Suggestion from circle ci support to fix androidauto-test
  .circleci/config.yml
Labels: skip changelog, Android Auto

#6245 Fix `MapboxNavigation#detach` issue
  CHANGELOG.md
  libnavigation-core/src/main/java/com/mapbox/navigation/core/lifecycle/MapboxNavigationOwner.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/lifecycle/MapboxNavigationAppDelegateTest.kt
Labels: bug

#6249 add ability to observe when info panel is dragging or settling
  CHANGELOG.md
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewListener.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewListenerRegistry.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/NavigationViewListenerRegistryTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/LoggingNavigationViewListener.kt
Labels: UI

#6135 use media store on newer versions to write files
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/history/MapboxHistoryTestRule.kt
  libnavui-androidauto/src/androidTest/java/com/mapbox/androidauto/testing/BitmapTestUtil.kt
Labels: skip changelog
