Repository mapbox/mapbox-navigation-android, pull requests merged in 2022-09, with the labels that each got.

#6244 [Drop-In UI] Allow users to handle back press events.
  CHANGELOG.md
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewListener.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewListenerRegistry.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/backpress/OnKeyListenerComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/NavigationViewListenerRegistryTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/backpress/OnKeyListenerComponentTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
Labels: UI

#6209 grant POST_NOTIFICATIONS permission in tests
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/BaseTest.kt
Labels: skip changelog

#6258 Bump mapbox-java v6.8.0-beta.3
  gradle/dependencies.gradle
Labels: skip changelog

#6262 add changelog for androidauto-0.9.0
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/build.gradle
Labels: Android Auto

#6265 Pull in the latest translations from Transifex
  libnavigation-base/src/main/res/values-es/strings.xml
  libnavigation-base/src/main/res/values-fr/strings.xml
  libnavigation-base/src/main/res/values-pt-rBR/strings.xml
  libnavigation-base/src/main/res/values-pt-rPT/strings.xml
  libnavigation-base/src/main/res/values-uz/strings.xml
  libnavui-maps/src/main/res/values-ca/strings.xml
  libnavui-maps/src/main/res/values-uk/strings.xml
  libnavui-maps/src/main/res/values-vi/strings.xml
Labels: skip changelog

#6207 request WRITE_EXTERNAL_STORAGE only until Android R
  examples/src/main/java/com/mapbox/navigation/examples/MainActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MainActivity.kt
Labels: skip changelog

#6276 Bump NN to `v114.0`
  gradle/dependencies.gradle
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/eh/RoadObjectMatcher.kt
Labels: skip changelog

#6278 override overview camera pitch in all states
  CHANGELOG.md
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/camera/CameraComponentTest.kt
Labels: bug, UI

#6283 prefer active routes to preview ones in camera component
  CHANGELOG.md
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/camera/CameraComponentTest.kt
Labels: bug, UI

#6291 handle route changes and navigation state separately
  CHANGELOG.md
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/camera/CameraComponentTest.kt
Labels: bug, UI

#6296 Fix step distance and trip progress views
  CHANGELOG.md
  libnavui-maneuver/src/main/res/layout/mapbox_main_maneuver_layout.xml
  libnavui-tripprogress/src/main/res/layout/mapbox_trip_progress_layout.xml
Labels: bug

#6295 Experimental route util API: check if route has unexpected closures
  CHANGELOG.md
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/utils/route/NavigationRouteEx.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/utils/route/NavigationRouteExTest.kt
  libnavigation-base/src/test/resources/route_closure_between_silent_and_regular_waypoints.json
  libnavigation-base/src/test/resources/route_closure_between_two_regular_waypoints.json
  libnavigation-base/src/test/resources/route_closure_last_coordinate.json
  libnavigation-base/src/test/resources/route_closure_second_silent_waypoin.json
  libnavigation-base/src/test/resources/route_closure_second_waypoint.json
  libnavigation-base/src/test/resources/route_closure_start_coordinate.json
Labels: release blocker

#6299 Revert "changelog for v2.8.0-beta.3 (#6298)"
  CHANGELOG.md
Labels: skip changelog

#6284 Updated QA route line related activities
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivitySuite.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/InactiveRouteStylingActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/InactiveRouteStylingWithRestrictionsActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/RouteRestrictionsActivity.kt
Labels: skip changelog

#6306 fix changelog link
  CHANGELOG.md
Labels: skip changelog

#6292 [Android Auto] Start declaring apis with java interop
  CHANGELOG.md
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/lifecycle/MapboxNavigationApp.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/lifecycle/RequireMapboxNavigationTest.kt
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/MapboxCarNavigationManager.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/testing/CarAppTestRule.kt
  libnavui-base/src/test/java/com/mapbox/navigation/ui/base/installer/ComponentInstallerTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/coordinator/InfoPanelCoordinatorTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/testing/CarJavaInterfaceChecker.java
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/testing/JavaFlow.kt
Labels: Android Auto

#6318 leak canary: bump 2.9.1
  gradle/dependencies.gradle
Labels: skip changelog

#6316 [Android Auto] QA-Test-App Crash Fix
  libnavui-androidauto/build.gradle
Labels: skip changelog, Android Auto

#6319 add temporary workaround to run instrumentation tests on Android 13
  .circleci/config.yml
  instrumentation-tests/src/androidTest/AndroidManifest.xml
Labels: skip changelog

#6263 [Android Auto] Remove `MapboxNavigation` from `CarNavigationInfoObserver` constructor
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/build.gradle
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainCarContext.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/ActiveGuidanceScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarActiveGuidanceCarContext.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarNavigationEtaMapper.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarNavigationInfo.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarNavigationInfoObserver.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarNavigationInfoProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarNavigationInfoServices.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/car/extensions/MapboxNavigationExtensions.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/navigation/CarNavigationInfoProviderTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/CarNavigationEtaMapperTest.kt
Labels: Android Auto

#6273 [Drop-In UI] Split InfoPanelHeaderBinder into smaller binders.
  CHANGELOG.md
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewStyles.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewBinderCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewStyleCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/InfoPanelHeaderActiveGuidanceBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/InfoPanelHeaderArrivalBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/InfoPanelHeaderBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/InfoPanelHeaderDestinationPreviewBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/InfoPanelHeaderRoutesPreviewBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/infopanel/ArrivalTextComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/infopanel/EndNavigationButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/infopanel/InfoPanelHeaderComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/infopanel/POINameComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/infopanel/RoutePreviewButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/infopanel/StartNavigationButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/NavigationViewContextEx.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/extensions/MapboxExtendableButtonEx.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/extensions/NavigationViewContextFlowable.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/extensions/ReloadComponentEx.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/extensions/ReloadingComponent.kt
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_header_active_guidance_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_header_arrival_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_header_destination_preview_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_header_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_header_route_preview_layout.xml
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/binder/infopanel/InfoPanelHeaderBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/infopanel/EndNavigationButtonComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/infopanel/InfoPanelHeaderComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/infopanel/POINameComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/infopanel/RoutePreviewButtonComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/infopanel/StartNavigationButtonComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/testutil/TestLifecycleOwner.kt
Labels: UI

#6325 [Android Auto] Remove MapboxNavigation from CarSpeedLimitRenderer
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/speedlimit/CarSpeedLimitRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/speedlimit/CarSpeedLimitServices.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/navigation/speedlimit/CarSpeedLimitRendererTest.kt
Labels: Android Auto

#6329 Exposed alternatives id
  CHANGELOG.md
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/AlternativeRouteMetadata.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesController.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesControllerTest.kt
Labels: needs backporting

#6328 fix maneuver view layout in landscape with drop-in
  CHANGELOG.md
  libnavui-dropin/src/main/res/layout-land/mapbox_navigation_view_layout.xml
Labels: bug, UI

#6327 [Drop-In] Customise default drop-in buttons
  CHANGELOG.md
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/MapboxExtendableButtonParams.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewStyles.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewStyleCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/ActionButtonBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/InfoPanelHeaderActiveGuidanceBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/InfoPanelHeaderDestinationPreviewBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/InfoPanelHeaderRoutesPreviewBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/infopanel/EndNavigationButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/infopanel/RoutePreviewButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/infopanel/StartNavigationButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/NavigationViewContextEx.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/extensions/MapboxExtendableButtonEx.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/extensions/ViewGroupEx.kt
  libnavui-dropin/src/main/res/layout/mapbox_action_buttons_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_header_active_guidance_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_header_destination_preview_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_header_route_preview_layout.xml
  libnavui-dropin/src/main/res/values/dimens.xml
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/binder/ActionButtonBinderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/infopanel/EndNavigationButtonComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/infopanel/RoutePreviewButtonComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/infopanel/StartNavigationButtonComponentTest.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/installer/ComponentInstaller.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/CameraModeButtonComponent.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RecenterButtonComponent.kt
  libnavui-maps/src/main/res/values/styles.xml
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/CameraModeButtonComponentTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/RecenterButtonComponentTest.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/internal/ui/AudioGuidanceButtonComponent.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/internal/ui/AudioGuidanceButtonComponentTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
  qa-test-app/src/main/res/drawable/mapbox_bg_action_button.xml
Labels: bug

#6331 [Drop-In UI] Ability to inject custom End Navigation button via Binder.
  CHANGELOG.md
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewBinderCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewStyleCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/InfoPanelEndNavigationButtonBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/InfoPanelHeaderActiveGuidanceBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/infopanel/InfoPanelHeaderArrivalBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/NavigationViewContextEx.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/extensions/MapboxExtendableButtonEx.kt
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_header_active_guidance_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_header_arrival_layout.xml
  libnavui-dropin/src/main/res/values/dimens.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomInfoPanelEndNavButtonBinder.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomizedViewModel.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
  qa-test-app/src/main/res/layout/layout_drawer_menu_nav_view_custom.xml
Labels: UI

#6326 [Android Auto] Remove MapboxNavigation instance from ActiveGuidanceScreen
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainScreenManager.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/ActiveGuidanceScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarActiveGuidanceCarContext.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarActiveGuidanceMarkers.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarArrivalTrigger.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/navigation/CarArrivalTriggerTest.kt
Labels: Android Auto

#6343 Add changelog for androidauto-0.11.0
  libnavui-androidauto/CHANGELOG.md
Labels: Android Auto

#6344 Bump AA dependencies
  LICENSE.md
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/build.gradle
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/FavoritesApi.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/search/FavoritesApiTest.kt
Labels: skip changelog, Android Auto

#6334 always search for relevant notification
  libnavigation-core/src/androidTest/java/com/mapbox/navigation/core/trip/service/TripServiceTest.kt
Labels: skip changelog

#6346 Dependencies bump
  CHANGELOG.md
  gradle/dependencies.gradle
Labels: needs backporting

#6358 Fix maps version links in the changelogs
  CHANGELOG.md
Labels: skip changelog

#6357 fix camera animations not canceling by gestures
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarNavigationCamera.kt
Labels: Android Auto

#6333 [Drop-In UI] remove arrow layers when arrow component is detached
  CHANGELOG.md
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteArrowComponent.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/arrow/RouteArrowUtils.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/RouteArrowComponentTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/arrow/RouteArrowUtilsTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
Labels: bug, UI

#6206 [Drop-In UI] Moved LocationComponent outside Drop-In UI
  CHANGELOG.md
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/LocationStateController.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/internal/controller/LocationStateControllerTest.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewContext.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/MapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/location/LocationComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/location/LocationComponentTest.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/installer/ComponentInstaller.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/LocationComponent.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/LocationPuckComponent.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/LocationComponentTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/LocationPuckComponentTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/ComponentsActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/ComponentsAltActivity.kt
Labels: UI

#6362 [Drop-In UI] add changes to how margins are assigned to custom buttons
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/ActionButtonBinder.kt
Labels: skip changelog

#6365 [Drop-In UI] add option to specify custom location puck with drop-in
  CHANGELOG.md
  libnavigation-core/api/current.txt
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewStyles.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewStyleCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/MapBinder.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/installer/ComponentInstaller.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/LocationPuckComponent.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/LocationPuckComponentTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
Labels: UI

#6364 NAVAND-646: adjust incidents and closures indices after refresh
  CHANGELOG.md
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteRefreshTest.kt
  instrumentation-tests/src/main/res/raw/route_response_multileg_with_incidents.json
  instrumentation-tests/src/main/res/raw/route_response_route_refresh_multileg.json
  instrumentation-tests/src/main/res/raw/route_response_route_refresh_multileg_with_incidents.json
  instrumentation-tests/src/main/res/raw/route_response_route_refresh_truncated_next_leg.json
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/route/NavigationRouteEx.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/internal/route/NavigationRouteExTest.kt
Labels: release blocker

#6366 Bump resource class for androidauto test
  .circleci/config.yml
Labels: skip changelog

#6360 [Drop-In UI] add ability to observe when map click was not handled by drop-in
  CHANGELOG.md
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewContext.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewListener.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewListenerRegistry.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/MapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/MapClickBehavior.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/NavigationViewListenerRegistryTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/binder/map/MapClickBehaviorTest.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteLineComponent.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/RouteLineComponentTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/LoggingNavigationViewListener.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
  qa-test-app/src/main/res/drawable/ic_sv_puck.xml
Labels: UI

#6370 Route refresh: added experimental state observer (#6345)
  CHANGELOG.md
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshControllerProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshExtra.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshStateResult.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshStatesObserver.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routerefresh/RouteRefreshControllerTest.kt
Labels: release blocker

#6367 Fixed crash caused by ConstantVelocityInterpolator creating PathInterpolator with an invalid path.
  CHANGELOG.md
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/location/ConstantVelocityInterpolator.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/location/ConstantVelocityInterpolatorTest.kt
Labels: bug :beetle:

#6374 [Drop-In UI] Implemented logic to refactor margins for action buttons
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewStyleCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/ActionButtonBinder.kt
  libnavui-dropin/src/main/res/layout-land/mapbox_navigation_view_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_navigation_view_layout.xml
  libnavui-dropin/src/main/res/values/dimens.xml
Labels: skip changelog

#6375 optimizes road objects creation by re-using the parsing that was already done
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
Labels: needs backporting, skip changelog, improvement

#6373 Bumped NN
  CHANGELOG.md
  gradle/dependencies.gradle
Labels: needs backporting

#6376 Backport #6375 #6378
  CHANGELOG.md
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteRefreshTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/coroutines/Adapters.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/route/NavigationRouteEx.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NativeSetRouteResult.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationBaseTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationSetNavigationRoutesCallbackTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationSetNavigationRoutesHistoryRecordingTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
Labels: skip changelog, improvement

#6378 fixes an issue where `NavigationRoute#upcomingRoadObjects` was not refreshed
  CHANGELOG.md
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteRefreshTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/coroutines/Adapters.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/route/NavigationRouteEx.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NativeSetRouteResult.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationBaseTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationSetNavigationRoutesCallbackTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationSetNavigationRoutesHistoryRecordingTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
Labels: needs backporting

#6372 [AndroidAuto] Migrate CarRouteRequest to MapboxNavigationApp
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainActionStrip.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/placeslistonmap/PlacesListOnMapScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRouteRequest.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/PlaceSearchScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/SearchCarContext.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/deeplink/GeoDeeplinkNavigateAction.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/preview/CarRouteRequestTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/internal/car/search/PlaceSearchScreenTest.kt
Labels: Android Auto

#6381 [Drop-In UI] use maneuver view visibility instead of height
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/maneuver/ManeuverBehavior.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/maneuver/ManeuverComponentContractImpl.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/map/ScalebarPlaceholderComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/ScalebarPlaceholderBinder.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/maneuver/ManeuverBehaviorTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/maneuver/ManeuverComponentContractImplTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/map/ScalebarPlaceholderComponentTest.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/internal/ManeuverComponent.kt
  libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/view/MapboxManeuverView.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/internal/ManeuverComponentTest.kt
  libnavui-maneuver/src/test/java/com/mapbox/navigation/ui/maneuver/view/MapboxManeuverViewTest.kt
Labels: skip changelog

#6392 Fix data store crash
  CHANGELOG.md
  libnavui-util/src/main/java/com/mapbox/navigation/ui/utils/internal/datastore/NavigationDataStoreOwner.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxAudioGuidance.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/internal/impl/MapboxAudioGuidanceServices.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/TestMapboxAudioGuidanceServices.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/MapboxAudioGuidanceTest.kt
Labels: skip changelog, Android Auto

#6388 Prepare androidauto-v0.12.0
  LICENSE.md
  gradle/dependencies.gradle
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/build.gradle
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/car/MainCarSession.kt
Labels: skip changelog, Android Auto

#6394 Add changelog release diff link
  libnavui-androidauto/CHANGELOG.md
Labels: skip changelog

#6396 [Android Auto] Update api from 0.3.0 upgrade
  libnavui-androidauto/api/current.txt
Labels: skip changelog, Android Auto

#6390 [Drop-In UI] NavigationViewApi error types enumeration
  CHANGELOG.md
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewApi.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewApiError.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/MapboxNavigationViewApi.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/internal/MapboxNavigationViewApiTest.kt
Labels: UI

#6387 Add `CopilotOptions` to `NavigationOptions`
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/CopilotOptions.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/extensions/NavigationOptionsEx.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/NavigationOptions.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/internal/CopilotOptionsTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/NavigationOptionsTest.kt
  libnavigation-core/api/current.txt
Labels: Core, skip changelog

#6398 [Android Auto] Fix incorrect coroutine scope
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/placeslistonmap/PlacesListOnMapManager.kt
Labels: skip changelog

#6404 NAVAND-692: working around an issue with out of bounds index of fork geometry for alternative route lines
  CHANGELOG.md
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/RouteLineLayersTest.kt
  instrumentation-tests/src/main/res/raw/route_response_japan_1.json
  instrumentation-tests/src/main/res/raw/route_response_japan_1_url.json
  instrumentation-tests/src/main/res/raw/route_response_japan_2.json
  instrumentation-tests/src/main/res/raw/route_response_japan_2_url.json
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiRoboTest.kt
Labels: needs backporting

#6413 bump mapbox-java to 6.8.0
  gradle/dependencies.gradle
Labels: skip changelog

#6412 bump mapbox-java to 6.8.0
  gradle/dependencies.gradle
Labels: skip changelog

#6406 [Android Auto] Migrate CarRouteLine to MapboxNavigationApp
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainCarScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/location/CarLocationRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/ActiveGuidanceScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/placeslistonmap/PlacesListOnMapScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRouteLine.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRoutePreviewScreen.kt
Labels: Android Auto

#6419 fix unreleased changelog
  CHANGELOG.md
Labels: skip changelog

#6400 [Drop-In UI] Moved RoadNameLabelComponent to libnavui-maps module
  CHANGELOG.md
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/roadlabel/RoadNameViewBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/roadlabel/RoadNameComponentContractImpl.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/roadlabel/RoadNameLabelComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/RoadNameCoordinator.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/roadlabel/RoadNameLabelComponentTest.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/installer/ComponentInstaller.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RoadNameComponent.kt
  libnavui-maps/src/main/res/drawable/mapbox_road_name_view_background.xml
  libnavui-maps/src/main/res/values/styles.xml
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/RoadNameComponentTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/ComponentsActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/ComponentsAltActivity.kt
  qa-test-app/src/main/res/layout/components_activity_layout.xml
Labels: UI

#6421 [Drop-In UI] NAVAND-702: add coordinators unit tests
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/BoundMapViewProvider.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/coordinator/MapLayoutCoordinator.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/coordinator/LeftFrameCoordinatorTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/coordinator/ManeuverCoordinatorTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/coordinator/MapLayoutCoordinatorTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/coordinator/RightFrameCoordinatorTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/coordinator/RoadNameLabelCoordinatorTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/coordinator/SpeedLimitCoordinatorTest.kt
Labels: skip changelog

#6425 [Drop-In UI] Post merge Unit-tests fix
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/coordinator/RoadNameCoordinatorTest.kt
Labels: skip changelog
