Repository mapbox/mapbox-navigation-android, pull requests merged in 2022-12, with the labels that each got.

#6664 Backport #6660 to `release-v2.9`
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistoryUploadWorker.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/CopilotTestUtils.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/HistoryAttachmentsUtilsTest.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/HistoryUploadWorkerTest.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/MapboxCopilotImplTest.kt
Labels: Core, skip changelog

#6662 [Drop-In UI] Fixed the last audio instruction repeat on the next session
  CHANGELOG.md
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/internal/MapboxVoiceInstructions.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/internal/impl/MapboxVoiceInstructionsTest.kt
Labels: UI

#6658 [Drop-In UI] Location puck should switch between regular and navigation puck in different camera states
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/extensions/NavigationViewContextEx.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/map/MapViewBinder.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/map/MapViewBinderTest.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/puck/LocationPuckOptions.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/puck/LocationPuckOptionsTest.kt
Labels: UI

#6673 [Android Auto] Fix car library NavigationManager updateTrip crash
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/MapboxCarNavigationManager.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/MapboxCarNavigationManagerTest.kt
Labels: Android Auto

#6679 [Android Auto] Fix AAOS Google Play release issue
  android-auto-app/build.gradle
  android-auto-app/src/main/AndroidManifest.xml
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/build.gradle
  libnavui-androidauto/src/main/AndroidManifest.xml
Labels: Android Auto

#6688 minor fixes
  CHANGELOG.md
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
Labels: skip changelog

#6692 MapboxTripSession: add logs voice and banner instructions
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
Labels: skip changelog

#6690 [Copilot] Fix / support both use cases in which `MapboxNavigationApp` is or is not integrated from the client side
  gradle/dependencies.gradle
  libnavigation-copilot/build.gradle
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilot.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/CopilotTestUtils.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/MapboxCopilotImplTest.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/MapboxCopilotTest.kt
Labels: Core, needs backporting, skip changelog

#6696 Backport #6690 to `release-v2.9`
  gradle/dependencies.gradle
  libnavigation-copilot/build.gradle
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilot.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/CopilotTestUtils.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/MapboxCopilotImplTest.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/MapboxCopilotTest.kt
Labels: Core, skip changelog

#6677 added test for turning off to alternative
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CoreRerouteTest.kt
Labels: skip changelog

#6705 block until deprecated MapboxNavigation#resetTripSession() finishes
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
Labels: skip changelog

#6709 tweak v2.10.0-beta.3 changelog
  CHANGELOG.md
Labels: skip changelog

#6710 added instrumentation test for synchronous resetTripSession
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxNavigationTest.kt
Labels: skip changelog

#6681 [Android Auto] Customizable ActionStrips for MapboxScreens
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/car/MainCarSession.kt
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/MapboxCarOptions.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/action/MapboxActionProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/action/MapboxScreenActionStripProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/feedback/ui/CarFeedbackAction.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/freedrive/FreeDriveActionStrip.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/freedrive/FreeDriveCarScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/ActiveGuidanceScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/CarAudioGuidanceAction.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/placeslistonmap/PlacesListOnMapScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/preview/CarRoutePreviewScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/screenmanager/MapboxScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/screenmanager/factories/ActiveGuidanceScreenFactory.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/screenmanager/factories/FavoritesScreenFactory.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/screenmanager/factories/GeoDeeplinkPlacesCarScreenFactory.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/search/PlaceSearchScreen.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/action/MapboxScreenActionStripProviderTest.kt
Labels: Android Auto

#6714 [Android Auto] Fix compatiblity issue with 2.10.0-beta.3
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/lanes/CarLanesImageRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/screenmanager/MapboxScreenManager.kt
Labels: Android Auto

#6652 Auto-assigning reviewers
  .github/CODEOWNERS
  .github/workflows/set_reviewers.yml
  scripts/reviewers/README.md
  scripts/reviewers/owners.json
  scripts/reviewers/set_reviewers.py
  scripts/reviewers/set_reviewers_defs.py
  scripts/reviewers/set_reviewers_defs_tests.py
  scripts/reviewers/teams.json
Labels: skip changelog

#6695 Fix for SAPA map presentation
  CHANGELOG.md
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/guidance/restarea/RestAreaProcessor.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/guidance/restarea/RestAreaProcessorTest.kt
  qa-test-app/src/main/AndroidManifest.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivitySuite.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/utils/MapboxNavigationEx.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/componentinstaller/RestAreaActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/componentinstaller/components/MapMarkersLegSteps.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/componentinstaller/components/MapMarkersRestStops.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/componentinstaller/components/RestAreaGuideMap.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/componentinstaller/components/SimpleFollowingCamera.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/NavigationViewController.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/util/IconFactory.kt
  qa-test-app/src/main/res/drawable/ic_text_marker.xml
  qa-test-app/src/main/res/layout/layout_activity_rest_area.xml
  qa-test-app/src/main/res/layout/layout_map_marker_with_text.xml
  qa-test-app/src/main/res/values/strings.xml
Labels: bug, UI

#6730 [Drop-In UI] Adjusted Following Camera padding in landscape orientation
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/camera/CameraLayoutObserver.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/camera/CameraLayoutObserverTest.kt
Labels: bug

#6723 set isUpdatingRoute to true for refreshes
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
Labels: skip changelog

#6719 [NAVAND-935] do not interrupt reroute when alternative or refreshed routes are set
  CHANGELOG.md
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CoreRerouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/assertions/RerouteStateTransitionAssertion.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/assertions/RouteProgressStateTransitionAssertion.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/location/MockLocationReplayer.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/routes/RoutesProvider.kt
  instrumentation-tests/src/main/res/raw/route_response_dc_short_with_alternative.json
  instrumentation-tests/src/main/res/raw/route_response_dc_short_with_alternative_refresh_route_0.json
  instrumentation-tests/src/main/res/raw/route_response_dc_short_with_alternative_reroute.json
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/SetRoutes.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/reroute/MapboxRerouteController.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavui-maps/src/test/resources/snapshotter-here-based-junctions.json
Labels: release blocker

#6750 bump Nav Native to v123.1.0
  gradle/dependencies.gradle
Labels: skip changelog

#6751 changelog for Nav Native v123.1.0 bump
  CHANGELOG.md
Labels: skip changelog

#6678 [Drop-In UI] Updated the default navigation puck vector asset
  CHANGELOG.md
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/puck/LocationPuckOptions.kt
  libnavui-maps/src/main/res/drawable/mapbox_navigation_puck_icon2.xml
  libnavui-maps/src/main/res/drawable/mapbox_navigation_puck_icon2_shadow.xml
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/puck/LocationPuckOptionsTest.kt
  libnavui-util/src/main/java/com/mapbox/navigation/ui/utils/internal/extensions/DrawableEx.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomizedViewModel.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
  qa-test-app/src/main/res/drawable/mapbox_navigation_puck_icon2a.xml
  qa-test-app/src/main/res/drawable/mapbox_navigation_puck_icon2b.xml
  qa-test-app/src/main/res/layout/layout_drawer_menu_nav_view_custom.xml
  qa-test-app/src/main/res/values/strings.xml
Labels: UI

#6753 [Android Auto] Bump example to 2.10
  android-auto-app/build.gradle
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/CarAppSyncComponent.kt
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/ReplayRouteTripSession.kt
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/car/MainCarSession.kt
Labels: skip changelog, Android Auto

#6762 [copilot] Add Proguard rule to prevent obfuscation of route properties
  libnavigation-copilot/proguard-rules.pro
Labels: Core, needs backporting, bug :beetle:

#6763 Backport #6762 to `release-v2.9`
  libnavigation-copilot/proguard-rules.pro
Labels: Core

#6768 increased instrumentation tests timeout to 25 minutes per device
  .circleci/config.yml
Labels: skip changelog

#6760 NAVAND-1025: fix the crash in MapboxVoiceInstructionsPlayer
  CHANGELOG.md
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceInstructionsPlayer.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceInstructionsPlayerTest.kt
Labels: bug, needs backporting, v2.x

#6774 fix standalone maneuver view appearance when drop-in ui is integrated
  CHANGELOG.md
  examples/src/main/res/values/strings.xml
  libnavui-maneuver/src/main/res/values-night/colors.xml
  libnavui-maneuver/src/main/res/values/colors.xml
Labels: bug, UI, needs backporting
