Repository mapbox/mapbox-navigation-android, pull requests merged in 2022-05, with the labels that each got.

#5698 Adjusted flakey test in an attempt to remove flakiness.
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/SetRouteOrderTest.kt
Labels: skip changelog

#5771 [DROP-IN] Renaming *ViewModel classes to *StateController.
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewModel.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/location/LocationComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/controller/AudioGuidanceStateController.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/controller/CameraStateController.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/controller/DestinationStateController.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/controller/LocationStateController.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/controller/NavigationStateController.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/controller/RoutesStateController.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/controller/StateController.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/controller/TripSessionStarterStateController.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/location/LocationComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/controller/AudioGuidanceStateControllerTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/controller/CameraStateControllerTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/controller/DestinationStateControllerTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/controller/LocationStateControllerTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/controller/NavigationStateControllerTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/controller/RoutesStateControllerTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/controller/TripSessionStarterStateControllerTest.kt
Labels: UI, skip changelog

#5774 update mapbox-base-android to v0.8.0
  gradle/dependencies.gradle
Labels: skip changelog

#5772 [Android Auto] Enable unit tests
  .circleci/config.yml
  libnavui-androidauto/build.gradle
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/MapboxCarNavigationManagerTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/navigation/maneuver/CarManeuverIconOptionsTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/search/FavoritesApiTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/search/SearchScreenTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/deeplink/GeoDeeplinkParserTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/deeplink/GeoDeeplinkPlacesListOnMapProviderTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxAudioGuidanceImplTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxAudioGuidanceVoiceTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxVoiceInstructionsTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/testing/BuilderTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/testing/MainCoroutineRule.kt
Labels: skip changelog, Android Auto

#5776 Bump `mapboxSdkServices` dependency to 6.5.0-beta.4
  gradle/dependencies.gradle
Labels: release blocker, skip changelog

#5777 Bump `mapboxMapSdk` to 10.5.0 (gl-native v10.5.1)
  gradle/dependencies.gradle
Labels: release blocker, skip changelog

#5779 Add `v2.5.0-beta.3` CHANGELOG release notes
  CHANGELOG.md
Labels: skip changelog

#5769 [Android Auto] Enable androidTest
  .circleci/config.yml
  gradle/dependencies.gradle
  libnavui-androidauto/build.gradle
Labels: skip changelog, Android Auto

#5773 [Android Auto] Enable publisher
  .circleci/config.yml
  Makefile
  gradle.properties
  gradle/artifact-settings.gradle
  gradle/dependencies.gradle
  gradle/publish.gradle
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/README.md
  libnavui-androidauto/build.gradle
  libnavui-androidauto/gradle.properties
  libnavui-androidauto/screenshots/active-guidance.png
  libnavui-androidauto/screenshots/free-drive.png
  libnavui-androidauto/src/main/AndroidManifest.xml
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainActionStrip.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainMapActionStrip.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/ui/CarFeedbackAction.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/ui/CarFeedbackIcon.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/ui/CarFeedbackItem.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/ui/CarGridFeedbackScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/location/CarLocationPuck.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/map/widgets/compass/CompassWidget.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/map/widgets/logo/LogoWidget.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/ActiveGuidanceScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/lanes/CarLaneIconOptions.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/maneuver/CarManeuverIconOptions.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/permissions/NeedsLocationPermissionsScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/placeslistonmap/PlaceMarkerRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/placeslistonmap/PlacesListOnMapLayerUtil.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/placeslistonmap/PlacesListOnMapScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRoutePreviewScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/SearchScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/settings/CarSettingsScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/settings/SettingsFailureScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/AppAudioGuidanceUi.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/CarAudioGuidanceUi.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/navigation/maneuver/CarManeuverIconOptionsTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/search/SearchScreenTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/settings/CarSettingsScreenTest.kt
  qa-test-app/build.gradle
Labels: skip changelog, Android Auto

#5788 [Android Auto] Update dokka
  .circleci/config.yml
  Makefile
Labels: skip changelog, Android Auto

#5792 Update qa-test-app android auto search location engine
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/QaTestApplication.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/car/search/CarSearchLocationProvider.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/car/search/MapboxCarSearchApp.kt
Labels: skip changelog, Android Auto

#5795 [Android Auto] Enable linter
  Makefile
  libnavui-androidauto/src/androidTest/java/com/mapbox/androidauto/car/navigation/roadlabel/RoadLabelRendererTest.kt
  libnavui-androidauto/src/androidTest/java/com/mapbox/androidauto/car/navigation/speedlimit/SpeedLimitRendererTest.kt
  libnavui-androidauto/src/androidTest/java/com/mapbox/androidauto/testing/BitmapTestUtil.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainCarScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainMapActionStrip.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/MainScreenManager.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/ui/CarFeedbackIcon.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/ui/CarFeedbackItem.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/ui/CarGridFeedbackScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/location/CarLocationPuck.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/location/CarLocationRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/map/widgets/ImageOverlayHost.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/map/widgets/compass/CompassWidget.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/map/widgets/logo/LogoWidget.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/ActiveGuidanceScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarActiveGuidanceCarContext.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarLocationsOverviewCamera.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarNavigationCamera.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarNavigationEtaMapper.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarNavigationInfoMapper.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/maneuver/CarManeuverIconRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/maneuver/CarManeuverInstructionRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/maneuver/CarManeuverMapper.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/roadlabel/RoadLabelRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/speedlimit/CarSpeedLimitRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/speedlimit/SpeedLimitWidget.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/placeslistonmap/PlaceMarkerRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/placeslistonmap/PlacesListOnMapProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/placeslistonmap/PlacesListOnMapScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRouteLine.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRoutePreviewScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRouteRequest.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/CarSearchEngine.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/FavoritesApi.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/search/SearchScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/deeplink/GeoDeeplinkGeocoding.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/deeplink/GeoDeeplinkNavigateAction.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/deeplink/GeoDeeplinkPlacesListOnMapProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/CarAudioGuidanceUi.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/MapboxAudioGuidanceServices.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxAudioGuidanceImpl.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxAudioGuidanceServicesImpl.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxAudioGuidanceVoice.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/MapboxCarNavigationManagerTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/navigation/maneuver/CarManeuverMapperTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/placeslistonmap/PlacesListItemMapperTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/placeslistonmap/PlacesListOnMapLayerUtilTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/preview/CarRouteRequestTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/search/FavoritesApiTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/settings/CarSettingsScreenTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/deeplink/GeoDeeplinkPlacesListOnMapProviderTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/CarLocationsOverviewCameraTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxAudioGuidanceImplTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxAudioGuidanceVoiceTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxVoiceInstructionsTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/search/PlaceRecordMapperTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/testing/TestCarAppDataStoreOwner.kt
Labels: skip changelog, Android Auto

#5789 Logger frontend
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/history/MapboxHistoryRecorderTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/lifecycle/CarAppLifecycleOwnerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/lifecycle/MapboxNavigationAppDelegateTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/lifecycle/MapboxNavigationOwnerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/history/ReplayHistoryMapperTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/route/ReplayRouteMapperTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/reroute/MapboxRerouteControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/RouteOptionsUpdaterTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routerefresh/RouteRefreshControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/LocationsCollectorTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/service/MapboxTripServiceTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionNoSetupTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/RouterWrapperTests.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/LoggerFrontend.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/LoggerProvider.kt
  libnavigation-util/src/test/java/com/mapbox/navigation/utils/internal/ConnectivityHandlerTest.kt
  libnavigation-util/src/test/java/com/mapbox/navigation/utils/internal/LoggerProviderFormatTest.kt
  libnavigation-util/src/test/java/com/mapbox/navigation/utils/internal/LoggerProviderTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/marker/RoutePreviewLongPressMapComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/controller/CameraStateControllerTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/controller/LocationStateControllerTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/model/StoreTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/PredictiveCacheControllerTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceInstructionsPlayerTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsFilePlayerTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/VoiceInstructionsTextPlayerTest.kt
  libtesting-utils/src/main/java/com/mapbox/navigation/testing/MockLoggerRule.kt
Labels: skip changelog, op-ex

#5749 Route refresh: added `incidents`
  CHANGELOG.md
  gradle/dependencies.gradle
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteRefreshTest.kt
  instrumentation-tests/src/main/res/raw/route_response_route_refresh.json
  instrumentation-tests/src/main/res/raw/route_response_route_refresh_annotations.json
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/route/NavigationRouteEx.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/internal/route/NavigationRouteExTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/RouterWrapper.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt
Labels: release blocker, Core

#5805 [Android Auto] Remove extra arrival feedback options
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/feedback/ui/CarFeedbackItem.kt
  libnavui-androidauto/src/main/res/values/strings.xml
  scripts/validate-changelog.py
Labels: Android Auto

#5811 Don't upload cov in changelog branches
  .circleci/config.yml
Labels: skip changelog

#5816 updated GL-Native to v10.5.2
  CHANGELOG.md
  gradle/dependencies.gradle
  libnavui-maps/build.gradle
Labels: release blocker, needs backporting

#5817 Backport #5816 to release-v2.5
  CHANGELOG.md
  gradle/dependencies.gradle
  libnavui-maps/build.gradle
Labels: release blocker

#5778 add notification interceptor for android auto
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/build.gradle
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/notification/ActiveGuidanceExtenderUpdater.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/notification/CarNotificationInterceptor.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/notification/FreeDriveExtenderUpdater.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/notification/IdleExtenderUpdater.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/notification/CarNotificationInterceptorTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/car/MainCarSession.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/AppLifecycleActivity.kt
Labels: Android Auto

#5824 Fix snapshots
  Makefile
Labels: skip changelog

#5821 Integrate `Logger` changes from `common`
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/LoggerFrontend.kt
  libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/LoggerProvider.kt
Labels: Core, skip changelog

#5819 Upgrade agents for unit jobs
  .circleci/config.yml
Labels: skip changelog

#5822 Bump mapbox java to 5.6.0-beta.6
  gradle/dependencies.gradle
Labels: skip changelog

#5832 Changelog for 2.5.0-rc.2 and 2.6.0-alpha.1
  CHANGELOG.md
Labels: skip changelog

#5831 Changelog for v2.5.0-rc.2
  CHANGELOG.md
Labels: skip changelog

#5825 [Android auto] first instruction fix
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/MapboxAudioGuidanceServices.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxAudioGuidanceImpl.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxAudioGuidanceServicesImpl.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxVoiceInstructions.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxAudioGuidanceImplTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxVoiceInstructionsTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/testing/TestMapboxAudioGuidanceServices.kt
Labels: bug :beetle:

#5829 Adding support for sharing multiple instances of MapboxNavigationObserver
  CHANGELOG.md
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/lifecycle/MapboxNavigationApp.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/lifecycle/MapboxNavigationAppDelegate.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/lifecycle/MapboxNavigationOwner.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/lifecycle/MapboxNavigationAppDelegateTest.kt
Labels: UI, Core, Android Auto

#5836 Changelog for androidauto-v0.2.0
  libnavui-androidauto/CHANGELOG.md
Labels: skip changelog

#5848 NN 101
  CHANGELOG.md
  gradle/dependencies.gradle
Labels: needs backporting

#5842 Resetting the trim-offset to 0.0 when routes are drawn.
  CHANGELOG.md
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/RouteLineTrimOffset.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineView.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineDynamicData.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineViewTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineDynamicDataTest.kt
Labels: release blocker, needs backporting

#5741 create trigger commit PR from publisher production
  scripts/publish_api_docs_android.sh
Labels: skip changelog

#5862 Updated mapbox-java to 6.5.0 for 2.5 release
  gradle/dependencies.gradle
Labels: skip changelog

#5872 Fixed mapbox java version in changelog
  CHANGELOG.md
Labels: needs backporting

#5846 [Android Auto] Integrate `AudioGuidanceComponent` with AA (2/2).
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/build.gradle
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/MapboxCarApp.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/configuration/CarAppConfigOwner.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/datastore/CarAppDataStoreKey.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/datastore/CarAppDataStoreOwner.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/AppAudioGuidanceUi.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/MapboxAudioGuidance.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/MapboxAudioGuidanceServices.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxAudioGuidanceImpl.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxAudioGuidanceServicesImpl.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxAudioGuidanceVoice.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxVoiceInstructions.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxAudioGuidanceImplTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxAudioGuidanceVoiceTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/audioguidance/impl/MapboxVoiceInstructionsTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/testing/TestCarAppDataStoreOwner.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/testing/TestMapboxAudioGuidanceServices.kt
Labels: skip changelog, Android Auto
