Repository mapbox/mapbox-navigation-android, pull requests merged in 2022-06, with the labels that each got.

#5818 NavigationView lifecycle with Fragments
  CHANGELOG.md
  instrumentation-tests/build.gradle
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/dropin/NavigationViewLifecycleTest.kt
  instrumentation-tests/src/main/AndroidManifest.xml
  instrumentation-tests/src/main/java/com/mapbox/navigation/instrumentation_tests/activity/NavigationViewLifecycleTestActivity.kt
  instrumentation-tests/src/main/res/layout/layout_activity_navigation_view_lifecycle_test.xml
  instrumentation-tests/src/main/res/layout/layout_fragment_frame.xml
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/extensions/ContextEx.kt
  libnavui-util/src/main/java/com/mapbox/navigation/ui/utils/internal/lifecycle/ViewLifecycleRegistry.kt
  libnavui-util/src/test/java/com/mapbox/navigation/ui/utils/internal/lifecycle/ViewLifecycleRegistryTest.kt
  qa-test-app/README.md
  qa-test-app/src/main/AndroidManifest.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivitySuite.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/NavigationViewFragmentLifecycleActivity.kt
  qa-test-app/src/main/res/layout/layout_activity_navigation_view_fragment_lifecycle.xml
  qa-test-app/src/main/res/layout/layout_fragment_frame.xml
  qa-test-app/src/main/res/values/strings.xml
Labels: UI, improvement

#5884 [Android Auto] Use specific version of ui-app
  libnavui-androidauto/build.gradle
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/QaTestApplication.kt
Labels: skip changelog

#5889 changelog for v2.6.0-beta.1
  CHANGELOG.md
Labels: skip changelog

#5883 Update Metalava
  docs/metalava.md
  gradle/metalava-dependencies.gradle
  gradle/track-public-apis.gradle
  libnavigation-base/api/current.txt
  libnavigation-core/api/current.txt
  libnavui-base/api/current.txt
  libnavui-dropin/api/current.txt
  libnavui-maneuver/api/current.txt
  libnavui-maps/api/current.txt
  libnavui-speedlimit/api/current.txt
  libnavui-status/api/current.txt
  libnavui-tripprogress/api/current.txt
  libnavui-voice/api/current.txt
  metalava/metalava.jar
  scripts/update_metalava.sh
Labels: Core, skip changelog, op-ex

#5895 Added changelog for v2.5.1
  CHANGELOG.md
Labels: skip changelog

#5896 cherry pick changes
  docs/metalava.md
  gradle/metalava-dependencies.gradle
  gradle/track-public-apis.gradle
  libnavigation-base/api/current.txt
  libnavigation-core/api/current.txt
  libnavui-dropin/api/current.txt
  libnavui-maneuver/api/current.txt
  libnavui-maps/api/current.txt
  libnavui-speedlimit/api/current.txt
  libnavui-status/api/current.txt
  libnavui-tripprogress/api/current.txt
  libnavui-voice/api/current.txt
  metalava/metalava.jar
  scripts/update_metalava.sh
Labels: skip changelog

#5894 Bump NN to 101.0.1
  gradle/dependencies.gradle
Labels: skip changelog

#5897 Added changelog for v2.5.1
  CHANGELOG.md
Labels: skip changelog

#5901 refactors v2.5.1 changelog
  CHANGELOG.md
Labels: skip changelog

#5902 Backport #5901 to release-v2.5
  CHANGELOG.md
Labels: skip changelog

#5887 instrumentation test for route refresh
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteRefreshTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/coroutines/Adapters.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/coroutines/TestUtils.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/http/FailByRequestMockRequestHandler.kt
Labels: skip changelog

#5893 Fixed Android Studio throwing compile time errors for view bindings.
  LICENSE.md
  gradle/dependencies.gradle
  libnavui-base/build.gradle
Labels: skip changelog

#5903 Bump `mapboxEvents` dependency library version to `8.1.2`
  gradle/dependencies.gradle
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
Labels: Core, skip changelog

#5874 [Drop-In UI] Making UI Components usable outside DropIn UI
  CHANGELOG.md
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/extensions/MapboxLifecycleExtensions.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/extensions/MapboxNavigationObserverEx.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/extensions/MapboxLifecycleExtensionsKtTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/internal/extensions/MapboxNavigationObserverChainTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/testutil/TestLifecycleOwner.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/testutil/TestMapboxNavigationObserver.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/SharedApp.kt
  libnavui-base/api/current.txt
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/installer/ComponentInstaller.kt
  libnavui-base/src/test/java/com/mapbox/navigation/ui/base/installer/ComponentInstallerTest.kt
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewStyleCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/ActionButtonBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/MapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/audioguidance/AudioGuidanceButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/model/Store.kt
  libnavui-dropin/src/main/res/layout/mapbox_action_buttons_layout.xml
  libnavui-dropin/src/main/res/values/attrs.xml
  libnavui-dropin/src/main/res/values/dimens.xml
  libnavui-dropin/src/main/res/values/styles.xml
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/installer/ComponentInstaller.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteArrowComponent.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteLineComponent.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/RouteArrowComponentTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/RouteLineComponentTest.kt
  libnavui-resources/src/main/res/drawable/mapbox_bg_button.xml
  libnavui-resources/src/main/res/values/dimens.xml
  libnavui-util/src/main/java/com/mapbox/navigation/ui/utils/internal/Provider.kt
  libnavui-util/src/main/java/com/mapbox/navigation/ui/utils/internal/extensions/StateFlowEx.kt
  libnavui-voice/api/current.txt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/installer/ComponentInstaller.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/internal/impl/MapboxAudioGuidanceImpl.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/internal/ui/AudioGuidanceButtonComponent.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/view/MapboxAudioGuidanceButton.kt
  libnavui-voice/src/main/res/layout/mapbox_audio_guidance_button_layout.xml
  libnavui-voice/src/main/res/values/attrs.xml
  libnavui-voice/src/main/res/values/dimens.xml
  libnavui-voice/src/main/res/values/styles.xml
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/internal/ui/AudioGuidanceButtonComponentTest.kt
  qa-test-app/src/main/AndroidManifest.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivitySuite.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/lifecycle/DropInLocationPuck.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/AppLifecycleActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/ComponentsActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/ComponentsAltActivity.kt
  qa-test-app/src/main/res/layout/components_activity_layout.xml
  qa-test-app/src/main/res/menu/activity_components.xml
  qa-test-app/src/main/res/values/strings.xml
Labels: UI

#5907 Update androidauto-test
  .circleci/config.yml
Labels: skip changelog

#5853 MapboxCarMapSurface observe map style
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/internal/extensions/MapboxCarMapSurfaceExtensions.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/map/widgets/compass/CarCompassSurfaceRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/map/widgets/logo/CarLogoSurfaceRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/ActiveGuidanceScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/roadlabel/RoadLabelSurfaceLayer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/speedlimit/CarSpeedLimitRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/placeslistonmap/PlacesListOnMapScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRouteLine.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/preview/CarRoutePreviewScreen.kt
Labels: improvement

#5911 Refactored dependencies of route refresh controller
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/DirectionsSession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/RouteRefresh.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshController.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routerefresh/RouteRefreshControllerTest.kt
Labels: skip changelog

#5909 Remove MapView from RouteLineComponent
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/MapBinder.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/installer/ComponentInstaller.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteLineComponent.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/ui/RouteLineComponentTest.kt
Labels: skip changelog

#5914 fix view binding dependency
  gradle/dependencies.gradle
Labels: skip changelog

#5906 add option to observe user feedbacks
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/telemetry/CachedNavigationFeedbackEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/telemetry/MapboxNavigationFeedbackCache.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/telemetry/TelemetryEx.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/telemetry/UserFeedback.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/telemetry/UserFeedbackCallback.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/utils/TelemetryEx.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/FeedbackMetadata.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/FeedbackMetadataTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/events/FeedbackMetadataWrapperTest.kt
Labels: skip changelog

#5916 Add `2.6.0-beta.2` `CHANGELOG` entry
  CHANGELOG.md
Labels: skip changelog

#5929 Added a numeric version of the traffic update activity to QA app.
  qa-test-app/src/main/AndroidManifest.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivitySuite.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/RouteNumericTrafficUpdateActivity.kt
  qa-test-app/src/main/res/values/strings.xml
Labels: skip changelog

#5922 [Drop-in UI] Added support for NavigationViewListener
  CHANGELOG.md
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewContext.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewListener.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewListenerRegistry.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/NavigationViewListenerRegistryTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxNavigationViewCustomizedActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/NavigationViewFragment.java
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/NavigationViewFragment.kt
Labels: feature, UI

#5927 Add `predictiveCacheGuidanceLocationOptions` to `PredictiveCacheController`
  CHANGELOG.md
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/PredictiveCacheController.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/PredictiveCacheControllerTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxRouteLineActivity.java
Labels: improvement

#5935 Use the same `HistoryRecorderHandle` instance everywhere
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/NavigatorLoader.kt
Labels: Core, skip changelog, bug :beetle:

#5938 Set routes to nav session
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NavigationSession.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/NavigationSessionTest.kt
Labels: skip changelog, improvement

#5928 display formatted distance in instrument cluster
  libnavui-androidauto/CHANGELOG.md
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/MapboxCarNavigationManager.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/maneuver/CarManeuverMapper.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/car/navigation/maneuver/CarManeuverMapperTest.kt
Labels: Android Auto

#5949 Fix `Makefile` `publish-local`
  Makefile
Labels: skip changelog, op-ex, bug :beetle:

#5943 Patched puck position anim glitch and re-enabled Puck Velocity Fix
  CHANGELOG.md
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/location/NavigationLocationProvider.kt
Labels: ⚠️ DO NOT MERGE

#5948 add callbacks related to fecthing routes
  CHANGELOG.md
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/routefetch/RoutesState.kt
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewListener.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewListenerRegistry.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/NavigationViewListenerRegistryTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxNavigationViewCustomizedActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/NavigationViewFragment.java
Labels: skip changelog

#5966 Bump Navigation Native dependency version to `107.0.0`
  gradle/dependencies.gradle
Labels: Core, skip changelog

#5962 Updated MapboxAudioGuidanceButton, MapboxCameraModeButton and MapboxExtendableButton to support square, oval and circle shapes.
  CHANGELOG.md
  LICENSE.md
  libnavui-base/api/current.txt
  libnavui-base/build.gradle
  libnavui-base/src/main/java/com/mapbox/navigation/ui/base/view/MapboxExtendableButton.kt
  libnavui-base/src/main/res/layout/mapbox_extendable_button_layout.xml
  libnavui-base/src/main/res/values/attrs.xml
  libnavui-base/src/main/res/values/dimens.xml
  libnavui-base/src/main/res/values/styles.xml
  libnavui-base/src/test/java/com/mapbox/navigation/ui/base/view/MapboxExtendableButtonTest.kt
  libnavui-dropin/api/current.txt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewStyleCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/cameramode/CameraModeButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonComponent.kt
  libnavui-dropin/src/main/res/layout/mapbox_action_buttons_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_info_panel_header_layout.xml
  libnavui-dropin/src/main/res/values/attrs.xml
  libnavui-dropin/src/main/res/values/dimens.xml
  libnavui-dropin/src/main/res/values/styles.xml
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/cameramode/CameraModeButtonComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/recenter/RecenterButtonComponentTest.kt
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/view/MapboxCameraModeButton.kt
  libnavui-maps/src/main/res/drawable/mapbox_ic_camera_follow.xml
  libnavui-maps/src/main/res/drawable/mapbox_ic_camera_overview.xml
  libnavui-maps/src/main/res/layout/mapbox_camera_mode_button_layout.xml
  libnavui-maps/src/main/res/values/attrs.xml
  libnavui-maps/src/main/res/values/styles.xml
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/view/MapboxCameraModeButtonTest.kt
  libnavui-resources/src/main/res/drawable/mapbox_bg_circle_outline.xml
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/view/MapboxAudioGuidanceButton.kt
  libnavui-voice/src/main/res/layout/mapbox_audio_guidance_button_layout.xml
  libnavui-voice/src/main/res/values/styles.xml
  qa-test-app/src/main/AndroidManifest.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivitySuite.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/DropInButtonsActivity.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/base/BaseNavigationActivity.kt
  qa-test-app/src/main/res/drawable/bg_custom_button.xml
  qa-test-app/src/main/res/drawable/bg_custom_circle_button.xml
  qa-test-app/src/main/res/layout/layout_activity_dropin_buttons.xml
  qa-test-app/src/main/res/values/strings.xml
  qa-test-app/src/main/res/values/styles.xml
Labels: UI

#5971 Events changes needed for Copilot
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/options/EventsAppMetadata.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/options/EventsAppMetadataTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/PhoneState.kt
Labels: Core, skip changelog

#5947 Send custom events to determine the usage of Drop-In UI
  libnavigation-base/api/current.txt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/metrics/MetricEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/telemetry/CustomEvent.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/telemetry/TelemetryEx.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/NavigationCustomEvent.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetryTest.kt
  libnavigation-metrics/src/main/java/com/mapbox/navigation/metrics/extensions/MetricEventEx.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/analytics/AnalyticsComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/analytics/AnalyticsComponentTest.kt
Labels: skip changelog

#5965 More logs for get routes
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/NavigationRoute.kt
  libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/RouterWrapper.kt
  libnavigation-router/src/test/java/com/mapbox/navigation/route/internal/RouterWrapperTests.kt
  libtesting-navigation-base/src/main/java/com/mapbox/navigation/testing/factories/NavigationRouteFactory.kt
Labels: skip changelog

#5976 [Drop-In UI] Added support for edge-to-edge display.
  CHANGELOG.md
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationViewContext.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/binder/map/MapBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/logo/LogoAttributionComponent.kt
  libnavui-dropin/src/main/res/layout-land/mapbox_navigation_view_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_navigation_view_layout.xml
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/component/logo/LogoAttributionComponentTest.kt
  qa-test-app/src/main/AndroidManifest.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/domain/TestActivitySuite.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/MapboxNavigationViewFragmentActivity.kt
  qa-test-app/src/main/res/values-night/themes.xml
  qa-test-app/src/main/res/values/themes.xml
Labels: UI
