Repository mapbox/mapbox-navigation-android, pull requests merged in 2023-06, with the labels that each got.

#7237 NAVAND-1379: ignore expected closures in `RouteProgress#hasUnexpectedUpcomingClosures`
  changelog/unreleased/bugfixes/7237.md
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/ClosuresTest.kt
  instrumentation-tests/src/main/res/raw/route_response_route_refresh_no_closures.json
  libnavigation-base/src/main/java/com/mapbox/navigation/base/route/NavigationRoute.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/utils/route/RouteProgressEx.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/internal/route/RouteProgressExTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/route/NavigationRouteTest.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/utils/route/RouteProgressExTest.kt
Labels: needs backporting

#7196 Billing e2e tests
  .circleci/config.yml
  billing-tests/build.gradle
  billing-tests/src/androidTest/java/com/mapbox/navigation/billing/test/BillingTests.kt
  scripts/validate_billing_e2e_sessions.py
Labels: skip changelog

#7301 up license version
  build.gradle
  gradle/dependencies.gradle
  libnavigation-copilot/src/main/assets/open_source_licenses.html
  scripts/generate-license.py
Labels: skip changelog

#7300 bump Maps SDK to 10.14.1
  build.gradle
  gradle/dependencies.gradle
  libnavigation-copilot/src/main/assets/open_source_licenses.html
  scripts/generate-license.py
Labels: skip changelog

#7304 bump NN to 137.1.1
  gradle/dependencies.gradle
Labels: needs backporting, skip changelog
