Repository mapbox/mapbox-navigation-android, pull requests merged in 2023-01, with the labels that each got.

#6741 NAVAND-995: add NativeNavigatorTest
  .circleci/config.yml
  libnavigation-core/.gitignore
  libnavigation-core/src/androidTest/java/com/mapbox/navigation/core/trip/service/NativeNavigatorCallbackOrderTest.kt
  libnavigation-core/src/androidTest/res/raw/multileg_route.json
  libnavigation-core/src/androidTest/res/raw/route_response_route_refresh.json
  libnavigation-core/src/androidTest/res/raw/route_response_route_refresh_annotations.json
Labels: skip changelog

#6557 add suspend version of stopRecording method
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CoreRerouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxHistoryTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/coroutines/Adapters.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/history/MapboxHistoryTestRule.kt
Labels: skip changelog

#6780 fix info panel dimensions in landscape with a full screen theme
  changelog/unreleased/bugfixes/6780.md
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/infopanel/InfoPanelComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/infopanel/InfoPanelComponentTest.kt
Labels: bug, UI

#6703 NAVAND-969: do not start new billing session for different EV chargers
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/extensions/WaypointEx.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/accounts/BillingController.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/accounts/BillingControllerTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/accounts/BillingControllerWaypointsComparisonTest.kt
Labels: skip changelog

#6782 Bump NN dependency version to `111.1.1`
  gradle/dependencies.gradle
Labels: Core, skip changelog

#6785 Bump NN dependency version to `119.0.6`
  CHANGELOG.md
  gradle/dependencies.gradle
Labels: Core

#6781 Updated rename_changelog_file.yml GitHub workflow to account for DRAFT and “skip changelog” labelled PRs.
  .github/workflows/rename_changelog_file.yml
Labels: skip changelog

#6638 [Drop-In UI] Move `fetchRouteIfNeeded` to `RoutePreviewStateController`:
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/SharedApp.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/ThunkActions.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RoutePreviewStateController.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/extension/MapboxNavigationExtensions.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/routefetch/RoutePreviewAction.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/internal/controller/RoutePreviewStateControllerTest.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/testing/TestStore.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/extendablebutton/RoutePreviewButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/extendablebutton/StartNavigationButtonComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/infopanel/InfoPanelRoutePreviewButtonBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/infopanel/InfoPanelStartNavigationButtonBinder.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/map/longpress/RoutePreviewLongPressMapComponent.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/navigationview/NavigationViewContext.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/extendablebutton/RoutePreviewButtonComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/extendablebutton/StartNavigationButtonComponentTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/map/longpress/RoutePreviewLongPressMapComponentTest.kt
Labels: UI, skip changelog

#6783 Assemble changelog only in PRs comments
  .github/workflows/assemble_changelog.yml
  changelog/README.md
  scripts/changelog/assemble_changelog.py
Labels: skip changelog

#6792 [Drop-In UI] Changes RoadName positioning and customization
  changelog/unreleased/features/6792.md
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/ViewStyleCustomization.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/infopanel/InfoPanelCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/navigationview/NavigationViewStyles.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/navigationview/NavigationViewStylesTest.kt
Labels: UI

#6811 fix info panel dimensions in landscape with a full screen theme
  CHANGELOG.md
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/infopanel/InfoPanelComponent.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/infopanel/InfoPanelComponentTest.kt
Labels: bug, UI

#6810 fix standalone maneuver view appearance when drop-in ui is integrated
  CHANGELOG.md
  examples/src/main/res/values/strings.xml
  libnavui-maneuver/src/main/res/values-night/colors.xml
  libnavui-maneuver/src/main/res/values/colors.xml
Labels: bug, UI

#6819 Fix `2.7.2` `CHANGELOG`
  CHANGELOG.md
Labels: skip changelog

#6821 Fix Copilot `unrecognized` fields serialization
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
Labels: needs backporting, skip changelog

#6824 Backport #6821 to `release-v2.9`
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
Labels: Core, skip changelog

#6825 Backport #6821 and #6762 to `release-v2.10`
  libnavigation-copilot/proguard-rules.pro
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
Labels: Core, skip changelog

#6823 Backport #6821 and #6762 to `release-v2.8`
  libnavigation-copilot/proguard-rules.pro
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
Labels: Core, skip changelog

#6822 Backport #6821 and #6762 to `release-v2.7`
  libnavigation-copilot/proguard-rules.pro
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
Labels: Core, skip changelog

#6818 Added additional documentation regarding the default route line color …
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineColorResources.kt
Labels: skip changelog

#6834 Bump NN dependency version to `123.2.0`
  changelog/unreleased/bugfixes/6834.md
  gradle/dependencies.gradle
Labels: Core, needs backporting

#6835 Backport #6834 to `release-v2.10`
  changelog/unreleased/bugfixes/6834.md
  gradle/dependencies.gradle
Labels: Core

#6840 restore overview camera when routes change during route preview state
  changelog/unreleased/bugfixes/6840.md
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/AudioGuidanceStateController.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/CameraStateController.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/DestinationStateController.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/LocationStateController.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/NavigationStateController.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteStateController.kt
  libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/StateController.kt
  libnavui-app/src/test/java/com/mapbox/navigation/ui/app/internal/controller/CameraStateControllerTest.kt
Labels: UI

#6799 Fast integration test for artificial driver
  libnavigation-core/src/androidTest/java/com/mapbox/navigation/core/trip/service/ArtificialDriverTest.kt
  libnavigation-core/src/androidTest/res/raw/test_long_route.json
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/ReplayLocationEngine.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayEventLocationMapper.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/history/ReplayEventLocationMapperTest.kt
Labels: skip changelog

#6843 [CI] CI does not publish snapshots of release branches
  .circleci/config.yml
  gradle/artifact-settings.gradle
Labels: publish-snapshot

#6853 Set patch version for snapshots
  gradle/artifact-settings.gradle
Labels: publish-snapshot

#6850 up mapbox java version to 6.10.0
  gradle/dependencies.gradle
Labels: skip changelog

#6849 [Android Auto] Add support for Junction Views
  android-auto-app/build.gradle
  android-auto-app/src/main/AndroidManifest.xml
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/app/DrawerActivity.kt
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/app/MainActivity.kt
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/utils/MapboxNavigationEx.kt
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/utils/NavigationViewController.kt
  android-auto-app/src/main/java/com/mapbox/navigation/examples/androidauto/utils/TestRoutes.kt
  android-auto-app/src/main/res/drawable/ic_baseline_menu_24.xml
  android-auto-app/src/main/res/drawable/menu_button_bg.xml
  android-auto-app/src/main/res/layout/activity_drawer.xml
  android-auto-app/src/main/res/layout/activity_main.xml
  android-auto-app/src/main/res/layout/layout_drawer_menu_nav_view.xml
  android-auto-app/src/main/res/layout/mapbox_activity_navigation_view.xml
  android-auto-app/src/main/res/values/strings.xml
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/changelog/unreleased/features/6849.md
  libnavui-androidauto/src/androidTest/java/com/mapbox/androidauto/car/navigation/lanes/CarLanesImageRendererTest.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/CarNavigationInfoMapper.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/CarNavigationInfoProvider.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/CarNavigationInfoServices.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/lanes/CarLanesImageRenderer.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/CarNavigationInfoMapperTest.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/CarNavigationInfoProviderTest.kt
Labels: feature, Android Auto

#6790 update license file & generator script
  LICENSE.md
  scripts/generate-license.py
Labels: skip changelog

#6866 CI config, release-snapshot: remove `check-public-documentation`
  .circleci/config.yml
Labels: skip changelog

#6859 [Android Auto] Optimized SpeedLimitWidget memory usage
  libnavui-androidauto/changelog/unreleased/bugfixes/6859.md
  libnavui-androidauto/src/androidTest/java/com/mapbox/androidauto/car/navigation/speedlimit/SpeedLimitRendererTest.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/speedlimit/MutcdSpeedLimitDrawable.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/speedlimit/SpeedLimitBitmapRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/speedlimit/SpeedLimitDrawable.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/speedlimit/SpeedLimitWidget.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/speedlimit/ViennaSpeedLimitDrawable.kt
  libnavui-androidauto/src/test/java/com/mapbox/androidauto/navigation/speedlimit/SpeedLimitBitmapRendererTest.kt
Labels: Android Auto, improvement

#6845 ignore ime insets in navigation view
  changelog/unreleased/bugfixes/6845.md
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/NavigationView.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/camera/CameraLayoutObserver.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/infopanel/InfoPanelCoordinator.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/internal/extensions/NavigationViewContextEx.kt
  libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/map/MapViewBinder.kt
  libnavui-dropin/src/main/res/layout-land/mapbox_navigation_view_layout.xml
  libnavui-dropin/src/main/res/layout/mapbox_navigation_view_layout.xml
  libnavui-dropin/src/main/res/values-land/dimens.xml
  libnavui-dropin/src/main/res/values/dimens.xml
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/camera/CameraLayoutObserverTest.kt
  libnavui-dropin/src/test/java/com/mapbox/navigation/dropin/infopanel/InfoPanelCoordinatorTest.kt
Labels: bug, UI

#6872 Wrap PR links in changelog comments in code blocks
  scripts/changelog/assemble_changelog.py
Labels: skip changelog

#6869 NAVAND-1108: test that reproduces the issue
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/UpcomingRouteObjectsTest.kt
  instrumentation-tests/src/main/res/raw/route_through_incident_6058002857835914_one_leg.json
  instrumentation-tests/src/main/res/raw/route_through_incident_6058002857835914_two_legs.json
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/roadobject/UpcomingRoadObject.kt
Labels: skip changelog

#6876 Fix Copilot ANR
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistoryAttachmentsUtils.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/HistoryUploadWorkerTest.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/MapboxCopilotImplTest.kt
Labels: Core, needs backporting, skip changelog

#6855 Add a ReplayHistorySession
  changelog/unreleased/features/6855.md
  examples/src/main/java/com/mapbox/navigation/examples/MainActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt
  examples/src/main/java/com/mapbox/navigation/examples/core/replay/HistoryFileLoader.kt
  examples/src/main/res/layout/activity_replay_history_layout.xml
  libnavigation-core/api/current.txt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/history/MapboxHistoryReaderProvider.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistorySession.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/history/ReplayHistorySessionOptions.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/MapboxTripStarter.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/MapboxTripStarterType.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/history/ReplayHistorySessionOptionsTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/replay/history/ReplayHistorySessionTest.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/MapboxTripStarterTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/RoadObjectsActivity.kt
Labels: publish-snapshot

#6877 Backport #6876 to `release-v2.10`
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistoryAttachmentsUtils.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/HistoryUploadWorkerTest.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/MapboxCopilotImplTest.kt
Labels: Core, skip changelog

#6874 Release snapshot workflow refactoring
  .circleci/config.yml
  .github/workflows/run_release_snapshot.yml
Labels: skip changelog, publish-snapshot

#6884 fixed upcoming route objects test
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/UpcomingRouteObjectsTest.kt
Labels: skip changelog

#6878 Backport #6876 to `release-v2.9`
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistoryAttachmentsUtils.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/HistoryUploadWorkerTest.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/MapboxCopilotImplTest.kt
Labels: Core, skip changelog

#6880 Backport #6876 to `release-v2.7`
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistoryAttachmentsUtils.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/HistoryUploadWorkerTest.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/MapboxCopilotImplTest.kt
Labels: Core, skip changelog

#6879 Backport #6876 to `release-v2.8`
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistoryAttachmentsUtils.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/HistoryUploadWorkerTest.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/MapboxCopilotImplTest.kt
Labels: Core, skip changelog

#6865 add debug logs to callback flows
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/coroutines/Adapters.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/trip/model/RouteProgress.kt
Labels: skip changelog

#6885 (split) use relative paths for nested gradle scripts
  android-auto-app/build.gradle
  examples/build.gradle
  gradle/ktlint.gradle
  gradle/publish.gradle
  gradle/track-public-apis.gradle
  instrumentation-tests/build.gradle
  libnavigation-android/build.gradle
  libnavigation-base/build.gradle
  libnavigation-copilot/build.gradle
  libnavigation-core/build.gradle
  libnavigation-metrics/build.gradle
  libnavigation-router/build.gradle
  libnavigation-util/build.gradle
  libnavigator/build.gradle
  libnavui-androidauto/build.gradle
  libnavui-app/build.gradle
  libnavui-base/build.gradle
  libnavui-dropin/build.gradle
  libnavui-maneuver/build.gradle
  libnavui-maps/build.gradle
  libnavui-resources/build.gradle
  libnavui-shield/build.gradle
  libnavui-speedlimit/build.gradle
  libnavui-status/build.gradle
  libnavui-tripprogress/build.gradle
  libnavui-util/build.gradle
  libnavui-voice/build.gradle
  libtesting-navigation-base/build.gradle
  libtesting-navigation-util/build.gradle
  libtesting-thirdparty/build.gradle
  libtesting-ui/build.gradle
  libtesting-utils/build.gradle
  libtrip-notification/build.gradle
  qa-test-app/build.gradle
  qa-test-app/gradle/task_generate_icons_preview.gradle
Labels: skip changelog

#6873 use CarActiveGuidanceMarkers in route preview screen
  libnavui-androidauto/api/current.txt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/internal/extensions/MapboxCarMapSurfaceExtensions.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/CarActiveGuidanceMarkers.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/navigation/roadlabel/CarRoadLabelRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/placeslistonmap/PlacesListOnMapManager.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/preview/CarRouteLineRenderer.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/preview/CarRoutePreviewScreen.kt
Labels: skip changelog, Android Auto

#6916 Add `2.7.3` `CHANGELOG`
  CHANGELOG.md
Labels: skip changelog

#6917 Add `2.8.3` `CHANGELOG`
  CHANGELOG.md
Labels: skip changelog

#6918 Add `2.9.7` `CHANGELOG`
  CHANGELOG.md
Labels: skip changelog

#6920 ignore MapboxNavigationApp detach calls without attach
  changelog/unreleased/bugfixes/6920.md
  libnavigation-core/src/main/java/com/mapbox/navigation/core/lifecycle/CarAppLifecycleOwner.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/lifecycle/CarAppLifecycleOwnerTest.kt
Labels: bug

#6914 fix left frame anchor in landscape during active guidance
  changelog/unreleased/bugfixes/6914.md
  libnavui-dropin/src/main/res/layout-land/mapbox_navigation_view_layout.xml
Labels: bug, UI

#6921 force route line layers to be initialized before route arrow layers are
  libnavui-androidauto/changelog/unreleased/bugfixes/6921.md
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/preview/CarRouteLineRenderer.kt
Labels: bug, Android Auto

#6919 SpeedInfo - fixed MUTCD 3-digit speed limit rendering
  changelog/unreleased/bugfixes/6919.md
  libnavui-speedlimit/src/main/res/layout/mapbox_speed_info_view.xml
  libnavui-speedlimit/src/main/res/values/styles.xml
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/CustomizedViewModel.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt
  qa-test-app/src/main/res/layout/layout_drawer_menu_nav_view_custom.xml
  qa-test-app/src/main/res/values/strings.xml
Labels: UI
