Repository mapbox/mapbox-navigation-android, pull requests merged in 2023-07, with the labels that each got.

#7322 [NAVAND-1409] added RouteLineColorResources to style congestion on inactive legs and fixed an issue where restrictions were not shown on inactive legs
  changelog/unreleased/bugfixes/7322.md
  changelog/unreleased/features/7322.md
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/RouteLayerConstants.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLine.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/InactiveRouteColors.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineColorResources.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineExpressionData.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsRoboTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiRoboTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLineRoboTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/model/RouteLineColorResourcesTest.kt
  libnavui-maps/src/test/resources/multileg_route_with_overlap_all_congestion.json
Labels: needs backporting

#7334 Register SDK information
  libnavigation-core/src/androidTest/java/com/mapbox/navigation/core/MapboxNavigationSDKInitializerTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/MapboxNavigationSDKInitializer.kt
Labels: feature, skip changelog

#7331 fix restricted masking data calculation
  libnavui-maps/api/current.txt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLine.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApiRoboTest.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLineRoboTest.kt
Labels: skip changelog

#7337 Support for voice gender.
  changelog/unreleased/features/7337.md
  libnavui-voice/api/current.txt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxAudioGuidance.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxSpeechProvider.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/internal/impl/MapboxAudioGuidanceServices.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/options/MapboxSpeechApiOptions.kt
  libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/options/VoiceGender.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/TestMapboxAudioGuidanceServices.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/MapboxAudioGuidanceTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/api/MapboxSpeechProviderTest.kt
  libnavui-voice/src/test/java/com/mapbox/navigation/ui/voice/options/MapboxSpeechApiOptionsTest.kt
Labels: feature

#7361 Dependency bump
  gradle/dependencies.gradle
Labels: skip changelog

#7386 Flaky tests fixes
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/Network.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/tiles/TileStore.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesControllerTest.kt
Labels: needs backporting, skip changelog

#7396 NAVAND-1443: reconsider mechanism that prevents adding server waypoints again and again for stickiness
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/extensions/WaypointEx.kt
  libnavigation-base/src/main/java/com/mapbox/navigation/base/internal/route/EvDataApi.kt
  libnavigation-base/src/test/java/com/mapbox/navigation/base/internal/extensions/WaypointExTest.kt
  libnavigation-core/src/main/java/com/mapbox/navigation/core/routeoptions/RouteOptionsUpdater.kt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/ev/EvRouteOptionsUpdaterTest.kt
  libnavigation-core/src/test/resources/com.mapbox.navigation.core.routeoptions.ev/testRouteAfterRerouteFromOrigin.json
  libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/building/BuildingProcessor.kt
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/building/BuildingProcessorTest.kt
Labels: needs backporting, skip changelog

#7411 fix alternative_requests_use_original_route_base_url
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt
Labels: needs backporting, skip changelog
