Repository mapbox/mapbox-navigation-android, pull requests merged in 2023-03, with the labels that each got.

#6977 fix refresh errors
  LICENSE.md
  libnavigation-core/api/current.txt
  libnavigation-core/src/test/java/com/mapbox/navigation/core/routerefresh/RouteRefreshIntegrationTest.kt
Labels: skip changelog

#6978 Copilot: avoid ANRs
  changelog/unreleased/bugfixes/6978.md
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/HistoryEvents.kt
  libnavigation-copilot/src/main/java/com/mapbox/navigation/copilot/MapboxCopilotImpl.kt
  libnavigation-copilot/src/test/java/com/mapbox/navigation/copilot/MapboxCopilotImplTest.kt
Labels: needs backporting

#6987 Bump `mapbox-java` dependency version to `6.11.0`
  LICENSE.md
  gradle/dependencies.gradle
Labels: skip changelog

#6989 `CHANGELOG` for `v2.10.3` (#6988)
  CHANGELOG.md
Labels: skip changelog

#6990 Bump mapbox-java dependency version to `6.11.0` (#6987)
  LICENSE.md
  gradle/dependencies.gradle
Labels: skip changelog

#6994 `CHANGELOG` for `v2.11.0` (#6993)
  CHANGELOG.md
Labels: skip changelog

#7014 show a spinner in route preview screen when there are no routes
  libnavui-androidauto/changelog/unreleased/bugfixes/7014.md
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/preview/CarRoutePreviewScreen2.kt
Labels: Android Auto, bug :beetle:

#6973 Billing sessions integration tests
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/BannerAndVoiceInstructionsTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CopilotIntegrationTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CoreRerouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SanityCoreRouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/TripSessionsBillingTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/SimpleMapViewNavigationTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/AlternativeRouteSelectionTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/RouteLineLayersTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/SetRouteOrderTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/Url.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/coroutines/TestUtils.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/http/HttpServiceEventsObserver.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/BaseCoreNoCleanUpTest.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/BaseTest.kt
  qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/LoggingNavigationViewListener.kt
Labels: skip changelog

#7019 More logs in case of native status processing failure
  libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
Labels: skip changelog

#7031 fix distance in route preview screens
  libnavui-androidauto/changelog/unreleased/bugfixes/7031.md
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/preview/CarRoutePreviewScreen.kt
  libnavui-androidauto/src/main/java/com/mapbox/androidauto/preview/CarRoutePreviewScreen2.kt
Labels: bug, Android Auto

#6953 add jct/ic tests
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/UpcomingRouteObjectsTest.kt
  instrumentation-tests/src/main/res/raw/route_with_ic.json
  instrumentation-tests/src/main/res/raw/route_with_jct.json
  instrumentation-tests/src/main/res/raw/route_with_road_objects.json
Labels: skip changelog

#7044 fix MapboxRouteLineUtilsTest
  libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt
Labels: skip changelog

#7042 e2e tests module
  .circleci/config.yml
  billing-tests/.gitignore
  billing-tests/build.gradle
  billing-tests/proguard-rules.pro
  billing-tests/src/androidTest/java/com/mapbox/navigation/billing/test/BillingTests.kt
  billing-tests/src/main/AndroidManifest.xml
  billing-tests/src/main/res/values/strings.xml
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/BannerAndVoiceInstructionsTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CopilotIntegrationTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CoreRerouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/EVRerouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/EVRouteRefreshTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/HistoryRecordingStateChangeObserverTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxHistoryTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxNavigationTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/NavigationRouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/ReplayLocationTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteRefreshOnDemandTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteRefreshTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RoutesPreviewTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SanityCoreRouteTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SetRoutesTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/TripSessionsBillingTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/UpcomingRouteObjectsTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/WaypointsTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/SimpleMapViewNavigationTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/AlternativeRouteSelectionTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/RouteLineLayersTest.kt
  instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/history/MapboxHistoryTestRule.kt
  libtesting-ui/build.gradle
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/http/HttpServiceEvent.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/http/HttpServiceEventsObserver.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/utils/MapboxNavigationRule.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/utils/Url.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/utils/coroutines/Adapters.kt
  libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/utils/coroutines/TestUtils.kt
  settings.gradle
Labels: skip changelog

#7062 CI: revert back verify common sdk version
  .circleci/config.yml
Labels: skip changelog
